local UNDERCOIN = 2803;
local NERUBIAN_DELVES_TWW = { EARTHCRAWL_MINES, SKITTERING_BREACH, THE_DREAD_PIT, THE_SPIRAL_WEAVE, THE_UNDERKEEP };
local FUNGARIAN_DELVES_TWW = { FUNGAL_FOLLY, MYCOMANCER_CAVERN };
local KOBOLD_DELVES_TWW = { KRIEGVALS_REST, THE_WATERWORKS };
local SHADOW_DELVES_TWW = { NIGHTFALL_SANCTUM };
local KOBYSS_DELVES_TWW = { TAK_RETHAN_ABYSS, THE_SINKHOLE };
local OVERCHARGED_DELVES_TWW = { FUNGAL_FOLLY, KRIEGVALS_REST, NIGHTFALL_SANCTUM, SIDESTREET_SLUICE, SKITTERING_BREACH, THE_SPIRAL_WEAVE };
local ALL_REGULAR_DELVES_TWW = {
	EARTHCRAWL_MINES,
	FUNGAL_FOLLY,
	KRIEGVALS_REST,
	MYCOMANCER_CAVERN,
	NIGHTFALL_SANCTUM,
	SKITTERING_BREACH,
	TAK_RETHAN_ABYSS,
	THE_DREAD_PIT,
	THE_SINKHOLE,
	THE_SPIRAL_WEAVE,
	THE_UNDERKEEP,
	THE_WATERWORKS,
	-- #if AFTER 11.1.0
	EXCAVATION_SITE_9,
	SIDESTREET_SLUICE,
	-- #endif
	-- #if AFTER 11.2.0
	ARCHIVAL_ASSAULT,
	-- #endif
};
local ALL_THE_DELVES_TWW = {
	EARTHCRAWL_MINES,
	FUNGAL_FOLLY,
	KRIEGVALS_REST,
	MYCOMANCER_CAVERN,
	NIGHTFALL_SANCTUM,
	SKITTERING_BREACH,
	TAK_RETHAN_ABYSS,
	THE_DREAD_PIT,
	THE_SINKHOLE,
	THE_SPIRAL_WEAVE,
	THE_UNDERKEEP,
	THE_WATERWORKS,
	ZEKVIRS_LAIR,
	-- #if AFTER 11.1.0
	DEMOLITION_DOME,
	EXCAVATION_SITE_9,
	SIDESTREET_SLUICE,
	-- #endif
	-- #if AFTER 11.2.0
	ARCHIVAL_ASSAULT,
	DELVE_ETHEREAL_KYVEZA,
	-- #endif
};
local mapped = function(t)
	if not t.maps then
		t.maps = ALL_REGULAR_DELVES_TWW
	end
	return t
end

root(ROOTS.Delves, expansion(EXPANSION.TWW, applyDataSelf({ ["timeline"] = { ADDED_11_0_2 } }, {
	n(ACHIEVEMENTS, {
		ach(40460, {	-- Delve Deep
			["maps"] = ALL_THE_DELVES_TWW,
		}),
		ach(40462, {	-- Delve Deeper
			["maps"] = ALL_THE_DELVES_TWW,
		}),
		ach(40463, {	-- Delve Deepest (100)
			["maps"] = ALL_THE_DELVES_TWW,
		}),
		ach(41095, {	-- Delve Beyond (500)
			["timeline"] = { ADDED_11_1_0 },
			["maps"] = ALL_THE_DELVES_TWW,
			["groups"] = {
				-- #if AFTER 11.2.0
				--title(650),	-- Delver %s // doesn't load ingame
				-- #else
				title(598),	-- Delver %s
				-- #endif
			},
		}),
		ach(41096, {	-- Delve Infinite (1000)
			["timeline"] = { ADDED_11_1_0 },
			["maps"] = ALL_THE_DELVES_TWW,
			["groups"] = { title(599) },	-- Infinite Delver %s
		}),
	}),
})));
