# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
reviews:
  path_filters: 
    - "!db/**"
    - "!**/*.csv"
    - "!**/*.txt"
  tools:
    github-checks:
      timeout_ms: 900000
