createLocalizationString({
	readable = "[icon:Expansion_DF] Mount Modifications",
	constant = "MOUNTMODS_CHECKBOX",
	icon = [[~_.asset("Expansion_DF")]],
	export = true,
	text = {
		en = "Mount Modifications",
		-- TODO: de = "",
		es = "Modificaciones de montura",
		es = "Modificaciones de montura",
		mx = "Modificaciones de montura",
		-- TODO: fr = "",
		-- TODO: it = "",
		-- TODO: ko = "",
		-- TODO: pt = "",
		ru = "Модификации транспорта",
		-- TODO: ko = "",
		cn = "坐骑定制",
		tw = "坐騎外形",
	},
})
