DEMON_TRAINER = createHeader({
	readable = "Demon Trainer",
	icon = 133738,
	text = {
		en = "Demon Trainer",
		de = "Dämonenausbilderin",
		es = "Instructor de demonios",
		mx = "Instructor de demonios",
		fr = "Maître des démons",
		-- TODO: it = "",
		ko = "악마 훈련사",
		pt = "Treinamento de Demônios",
		ru = "Наставник демонов",
		cn = "恶魔训练师",
		tw = "惡魔訓練師",
	},
	description = {
		en = "Warlocks can teach their demons new tricks. Some of the higher level grimoires can only be purchased from the Demon Trainer in your faction's capital cities.",
		-- TODO: de = "",
		-- TODO: es = "",
		-- TODO: mx = "",
		-- TODO: fr = "",
		-- TODO: it = "",
		-- TODO: ko = "",
		-- TODO: pt = "",
		-- TODO: ru = "",
		-- TODO: cn = "",
		tw = "術士可以教導他們的惡魔新技能，一些高等級的魔典只能從你陣營首都的惡魔訓練師那裡購買。",
	},
});
