EVENT_COMPLETION = createHeader({
	readable = "Event Completion",
	constant = "EVENT_COMPLETION",
	icon = [[~_.asset("Interface_Rewards")]],
	text = {
		en = "Event Completion",
		-- TODO: de = "",
		es = "Finalización del evento",
		mx = "Al completar el evento",
		-- TODO: fr = "",
		-- TODO: it = "",
		-- TODO: ko = "",
		-- TODO: pt = "",
		-- TODO: ru = "",
		cn = "事件完成",
		-- TODO: tw = "",
	},
	description = {
		en = "Contains things that are rewarded upon completing that event.",
		-- TODO: de = "",
		es = "Contiene cosas que se otorgan como recompensa al finalizar ese evento.",
		mx = "Contiene cosas que se otorgan como recompensa al completar este evento.",
		fr = "Contient des objets de récompenses ou disponibles dans d’autres contenus de la section qui les contient.\nIls sont regroupés ici dans le but de réduire la duplication de nombreuses sources possibles.",
		-- TODO: it = "",
		-- TODO: ko = "",
		-- TODO: pt = "",
		ru = "Штучки, которые можно получить в награду с разного контента в родительской секции.\nОни собраны здесь, чтобы уменьшить количество источников, когда Штучка доступна из многих мест.",
		cn = "包含有奖励或可从包含部分中的其他内容获得的事物。\n在此处合并以减少来自许多可能重复来源。",
		-- TODO: tw = "",
	},
});
