SCENARIO_COMPLETION = createHeader({
	readable = "Scenario Completion",
	constant = "SCENARIO_COMPLETION",
	minilist_ignore = true,
	icon = [[~_.asset("Interface_Rewards")]],
	text = {
		en = "Scenario Completion",
		-- TODO: de = "",
		es = "Escenario completado",
		mx = "Escenario completado",
		-- TODO: fr = "",
		-- TODO: it = "",
		-- TODO: ko = "",
		-- TODO: pt = "",
		ru = "Награда сценария",
		cn = "场景战役完成",
		tw = "戰役完成",
	},
	description = {
		en = "Contains Things which are rewarded that upon completing that scenario.",
		-- TODO: de = "",
		es = "Contiene cosas que se obtienen como recompensa al completar ese escenario.",
		mx = "Contiene cosas que se obtienen como recompensa al completar este escenario.",
		fr = "Contient des objets de récompenses ou disponibles dans d’autres contenus de la section qui les contient.\nIls sont regroupés ici dans le but de réduire la duplication de nombreuses sources possibles.",
		-- TODO: it = "",
		-- TODO: ko = "",
		-- TODO: pt = "",
		ru = "Штучки, которые можно получить в награду с разного контента в родительской секции.\nОни собраны здесь, чтобы уменьшить количество источников, когда Штучка доступна из многих мест.",
		cn = "包含有奖励或可从包含部分中的其他内容获得的事物。\n在此处合并以减少来自许多可能重复来源。",
		-- TODO: tw = "",
	},
});
