local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[659301] = {
		readable = "Highland Redcap",
		model = 4884010,
		text = {
			en = "Highland Redcap",
			es = "[Highland Redcap]",
			mx = "[Highland Redcap]",
			de = "[Highland Redcap]",
			fr = "[Highland Redcap]",
			it = "[Highland Redcap]",
			pt = "[Highland Redcap]",
			ru = "[Highland Redcap]",
			ko = "[Highland Redcap]",
			cn = "[Highland Redcap]",
			tw = "[Highland Redcap]",
		},
	},
	[659302] = {
		readable = "Marshy Redcap",
		model = 4884010,
		text = {
			en = "Marshy Redcap",
			es = "[Marshy Redcap]",
			mx = "[Marshy Redcap]",
			de = "[Marshy Redcap]",
			fr = "[Marshy Redcap]",
			it = "[Marshy Redcap]",
			pt = "[Marshy Redcap]",
			ru = "[Marshy Redcap]",
			ko = "[Marshy Redcap]",
			cn = "[Marshy Redcap]",
			tw = "[Marshy Redcap]",
		},
	},
	[659303] = {
		readable = "Dusty Redcap",
		model = 4884010,
		text = {
			en = "Dusty Redcap",
			es = "[Dusty Redcap]",
			mx = "[Dusty Redcap]",
			de = "[Dusty Redcap]",
			fr = "[Dusty Redcap]",
			it = "[Dusty Redcap]",
			pt = "[Dusty Redcap]",
			ru = "[Dusty Redcap]",
			ko = "[Dusty Redcap]",
			cn = "[Dusty Redcap]",
			tw = "[Dusty Redcap]",
		},
	},
	[659304] = {
		readable = "Airy Redcap",
		model = 4884010,
		text = {
			en = "Airy Redcap",
			es = "[Airy Redcap]",
			mx = "[Airy Redcap]",
			de = "[Airy Redcap]",
			fr = "[Airy Redcap]",
			it = "[Airy Redcap]",
			pt = "[Airy Redcap]",
			ru = "[Airy Redcap]",
			ko = "[Airy Redcap]",
			cn = "[Airy Redcap]",
			tw = "[Airy Redcap]",
		},
	},
})
do ObjectDB[objectID] = objectData; end
