local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[588950] = {
		readable = "Tusk Taker's Taken Tusk Trophy",
		model = 4293060,
		text = {
			en = "Tusk Taker's Taken Tusk Trophy",
			es = "Trofeo de colmillos robado de Robacolmillos",
			mx = "[Tusk Taker's Taken Tusk Trophy]",
			de = "Hauerbrechers Hauertrophäe",
			fr = "Trophée de défenses volé à la voleuse de défenses",
			it = "Trofeo della Zanna Presa di Prendizanne",
			pt = "Prêmio de Presa Apreendido",
			ru = "Краденый клык Клыкокрада",
			ko = "[Tusk Taker's Taken Tusk Trophy]",
			cn = "夺牙魔的獠牙战利品",
			tw = "奪牙者的奪來的獠牙戰利品",
		},
	},
	[605174] = {
		readable = "Haunted Weapon Rack",
		model = 6212430,
		text = {
			en = "Haunted Weapon Rack",
			es = "Expositor de armas embrujado",
			mx = "[Haunted Weapon Rack]",
			de = "Heimgesuchtes Waffenregal",
			fr = "Râtelier d’armes hanté",
			it = "[Haunted Weapon Rack]",
			pt = "[Haunted Weapon Rack]",
			ru = "Одержимая оружейная стойка",
			ko = "귀신 들린 무기 선반",
			cn = "[Haunted Weapon Rack]",
			tw = "[Haunted Weapon Rack]",
		},
	},
	[612274] = {
		readable = "Portal to K'aresh",
		model = 166523,
		text = {
			en = "Portal to K'aresh",
			es = "Portal a K'aresh",
			mx = "Portal a K'aresh",
			de = "Portal nach K'aresh",
			fr = "Portail vers K’aresh",
			it = "Portale per K'aresh",
			pt = "Portal para K'aresh",
			ru = "Портал на К'ареш",
			ko = "크아레쉬로 통하는 차원문",
			cn = "通往卡雷什的传送门",
			tw = "凱瑞西傳送門",
		},
	},
	[613268] = {
		readable = "Burning Torch",
		model = 896448,
		text = {
			en = "Burning Torch",
			es = "Antorcha encendida",
			mx = "Antorcha ardiente",
			de = "Brennende Fackel",
			fr = "Torche ardente",
			it = "Torcia Accesa",
			pt = "Tocha Ardente",
			ru = "Горящий факел",
			ko = "[Burning Torch]",
			cn = "燃烧的火炬",
			tw = "燃燒的火炬",
		},
	},
	[613789] = {
		readable = "Paint Globule",
		model = 5465249,
		text = {
			en = "Paint Globule",
			es = "Pegote de pintura",
			mx = "Glóbulo de pintura",
			de = "Farbkugel",
			fr = "Globule de peinture",
			it = "Globulo di Vernice",
			pt = "Glóbulo de Tinta",
			ru = "Сгусток краски",
			ko = "물감 방울",
			cn = "颜料液球",
			tw = "顏料水珠",
		},
	},
	[613852] = {
		readable = "Potion of Unquestionable Strength",
		model = 240973,
		text = {
			en = "Potion of Unquestionable Strength",
			es = "Poción de fuerza incuestionable",
			mx = "[Potion of Unquestionable Strength]",
			de = "Trank der unbestrittenen Stärke",
			fr = "Potion de force incontestable",
			it = "Pozione della Forza Innegabile",
			pt = "Poção de Força Inquestionável",
			ru = "Зелье несомненной силы",
			ko = "의심의 여지 없는 힘의 물약",
			cn = "毋庸置疑的强力药水",
			tw = "無庸置疑力量藥水",
		},
	},
	[613945] = {
		readable = "Orb of Translocation",
		model = 6024535,
		text = {
			en = "Orb of Translocation",
			es = "Orbe de traslado",
			mx = "Orbe de traslado",
			de = "Translokationskugel",
			fr = "Orbe de transposition",
			it = "Sfera di Traslocazione",
			pt = "Orbe de Deslocamento",
			ru = "Сфера транслокации",
			ko = "순간이동의 보주",
			cn = "传送宝珠",
			tw = "傳送之門",
		},
	},
	[614893] = {
		readable = "Paint Bowl",
		model = 6326881,
		text = {
			en = "Paint Bowl",
			es = "Cuenco de pintura",
			mx = "Cuenco de pintura",
			de = "Farbschale",
			fr = "Bol de peinture",
			it = "Scodella di Vernice",
			pt = "Tigela de Tinta",
			ru = "Миска для краски",
			ko = "물감 사발",
			cn = "颜料碗",
			tw = "顏料碗",
		},
	},
	[616055] = {
		readable = "Forgotten Cache",
		model = 6017293,
		text = {
			en = "Forgotten Cache",
			es = "Alijo olvidado",
			mx = "Alijo olvidado",
			de = "Vergessene Truhe",
			fr = "Cache oubliée",
			it = "Cassa Dimenticata",
			pt = "Arca Esquecida",
			ru = "Забытый нефрит",
			ko = "잊힌 보관함",
			cn = "被遗忘的宝箱",
			tw = "被遺忘的儲物箱",
		},
	},
	[616916] = {
		readable = "Eye of the Void",
		model = 3193614,
		text = {
			en = "Eye of the Void",
			es = "Ojo del Vacío",
			mx = "Ojo del Vacío",
			de = "Auge der Leere",
			fr = "Œil du Vide",
			it = "Occhio del Vuoto",
			pt = "Olho do Caos",
			ru = "Око Бездны",
			ko = "공허의 눈",
			cn = "虚空之眼",
			tw = "虛無之眼",
		},
	},
	[616917] = {
		readable = "Cosmic Void",
		model = 5045776,
		text = {
			en = "Cosmic Void",
			es = "Vacío Cósmico",
			mx = "Vacío cósmico",
			de = "Kosmische Leere",
		},
	},
})
do ObjectDB[objectID] = objectData; end
