local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[505258] = {
		readable = "Pestilential Necroray",
		model = 1570694,
		text = {
			en = "Pestilential Necroray",
			es = "[Pestilential Necroray]",
			mx = "Necrorraya pestífero",
			de = "[Pestilential Necroray]",
			fr = "[Pestilential Necroray]",
			it = "[Pestilential Necroray]",
			pt = "[Pestilential Necroray]",
			ru = "[Pestilential Necroray]",
			ko = "[Pestilential Necroray]",
			cn = "[Pestilential Necroray]",
			tw = "[Pestilential Necroray]",
		},
	},
	[507176] = {
		readable = "Crate of Food",
		model = 3450703,
		text = {
			en = "Crate of Food",
			es = "[Crate of Food]",
			mx = "Cajón de comida",
			de = "[Crate of Food]",
			fr = "[Crate of Food]",
			it = "[Crate of Food]",
			pt = "[Crate of Food]",
			ru = "[Crate of Food]",
			ko = "[Crate of Food]",
			cn = "[Crate of Food]",
			tw = "[Crate of Food]",
		},
	},
	[507178] = {
		readable = "Bowl of Succulents",
		model = 3870815,
		text = {
			en = "Bowl of Succulents",
			es = "[Bowl of Succulents]",
			mx = "Cuenco de suculentas",
			de = "[Bowl of Succulents]",
			fr = "[Bowl of Succulents]",
			it = "[Bowl of Succulents]",
			pt = "[Bowl of Succulents]",
			ru = "[Bowl of Succulents]",
			ko = "[Bowl of Succulents]",
			cn = "[Bowl of Succulents]",
			tw = "[Bowl of Succulents]",
		},
	},
	[507219] = {
		readable = "Slab of Meat",
		model = 4254401,
		text = {
			en = "Slab of Meat",
			es = "[Slab of Meat]",
			mx = "Porción de carne",
			de = "[Slab of Meat]",
			fr = "[Slab of Meat]",
			it = "[Slab of Meat]",
			pt = "[Slab of Meat]",
			ru = "[Slab of Meat]",
			ko = "[Slab of Meat]",
			cn = "[Slab of Meat]",
			tw = "[Slab of Meat]",
		},
	},
	[507220] = {
		readable = "Chopped Plants",
		model = 3870813,
		text = {
			en = "Chopped Plants",
			es = "[Chopped Plants]",
			mx = "Plantas cortadas",
			de = "[Chopped Plants]",
			fr = "[Chopped Plants]",
			it = "[Chopped Plants]",
			pt = "[Chopped Plants]",
			ru = "[Chopped Plants]",
			ko = "[Chopped Plants]",
			cn = "[Chopped Plants]",
			tw = "[Chopped Plants]",
		},
	},
})
do ObjectDB[objectID] = objectData; end
