local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[589205] = {
		readable = "A Lost Hunting Knife",
		model = 6252856,
		text = {
			en = "A Lost Hunting Knife",
			es = "[A Lost Hunting Knife]",
			mx = "[A Lost Hunting Knife]",
			de = "Ein verlorenes Jagdmesser",
			fr = "Couteau de chasse perdu",
			it = "[A Lost Hunting Knife]",
			pt = "[A Lost Hunting Knife]",
			ru = "[A Lost Hunting Knife]",
			ko = "[A Lost Hunting Knife]",
			cn = "[A Lost Hunting Knife]",
			tw = "[A Lost Hunting Knife]",
		},
	},
	[590801] = {
		readable = "A Rolled Up Pillow",
		model = 5161738,
		text = {
			en = "A Rolled Up Pillow",
			es = "Almohada enrollada",
			mx = "[A Rolled Up Pillow]",
			de = "Ein zusammengerolltes Kissen",
			fr = "Oreiller enroulé",
			it = "[A Rolled Up Pillow]",
			pt = "[A Rolled Up Pillow]",
			ru = "[A Rolled Up Pillow]",
			ko = "[A Rolled Up Pillow]",
			cn = "[A Rolled Up Pillow]",
			tw = "[A Rolled Up Pillow]",
		},
	},
	[612038] = {
		readable = "Agitated Tome",
		model = 4556819,
		text = {
			en = "Agitated Tome",
			es = "Escrito perturbado",
			mx = "Tomo agitado",
			de = "Aufgebrachter Foliant",
			fr = "Tome agité",
			it = "Tomo Agitato",
			pt = "Tomos Agitados",
			ru = "Потревоженный фолиант",
			ko = "격랑의 마법서",
			cn = "焦躁的书籍",
			tw = "激動的典籍",
		},
	},
	[612079] = {
		readable = "Foul Carcass",
		model = 124640,
		text = {
			en = "Foul Carcass",
			es = "[Foul Carcass]",
			mx = "[Foul Carcass]",
			de = "[Foul Carcass]",
			fr = "[Foul Carcass]",
			it = "[Foul Carcass]",
			pt = "[Foul Carcass]",
			ru = "[Foul Carcass]",
			ko = "[Foul Carcass]",
			cn = "[Foul Carcass]",
			tw = "[Foul Carcass]",
		},
	},
	[612081] = {
		readable = "Foul Carcass",
		model = 124640,
		text = {
			en = "Foul Carcass",
			es = "[Foul Carcass]",
			mx = "[Foul Carcass]",
			de = "[Foul Carcass]",
			fr = "[Foul Carcass]",
			it = "[Foul Carcass]",
			pt = "[Foul Carcass]",
			ru = "[Foul Carcass]",
			ko = "[Foul Carcass]",
			cn = "[Foul Carcass]",
			tw = "[Foul Carcass]",
		},
	},
	[612270] = {
		readable = "Embedded Spear",
		model = 6935789,
		text = {
			en = "Embedded Spear",
			es = "[Embedded Spear]",
			mx = "[Embedded Spear]",
			de = "[Embedded Spear]",
			fr = "[Embedded Spear]",
			it = "[Embedded Spear]",
			pt = "[Embedded Spear]",
			ru = "[Embedded Spear]",
			ko = "[Embedded Spear]",
			cn = "[Embedded Spear]",
			tw = "[Embedded Spear]",
		},
	},
	[612282] = {
		readable = "Stolen Meat",
		model = 4254400,
		text = {
			en = "Stolen Meat",
			es = "Stolen Meat",
			mx = "Stolen Meat",
			de = "Stolen Meat",
			fr = "Stolen Meat",
			it = "Stolen Meat",
			pt = "Stolen Meat",
			ru = "Stolen Meat",
			ko = "Stolen Meat",
			cn = "Stolen Meat",
			tw = "Stolen Meat",
		},
	},
	[612891] = {
		readable = "Bloody Sack",
		model = 977078,
		text = {
			en = "Bloody Sack",
			es = "[Bloody Sack]",
			mx = "[Bloody Sack]",
			de = "[Bloody Sack]",
			fr = "[Bloody Sack]",
			it = "[Bloody Sack]",
			pt = "[Bloody Sack]",
			ru = "[Bloody Sack]",
			ko = "[Bloody Sack]",
			cn = "[Bloody Sack]",
			tw = "[Bloody Sack]",
		},
	},
	[613252] = {
		readable = "Triple-Locked Safebox",
		model = 875132,
		text = {
			en = "Triple-Locked Safebox",
			es = "Caja fuerte con triple cierre",
			mx = "Caja fuerte de triple cerrojo",
			de = "Dreifach verriegelte Truhe",
			fr = "Coffre-fort extra-fort",
			it = "Cassetta di Sicurezza con Serratura Tripla",
			pt = "Cofre com Tranca Tripla",
			ru = "Сейф с тремя замками",
		},
	},
})
do ObjectDB[objectID] = objectData; end
