local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[526844] = {
		readable = "Arcane Remnant",
		model = 5916229,
		text = {
			en = "Arcane Remnant",
			es = "Arcane Remnant",
			mx = "Arcane Remnant",
			de = "Arcane Remnant",
			fr = "Arcane Remnant",
			it = "Arcane Remnant",
			pt = "Arcane Remnant",
			ru = "Arcane Remnant",
			ko = "Arcane Remnant",
			cn = "Arcane Remnant",
			tw = "Arcane Remnant",
		},
	},
	[557572] = {
		readable = "Nutrient Rich Dirt",
		model = 189528,
		text = {
			en = "Nutrient Rich Dirt",
			es = "Nutrient Rich Dirt",
			mx = "Nutrient Rich Dirt",
			de = "Nutrient Rich Dirt",
			fr = "Nutrient Rich Dirt",
			it = "Nutrient Rich Dirt",
			pt = "Nutrient Rich Dirt",
			ru = "Nutrient Rich Dirt",
			ko = "Nutrient Rich Dirt",
			cn = "Nutrient Rich Dirt",
			tw = "Nutrient Rich Dirt",
		},
	},
	[560300] = {
		readable = "Unpublished Manuscript",
		text = {
			en = "Unpublished Manuscript",
			es = "Unpublished Manuscript",
			mx = "Unpublished Manuscript",
			de = "Unpublished Manuscript",
			fr = "Unpublished Manuscript",
			it = "Unpublished Manuscript",
			pt = "Unpublished Manuscript",
			ru = "Unpublished Manuscript",
			ko = "Unpublished Manuscript",
			cn = "Unpublished Manuscript",
			tw = "Unpublished Manuscript",
		},
	},
})
do ObjectDB[objectID] = objectData; end
