local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[531477] = {
		readable = "Coalesced Light",
		model = 5536353,
		text = {
			en = "Coalesced Light",
			es = "Luz fusionada",
			mx = "[Coalesced Light]",
			de = "Verschmolzenes Licht",
			fr = "Lumière amalgamée",
			it = "Luce Condensata",
			pt = "Luz Coalescida",
			ru = "Сгусток Света",
			ko = "[Coalesced Light]",
			cn = "凝聚圣光",
			tw = "[Coalesced Light]",
		},
	},
	[531507] = {
		readable = "Depleted Wardbreaker",
		model = 2059988,
		text = {
			en = "Depleted Wardbreaker",
			es = "Romperresguardos agotado",
			mx = "Romperresguardos agotado",
			de = "Erschöpfter Schutzbrecher",
			fr = "Brise-protection épuisé",
			it = "Spezzaguardia Esaurito",
			pt = "Quebra-guaridas Exaurido",
			ru = "Разряженный разрушитель оберегов",
			ko = "소진된 수호물파괴기",
			cn = "枯竭的结界破坏者",
			tw = "耗盡的結界破除裝置",
		},
	},
	[536899] = {
		readable = "Dropped Tome",
		model = 6081188,
		text = {
			en = "Dropped Tome",
			es = "Tomo caído",
			mx = "Tomo abandonado",
			de = "Fallen gelassener Foliant",
			fr = "Tome égaré",
			it = "Tomo Caduto",
			pt = "Tomo Largado",
			ru = "Упавший фолиант",
			ko = "떨어뜨린 고서",
			cn = "掉落的书典",
			tw = "掉落的典籍",
		},
	},
	[536903] = {
		readable = "Dropped Tome",
		model = 6025931,
		text = {
			en = "Dropped Tome",
			es = "Tomo caído",
			mx = "Tomo abandonado",
			de = "Fallen gelassener Foliant",
			fr = "Tome égaré",
			it = "Tomo Caduto",
			pt = "Tomo Largado",
			ru = "Упавший фолиант",
			ko = "떨어뜨린 고서",
			cn = "掉落的书典",
			tw = "掉落的典籍",
		},
	},
	[537177] = {
		readable = "Strange Lightbloom Plant",
		model = 6018376,
		text = {
			en = "Strange Lightbloom Plant",
			es = "Planta de flor de Luz extraña",
			mx = "Planta floraluz extraña",
			de = "Seltsame Lichtblüte",
			fr = "Pied luméclat étrange",
			it = "Strana Pianta della Fioritura di Luce",
			pt = "Planta de Floraluz Estranha",
			ru = "Странный побег светоцвета",
			ko = "특이한 빛만개 식물",
			cn = "奇怪的光绽植物",
			tw = "奇怪的光綻植物",
		},
	},
	[537178] = {
		readable = "Strange Lightbloom Plant",
		model = 5913403,
		text = {
			en = "Strange Lightbloom Plant",
			es = "Planta de flor de Luz extraña",
			mx = "Planta floraluz extraña",
			de = "Seltsame Lichtblüte",
			fr = "Pied luméclat étrange",
			it = "Strana Pianta della Fioritura di Luce",
			pt = "Planta de Floraluz Estranha",
			ru = "Странный побег светоцвета",
			ko = "특이한 빛만개 식물",
			cn = "奇怪的光绽植物",
			tw = "奇怪的光綻植物",
		},
	},
	[537179] = {
		readable = "Strange Lightbloom Plant",
		model = 6018378,
		text = {
			en = "Strange Lightbloom Plant",
			es = "Planta de flor de Luz extraña",
			mx = "Planta floraluz extraña",
			de = "Seltsame Lichtblüte",
			fr = "Pied luméclat étrange",
			it = "Strana Pianta della Fioritura di Luce",
			pt = "Planta de Floraluz Estranha",
			ru = "Странный побег светоцвета",
			ko = "특이한 빛만개 식물",
			cn = "奇怪的光绽植物",
			tw = "奇怪的光綻植物",
		},
	},
	[540500] = {
		readable = "Brewfest Resources",
		model = 3936818,
		text = {
			en = "Brewfest Resources",
			es = "Recursos de la Fiesta de la Cerveza",
			mx = "Recursos de la Fiesta de la Cerveza",
			de = "Braufestressourcen",
			fr = "Ressources de la fête des Brasseurs",
			it = "Risorse della Festa della Birra",
			pt = "Materiais da CervaFest",
			ru = "Припасы Хмельного фестиваля",
			ko = "가을 축제 자원",
			cn = "[Brewfest Resources]",
			tw = "啤酒節資源",
		},
	},
	[543115] = {
		readable = "Funny Candle",
		model = 5900860,
		text = {
			en = "Funny Candle",
			es = "Vela interesante",
			mx = "Vela inusual",
			de = "Witzige Kerze",
			fr = "Bougie amusante",
			it = "Candela Divertente",
			pt = "Vela Engraçada",
			ru = "Странная свеча",
			ko = "괴상한 양초",
			cn = "滑稽的蜡烛",
			tw = "搞怪蠟燭",
		},
	},
	[543116] = {
		readable = "Funny Candle",
		model = 5900860,
		text = {
			en = "Funny Candle",
			es = "Vela interesante",
			mx = "Vela inusual",
			de = "Witzige Kerze",
			fr = "Bougie amusante",
			it = "Candela Divertente",
			pt = "Vela Engraçada",
			ru = "Странная свеча",
			ko = "괴상한 양초",
			cn = "滑稽的蜡烛",
			tw = "搞怪蠟燭",
		},
	},
	[544167] = {
		readable = "Grappling Hook Rope",
		model = 5516436,
		text = {
			en = "Grappling Hook Rope",
			es = "Cuerda de gancho",
			mx = "Cuerda de gancho de agarre",
		},
	},
})
do ObjectDB[objectID] = objectData; end
