local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[571070] = {
		readable = "Olemba Lumber",
		model = 6922313,
		text = {
			en = "Olemba Lumber",
			es = "Madera de olemba",
			mx = "Madera de olemba",
			de = "Olembaholz",
			fr = "Bois d’olemba",
			it = "Legname di Olemba",
			pt = "Lenha de Olemba",
			ru = "Древесина Олембы",
			ko = "올렘바 목재",
			cn = "奥雷巴木料",
			tw = "奧萊姆貝木材",
		},
	},
	[571071] = {
		readable = "Olemba Lumber",
		model = 6922313,
		text = {
			en = "Olemba Lumber",
			es = "Madera de olemba",
			mx = "Madera de olemba",
			de = "Olembaholz",
			fr = "Bois d’olemba",
			it = "Legname di Olemba",
			pt = "Lenha de Olemba",
			ru = "Древесина Олембы",
			ko = "올렘바 목재",
			cn = "奥雷巴木料",
			tw = "奧萊姆貝木材",
		},
	},
	[571213] = {
		readable = "Olemba Lumber",
		model = 6922313,
		text = {
			en = "Olemba Lumber",
			es = "Madera de olemba",
			mx = "Madera de olemba",
			de = "Olembaholz",
			fr = "Bois d’olemba",
			it = "Legname di Olemba",
			pt = "Lenha de Olemba",
			ru = "Древесина Олембы",
			ko = "올렘바 목재",
			cn = "奥雷巴木料",
			tw = "奧萊姆貝木材",
		},
	},
	[571345] = {
		readable = "Olemba Lumber",
		model = 6922313,
		text = {
			en = "Olemba Lumber",
			es = "Madera de olemba",
			mx = "Madera de olemba",
			de = "Olembaholz",
			fr = "Bois d’olemba",
			it = "Legname di Olemba",
			pt = "Lenha de Olemba",
			ru = "Древесина Олембы",
			ko = "올렘바 목재",
			cn = "奥雷巴木料",
			tw = "奧萊姆貝木材",
		},
	},
	[572094] = {
		readable = "Olemba Lumber",
		model = 6922313,
		text = {
			en = "Olemba Lumber",
			es = "Madera de olemba",
			mx = "Madera de olemba",
			de = "Olembaholz",
			fr = "Bois d’olemba",
			it = "Legname di Olemba",
			pt = "Lenha de Olemba",
			ru = "Древесина Олембы",
			ko = "올렘바 목재",
			cn = "奥雷巴木料",
			tw = "奧萊姆貝木材",
		},
	},
	[572869] = {
		readable = "Olemba Lumber",
		model = 6922313,
		text = {
			en = "Olemba Lumber",
			es = "Madera de olemba",
			mx = "Madera de olemba",
			de = "Olembaholz",
			fr = "Bois d’olemba",
			it = "Legname di Olemba",
			pt = "Lenha de Olemba",
			ru = "Древесина Олембы",
			ko = "올렘바 목재",
			cn = "奥雷巴木料",
			tw = "奧萊姆貝木材",
		},
	},
	[572995] = {
		readable = "Olemba Lumber",
		model = 6922313,
		text = {
			en = "Olemba Lumber",
			es = "Madera de olemba",
			mx = "Madera de olemba",
			de = "Olembaholz",
			fr = "Bois d’olemba",
			it = "Legname di Olemba",
			pt = "Lenha de Olemba",
			ru = "Древесина Олембы",
			ko = "올렘바 목재",
			cn = "奥雷巴木料",
			tw = "奧萊姆貝木材",
		},
	},
})
do ObjectDB[objectID] = objectData; end
