local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[499054] = {
		readable = "Alleria's Void Portal",
		model = 1624366,
		text = {
			en = "Alleria's Void Portal",
			es = "Portal del Vacío de Alleria",
			mx = "Portal del Vacío de Alleria",
			de = "Allerias Leerenportal",
			fr = "Portail du Vide d’Alleria Coursevent",
			it = "Portale del Vuoto di Alleria",
			pt = "Portal do Caos de Alleria",
			ru = "Врата Бездны Аллерии",
			ko = "알레리아의 공허의 차원문",
			cn = "奥蕾莉亚的虚空传送门",
			tw = "艾蘭里亞的虛無傳送門",
		},
	},
	[499258] = {
		readable = "Ancestral K'areshi Relic",
		model = 3998007,
		text = {
			en = "Ancestral K'areshi Relic",
			es = "Reliquia ancestral k'areshi",
			mx = "Reliquia k'areshi ancestral",
			de = "Ahnenrelikt der K'areshi",
			fr = "Ancienne relique k’areshi",
			it = "Reliquia K'areshi Ancestrale",
			pt = "Relíquia k'areshi Ancestral",
			ru = "Древняя к'арешская реликвия",
			ko = "선조의 크아레쉬 유물",
			cn = "先祖卡雷什遗物",
			tw = "祖傳凱瑞西聖物",
		},
	},
	[499259] = {
		readable = "Ancestral K'areshi Relic",
		model = 3998006,
		text = {
			en = "Ancestral K'areshi Relic",
			es = "Reliquia ancestral k'areshi",
			mx = "Reliquia k'areshi ancestral",
			de = "Ahnenrelikt der K'areshi",
			fr = "Ancienne relique k’areshi",
			it = "Reliquia K'areshi Ancestrale",
			pt = "Relíquia k'areshi Ancestral",
			ru = "Древняя к'арешская реликвия",
			ko = "선조의 크아레쉬 유물",
			cn = "先祖卡雷什遗物",
			tw = "祖傳凱瑞西聖物",
		},
	},
	[499260] = {
		readable = "Ancestral K'areshi Relic",
		model = 3998002,
		text = {
			en = "Ancestral K'areshi Relic",
			es = "Reliquia ancestral k'areshi",
			mx = "Reliquia k'areshi ancestral",
			de = "Ahnenrelikt der K'areshi",
			fr = "Ancienne relique k’areshi",
			it = "Reliquia K'areshi Ancestrale",
			pt = "Relíquia k'areshi Ancestral",
			ru = "Древняя к'арешская реликвия",
			ko = "선조의 크아레쉬 유물",
			cn = "先祖卡雷什遗物",
			tw = "祖傳凱瑞西聖物",
		},
	},
	[499261] = {
		readable = "Ancestral K'areshi Relic",
		model = 3998010,
		text = {
			en = "Ancestral K'areshi Relic",
			es = "Reliquia ancestral k'areshi",
			mx = "Reliquia k'areshi ancestral",
			de = "Ahnenrelikt der K'areshi",
			fr = "Ancienne relique k’areshi",
			it = "Reliquia K'areshi Ancestrale",
			pt = "Relíquia k'areshi Ancestral",
			ru = "Древняя к'арешская реликвия",
			ko = "선조의 크아레쉬 유물",
			cn = "先祖卡雷什遗物",
			tw = "祖傳凱瑞西聖物",
		},
	},
	[500705] = {
		readable = "Portal to Mmarl",
		model = 3540722,
		text = {
			en = "Portal to Mmarl",
			es = "Portal a Mmarl",
			mx = "Portal a Mmarl",
			de = "Portal nach Mmarl",
			fr = "Portail vers Mmarl",
			it = "Portale per Mmarn",
			pt = "Portal para Mmarl",
			ru = "Портал в Ммарл",
			ko = "므말로 통하는 차원문",
			cn = "通往姆玛尔的传送门",
			tw = "姆瑪爾傳送門",
		},
	},
	[500844] = {
		readable = "Portal to K'aresh",
		model = 3540722,
		text = {
			en = "Portal to K'aresh",
			es = "Portal a K'aresh",
			mx = "Portal a K'aresh",
			de = "Portal nach K'aresh",
			fr = "Portail vers K’aresh",
			it = "Portale per K'aresh",
			pt = "Portal para K'aresh",
			ru = "Портал в К'ареш",
			ko = "크아레쉬로 통하는 차원문",
			cn = "通往卡雷什的传送门",
			tw = "凱瑞西傳送門",
		},
	},
	[504225] = {
		readable = "Portal to K'aresh",
		model = 3540722,
		text = {
			en = "Portal to K'aresh",
			es = "Portal a K'aresh",
			mx = "Portal a K'aresh",
			de = "Portal nach K'aresh",
			fr = "Portail vers K’aresh",
			it = "Portale per K'aresh",
			pt = "Portal para K'aresh",
			ru = "Портал в К'ареш",
			ko = "크아레쉬로 통하는 차원문",
			cn = "通往卡雷什的传送门",
			tw = "凱瑞西傳送門",
		},
	},
	[505191] = {
		readable = "Portal to Maldraxxus",
		model = 3540722,
		text = {
			en = "Portal to Maldraxxus",
			es = "Portal a Maldraxxus",
			mx = "Portal a Maldraxxus",
			de = "Portal nach Maldraxxus",
			fr = "Portail vers Maldraxxus",
			it = "Portale per Maldraxxus",
		},
	},
})
do ObjectDB[objectID] = objectData; end
