local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[525894] = {
		readable = "Voidstorm Leather Sample",
		model = 3619352,
		text = {
			en = "Voidstorm Leather Sample",
			es = "Muestra de cuero de Tormenta del Vacío",
			mx = "[Voidstorm Leather Sample]",
			de = "Leerensturmlederprobe",
			fr = "Échantillon de cuir de la tempête du Vide",
			it = "Campione di Cuoio della Tempesta del Vuoto",
			pt = "[Voidstorm Leather Sample]",
			ru = "Образец кожи из Бури Бездны",
			ko = "[Voidstorm Leather Sample]",
			cn = "[Voidstorm Leather Sample]",
			tw = "[Voidstorm Leather Sample]",
		},
	},
	[531478] = {
		readable = "Misplaced Tome",
		model = 6081188,
		text = {
			en = "Misplaced Tome",
			es = "Tomo extraviado",
			mx = "[Misplaced Tome]",
			de = "Verlegter Foliant",
			fr = "Tome perdu",
			it = "[Misplaced Tome]",
			pt = "Tomo Fora do Lugar",
			ru = "Потерянный фолиант",
			ko = "[Misplaced Tome]",
			cn = "[Misplaced Tome]",
			tw = "[Misplaced Tome]",
		},
	},
	[571166] = {
		readable = "Glowing Moth",
		model = 124932,
		text = {
			en = "Glowing Moth",
			es = "Polilla resplandeciente",
			mx = "Polilla brillante",
			de = "Leuchtende Motte",
			fr = "Phalène luminescent",
			it = "Falena Luminosa",
			pt = "Mariposa Brilhante",
			ru = "Светящийся мотылек",
			ko = "빛나는 나방",
			cn = "发光的飞蛾",
			tw = "發光蛾",
		},
	},
	[571167] = {
		readable = "Glowing Moth",
		model = 124932,
		text = {
			en = "Glowing Moth",
			es = "Polilla resplandeciente",
			mx = "Polilla brillante",
			de = "Leuchtende Motte",
			fr = "Phalène luminescent",
			it = "Falena Luminosa",
			pt = "Mariposa Brilhante",
			ru = "Светящийся мотылек",
			ko = "빛나는 나방",
			cn = "发光的飞蛾",
			tw = "發光蛾",
		},
	},
	[571168] = {
		readable = "Glowing Moth",
		model = 124932,
		text = {
			en = "Glowing Moth",
			es = "Polilla resplandeciente",
			mx = "Polilla brillante",
			de = "Leuchtende Motte",
			fr = "Phalène luminescent",
			it = "Falena Luminosa",
			pt = "Mariposa Brilhante",
			ru = "Светящийся мотылек",
			ko = "빛나는 나방",
			cn = "发光的飞蛾",
			tw = "發光蛾",
		},
	},
	[571170] = {
		readable = "Glowing Moth",
		model = 124932,
		text = {
			en = "Glowing Moth",
			es = "Polilla resplandeciente",
			mx = "Polilla brillante",
			de = "Leuchtende Motte",
			fr = "Phalène luminescent",
			it = "Falena Luminosa",
			pt = "Mariposa Brilhante",
			ru = "Светящийся мотылек",
			ko = "빛나는 나방",
			cn = "发光的飞蛾",
			tw = "發光蛾",
		},
	},
	[571171] = {
		readable = "Glowing Moth",
		model = 124932,
		text = {
			en = "Glowing Moth",
			es = "Polilla resplandeciente",
			mx = "Polilla brillante",
			de = "Leuchtende Motte",
			fr = "Phalène luminescent",
			it = "Falena Luminosa",
			pt = "Mariposa Brilhante",
			ru = "Светящийся мотылек",
			ko = "빛나는 나방",
			cn = "发光的飞蛾",
			tw = "發光蛾",
		},
	},
	[571172] = {
		readable = "Glowing Moth",
		model = 124932,
		text = {
			en = "Glowing Moth",
			es = "Polilla resplandeciente",
			mx = "Polilla brillante",
			de = "Leuchtende Motte",
			fr = "Phalène luminescent",
			it = "Falena Luminosa",
			pt = "Mariposa Brilhante",
			ru = "Светящийся мотылек",
			ko = "빛나는 나방",
			cn = "发光的飞蛾",
			tw = "發光蛾",
		},
	},
	[571174] = {
		readable = "Glowing Moth",
		model = 124932,
		text = {
			en = "Glowing Moth",
			es = "Polilla resplandeciente",
			mx = "Polilla brillante",
			de = "Leuchtende Motte",
			fr = "Phalène luminescent",
			it = "Falena Luminosa",
			pt = "Mariposa Brilhante",
			ru = "Светящийся мотылек",
			ko = "빛나는 나방",
			cn = "发光的飞蛾",
			tw = "發光蛾",
		},
	},
	[571176] = {
		readable = "Glowing Moth",
		model = 124932,
		text = {
			en = "Glowing Moth",
			es = "Polilla resplandeciente",
			mx = "Polilla brillante",
			de = "Leuchtende Motte",
			fr = "Phalène luminescent",
			it = "Falena Luminosa",
			pt = "Mariposa Brilhante",
			ru = "Светящийся мотылек",
			ko = "빛나는 나방",
			cn = "发光的飞蛾",
			tw = "發光蛾",
		},
	},
	[571177] = {
		readable = "Glowing Moth",
		model = 124932,
		text = {
			en = "Glowing Moth",
			es = "Polilla resplandeciente",
			mx = "Polilla brillante",
			de = "Leuchtende Motte",
			fr = "Phalène luminescent",
			it = "Falena Luminosa",
			pt = "Mariposa Brilhante",
			ru = "Светящийся мотылек",
			ko = "빛나는 나방",
			cn = "发光的飞蛾",
			tw = "發光蛾",
		},
	},
	[571178] = {
		readable = "Glowing Moth",
		model = 124932,
		text = {
			en = "Glowing Moth",
			es = "Polilla resplandeciente",
			mx = "Polilla brillante",
			de = "Leuchtende Motte",
			fr = "Phalène luminescent",
			it = "Falena Luminosa",
			pt = "Mariposa Brilhante",
			ru = "Светящийся мотылек",
			ko = "빛나는 나방",
			cn = "发光的飞蛾",
			tw = "發光蛾",
		},
	},
})
do ObjectDB[objectID] = objectData; end
