local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[619656] = {
		readable = "Vista Point",
		model = 4496829,
		text = {
			en = "Vista Point",
			es = "Punto de observación",
			mx = "[Vista Point]",
			de = "Aussichtspunkt",
			fr = "Point de vue",
			it = "[Vista Point]",
			pt = "[Vista Point]",
			ru = "[Vista Point]",
			ko = "[Vista Point]",
			cn = "[Vista Point]",
			tw = "[Vista Point]",
		},
	},
	[619657] = {
		readable = "Vista Point",
		model = 4496829,
		text = {
			en = "Vista Point",
			es = "Punto de observación",
			mx = "[Vista Point]",
			de = "Aussichtspunkt",
			fr = "Point de vue",
			it = "[Vista Point]",
			pt = "[Vista Point]",
			ru = "[Vista Point]",
			ko = "[Vista Point]",
			cn = "[Vista Point]",
			tw = "[Vista Point]",
		},
	},
	[619658] = {
		readable = "Vista Point",
		model = 4496829,
		text = {
			en = "Vista Point",
			es = "Punto de observación",
			mx = "[Vista Point]",
			de = "Aussichtspunkt",
			fr = "Point de vue",
			it = "[Vista Point]",
			pt = "[Vista Point]",
			ru = "[Vista Point]",
			ko = "[Vista Point]",
			cn = "[Vista Point]",
			tw = "[Vista Point]",
		},
	},
	[619659] = {
		readable = "Vista Point",
		model = 4496829,
		text = {
			en = "Vista Point",
			es = "Punto de observación",
			mx = "[Vista Point]",
			de = "Aussichtspunkt",
			fr = "Point de vue",
			it = "[Vista Point]",
			pt = "[Vista Point]",
			ru = "[Vista Point]",
			ko = "[Vista Point]",
			cn = "[Vista Point]",
			tw = "[Vista Point]",
		},
	},
	[619660] = {
		readable = "Vista Point",
		model = 4496829,
		text = {
			en = "Vista Point",
			es = "Punto de observación",
			mx = "[Vista Point]",
			de = "Aussichtspunkt",
			fr = "Point de vue",
			it = "[Vista Point]",
			pt = "[Vista Point]",
			ru = "[Vista Point]",
			ko = "[Vista Point]",
			cn = "[Vista Point]",
			tw = "[Vista Point]",
		},
	},
	[619661] = {
		readable = "Vista Point",
		model = 4496829,
		text = {
			en = "Vista Point",
			es = "[Vista Point]",
			mx = "[Vista Point]",
			de = "[Vista Point]",
			fr = "[Vista Point]",
			it = "[Vista Point]",
			pt = "[Vista Point]",
			ru = "[Vista Point]",
			ko = "[Vista Point]",
			cn = "[Vista Point]",
			tw = "[Vista Point]",
		},
	},
	[619662] = {
		readable = "Vista Point",
		model = 4496829,
		text = {
			en = "Vista Point",
			es = "[Vista Point]",
			mx = "[Vista Point]",
			de = "[Vista Point]",
			fr = "[Vista Point]",
			it = "[Vista Point]",
			pt = "[Vista Point]",
			ru = "[Vista Point]",
			ko = "[Vista Point]",
			cn = "[Vista Point]",
			tw = "[Vista Point]",
		},
	},
	[619663] = {
		readable = "Vista Point",
		model = 4496829,
		text = {
			en = "Vista Point",
			es = "[Vista Point]",
			mx = "[Vista Point]",
			de = "[Vista Point]",
			fr = "[Vista Point]",
			it = "[Vista Point]",
			pt = "[Vista Point]",
			ru = "[Vista Point]",
			ko = "[Vista Point]",
			cn = "[Vista Point]",
			tw = "[Vista Point]",
		},
	},
	[619664] = {
		readable = "Vista Point",
		model = 4496829,
		text = {
			en = "Vista Point",
			es = "[Vista Point]",
			mx = "[Vista Point]",
			de = "[Vista Point]",
		},
	},
})
do ObjectDB[objectID] = objectData; end
