local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[414639] = {
		readable = "Shadowblind Grouper",
		model = 1994490,
		text = {
			en = "Shadowblind Grouper",
			es = "Mero sombraceguera",
			mx = "Mero cegasombra",
			de = "Schattenblinder Barsch",
			fr = "Mérou sombrœil",
			it = "Cernia Ciecombra",
			pt = "Garoupa Sombracega",
			ru = "Окунь темной слепоты",
			ko = "어둠까막눈 농어",
			cn = "影盲石斑鱼",
			tw = "影盲石斑魚",
		},
	},
	[430347] = {
		readable = "Radiant Remnant",
		model = 5869303,
		text = {
			en = "Radiant Remnant",
			es = "Remanente radiante",
			mx = "Remanente radiante",
			de = "Strahlendes Überbleibsel",
			fr = "Vestige radieux",
			it = "Residuo Radioso",
			pt = "Resquício Radiante",
			ru = "Сияющие останки",
			ko = "광휘의 잔재",
			cn = "光耀残渣",
			tw = "輻光殘骸",
		},
	},
	[503639] = {
		readable = "Tools Chest",
		model = 5788112,
		text = {
			en = "Tools Chest",
			es = "Cofre de herramientas",
			mx = "Cofre de herramientas",
			de = "Werkzeugtruhe",
			fr = "Coffre à outils",
			it = "Cassetta degli Attrezzi",
			pt = "Baú de Ferramentas",
			ru = "Сундук с инструментами",
			ko = "연장 보관함",
			cn = "工具箱",
			tw = "工具箱",
		},
	},
	[543723] = {
		readable = "Dornic Fir Lumber",
		model = 6922313,
		text = {
			en = "Dornic Fir Lumber",
			es = "[Dornic Fir Lumber]",
			mx = "[Dornic Fir Lumber]",
			de = "[Dornic Fir Lumber]",
			fr = "[Dornic Fir Lumber]",
			it = "[Dornic Fir Lumber]",
			pt = "[Dornic Fir Lumber]",
			ru = "[Dornic Fir Lumber]",
			ko = "[Dornic Fir Lumber]",
			cn = "[Dornic Fir Lumber]",
			tw = "[Dornic Fir Lumber]",
		},
	},
	[551833] = {
		readable = "Dragonpine Lumber",
		model = 6922313,
		text = {
			en = "Dragonpine Lumber",
			es = "[Dragonpine Lumber]",
			mx = "[Dragonpine Lumber]",
			de = "[Dragonpine Lumber]",
			fr = "[Dragonpine Lumber]",
			it = "[Dragonpine Lumber]",
			pt = "[Dragonpine Lumber]",
			ru = "[Dragonpine Lumber]",
			ko = "[Dragonpine Lumber]",
			cn = "[Dragonpine Lumber]",
			tw = "[Dragonpine Lumber]",
		},
	},
	[553616] = {
		readable = "Arden Lumber",
		model = 6922313,
		text = {
			en = "Arden Lumber",
			es = "[Arden Lumber]",
			mx = "[Arden Lumber]",
			de = "[Arden Lumber]",
			fr = "[Arden Lumber]",
			it = "[Arden Lumber]",
			pt = "[Arden Lumber]",
			ru = "[Arden Lumber]",
			ko = "[Arden Lumber]",
			cn = "[Arden Lumber]",
			tw = "[Arden Lumber]",
		},
	},
	[556425] = {
		readable = "Darkpine Lumber",
		model = 6922313,
		text = {
			en = "Darkpine Lumber",
			es = "[Darkpine Lumber]",
			mx = "[Darkpine Lumber]",
			de = "[Darkpine Lumber]",
			fr = "[Darkpine Lumber]",
			it = "[Darkpine Lumber]",
			pt = "[Darkpine Lumber]",
			ru = "[Darkpine Lumber]",
			ko = "[Darkpine Lumber]",
			cn = "[Darkpine Lumber]",
			tw = "[Darkpine Lumber]",
		},
	},
	[559409] = {
		readable = "Fel-Touched Lumber",
		model = 6922313,
		text = {
			en = "Fel-Touched Lumber",
			es = "[Fel-Touched Lumber]",
			mx = "[Fel-Touched Lumber]",
			de = "[Fel-Touched Lumber]",
			fr = "[Fel-Touched Lumber]",
			it = "[Fel-Touched Lumber]",
			pt = "[Fel-Touched Lumber]",
			ru = "[Fel-Touched Lumber]",
			ko = "[Fel-Touched Lumber]",
			cn = "[Fel-Touched Lumber]",
			tw = "[Fel-Touched Lumber]",
		},
	},
	[562440] = {
		readable = "Bamboo Lumber",
		model = 6922313,
		text = {
			en = "Bamboo Lumber",
			es = "[Bamboo Lumber]",
			mx = "[Bamboo Lumber]",
			de = "[Bamboo Lumber]",
			fr = "[Bamboo Lumber]",
			it = "[Bamboo Lumber]",
			pt = "[Bamboo Lumber]",
			ru = "[Bamboo Lumber]",
			ko = "[Bamboo Lumber]",
			cn = "[Bamboo Lumber]",
			tw = "[Bamboo Lumber]",
		},
	},
	[569722] = {
		readable = "Coldwind Lumber",
		model = 6922313,
		text = {
			en = "Coldwind Lumber",
			es = "[Coldwind Lumber]",
			mx = "[Coldwind Lumber]",
			de = "[Coldwind Lumber]",
			fr = "[Coldwind Lumber]",
			it = "[Coldwind Lumber]",
			pt = "[Coldwind Lumber]",
			ru = "[Coldwind Lumber]",
			ko = "[Coldwind Lumber]",
			cn = "[Coldwind Lumber]",
			tw = "[Coldwind Lumber]",
		},
	},
	[572129] = {
		readable = "Olemba Lumber",
		model = 6922313,
		text = {
			en = "Olemba Lumber",
			es = "[Olemba Lumber]",
			mx = "[Olemba Lumber]",
			de = "[Olemba Lumber]",
			fr = "[Olemba Lumber]",
			it = "[Olemba Lumber]",
			pt = "[Olemba Lumber]",
			ru = "[Olemba Lumber]",
			ko = "[Olemba Lumber]",
			cn = "[Olemba Lumber]",
			tw = "[Olemba Lumber]",
		},
	},
	[575032] = {
		readable = "Ironwood Lumber",
		model = 6922313,
		text = {
			en = "Ironwood Lumber",
			es = "[Ironwood Lumber]",
			mx = "[Ironwood Lumber]",
			de = "[Ironwood Lumber]",
			fr = "[Ironwood Lumber]",
			it = "[Ironwood Lumber]",
			pt = "[Ironwood Lumber]",
			ru = "[Ironwood Lumber]",
			ko = "[Ironwood Lumber]",
			cn = "[Ironwood Lumber]",
			tw = "[Ironwood Lumber]",
		},
	},
	[578160] = {
		readable = "Ashwood Lumber",
		model = 6922313,
		text = {
			en = "Ashwood Lumber",
			es = "[Ashwood Lumber]",
			mx = "[Ashwood Lumber]",
			de = "[Ashwood Lumber]",
			fr = "[Ashwood Lumber]",
			it = "[Ashwood Lumber]",
			pt = "[Ashwood Lumber]",
			ru = "[Ashwood Lumber]",
			ko = "[Ashwood Lumber]",
			cn = "[Ashwood Lumber]",
			tw = "[Ashwood Lumber]",
		},
	},
})
do ObjectDB[objectID] = objectData; end
