local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[571327] = {
		readable = "Glowing Moth",
		model = 124932,
		text = {
			en = "Glowing Moth",
			es = "Polilla resplandeciente",
			mx = "Polilla brillante",
			de = "Leuchtende Motte",
			fr = "Phalène luminescent",
			it = "Falena Luminosa",
			pt = "Mariposa Brilhante",
			ru = "Светящийся мотылек",
			ko = "빛나는 나방",
			cn = "发光的飞蛾",
			tw = "發光蛾",
		},
	},
	[571328] = {
		readable = "Glowing Moth",
		model = 124932,
		text = {
			en = "Glowing Moth",
			es = "Polilla resplandeciente",
			mx = "Polilla brillante",
			de = "Leuchtende Motte",
			fr = "Phalène luminescent",
			it = "Falena Luminosa",
			pt = "Mariposa Brilhante",
			ru = "Светящийся мотылек",
			ko = "빛나는 나방",
			cn = "发光的飞蛾",
			tw = "發光蛾",
		},
	},
	[574587] = {
		readable = "Lilaju's Hiding Spot",
		model = 204112,
		text = {
			en = "Lilaju's Hiding Spot",
			es = "Escondite de Lilaju",
			mx = "[Lilaju's Hiding Spot]",
			de = "Lilajus Versteck",
			fr = "Cachette de Lilaju",
			it = "Nascondiglio di Lilaju",
			pt = "Esconderijo de Lilaju",
			ru = "Укрытие Лиладжу",
			ko = "[Lilaju's Hiding Spot]",
			cn = "利拉祖的藏身处",
			tw = "莉拉菊的藏身處",
		},
	},
	[627489] = {
		readable = "Forgotten Button",
		model = 5737987,
		text = {
			en = "Forgotten Button",
			es = "[Forgotten Button]",
			mx = "[Forgotten Button]",
			de = "Vergessener Knopf",
			fr = "Bouton oublié",
			it = "[Forgotten Button]",
			pt = "Botão Esquecido",
			ru = "Забытая пуговица",
			ko = "[Forgotten Button]",
			cn = "[Forgotten Button]",
			tw = "[Forgotten Button]",
		},
	},
	[633792] = {
		readable = "Message in a Bottle",
		model = 1852966,
		text = {
			en = "Message in a Bottle",
			es = "Mensaje en una botella",
			mx = "Mensaje en una botella",
			de = "Flaschenpost",
			fr = "Message dans une bouteille",
			it = "Messaggio nella Bottiglia",
			pt = "Mensagem na Garrafa",
			ru = "Послание в бутылке",
			ko = "병에 든 쪽지",
			cn = "瓶中信",
			tw = "瓶中信",
		},
	},
	[633805] = {
		readable = "Hastily-Scribbled Note",
		model = 5975119,
		text = {
			en = "Hastily-Scribbled Note",
			es = "Nota garabateada apresuradamente",
			mx = "Nota garabateada apresuradamente",
			de = "Hastig geschriebene Notiz",
			fr = "Note griffonnée à la hâte",
			it = "Appunti Scribacchiati di Fretta",
			pt = "Bilhete Rabiscado às Pressas",
			ru = "Нацарапанная в спешке записка",
			ko = "급히 휘갈긴 쪽지",
			cn = "匆忙写下的笔记",
			tw = "匆忙寫下的紙條",
		},
	},
	[633814] = {
		readable = "Scrap of Singed Paper",
		model = 4373475,
		text = {
			en = "Scrap of Singed Paper",
			es = "Trozo de papel chamuscado",
			mx = "Trozo de papel chamuscado",
			de = "Angesengter Papierfetzen",
			fr = "Morceau de papier brûlé",
			it = "Brandello di Carta Bruciata",
			pt = "Pedaço de Papel Chamuscado",
			ru = "Клочок обгоревшей бумаги",
			ko = "그을린 종잇조각",
			cn = "烧焦的纸片",
			tw = "燒焦的碎紙片",
		},
	},
	[633815] = {
		readable = "Moldy Diary",
		model = 6025930,
		text = {
			en = "Moldy Diary",
			es = "Diario mohoso",
			mx = "Diario mohoso",
			de = "Modriges Tagebuch",
			fr = "Journal moisi",
			it = "Diario Ammuffito",
			pt = "Diário Mofado",
			ru = "Покрытый плесенью дневник",
			ko = "곰팡이 슨 일기",
			cn = "发霉的日记",
			tw = "發黴的日記",
		},
	},
	[633820] = {
		readable = "Discarded Scroll",
		model = 5975120,
		text = {
			en = "Discarded Scroll",
			es = "Pergamino desechado",
			mx = "Pergamino descartado",
			de = "Weggeworfene Schriftrolle",
			fr = "Parchemin abandonné",
			it = "Pergamena Scartata",
			pt = "Pergaminho Descartado",
			ru = "Выброшенный свиток",
			ko = "버려진 두루마리",
			cn = "丢弃的卷轴",
			tw = "被丟棄的卷軸",
		},
	},
	[633823] = {
		readable = "Parting Note",
		model = 3978478,
		text = {
			en = "Parting Note",
			es = "Nota de despedida",
			mx = "Nota de despedida",
			de = "Abschiedsbrief",
			fr = "Note d’adieu",
			it = "Messaggio d'Addio",
			pt = "Bilhete de Partida",
			ru = "Прощальная записка",
			ko = "작별 쪽지",
			cn = "[Parting Note]",
			tw = "[Parting Note]",
		},
	},
})
do ObjectDB[objectID] = objectData; end
