local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[526844] = {
		readable = "Arcane Remnant",
		model = 5916229,
		text = {
			en = "Arcane Remnant",
			es = "Arcane Remnant",
			mx = "Arcane Remnant",
			de = "Arcane Remnant",
			fr = "Arcane Remnant",
			it = "Arcane Remnant",
			pt = "Arcane Remnant",
			ru = "Arcane Remnant",
			ko = "Arcane Remnant",
			cn = "Arcane Remnant",
			tw = "Arcane Remnant",
		},
	},
	[557572] = {
		readable = "Nutrient Rich Dirt",
		model = 189528,
		text = {
			en = "Nutrient Rich Dirt",
			es = "Nutrient Rich Dirt",
			mx = "Nutrient Rich Dirt",
			de = "Nutrient Rich Dirt",
			fr = "Nutrient Rich Dirt",
			it = "Nutrient Rich Dirt",
			pt = "Nutrient Rich Dirt",
			ru = "Nutrient Rich Dirt",
			ko = "Nutrient Rich Dirt",
			cn = "Nutrient Rich Dirt",
			tw = "Nutrient Rich Dirt",
		},
	},
	[560300] = {
		readable = "Unpublished Manuscript",
		text = {
			en = "Unpublished Manuscript",
			es = "Unpublished Manuscript",
			mx = "Unpublished Manuscript",
			de = "Unpublished Manuscript",
			fr = "Unpublished Manuscript",
			it = "Unpublished Manuscript",
			pt = "Unpublished Manuscript",
			ru = "Unpublished Manuscript",
			ko = "Unpublished Manuscript",
			cn = "Unpublished Manuscript",
			tw = "Unpublished Manuscript",
		},
	},
	[560325] = {
		readable = "Core Chest",
		text = {
			en = "Core Chest",
			es = "Core Chest",
			mx = "Core Chest",
			de = "Core Chest",
			fr = "Core Chest",
			it = "Core Chest",
			pt = "Core Chest",
			ru = "Core Chest",
			ko = "Core Chest",
			cn = "Core Chest",
			tw = "Core Chest",
		},
	},
	[567709] = {
		readable = "Hieron's Belongings",
		text = {
			en = "Hieron's Belongings",
			es = "Hieron's Belongings",
			mx = "Hieron's Belongings",
			de = "Hieron's Belongings",
			fr = "Hieron's Belongings",
			it = "Hieron's Belongings",
			pt = "Hieron's Belongings",
			ru = "Hieron's Belongings",
			ko = "Hieron's Belongings",
			cn = "Hieron's Belongings",
			tw = "Hieron's Belongings",
		},
	},
	[587194] = {
		readable = "Stashed Singularity Supplies",
		text = {
			en = "Stashed Singularity Supplies",
			es = "Stashed Singularity Supplies",
			mx = "Stashed Singularity Supplies",
			de = "Stashed Singularity Supplies",
			fr = "Stashed Singularity Supplies",
			it = "Stashed Singularity Supplies",
			pt = "Stashed Singularity Supplies",
			ru = "Stashed Singularity Supplies",
			ko = "Stashed Singularity Supplies",
			cn = "Stashed Singularity Supplies",
			tw = "Stashed Singularity Supplies",
		},
	},
	[587240] = {
		readable = "Mysterious Domanaar Vessel",
		text = {
			en = "Mysterious Domanaar Vessel",
			es = "Mysterious Domanaar Vessel",
			mx = "Mysterious Domanaar Vessel",
			de = "Mysterious Domanaar Vessel",
			fr = "Mysterious Domanaar Vessel",
			it = "Mysterious Domanaar Vessel",
			pt = "Mysterious Domanaar Vessel",
			ru = "Mysterious Domanaar Vessel",
			ko = "Mysterious Domanaar Vessel",
			cn = "Mysterious Domanaar Vessel",
			tw = "Mysterious Domanaar Vessel",
		},
	},
	[605169] = {
		readable = "Final Clutch of Predaxas",
		text = {
			en = "Final Clutch of Predaxas",
			es = "Final Clutch of Predaxas",
			mx = "Final Clutch of Predaxas",
			de = "Final Clutch of Predaxas",
			fr = "Final Clutch of Predaxas",
			it = "Final Clutch of Predaxas",
			pt = "Final Clutch of Predaxas",
			ru = "Final Clutch of Predaxas",
			ko = "Final Clutch of Predaxas",
			cn = "Final Clutch of Predaxas",
			tw = "Final Clutch of Predaxas",
		},
	},
	[607115] = {
		readable = "Loosened Sand",
		model = 2059166,
		text = {
			en = "Loosened Sand",
			es = "Loosened Sand",
			mx = "Loosened Sand",
			de = "Loosened Sand",
			fr = "Loosened Sand",
			it = "Loosened Sand",
			pt = "Loosened Sand",
			ru = "Loosened Sand",
			ko = "Loosened Sand",
			cn = "Loosened Sand",
			tw = "Loosened Sand",
		},
	},
})
do ObjectDB[objectID] = objectData; end
