local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[525948] = {
		readable = "Primal Essence Orb",
		model = 4508234,
		text = {
			en = "Primal Essence Orb",
			es = "[Primal Essence Orb]",
			mx = "[Primal Essence Orb]",
			de = "Urzeitliche Essenzkugel",
			fr = "[Primal Essence Orb]",
			it = "[Primal Essence Orb]",
			pt = "[Primal Essence Orb]",
			ru = "[Primal Essence Orb]",
			ko = "[Primal Essence Orb]",
			cn = "[Primal Essence Orb]",
			tw = "[Primal Essence Orb]",
		},
	},
	[525949] = {
		readable = "Entropic Shard",
		model = 4320282,
		text = {
			en = "Entropic Shard",
			es = "[Entropic Shard]",
			mx = "[Entropic Shard]",
			de = "[Entropic Shard]",
			fr = "Éclat entropique",
			it = "[Entropic Shard]",
			pt = "[Entropic Shard]",
			ru = "[Entropic Shard]",
			ko = "[Entropic Shard]",
			cn = "[Entropic Shard]",
			tw = "[Entropic Shard]",
		},
	},
	[525950] = {
		readable = "Everblazing Sunmote",
		model = 5597754,
		text = {
			en = "Everblazing Sunmote",
			es = "Mota de sol de fuego eterno",
			mx = "[Everblazing Sunmote]",
			de = "Immerbrennender Sonnenpartikel",
			fr = "Granule de soleil semperardent",
			it = "Granulo del Sole Ardente",
			pt = "[Everblazing Sunmote]",
			ru = "Вечнопылающая частица солнца",
			ko = "[Everblazing Sunmote]",
			cn = "[Everblazing Sunmote]",
			tw = "恆燃太陽微粒",
		},
	},
	[525951] = {
		readable = "Pure Void Crystal",
		model = 4563732,
		text = {
			en = "Pure Void Crystal",
			es = "[Pure Void Crystal]",
			mx = "[Pure Void Crystal]",
			de = "[Pure Void Crystal]",
			fr = "[Pure Void Crystal]",
			it = "[Pure Void Crystal]",
			pt = "[Pure Void Crystal]",
			ru = "[Pure Void Crystal]",
			ko = "[Pure Void Crystal]",
			cn = "[Pure Void Crystal]",
			tw = "[Pure Void Crystal]",
		},
	},
	[525953] = {
		readable = "Enchanted Amani Mask",
		model = 6163854,
		text = {
			en = "Enchanted Amani Mask",
			es = "[Enchanted Amani Mask]",
			mx = "[Enchanted Amani Mask]",
			de = "[Enchanted Amani Mask]",
			fr = "[Enchanted Amani Mask]",
			it = "[Enchanted Amani Mask]",
			pt = "[Enchanted Amani Mask]",
			ru = "[Enchanted Amani Mask]",
			ko = "[Enchanted Amani Mask]",
			cn = "[Enchanted Amani Mask]",
			tw = "[Enchanted Amani Mask]",
		},
	},
	[525954] = {
		readable = "Silvermoon Blacksmith's Hammer",
		model = 6033619,
		text = {
			en = "Silvermoon Blacksmith's Hammer",
			es = "Martillo de herrería de Lunargenta",
			mx = "Martillo de herrero de Lunargenta",
			de = "Silbermondschmiedehammer",
			fr = "Marteau de forge de Lune-d’Argent",
			it = "Martello da Fabbro di Lunargenta",
			pt = "[Silvermoon Blacksmith's Hammer]",
			ru = "Луносветский кузнечный молот",
			ko = "[Silvermoon Blacksmith's Hammer]",
			cn = "[Silvermoon Blacksmith's Hammer]",
			tw = "[Silvermoon Blacksmith's Hammer]",
		},
	},
	[525955] = {
		readable = "Sin'dorei Master's Forgemace",
		model = 6033619,
		text = {
			en = "Sin'dorei Master's Forgemace",
			es = "Mazo de forja de maestro sin'dorei",
			mx = "Maza de forja de maestro sin'dorei",
			de = "Schmiedestreitkolben des Sin'dorei-Meisters",
			fr = "Masse de forge de maîtrise sin’dorei",
			it = "Forgiamazza del Mastro Sin'dorei",
			pt = "[Sin'dorei Master's Forgemace]",
			ru = "Молот син'дорайского мастера",
			ko = "[Sin'dorei Master's Forgemace]",
			cn = "[Sin'dorei Master's Forgemace]",
			tw = "[Sin'dorei Master's Forgemace]",
		},
	},
	[525956] = {
		readable = "Rutaani Floratender's Sword",
		model = 6055061,
		text = {
			en = "Rutaani Floratender's Sword",
			es = "[Rutaani Floratender's Sword]",
			mx = "[Rutaani Floratender's Sword]",
			de = "[Rutaani Floratender's Sword]",
			fr = "[Rutaani Floratender's Sword]",
			it = "[Rutaani Floratender's Sword]",
			pt = "[Rutaani Floratender's Sword]",
			ru = "[Rutaani Floratender's Sword]",
			ko = "[Rutaani Floratender's Sword]",
			cn = "[Rutaani Floratender's Sword]",
			tw = "[Rutaani Floratender's Sword]",
		},
	},
	[525958] = {
		readable = "Metalworking Cheat Sheet",
		model = 5679909,
		text = {
			en = "Metalworking Cheat Sheet",
			es = "Guía rápida para trabajar con metales",
			mx = "[Metalworking Cheat Sheet]",
			de = "Spickzettel zu Metallarbeiten",
			fr = "Le travail du métal pour les nuls",
			it = "Promemoria sulla Lavorazione dei Metalli",
			pt = "[Metalworking Cheat Sheet]",
			ru = "[Metalworking Cheat Sheet]",
			ko = "[Metalworking Cheat Sheet]",
			cn = "[Metalworking Cheat Sheet]",
			tw = "[Metalworking Cheat Sheet]",
		},
	},
	[525959] = {
		readable = "Carefully Racked Spear",
		model = 6212433,
		text = {
			en = "Carefully Racked Spear",
			es = "[Carefully Racked Spear]",
			mx = "[Carefully Racked Spear]",
			de = "[Carefully Racked Spear]",
			fr = "[Carefully Racked Spear]",
			it = "[Carefully Racked Spear]",
			pt = "[Carefully Racked Spear]",
			ru = "[Carefully Racked Spear]",
			ko = "[Carefully Racked Spear]",
			cn = "[Carefully Racked Spear]",
			tw = "[Carefully Racked Spear]",
		},
	},
	[525960] = {
		readable = "Silvermoon Smithing Kit",
		model = 6125157,
		text = {
			en = "Silvermoon Smithing Kit",
			es = "Equipo de herrería de Lunargenta",
			mx = "[Silvermoon Smithing Kit]",
			de = "Silbermondschmiedeset",
			fr = "Kit de forge de Lune-d’Argent",
			it = "Kit da Forgiatura di Lunargenta",
			pt = "[Silvermoon Smithing Kit]",
			ru = "[Silvermoon Smithing Kit]",
			ko = "[Silvermoon Smithing Kit]",
			cn = "[Silvermoon Smithing Kit]",
			tw = "[Silvermoon Smithing Kit]",
		},
	},
	[525961] = {
		readable = "Deconstructed Forge Techniques",
		model = 203429,
		text = {
			en = "Deconstructed Forge Techniques",
			es = "Técnicas de forja deconstruidas",
			mx = "[Deconstructed Forge Techniques]",
			de = "Dekonstruierte Schmiedetechniken",
			fr = "Manifeste pour une forge déconstruite",
		},
	},
})
do ObjectDB[objectID] = objectData; end
