local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[544781] = {
		readable = "Dornic Fir Lumber",
		model = 6922313,
		text = {
			en = "Dornic Fir Lumber",
			es = "Madera de abeto de Dorn",
			mx = "Madera de abeto dórnico",
			de = "Dorntannenholz",
			fr = "Bois d’épicéa de Dornic",
			it = "Legname di Abete di Dornic",
			pt = "Lenha de Abeto de Dornic",
			ru = "Древесина дорнской ели",
			ko = "도르닉 전나무 목재",
			cn = "多恩冷杉木料",
			tw = "多尼克冷杉木材",
		},
	},
	[546737] = {
		readable = "Dornic Fir Lumber",
		model = 6922313,
		text = {
			en = "Dornic Fir Lumber",
			es = "Madera de abeto de Dorn",
			mx = "Madera de abeto dórnico",
			de = "Dorntannenholz",
			fr = "Bois d’épicéa de Dornic",
			it = "Legname di Abete di Dornic",
			pt = "Lenha de Abeto de Dornic",
			ru = "Древесина дорнской ели",
			ko = "도르닉 전나무 목재",
			cn = "多恩冷杉木料",
			tw = "多尼克冷杉木材",
		},
	},
	[546738] = {
		readable = "Dornic Fir Lumber",
		model = 6922313,
		text = {
			en = "Dornic Fir Lumber",
			es = "Madera de abeto de Dorn",
			mx = "Madera de abeto dórnico",
			de = "Dorntannenholz",
			fr = "Bois d’épicéa de Dornic",
			it = "Legname di Abete di Dornic",
			pt = "Lenha de Abeto de Dornic",
			ru = "Древесина дорнской ели",
			ko = "도르닉 전나무 목재",
			cn = "多恩冷杉木料",
			tw = "多尼克冷杉木材",
		},
	},
	[546928] = {
		readable = "Dornic Fir Lumber",
		model = 6922313,
		text = {
			en = "Dornic Fir Lumber",
			es = "Madera de abeto de Dorn",
			mx = "Madera de abeto dórnico",
			de = "Dorntannenholz",
			fr = "Bois d’épicéa de Dornic",
			it = "Legname di Abete di Dornic",
			pt = "Lenha de Abeto de Dornic",
			ru = "Древесина дорнской ели",
			ko = "도르닉 전나무 목재",
			cn = "多恩冷杉木料",
			tw = "多尼克冷杉木材",
		},
	},
	[546955] = {
		readable = "Dragonpine Lumber",
		model = 6922313,
		text = {
			en = "Dragonpine Lumber",
			es = "Madera de pinodragón",
			mx = "Madera de pinodragón",
			de = "Drachenkiefernholz",
			fr = "Bois de pin-des-dragons",
			it = "Legname di Pino Draconico",
			pt = "Lenha de Dracopinho",
			ru = "Древесина драконьей сосны",
			ko = "용침엽수 목재",
			cn = "龙松木料",
			tw = "龍松木材",
		},
	},
	[547258] = {
		readable = "Dragonpine Lumber",
		model = 6922313,
		text = {
			en = "Dragonpine Lumber",
			es = "Madera de pinodragón",
			mx = "Madera de pinodragón",
			de = "Drachenkiefernholz",
			fr = "Bois de pin-des-dragons",
			it = "Legname di Pino Draconico",
			pt = "Lenha de Dracopinho",
			ru = "Древесина драконьей сосны",
			ko = "용침엽수 목재",
			cn = "龙松木料",
			tw = "龍松木材",
		},
	},
	[547487] = {
		readable = "Dragonpine Lumber",
		model = 6922313,
		text = {
			en = "Dragonpine Lumber",
			es = "Madera de pinodragón",
			mx = "Madera de pinodragón",
			de = "Drachenkiefernholz",
			fr = "Bois de pin-des-dragons",
			it = "Legname di Pino Draconico",
			pt = "Lenha de Dracopinho",
			ru = "Древесина драконьей сосны",
			ko = "용침엽수 목재",
			cn = "龙松木料",
			tw = "龍松木材",
		},
	},
	[547740] = {
		readable = "Dragonpine Lumber",
		model = 6922313,
		text = {
			en = "Dragonpine Lumber",
			es = "Madera de pinodragón",
			mx = "Madera de pinodragón",
			de = "Drachenkiefernholz",
			fr = "Bois de pin-des-dragons",
			it = "Legname di Pino Draconico",
			pt = "Lenha de Dracopinho",
			ru = "Древесина драконьей сосны",
			ko = "용침엽수 목재",
			cn = "龙松木料",
			tw = "龍松木材",
		},
	},
	[549325] = {
		readable = "Dragonpine Lumber",
		model = 6922313,
		text = {
			en = "Dragonpine Lumber",
			es = "Madera de pinodragón",
			mx = "Madera de pinodragón",
			de = "Drachenkiefernholz",
			fr = "Bois de pin-des-dragons",
			it = "Legname di Pino Draconico",
			pt = "Lenha de Dracopinho",
			ru = "Древесина драконьей сосны",
			ko = "용침엽수 목재",
			cn = "龙松木料",
			tw = "龍松木材",
		},
	},
	[553646] = {
		readable = "Arden Lumber",
		model = 6922313,
		text = {
			en = "Arden Lumber",
			es = "Madera de Ardenweald",
			mx = "Madera de Arden",
			de = "Ardenholz",
			fr = "Bois d’Arden",
			it = "Legname di Arden",
			pt = "Lenha de Ardena",
			ru = "Арденвельдская древесина",
			ko = "몽환 목재",
			cn = "炽蓝木料",
			tw = "亞登木材",
		},
	},
	[553804] = {
		readable = "Arden Lumber",
		model = 6922313,
		text = {
			en = "Arden Lumber",
			es = "Madera de Ardenweald",
			mx = "Madera de Arden",
			de = "Ardenholz",
			fr = "Bois d’Arden",
			it = "Legname di Arden",
			pt = "Lenha de Ardena",
			ru = "Арденвельдская древесина",
			ko = "몽환 목재",
			cn = "炽蓝木料",
			tw = "亞登木材",
		},
	},
	[554661] = {
		readable = "Arden Lumber",
		model = 6922313,
		text = {
			en = "Arden Lumber",
			es = "Madera de Ardenweald",
			mx = "Madera de Arden",
			de = "Ardenholz",
			fr = "Bois d’Arden",
			it = "Legname di Arden",
			pt = "Lenha de Ardena",
			ru = "Арденвельдская древесина",
			ko = "몽환 목재",
			cn = "炽蓝木料",
			tw = "亞登木材",
		},
	},
	[555364] = {
		readable = "Dragonpine Lumber",
		model = 6922313,
		text = {
			en = "Dragonpine Lumber",
			es = "Madera de pinodragón",
			mx = "Madera de pinodragón",
			de = "Drachenkiefernholz",
			fr = "Bois de pin-des-dragons",
			it = "Legname di Pino Draconico",
			pt = "Lenha de Dracopinho",
			ru = "Древесина драконьей сосны",
			ko = "용침엽수 목재",
			cn = "龙松木料",
			tw = "龍松木材",
		},
	},
	[555545] = {
		readable = "Darkpine Lumber",
		model = 6922313,
		text = {
			en = "Darkpine Lumber",
			es = "Madera de pinoscuro",
			mx = "Madera de pinoscuro",
			de = "Düsterkiefernholz",
			fr = "Bois de sombrepin",
			it = "Legname di Pinoscuro",
			pt = "Lenha de Pinhonegro",
			ru = "Древесина темной сосны",
			ko = "어둠소나무 목재",
			cn = "黑松木料",
			tw = "暗松木材",
		},
	},
	[556076] = {
		readable = "Darkpine Lumber",
		model = 6922313,
		text = {
			en = "Darkpine Lumber",
			es = "Madera de pinoscuro",
			mx = "Madera de pinoscuro",
			de = "Düsterkiefernholz",
			fr = "Bois de sombrepin",
			it = "Legname di Pinoscuro",
			pt = "Lenha de Pinhonegro",
			ru = "Древесина темной сосны",
			ko = "어둠소나무 목재",
			cn = "黑松木料",
			tw = "暗松木材",
		},
	},
	[556387] = {
		readable = "Darkpine Lumber",
		model = 6922313,
		text = {
			en = "Darkpine Lumber",
			es = "Madera de pinoscuro",
			mx = "Madera de pinoscuro",
			de = "Düsterkiefernholz",
			fr = "Bois de sombrepin",
			it = "Legname di Pinoscuro",
			pt = "Lenha de Pinhonegro",
			ru = "Древесина темной сосны",
			ko = "어둠소나무 목재",
			cn = "黑松木料",
			tw = "暗松木材",
		},
	},
	[556704] = {
		readable = "Darkpine Lumber",
		model = 6922313,
		text = {
			en = "Darkpine Lumber",
			es = "Madera de pinoscuro",
			mx = "Madera de pinoscuro",
			de = "Düsterkiefernholz",
			fr = "Bois de sombrepin",
			it = "Legname di Pinoscuro",
			pt = "Lenha de Pinhonegro",
			ru = "Древесина темной сосны",
			ko = "어둠소나무 목재",
			cn = "黑松木料",
			tw = "暗松木材",
		},
	},
	[557988] = {
		readable = "Darkpine Lumber",
		model = 6922313,
		text = {
			en = "Darkpine Lumber",
			es = "Madera de pinoscuro",
			mx = "Madera de pinoscuro",
			de = "Düsterkiefernholz",
			fr = "Bois de sombrepin",
			it = "Legname di Pinoscuro",
			pt = "Lenha de Pinhonegro",
			ru = "Древесина темной сосны",
			ko = "어둠소나무 목재",
			cn = "黑松木料",
			tw = "暗松木材",
		},
	},
	[558338] = {
		readable = "Darkpine Lumber",
		model = 6922313,
		text = {
			en = "Darkpine Lumber",
			es = "Madera de pinoscuro",
			mx = "Madera de pinoscuro",
			de = "Düsterkiefernholz",
			fr = "Bois de sombrepin",
			it = "Legname di Pinoscuro",
			pt = "Lenha de Pinhonegro",
			ru = "Древесина темной сосны",
			ko = "어둠소나무 목재",
			cn = "黑松木料",
			tw = "暗松木材",
		},
	},
	[558361] = {
		readable = "Fel-Touched Lumber",
		model = 6922313,
		text = {
			en = "Fel-Touched Lumber",
			es = "Madera vilificada",
			mx = "Madera tocada por energía vil",
			de = "Teufelsberührtes Holz",
			fr = "Bois touché par la corruption",
			it = "Legname Viltoccato",
			pt = "Lenha Maculada pela Vileza",
			ru = "Оскверненная древесина",
			ko = "지옥 마력 목재",
			cn = "邪触木料",
			tw = "魔觸木材",
		},
	},
	[558389] = {
		readable = "Fel-Touched Lumber",
		model = 6922313,
		text = {
			en = "Fel-Touched Lumber",
			es = "Madera vilificada",
			mx = "Madera tocada por energía vil",
			de = "Teufelsberührtes Holz",
			fr = "Bois touché par la corruption",
			it = "Legname Viltoccato",
			pt = "Lenha Maculada pela Vileza",
			ru = "Оскверненная древесина",
			ko = "지옥 마력 목재",
			cn = "邪触木料",
			tw = "魔觸木材",
		},
	},
	[560358] = {
		readable = "Fel-Touched Lumber",
		model = 6922313,
		text = {
			en = "Fel-Touched Lumber",
			es = "Madera vilificada",
			mx = "Madera tocada por energía vil",
			de = "Teufelsberührtes Holz",
			fr = "Bois touché par la corruption",
			it = "Legname Viltoccato",
			pt = "Lenha Maculada pela Vileza",
			ru = "Оскверненная древесина",
			ko = "지옥 마력 목재",
			cn = "邪触木料",
			tw = "魔觸木材",
		},
	},
	[560822] = {
		readable = "Fel-Touched Lumber",
		model = 6922313,
		text = {
			en = "Fel-Touched Lumber",
			es = "Madera vilificada",
			mx = "Madera tocada por energía vil",
			de = "Teufelsberührtes Holz",
			fr = "Bois touché par la corruption",
			it = "Legname Viltoccato",
			pt = "Lenha Maculada pela Vileza",
			ru = "Оскверненная древесина",
			ko = "지옥 마력 목재",
			cn = "邪触木料",
			tw = "魔觸木材",
		},
	},
	[560826] = {
		readable = "Fel-Touched Lumber",
		model = 6922313,
		text = {
			en = "Fel-Touched Lumber",
			es = "Madera vilificada",
			mx = "Madera tocada por energía vil",
			de = "Teufelsberührtes Holz",
			fr = "Bois touché par la corruption",
			it = "Legname Viltoccato",
			pt = "Lenha Maculada pela Vileza",
			ru = "Оскверненная древесина",
			ko = "지옥 마력 목재",
			cn = "邪触木料",
			tw = "魔觸木材",
		},
	},
	[562159] = {
		readable = "Fel-Touched Lumber",
		model = 6922313,
		text = {
			en = "Fel-Touched Lumber",
			es = "Madera vilificada",
			mx = "Madera tocada por energía vil",
			de = "Teufelsberührtes Holz",
			fr = "Bois touché par la corruption",
			it = "Legname Viltoccato",
			pt = "Lenha Maculada pela Vileza",
			ru = "Оскверненная древесина",
			ko = "지옥 마력 목재",
			cn = "邪触木料",
			tw = "魔觸木材",
		},
	},
	[562439] = {
		readable = "Fel-Touched Lumber",
		model = 6922313,
		text = {
			en = "Fel-Touched Lumber",
			es = "Madera vilificada",
			mx = "Madera tocada por energía vil",
			de = "Teufelsberührtes Holz",
			fr = "Bois touché par la corruption",
			it = "Legname Viltoccato",
			pt = "Lenha Maculada pela Vileza",
			ru = "Оскверненная древесина",
			ko = "지옥 마력 목재",
			cn = "邪触木料",
			tw = "魔觸木材",
		},
	},
	[567726] = {
		readable = "Bamboo Lumber",
		model = 6922313,
		text = {
			en = "Bamboo Lumber",
			es = "Madera de bambú",
			mx = "Madera de bambú",
			de = "Bambusholz",
			fr = "Bois de bambou",
			it = "Legname di Bambù",
			pt = "Lenha de Bambu",
			ru = "Древесина бамбука",
			ko = "대나무 목재",
			cn = "翠竹木料",
			tw = "竹子木材",
		},
	},
	[567840] = {
		readable = "Bamboo Lumber",
		model = 6922313,
		text = {
			en = "Bamboo Lumber",
			es = "Madera de bambú",
			mx = "Madera de bambú",
			de = "Bambusholz",
			fr = "Bois de bambou",
			it = "Legname di Bambù",
			pt = "Lenha de Bambu",
			ru = "Древесина бамбука",
			ko = "대나무 목재",
			cn = "翠竹木料",
			tw = "竹子木材",
		},
	},
	[567867] = {
		readable = "Bamboo Lumber",
		model = 6922313,
		text = {
			en = "Bamboo Lumber",
			es = "Madera de bambú",
			mx = "Madera de bambú",
			de = "Bambusholz",
			fr = "Bois de bambou",
			it = "Legname di Bambù",
			pt = "Lenha de Bambu",
			ru = "Древесина бамбука",
			ko = "대나무 목재",
			cn = "翠竹木料",
			tw = "竹子木材",
		},
	},
	[568132] = {
		readable = "Bamboo Lumber",
		model = 6922313,
		text = {
			en = "Bamboo Lumber",
			es = "Madera de bambú",
			mx = "Madera de bambú",
			de = "Bambusholz",
			fr = "Bois de bambou",
			it = "Legname di Bambù",
			pt = "Lenha de Bambu",
			ru = "Древесина бамбука",
			ko = "대나무 목재",
			cn = "翠竹木料",
			tw = "竹子木材",
		},
	},
	[568137] = {
		readable = "Bamboo Lumber",
		model = 6922313,
		text = {
			en = "Bamboo Lumber",
			es = "Madera de bambú",
			mx = "Madera de bambú",
			de = "Bambusholz",
			fr = "Bois de bambou",
			it = "Legname di Bambù",
			pt = "Lenha de Bambu",
			ru = "Древесина бамбука",
			ko = "대나무 목재",
			cn = "翠竹木料",
			tw = "竹子木材",
		},
	},
	[568199] = {
		readable = "Bamboo Lumber",
		model = 6922313,
		text = {
			en = "Bamboo Lumber",
			es = "Madera de bambú",
			mx = "Madera de bambú",
			de = "Bambusholz",
			fr = "Bois de bambou",
			it = "Legname di Bambù",
			pt = "Lenha de Bambu",
			ru = "Древесина бамбука",
			ko = "대나무 목재",
			cn = "翠竹木料",
			tw = "竹子木材",
		},
	},
	[568305] = {
		readable = "Bamboo Lumber",
		model = 6922313,
		text = {
			en = "Bamboo Lumber",
			es = "Madera de bambú",
			mx = "Madera de bambú",
			de = "Bambusholz",
			fr = "Bois de bambou",
			it = "Legname di Bambù",
			pt = "Lenha de Bambu",
			ru = "Древесина бамбука",
			ko = "대나무 목재",
			cn = "翠竹木料",
			tw = "竹子木材",
		},
	},
	[568405] = {
		readable = "Bamboo Lumber",
		model = 6922313,
		text = {
			en = "Bamboo Lumber",
			es = "Madera de bambú",
			mx = "Madera de bambú",
			de = "Bambusholz",
			fr = "Bois de bambou",
			it = "Legname di Bambù",
			pt = "Lenha de Bambu",
			ru = "Древесина бамбука",
			ko = "대나무 목재",
			cn = "翠竹木料",
			tw = "竹子木材",
		},
	},
	[568528] = {
		readable = "Coldwind Lumber",
		model = 6922313,
		text = {
			en = "Coldwind Lumber",
			es = "Madera vientofrío",
			mx = "Madera vientofrío",
			de = "Kaltwindholz",
			fr = "Bois de Vent-froid",
			it = "Legname di Ventogelido",
			pt = "Lenha do Vento Frio",
			ru = "Морозная древесина",
			ko = "눈바람 목재",
			cn = "冷风木料",
			tw = "冷風木材",
		},
	},
	[569408] = {
		readable = "Coldwind Lumber",
		model = 6922313,
		text = {
			en = "Coldwind Lumber",
			es = "Madera vientofrío",
			mx = "Madera vientofrío",
			de = "Kaltwindholz",
			fr = "Bois de Vent-froid",
			it = "Legname di Ventogelido",
			pt = "Lenha do Vento Frio",
			ru = "Морозная древесина",
			ko = "눈바람 목재",
			cn = "冷风木料",
			tw = "冷風木材",
		},
	},
	[569785] = {
		readable = "Coldwind Lumber",
		model = 6922313,
		text = {
			en = "Coldwind Lumber",
			es = "Madera vientofrío",
			mx = "Madera vientofrío",
			de = "Kaltwindholz",
			fr = "Bois de Vent-froid",
			it = "Legname di Ventogelido",
			pt = "Lenha do Vento Frio",
			ru = "Морозная древесина",
			ko = "눈바람 목재",
			cn = "冷风木料",
			tw = "冷風木材",
		},
	},
	[570233] = {
		readable = "Coldwind Lumber",
		model = 6922313,
		text = {
			en = "Coldwind Lumber",
			es = "Madera vientofrío",
			mx = "Madera vientofrío",
			de = "Kaltwindholz",
			fr = "Bois de Vent-froid",
			it = "Legname di Ventogelido",
			pt = "Lenha do Vento Frio",
			ru = "Морозная древесина",
			ko = "눈바람 목재",
			cn = "冷风木料",
			tw = "冷風木材",
		},
	},
	[570347] = {
		readable = "Coldwind Lumber",
		model = 6922313,
		text = {
			en = "Coldwind Lumber",
			es = "Madera vientofrío",
			mx = "Madera vientofrío",
			de = "Kaltwindholz",
			fr = "Bois de Vent-froid",
			it = "Legname di Ventogelido",
			pt = "Lenha do Vento Frio",
			ru = "Морозная древесина",
			ko = "눈바람 목재",
			cn = "冷风木料",
			tw = "冷風木材",
		},
	},
	[570896] = {
		readable = "Coldwind Lumber",
		model = 6922313,
		text = {
			en = "Coldwind Lumber",
			es = "Madera vientofrío",
			mx = "Madera vientofrío",
			de = "Kaltwindholz",
			fr = "Bois de Vent-froid",
			it = "Legname di Ventogelido",
			pt = "Lenha do Vento Frio",
			ru = "Морозная древесина",
			ko = "눈바람 목재",
			cn = "冷风木料",
			tw = "冷風木材",
		},
	},
	[570942] = {
		readable = "Coldwind Lumber",
		model = 6922313,
		text = {
			en = "Coldwind Lumber",
			es = "Madera vientofrío",
			mx = "Madera vientofrío",
			de = "Kaltwindholz",
			fr = "Bois de Vent-froid",
			it = "Legname di Ventogelido",
			pt = "Lenha do Vento Frio",
			ru = "Морозная древесина",
			ko = "눈바람 목재",
			cn = "冷风木料",
			tw = "冷風木材",
		},
	},
	[571034] = {
		readable = "Coldwind Lumber",
		model = 6922313,
		text = {
			en = "Coldwind Lumber",
			es = "Madera vientofrío",
			mx = "Madera vientofrío",
			de = "Kaltwindholz",
			fr = "Bois de Vent-froid",
			it = "Legname di Ventogelido",
			pt = "Lenha do Vento Frio",
			ru = "Морозная древесина",
			ko = "눈바람 목재",
			cn = "冷风木料",
			tw = "冷風木材",
		},
	},
	[573547] = {
		readable = "Ashwood Lumber",
		model = 6922313,
		text = {
			en = "Ashwood Lumber",
			es = "Madera de fresno",
			mx = "Madera de xiloceniza",
			de = "Aschenholz",
			fr = "Bois de frêne",
			it = "Legname di Legno Secco",
			pt = "Lenha de Freixo",
			ru = "Ясеневая древесина",
			ko = "잿빛나무 목재",
			cn = "灰木木料",
			tw = "灰木木材",
		},
	},
	[586651] = {
		readable = "Ashwood Lumber",
		model = 6922313,
		text = {
			en = "Ashwood Lumber",
			es = "Madera de fresno",
			mx = "Madera de xiloceniza",
			de = "Aschenholz",
			fr = "Bois de frêne",
			it = "Legname di Legno Secco",
			pt = "Lenha de Freixo",
			ru = "Ясеневая древесина",
			ko = "잿빛나무 목재",
			cn = "灰木木料",
			tw = "灰木木材",
		},
	},
})
do ObjectDB[objectID] = objectData; end
