local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[620327] = {
		readable = "Tablet of Filo",
		model = 6212409,
		text = {
			en = "Tablet of Filo",
			es = "[Tablet of Filo]",
			mx = "Tablilla de Filo",
			de = "Schrifttafel von Filo",
			fr = "Tablette de Filo",
			it = "Tavoletta di Filo",
			pt = "Tabuleta de Filo",
			ru = "Скрижаль Фило",
			ko = "[Tablet of Filo]",
			cn = "[Tablet of Filo]",
			tw = "[Tablet of Filo]",
		},
	},
	[620460] = {
		readable = "Voidhoarder's Corpse",
		model = 7012542,
		text = {
			en = "Voidhoarder's Corpse",
			es = "[Voidhoarder's Corpse]",
			mx = "[Voidhoarder's Corpse]",
			de = "[Voidhoarder's Corpse]",
			fr = "[Voidhoarder's Corpse]",
			it = "[Voidhoarder's Corpse]",
			pt = "[Voidhoarder's Corpse]",
			ru = "[Voidhoarder's Corpse]",
			ko = "[Voidhoarder's Corpse]",
			cn = "[Voidhoarder's Corpse]",
			tw = "[Voidhoarder's Corpse]",
		},
	},
	[620497] = {
		readable = "Ruia's Musings",
		model = 6326919,
		text = {
			en = "Ruia's Musings",
			es = "[Ruia's Musings]",
			mx = "[Ruia's Musings]",
			de = "Ruias Gedanken",
			fr = "Réflexions de Ruia",
			it = "[Ruia's Musings]",
			pt = "[Ruia's Musings]",
			ru = "[Ruia's Musings]",
			ko = "[Ruia's Musings]",
			cn = "[Ruia's Musings]",
			tw = "[Ruia's Musings]",
		},
	},
	[620498] = {
		readable = "Ruia's Musings",
		model = 6326919,
		text = {
			en = "Ruia's Musings",
			es = "[Ruia's Musings]",
			mx = "[Ruia's Musings]",
			de = "Ruias Gedanken",
			fr = "Réflexions de Ruia",
			it = "[Ruia's Musings]",
			pt = "[Ruia's Musings]",
			ru = "[Ruia's Musings]",
			ko = "[Ruia's Musings]",
			cn = "[Ruia's Musings]",
			tw = "[Ruia's Musings]",
		},
	},
	[621669] = {
		readable = "Artisan's Cache",
		model = 6017293,
		text = {
			en = "Artisan's Cache",
			es = "Alijo de artesano",
			mx = "Alijo de artesano",
			de = "Truhe des Fachmanns",
			fr = "Cache d’artisan",
			it = "Cassa dell'Artigiano",
			pt = "Baú de Artífice",
			ru = "Тайник умельца",
			ko = "장인의 보관함",
			cn = "工匠之箱",
			tw = "工匠寶箱",
		},
	},
	[621700] = {
		readable = "Babble and Brook",
		model = 7241263,
		text = {
			en = "Babble and Brook",
			es = "Murmullo y arroyo",
			mx = "Arroyo arrollador",
			de = "Plätschernder Bach",
			fr = "Babils et roseaux",
			it = "Gorgoglio di Ruscello",
			pt = "Papo e Riacho",
			ru = "Журчание у ручья",
			ko = "[Babble and Brook]",
			cn = "潺潺溪流",
			tw = "流水潺潺",
		},
	},
	[621707] = {
		readable = "Sway of Red and Gold",
		model = 7241267,
		text = {
			en = "Sway of Red and Gold",
			es = "Influencia de rojo y dorado",
			mx = "Influencia de rojo y oro",
			de = "Wogen in Rot und Gold",
			fr = "Ondulations rouge et or",
			it = "Pennellate Rosso e Oro",
			pt = "Balanço Vermelho e Dourado",
			ru = "Волны красного и золотого",
			ko = "[Sway of Red and Gold]",
			cn = "红金摇曳",
			tw = "紅金之流",
		},
	},
	[621709] = {
		readable = "Memories of Ghosts",
		model = 7241264,
		text = {
			en = "Memories of Ghosts",
			es = "Recuerdos de fantasmas",
			mx = "Recuerdos de fantasmas",
			de = "Erinnerungen an Geister",
			fr = "Souvenirs de fantômes",
			it = "Ricordi di Fantasmi",
			pt = "Memórias de Fantasmas",
			ru = "Воспоминания о призраках",
			ko = "[Memories of Ghosts]",
			cn = "幽魂的记忆",
			tw = "鬼魂的記憶",
		},
	},
	[621711] = {
		readable = "Elrendar's Song",
		model = 7241265,
		text = {
			en = "Elrendar's Song",
			es = "Canción de Elrendar",
			mx = "Canción de Elrendar",
			de = "Elrendars Lied",
			fr = "Chant d’Elrendar",
			it = "Canto di Elrendar",
			pt = "Canção de Elrendar",
			ru = "Элрендарская песнь",
			ko = "[Elrendar's Song]",
			cn = "艾伦达尔之歌",
			tw = "艾蘭達之歌",
		},
	},
	[621732] = {
		readable = "Light Consuming",
		model = 7241268,
		text = {
			en = "Light Consuming",
			es = "Consunción de la Luz",
			mx = "Consumo de luz",
			de = "Verschlingendes Licht",
			fr = "Lumière insatiable",
			it = "Consumo della Luce",
			pt = "Devora-luz",
			ru = "Свет всепоглощающий",
			ko = "[Light Consuming]",
			cn = "吞噬之光",
			tw = "聖光吞噬",
		},
	},
	[621734] = {
		readable = "Lost Lamppost",
		model = 7241269,
		text = {
			en = "Lost Lamppost",
			es = "Poste de luz perdido",
		},
	},
})
do ObjectDB[objectID] = objectData; end
