local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[618285] = {
		readable = "Sturdy Chest",
		model = 5128194,
		text = {
			en = "Sturdy Chest",
			es = "[Sturdy Chest]",
			mx = "Cofre robusto",
			de = "Robuste Truhe",
			fr = "[Sturdy Chest]",
			it = "[Sturdy Chest]",
			pt = "[Sturdy Chest]",
			ru = "Прочный сундук",
			ko = "[Sturdy Chest]",
			cn = "[Sturdy Chest]",
			tw = "[Sturdy Chest]",
		},
	},
	[618286] = {
		readable = "Sturdy Chest",
		model = 5128194,
		text = {
			en = "Sturdy Chest",
			es = "[Sturdy Chest]",
			mx = "Cofre robusto",
			de = "Robuste Truhe",
			fr = "[Sturdy Chest]",
			it = "[Sturdy Chest]",
			pt = "[Sturdy Chest]",
			ru = "Прочный сундук",
			ko = "[Sturdy Chest]",
			cn = "[Sturdy Chest]",
			tw = "[Sturdy Chest]",
		},
	},
	[618288] = {
		readable = "Sturdy Chest",
		model = 5128194,
		text = {
			en = "Sturdy Chest",
			es = "[Sturdy Chest]",
			mx = "[Sturdy Chest]",
			de = "Robuste Truhe",
			fr = "Coffre solide",
			it = "[Sturdy Chest]",
			pt = "[Sturdy Chest]",
			ru = "[Sturdy Chest]",
			ko = "[Sturdy Chest]",
			cn = "[Sturdy Chest]",
			tw = "[Sturdy Chest]",
		},
	},
	[618289] = {
		readable = "Sturdy Chest",
		model = 5128194,
		text = {
			en = "Sturdy Chest",
			es = "[Sturdy Chest]",
			mx = "[Sturdy Chest]",
			de = "Robuste Truhe",
			fr = "Coffre solide",
			it = "[Sturdy Chest]",
			pt = "[Sturdy Chest]",
			ru = "[Sturdy Chest]",
			ko = "[Sturdy Chest]",
			cn = "[Sturdy Chest]",
			tw = "[Sturdy Chest]",
		},
	},
	[618291] = {
		readable = "Sturdy Chest",
		model = 5128194,
		text = {
			en = "Sturdy Chest",
			es = "[Sturdy Chest]",
			mx = "[Sturdy Chest]",
			de = "[Sturdy Chest]",
			fr = "[Sturdy Chest]",
			it = "[Sturdy Chest]",
			pt = "[Sturdy Chest]",
			ru = "[Sturdy Chest]",
			ko = "[Sturdy Chest]",
			cn = "[Sturdy Chest]",
			tw = "[Sturdy Chest]",
		},
	},
	[618292] = {
		readable = "Sturdy Chest",
		model = 5128194,
		text = {
			en = "Sturdy Chest",
			es = "Cofre robusto",
			mx = "[Sturdy Chest]",
			de = "Robuste Truhe",
			fr = "Coffre solide",
			it = "[Sturdy Chest]",
			pt = "[Sturdy Chest]",
			ru = "[Sturdy Chest]",
			ko = "[Sturdy Chest]",
			cn = "[Sturdy Chest]",
			tw = "[Sturdy Chest]",
		},
	},
	[618293] = {
		readable = "Sturdy Chest",
		model = 5128194,
		text = {
			en = "Sturdy Chest",
			es = "[Sturdy Chest]",
			mx = "[Sturdy Chest]",
			de = "[Sturdy Chest]",
			fr = "[Sturdy Chest]",
			it = "[Sturdy Chest]",
			pt = "[Sturdy Chest]",
			ru = "[Sturdy Chest]",
			ko = "[Sturdy Chest]",
			cn = "[Sturdy Chest]",
			tw = "[Sturdy Chest]",
		},
	},
	[618294] = {
		readable = "Sturdy Chest",
		model = 5128194,
		text = {
			en = "Sturdy Chest",
			es = "[Sturdy Chest]",
			mx = "[Sturdy Chest]",
			de = "[Sturdy Chest]",
			fr = "[Sturdy Chest]",
			it = "[Sturdy Chest]",
			pt = "[Sturdy Chest]",
			ru = "[Sturdy Chest]",
			ko = "[Sturdy Chest]",
			cn = "[Sturdy Chest]",
			tw = "[Sturdy Chest]",
		},
	},
	[618295] = {
		readable = "Sturdy Chest",
		model = 5128194,
		text = {
			en = "Sturdy Chest",
			es = "[Sturdy Chest]",
			mx = "[Sturdy Chest]",
			de = "[Sturdy Chest]",
			fr = "[Sturdy Chest]",
			it = "[Sturdy Chest]",
			pt = "[Sturdy Chest]",
			ru = "[Sturdy Chest]",
			ko = "[Sturdy Chest]",
			cn = "[Sturdy Chest]",
			tw = "[Sturdy Chest]",
		},
	},
	[618517] = {
		readable = "Thalassian Lumber",
		model = 6922313,
		text = {
			en = "Thalassian Lumber",
			es = "Madera thalassiana",
			mx = "[Thalassian Lumber]",
			de = "Thalassisches Holz",
			fr = "Bois thalassien",
			it = "Legname Thalassiano",
			pt = "Lenha Talassiana",
			ru = "Талассийская древесина",
			ko = "[Thalassian Lumber]",
		},
	},
})
do ObjectDB[objectID] = objectData; end
