local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[525897] = {
		readable = "Lightbloom Afflicted Hide",
		model = 4288076,
		text = {
			en = "Lightbloom Afflicted Hide",
			es = "[Lightbloom Afflicted Hide]",
			mx = "[Lightbloom Afflicted Hide]",
			de = "[Lightbloom Afflicted Hide]",
			fr = "[Lightbloom Afflicted Hide]",
			it = "[Lightbloom Afflicted Hide]",
			pt = "[Lightbloom Afflicted Hide]",
			ru = "[Lightbloom Afflicted Hide]",
			ko = "[Lightbloom Afflicted Hide]",
			cn = "[Lightbloom Afflicted Hide]",
			tw = "[Lightbloom Afflicted Hide]",
		},
	},
	[587195] = {
		readable = "Mysterious Domanaar Vessel",
		model = 6391990,
		text = {
			en = "Mysterious Domanaar Vessel",
			es = "[Mysterious Domanaar Vessel]",
			mx = "[Mysterious Domanaar Vessel]",
			de = "[Mysterious Domanaar Vessel]",
			fr = "[Mysterious Domanaar Vessel]",
			it = "[Mysterious Domanaar Vessel]",
			pt = "[Mysterious Domanaar Vessel]",
			ru = "[Mysterious Domanaar Vessel]",
			ko = "[Mysterious Domanaar Vessel]",
			cn = "[Mysterious Domanaar Vessel]",
			tw = "[Mysterious Domanaar Vessel]",
		},
	},
	[587238] = {
		readable = "Stashed Singularity Supplies",
		model = 6701013,
		text = {
			en = "Stashed Singularity Supplies",
			es = "[Stashed Singularity Supplies]",
			mx = "[Stashed Singularity Supplies]",
			de = "[Stashed Singularity Supplies]",
			fr = "[Stashed Singularity Supplies]",
			it = "[Stashed Singularity Supplies]",
			pt = "[Stashed Singularity Supplies]",
			ru = "[Stashed Singularity Supplies]",
			ko = "[Stashed Singularity Supplies]",
			cn = "[Stashed Singularity Supplies]",
			tw = "[Stashed Singularity Supplies]",
		},
	},
	[620533] = {
		readable = "Lost Page",
		model = 6103388,
		text = {
			en = "Lost Page",
			es = "Página perdida",
			mx = "Página perdida",
			de = "Verlorene Seite",
			fr = "Page perdue",
			it = "Pagina Perduta",
			pt = "Página Perdida",
			ru = "Потерянная страница",
			ko = "잃어버린 책장",
			cn = "失落纸页",
			tw = "遺失的書頁",
		},
	},
	[620537] = {
		readable = "Lost Page",
		model = 6103388,
		text = {
			en = "Lost Page",
			es = "Página perdida",
			mx = "Página perdida",
			de = "Verlorene Seite",
			fr = "Page perdue",
			it = "Pagina Perduta",
			pt = "Página Perdida",
			ru = "Потерянная страница",
			ko = "[Lost Page]",
			cn = "失落纸页",
			tw = "遺失的書頁",
		},
	},
	[620538] = {
		readable = "Lost Page",
		model = 6103388,
		text = {
			en = "Lost Page",
			es = "Página perdida",
			mx = "Página perdida",
			de = "Verlorene Seite",
			fr = "Page perdue",
			it = "Pagina Perduta",
			pt = "Página Perdida",
			ru = "Потерянная страница",
			ko = "[Lost Page]",
			cn = "失落纸页",
			tw = "遺失的書頁",
		},
	},
	[620688] = {
		readable = "Incomplete Book of Sonnets",
		model = 6081188,
		text = {
			en = "Incomplete Book of Sonnets",
			es = "Libro de sonetos incompleto",
			mx = "Libro de sonetos incompleto",
			de = "Unvollständiges Buch der Sonette",
			fr = "Livret de sonnets incomplet",
			it = "Libro di Sonetti Incompleto",
			pt = "Livreto dos Sonetos Incompleto",
			ru = "Неполная книга сонетов",
			ko = "[Incomplete Book of Sonnets]",
			cn = "未完成的十四行诗集",
			tw = "未完成的長詩集",
		},
	},
})
do ObjectDB[objectID] = objectData; end
