local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[618285] = {
		readable = "<span style=\"color: #A335EE\">Sturdy Chest</span>",
		model = 5128194,
		text = {
			en = "<span style=\"color: #A335EE\">Sturdy Chest</span>",
			es = "[Sturdy Chest]",
			mx = "<span style=\"color: #A335EE\">Cofre robusto</span>",
			de = "<span style=\"color: #A335EE\">Robuste Truhe</span>",
			fr = "[Sturdy Chest]",
			it = "[Sturdy Chest]",
			pt = "[Sturdy Chest]",
			ru = "<span style=\"color: #A335EE\">Прочный сундук</span>",
			ko = "[Sturdy Chest]",
			cn = "[Sturdy Chest]",
			tw = "[Sturdy Chest]",
		},
	},
	[618286] = {
		readable = "<span style=\"color: #A335EE\">Sturdy Chest</span>",
		model = 5128194,
		text = {
			en = "<span style=\"color: #A335EE\">Sturdy Chest</span>",
			es = "[Sturdy Chest]",
			mx = "<span style=\"color: #A335EE\">Cofre robusto</span>",
			de = "<span style=\"color: #A335EE\">Robuste Truhe</span>",
			fr = "[Sturdy Chest]",
			it = "[Sturdy Chest]",
			pt = "[Sturdy Chest]",
			ru = "<span style=\"color: #A335EE\">Прочный сундук</span>",
			ko = "[Sturdy Chest]",
			cn = "[Sturdy Chest]",
			tw = "[Sturdy Chest]",
		},
	},
	[618288] = {
		readable = "<span style=\"color: #A335EE\">Sturdy Chest</span>",
		model = 5128194,
		text = {
			en = "<span style=\"color: #A335EE\">Sturdy Chest</span>",
			es = "[Sturdy Chest]",
			mx = "[Sturdy Chest]",
			de = "<span style=\"color: #A335EE\">Robuste Truhe</span>",
			fr = "<span style=\"color: #A335EE\">Coffre solide</span>",
			it = "[Sturdy Chest]",
			pt = "[Sturdy Chest]",
			ru = "[Sturdy Chest]",
			ko = "[Sturdy Chest]",
			cn = "[Sturdy Chest]",
			tw = "[Sturdy Chest]",
		},
	},
	[618289] = {
		readable = "<span style=\"color: #A335EE\">Sturdy Chest</span>",
		model = 5128194,
		text = {
			en = "<span style=\"color: #A335EE\">Sturdy Chest</span>",
			es = "[Sturdy Chest]",
			mx = "[Sturdy Chest]",
			de = "<span style=\"color: #A335EE\">Robuste Truhe</span>",
			fr = "<span style=\"color: #A335EE\">Coffre solide</span>",
			it = "[Sturdy Chest]",
			pt = "[Sturdy Chest]",
			ru = "[Sturdy Chest]",
			ko = "[Sturdy Chest]",
			cn = "[Sturdy Chest]",
			tw = "[Sturdy Chest]",
		},
	},
	[618291] = {
		readable = "<span style=\"color: #A335EE\">Sturdy Chest</span>",
		model = 5128194,
		text = {
			en = "<span style=\"color: #A335EE\">Sturdy Chest</span>",
			es = "[Sturdy Chest]",
			mx = "[Sturdy Chest]",
			de = "[Sturdy Chest]",
			fr = "[Sturdy Chest]",
			it = "[Sturdy Chest]",
			pt = "[Sturdy Chest]",
			ru = "[Sturdy Chest]",
			ko = "[Sturdy Chest]",
			cn = "[Sturdy Chest]",
			tw = "[Sturdy Chest]",
		},
	},
	[618292] = {
		readable = "<span style=\"color: #A335EE\">Sturdy Chest</span>",
		model = 5128194,
		text = {
			en = "<span style=\"color: #A335EE\">Sturdy Chest</span>",
			es = "<span style=\"color: #A335EE\">Cofre robusto</span>",
			mx = "[Sturdy Chest]",
			de = "<span style=\"color: #A335EE\">Robuste Truhe</span>",
			fr = "<span style=\"color: #A335EE\">Coffre solide</span>",
			it = "[Sturdy Chest]",
			pt = "[Sturdy Chest]",
			ru = "[Sturdy Chest]",
			ko = "[Sturdy Chest]",
			cn = "[Sturdy Chest]",
			tw = "[Sturdy Chest]",
		},
	},
	[618293] = {
		readable = "Sturdy Chest",
		model = 5128194,
		text = {
			en = "Sturdy Chest",
			es = "[Sturdy Chest]",
			mx = "[Sturdy Chest]",
			de = "[Sturdy Chest]",
			fr = "[Sturdy Chest]",
			it = "[Sturdy Chest]",
			pt = "[Sturdy Chest]",
			ru = "[Sturdy Chest]",
			ko = "[Sturdy Chest]",
			cn = "[Sturdy Chest]",
			tw = "[Sturdy Chest]",
		},
	},
	[618294] = {
		readable = "Sturdy Chest",
		model = 5128194,
		text = {
			en = "Sturdy Chest",
			es = "[Sturdy Chest]",
			mx = "[Sturdy Chest]",
			de = "[Sturdy Chest]",
			fr = "[Sturdy Chest]",
			it = "[Sturdy Chest]",
			pt = "[Sturdy Chest]",
			ru = "[Sturdy Chest]",
			ko = "[Sturdy Chest]",
			cn = "[Sturdy Chest]",
			tw = "[Sturdy Chest]",
		},
	},
	[618295] = {
		readable = "Sturdy Chest",
		model = 5128194,
		text = {
			en = "Sturdy Chest",
			es = "[Sturdy Chest]",
			mx = "[Sturdy Chest]",
			de = "[Sturdy Chest]",
			fr = "[Sturdy Chest]",
			it = "[Sturdy Chest]",
			pt = "[Sturdy Chest]",
			ru = "[Sturdy Chest]",
			ko = "[Sturdy Chest]",
			cn = "[Sturdy Chest]",
			tw = "[Sturdy Chest]",
		},
	},
	[618517] = {
		readable = "Thalassian Lumber",
		model = 6922313,
		text = {
			en = "Thalassian Lumber",
			es = "Madera thalassiana",
			mx = "[Thalassian Lumber]",
			de = "Thalassisches Holz",
			fr = "Bois thalassien",
			it = "Legname Thalassiano",
			pt = "Lenha Talassiana",
			ru = "Талассийская древесина",
			ko = "[Thalassian Lumber]",
		},
	},
})
do ObjectDB[objectID] = objectData; end
