local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[571070] = {
		readable = "Olemba Lumber",
		model = 6922313,
		text = {
			en = "Olemba Lumber",
			es = "[Olemba Lumber]",
			mx = "[Olemba Lumber]",
			de = "[Olemba Lumber]",
			fr = "[Olemba Lumber]",
			it = "[Olemba Lumber]",
			pt = "[Olemba Lumber]",
			ru = "[Olemba Lumber]",
			ko = "[Olemba Lumber]",
			cn = "[Olemba Lumber]",
			tw = "[Olemba Lumber]",
		},
	},
	[571071] = {
		readable = "Olemba Lumber",
		model = 6922313,
		text = {
			en = "Olemba Lumber",
			es = "[Olemba Lumber]",
			mx = "[Olemba Lumber]",
			de = "[Olemba Lumber]",
			fr = "[Olemba Lumber]",
			it = "[Olemba Lumber]",
			pt = "[Olemba Lumber]",
			ru = "[Olemba Lumber]",
			ko = "[Olemba Lumber]",
			cn = "[Olemba Lumber]",
			tw = "[Olemba Lumber]",
		},
	},
	[571213] = {
		readable = "Olemba Lumber",
		model = 6922313,
		text = {
			en = "Olemba Lumber",
			es = "[Olemba Lumber]",
			mx = "[Olemba Lumber]",
			de = "Olembaholz",
			fr = "Bois d’olemba",
			it = "[Olemba Lumber]",
			pt = "[Olemba Lumber]",
			ru = "Древесина Олембы",
			ko = "[Olemba Lumber]",
			cn = "[Olemba Lumber]",
			tw = "[Olemba Lumber]",
		},
	},
	[571345] = {
		readable = "Olemba Lumber",
		model = 6922313,
		text = {
			en = "Olemba Lumber",
			es = "[Olemba Lumber]",
			mx = "[Olemba Lumber]",
			de = "Olembaholz",
			fr = "[Olemba Lumber]",
			it = "[Olemba Lumber]",
			pt = "[Olemba Lumber]",
			ru = "Древесина Олембы",
			ko = "[Olemba Lumber]",
			cn = "[Olemba Lumber]",
			tw = "[Olemba Lumber]",
		},
	},
	[572094] = {
		readable = "Olemba Lumber",
		model = 6922313,
		text = {
			en = "Olemba Lumber",
			es = "Madera de olemba",
			mx = "[Olemba Lumber]",
			de = "Olembaholz",
			fr = "Bois d’olemba",
			it = "Legname di Olemba",
			pt = "Lenha de Olemba",
			ru = "Древесина Олембы",
			ko = "[Olemba Lumber]",
			cn = "[Olemba Lumber]",
			tw = "[Olemba Lumber]",
		},
	},
	[572869] = {
		readable = "Olemba Lumber",
		model = 6922313,
		text = {
			en = "Olemba Lumber",
			es = "Madera de olemba",
			mx = "[Olemba Lumber]",
			de = "Olembaholz",
			fr = "Bois d’olemba",
			it = "Legname di Olemba",
			pt = "Lenha de Olemba",
			ru = "Древесина Олембы",
			ko = "[Olemba Lumber]",
			cn = "[Olemba Lumber]",
			tw = "[Olemba Lumber]",
		},
	},
	[572995] = {
		readable = "Olemba Lumber",
		model = 6922313,
		text = {
			en = "Olemba Lumber",
			es = "Madera de olemba",
			mx = "[Olemba Lumber]",
			de = "Olembaholz",
			fr = "Bois d’olemba",
			it = "Legname di Olemba",
			pt = "Lenha de Olemba",
			ru = "Древесина Олембы",
			ko = "[Olemba Lumber]",
			cn = "[Olemba Lumber]",
			tw = "[Olemba Lumber]",
		},
	},
})
do ObjectDB[objectID] = objectData; end
