local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[617534] = {
		readable = "Gilded Armillary Sphere",
		model = 6033622,
		text = {
			en = "Gilded Armillary Sphere",
			es = "Esfera armilar dorada",
			mx = "Esfera armilar dorada",
			de = "Vergoldete Armillarsphäre",
			fr = "Sphère armillaire dorée",
			it = "Sfera Armillare Dorata",
			pt = "Esfera Armilar Dourada",
			ru = "Золоченая армиллярная сфера",
			ko = "금빛 고리 구체",
			cn = "镀金浑天仪球体",
			tw = "鍍金圓球",
		},
	},
	[617659] = {
		readable = "Sealed Twilight's Blade Bounty",
		model = 5975175,
		text = {
			en = "Sealed Twilight's Blade Bounty",
			es = "Recompensa sellada de la Hoja Crepuscular",
			mx = "Botín de la Daga Crepuscular sellado",
			de = "Versiegelte Beute der Zwielichtklinge",
			fr = "Prime de la Lame du Crépuscule scellée",
			it = "Bottino Sigillato della Lama del Crepuscolo",
			pt = "Recompensa da Lâmina Crepuscular Selada",
			ru = "Запечатанное сокровище Сумеречного Клинка",
			ko = "[Sealed Twilight's Blade Bounty]",
			cn = "[Sealed Twilight's Blade Bounty]",
			tw = "[Sealed Twilight's Blade Bounty]",
		},
	},
	[617692] = {
		readable = "Crown of the Lost Queen",
		model = 3940006,
		text = {
			en = "Crown of the Lost Queen",
			es = "[Crown of the Lost Queen]",
			mx = "[Crown of the Lost Queen]",
			de = "[Crown of the Lost Queen]",
			fr = "[Crown of the Lost Queen]",
			it = "[Crown of the Lost Queen]",
			pt = "[Crown of the Lost Queen]",
			ru = "[Crown of the Lost Queen]",
			ko = "[Crown of the Lost Queen]",
			cn = "[Crown of the Lost Queen]",
			tw = "[Crown of the Lost Queen]",
		},
	},
	[617855] = {
		readable = "<span style=\"color: #A335EE\">Sturdy Chest</span>",
		model = 5128194,
		text = {
			en = "<span style=\"color: #A335EE\">Sturdy Chest</span>",
			es = "<span style=\"color: #A335EE\">Cofre robusto</span>",
			mx = "<span style=\"color: #A335EE\">Cofre robusto</span>",
			de = "<span style=\"color: #A335EE\">Robuste Truhe</span>",
			fr = "<span style=\"color: #A335EE\">Coffre solide</span>",
			it = "<span style=\"color: #A335EE\">Cassa Resistente</span>",
			pt = "<span style=\"color: #A335EE\">Baú Resistente</span>",
			ru = "<span style=\"color: #A335EE\">Прочный сундук</span>",
			ko = "[Sturdy Chest]",
			cn = "[Sturdy Chest]",
			tw = "<span style=\"color: #A335EE\">結實的箱子</span>",
		},
	},
	[617881] = {
		readable = "Rookery Cache",
		model = 6017293,
		text = {
			en = "Rookery Cache",
			es = "Alijo del Grajero",
			mx = "Alijo del Corvento",
			de = "Horsttruhe",
			fr = "Cache de la colonie",
			it = "Cassa della Corveria",
			pt = "Tesouro do Viveiro",
			ru = "Тайник Гнездовья",
			ko = "[Rookery Cache]",
			cn = "栖巢宝箱",
			tw = "培育所貯藏箱",
		},
	},
	[618016] = {
		readable = "Stellar Stash",
		model = 6210898,
		text = {
			en = "Stellar Stash",
			es = "[Stellar Stash]",
			mx = "[Stellar Stash]",
			de = "[Stellar Stash]",
			fr = "[Stellar Stash]",
			it = "[Stellar Stash]",
			pt = "[Stellar Stash]",
			ru = "[Stellar Stash]",
			ko = "[Stellar Stash]",
			cn = "[Stellar Stash]",
			tw = "[Stellar Stash]",
		},
	},
	[618111] = {
		readable = "<span style=\"color: #A335EE\">Sturdy Chest</span>",
		model = 5128194,
		text = {
			en = "<span style=\"color: #A335EE\">Sturdy Chest</span>",
			es = "<span style=\"color: #A335EE\">Cofre robusto</span>",
			mx = "<span style=\"color: #A335EE\">Cofre robusto</span>",
			de = "<span style=\"color: #A335EE\">Robuste Truhe</span>",
			fr = "<span style=\"color: #A335EE\">Coffre solide</span>",
			it = "<span style=\"color: #A335EE\">Cassa Resistente</span>",
			pt = "<span style=\"color: #A335EE\">Baú Resistente</span>",
			ru = "<span style=\"color: #A335EE\">Прочный сундук</span>",
			ko = "[Sturdy Chest]",
			cn = "[Sturdy Chest]",
			tw = "<span style=\"color: #A335EE\">結實的箱子</span>",
		},
	},
	[618112] = {
		readable = "<span style=\"color: #A335EE\">Sturdy Chest</span>",
		model = 5128194,
		text = {
			en = "<span style=\"color: #A335EE\">Sturdy Chest</span>",
			es = "<span style=\"color: #A335EE\">Cofre robusto</span>",
			mx = "<span style=\"color: #A335EE\">Cofre robusto</span>",
			de = "<span style=\"color: #A335EE\">Robuste Truhe</span>",
			fr = "<span style=\"color: #A335EE\">Coffre solide</span>",
			it = "<span style=\"color: #A335EE\">Cassa Resistente</span>",
			pt = "<span style=\"color: #A335EE\">Baú Resistente</span>",
			ru = "<span style=\"color: #A335EE\">Прочный сундук</span>",
			ko = "[Sturdy Chest]",
			cn = "[Sturdy Chest]",
			tw = "<span style=\"color: #A335EE\">結實的箱子</span>",
		},
	},
	[618270] = {
		readable = "<span style=\"color: #A335EE\">Sturdy Chest</span>",
		model = 5128194,
		text = {
			en = "<span style=\"color: #A335EE\">Sturdy Chest</span>",
			es = "<span style=\"color: #A335EE\">Cofre robusto</span>",
			mx = "[Sturdy Chest]",
			de = "<span style=\"color: #A335EE\">Robuste Truhe</span>",
			fr = "<span style=\"color: #A335EE\">Coffre solide</span>",
			it = "[Sturdy Chest]",
			pt = "[Sturdy Chest]",
			ru = "[Sturdy Chest]",
			ko = "[Sturdy Chest]",
			cn = "[Sturdy Chest]",
			tw = "[Sturdy Chest]",
		},
	},
	[618272] = {
		readable = "<span style=\"color: #A335EE\">Sturdy Chest</span>",
		model = 5128194,
		text = {
			en = "<span style=\"color: #A335EE\">Sturdy Chest</span>",
			es = "<span style=\"color: #A335EE\">Cofre robusto</span>",
			mx = "[Sturdy Chest]",
			de = "<span style=\"color: #A335EE\">Robuste Truhe</span>",
			fr = "<span style=\"color: #A335EE\">Coffre solide</span>",
			it = "[Sturdy Chest]",
		},
	},
})
do ObjectDB[objectID] = objectData; end
