local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[579193] = {
		readable = "Rusty Axe",
		model = 1005450,
		text = {
			en = "Rusty Axe",
			es = "Hacha oxidada",
			mx = "[Rusty Axe]",
			de = "Rostige Axt",
			fr = "Hache rouillée",
			it = "Ascia Arrugginita",
			pt = "Machado Enferrujado",
			ru = "Ржавый топор",
			ko = "[Rusty Axe]",
			cn = "[Rusty Axe]",
			tw = "[Rusty Axe]",
		},
	},
	[579233] = {
		readable = "Laments of Wey'nan--Part 1: Finding Hope",
		model = 6326920,
		text = {
			en = "Laments of Wey'nan--Part 1: Finding Hope",
			es = "Los lamentos de Wey'nan - Parte 1: En busca de esperanza",
			mx = "[Laments of Wey'nan--Part 1: Finding Hope]",
			de = "Wey'nans Wehklagen, Teil 1: Ein Funke der Hoffnung",
			fr = "Plaintes de Wey’nan, partie 1 : en quête d’espoir",
			it = "Lamenti di Wey'nan - Parte 1: Trovare la Speranza",
			pt = "Lamentos de Wey'nan, Parte 1: Em Busca de Esperança",
			ru = "Плач Вей'нана – часть 1: поиски надежды",
			ko = "[Laments of Wey'nan--Part 1: Finding Hope]",
			cn = "威南的哀悼——第1部分：找希望",
			tw = "偉南之悲--第1部：尋找希望",
		},
	},
	[579234] = {
		readable = "Laments of Wey'nan--Part 2:  Hunting Purpose",
		model = 6326920,
		text = {
			en = "Laments of Wey'nan--Part 2:  Hunting Purpose",
			es = "Los lamentos de Wey'nan - Parte 2: Tras un propósito",
			mx = "[Laments of Wey'nan--Part 2:  Hunting Purpose]",
			de = "Wey'nans Wehklagen, Teil 2: Die Jagd nach Sinn",
			fr = "Plaintes de Wey’nan, partie 2 : finalité de la chasse",
			it = "Lamenti di Wey'nan - Parte 2: A Caccia di uno Scopo",
			pt = "Lamentos de Wey'nan, Parte 2: À Caça de um Propósito",
			ru = "Плач Вей'нана – часть 2: цель охоты",
			ko = "[Laments of Wey'nan--Part 2:  Hunting Purpose]",
			cn = "威南的哀悼——第2部分：狩猎使命",
			tw = "偉南之悲--第2部：追求使命",
		},
	},
	[579235] = {
		readable = "Laments of Wey'nan--Part 3: There Must Be More",
		model = 6326920,
		text = {
			en = "Laments of Wey'nan--Part 3: There Must Be More",
			es = "Los lamentos de Wey'nan - Parte 3: Debe de haber más",
			mx = "[Laments of Wey'nan--Part 3: There Must Be More]",
			de = "Wey'nans Wehklagen, Teil 3: Das kann nicht alles sein",
			fr = "Plaintes de Wey’nan, partie 3 : plus encore",
			it = "Lamenti di Wey'nan - Parte 3: Deve Esserci Altro",
			pt = "Lamentos de Wey'nan, Parte 3: Tem que Haver Algo Mais",
			ru = "Плач Вей'нана – часть 3: рано отступать",
			ko = "[Laments of Wey'nan--Part 3: There Must Be More]",
			cn = "威南的哀悼——第3部分：定能超越",
			tw = "偉南之悲--第3部：永無止境",
		},
	},
	[579242] = {
		readable = "Tending the Lands--Part 1: The Conflict",
		model = 6326920,
		text = {
			en = "Tending the Lands--Part 1: The Conflict",
			es = "Cuidando las tierras - Parte 1: El conflicto",
			mx = "[Tending the Lands--Part 1: The Conflict]",
			de = "Im Dienst des Landes, Teil 1: Der Konflikt",
			fr = "Préservation des terres, partie 1 : le conflit",
			it = "[Tending the Lands--Part 1: The Conflict]",
			pt = "[Tending the Lands--Part 1: The Conflict]",
			ru = "Забота о земле – часть 1: раздор",
			ko = "[Tending the Lands--Part 1: The Conflict]",
			cn = "[Tending the Lands--Part 1: The Conflict]",
			tw = "[Tending the Lands--Part 1: The Conflict]",
		},
	},
	[579243] = {
		readable = "Tending the Lands--Part 2: The Plan",
		model = 6326920,
		text = {
			en = "Tending the Lands--Part 2: The Plan",
			es = "Cuidando las tierras - Parte 2: El plan",
			mx = "[Tending the Lands--Part 2: The Plan]",
			de = "Im Dienst des Landes, Teil 2: Der Plan",
			fr = "Préservation des terres, partie 2 : le plan",
			it = "[Tending the Lands--Part 2: The Plan]",
			pt = "[Tending the Lands--Part 2: The Plan]",
			ru = "Забота о земле – часть 2: план",
			ko = "[Tending the Lands--Part 2: The Plan]",
			cn = "[Tending the Lands--Part 2: The Plan]",
			tw = "[Tending the Lands--Part 2: The Plan]",
		},
	},
	[579244] = {
		readable = "Tending the Lands--Part 3: The Cycle",
		model = 6326920,
		text = {
			en = "Tending the Lands--Part 3: The Cycle",
			es = "Cuidando las tierras - Parte 3: El ciclo",
			mx = "[Tending the Lands--Part 3: The Cycle]",
			de = "Im Dienst des Landes, Teil 3: Der Kreislauf",
			fr = "Préservation des terres, partie 3 : le cycle",
			it = "[Tending the Lands--Part 3: The Cycle]",
			pt = "[Tending the Lands--Part 3: The Cycle]",
			ru = "Забота о земле – часть 3: цикл",
			ko = "[Tending the Lands--Part 3: The Cycle]",
			cn = "[Tending the Lands--Part 3: The Cycle]",
			tw = "[Tending the Lands--Part 3: The Cycle]",
		},
	},
	[582157] = {
		readable = "Spiritpaw Satchel",
		model = 1255202,
		text = {
			en = "Spiritpaw Satchel",
			es = "Bolsa de Pataespíritu",
			mx = "Bolsón de zarpánima",
			de = "Säckchen der Geisterpfoten",
			fr = "Sacoche patte-spirituelle",
			it = "Borsa degli Zampaspirito",
			pt = "Algibeira de Espiriturso",
			ru = "Сумка племени Призрачной Лапы",
			ko = "영혼발바닥 주머니",
			cn = "灵爪行囊",
			tw = "靈爪背袋",
		},
	},
	[584512] = {
		readable = "<span style=\"color: #889D9D\">Nemesis Strongbox</span>",
		model = 2907352,
		text = {
			en = "<span style=\"color: #889D9D\">Nemesis Strongbox</span>",
			es = "<span style=\"color: #889D9D\">Caja fuerte de némesis</span>",
			mx = "<span style=\"color: #889D9D\">Caja fuerte de némesis</span>",
			de = "<span style=\"color: #889D9D\">Schließkassette der Nemesis</span>",
			fr = "<span style=\"color: #889D9D\">Coffre-fort de Némésis</span>",
			it = "<span style=\"color: #889D9D\">Forziere della Nemesi</span>",
			pt = "<span style=\"color: #889D9D\">Caixa-forte da Nêmesis</span>",
			ru = "<span style=\"color: #889D9D\">Сейф заклятого врага</span>",
			ko = "[Nemesis Strongbox]",
			cn = "<span style=\"color: #889D9D\">宿敌保险箱</span>",
			tw = "<span style=\"color: #889D9D\">死敵保險箱</span>",
		},
	},
})
do ObjectDB[objectID] = objectData; end
