local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[618536] = {
		readable = "Scout's Pack",
		model = 6701013,
		text = {
			en = "Scout's Pack",
			es = "[Scout's Pack]",
			mx = "[Scout's Pack]",
			de = "[Scout's Pack]",
			fr = "[Scout's Pack]",
			it = "[Scout's Pack]",
			pt = "[Scout's Pack]",
			ru = "[Scout's Pack]",
			ko = "[Scout's Pack]",
			cn = "[Scout's Pack]",
			tw = "[Scout's Pack]",
		},
	},
	[618542] = {
		readable = "Void Armor",
		model = 6860745,
		text = {
			en = "Void Armor",
			es = "[Void Armor]",
			mx = "[Void Armor]",
			de = "[Void Armor]",
			fr = "[Void Armor]",
			it = "[Void Armor]",
			pt = "[Void Armor]",
			ru = "[Void Armor]",
			ko = "[Void Armor]",
			cn = "[Void Armor]",
			tw = "[Void Armor]",
		},
	},
	[618554] = {
		readable = "Ancient Tablet",
		model = 4235304,
		text = {
			en = "Ancient Tablet",
			es = "[Ancient Tablet]",
			mx = "[Ancient Tablet]",
			de = "[Ancient Tablet]",
			fr = "[Ancient Tablet]",
			it = "[Ancient Tablet]",
			pt = "[Ancient Tablet]",
			ru = "[Ancient Tablet]",
			ko = "[Ancient Tablet]",
			cn = "[Ancient Tablet]",
			tw = "[Ancient Tablet]",
		},
	},
	[618558] = {
		readable = "Abandoned Telescope",
		model = 6700990,
		text = {
			en = "Abandoned Telescope",
			es = "[Abandoned Telescope]",
			mx = "[Abandoned Telescope]",
			de = "[Abandoned Telescope]",
			fr = "[Abandoned Telescope]",
			it = "[Abandoned Telescope]",
			pt = "[Abandoned Telescope]",
			ru = "[Abandoned Telescope]",
			ko = "[Abandoned Telescope]",
			cn = "[Abandoned Telescope]",
			tw = "[Abandoned Telescope]",
		},
	},
	[618569] = {
		readable = "Tattered Page",
		model = 3152067,
		text = {
			en = "Tattered Page",
			es = "[Tattered Page]",
			mx = "[Tattered Page]",
			de = "[Tattered Page]",
			fr = "[Tattered Page]",
			it = "[Tattered Page]",
			pt = "[Tattered Page]",
			ru = "[Tattered Page]",
			ko = "[Tattered Page]",
			cn = "[Tattered Page]",
			tw = "[Tattered Page]",
		},
	},
	[618571] = {
		readable = "Shadowgraft Harness",
		model = 6860752,
		text = {
			en = "Shadowgraft Harness",
			es = "[Shadowgraft Harness]",
			mx = "[Shadowgraft Harness]",
			de = "[Shadowgraft Harness]",
			fr = "[Shadowgraft Harness]",
			it = "[Shadowgraft Harness]",
			pt = "[Shadowgraft Harness]",
			ru = "[Shadowgraft Harness]",
			ko = "[Shadowgraft Harness]",
			cn = "[Shadowgraft Harness]",
			tw = "[Shadowgraft Harness]",
		},
	},
	[618828] = {
		readable = "Stormarion Fragment",
		model = 1982821,
		text = {
			en = "Stormarion Fragment",
			es = "[Stormarion Fragment]",
			mx = "[Stormarion Fragment]",
			de = "[Stormarion Fragment]",
			fr = "[Stormarion Fragment]",
			it = "[Stormarion Fragment]",
			pt = "[Stormarion Fragment]",
			ru = "[Stormarion Fragment]",
			ko = "[Stormarion Fragment]",
			cn = "[Stormarion Fragment]",
			tw = "[Stormarion Fragment]",
		},
	},
	[619217] = {
		readable = "Overtaken Voidcaster",
		model = 511490,
		text = {
			en = "Overtaken Voidcaster",
			es = "Taumaturgo del Vacío superado",
			mx = "Invocavacío poseído",
			de = "Überwältigter Leerenwirker",
			fr = "Lanceur du Vide submergé",
			it = "Incantatore del Vuoto Sopraffatto",
			pt = "Lança-caos Sobrepujado",
			ru = "Поверженный маг Бездны",
			ko = "잠식당한 공허시전자",
			cn = "罹难的虚空施法者",
			tw = "受壓制的虛無法師",
		},
	},
	[619616] = {
		readable = "Thorncap",
		model = 5838120,
		text = {
			en = "Thorncap",
			es = "[Thorncap]",
			mx = "Hongoespina",
			de = "Dornenkappe",
			fr = "Champépine",
			it = "Cappaspina",
			pt = "Coguespinho",
			ru = "Капитерн",
			ko = "[Thorncap]",
			cn = "[Thorncap]",
			tw = "[Thorncap]",
		},
	},
	[619621] = {
		readable = "Vista Point",
		model = 4496829,
		text = {
			en = "Vista Point",
			es = "Punto de observación",
			mx = "Mirador",
		},
	},
})
do ObjectDB[objectID] = objectData; end
