local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[572254] = {
		readable = "Ironwood Lumber",
		model = 6922313,
		text = {
			en = "Ironwood Lumber",
			es = "Maderaférrea",
			mx = "Madera xiloférrea",
			de = "Eisenholz",
			fr = "Bois de bois-de-fer",
			it = "Legname di Legnoduro",
			pt = "Lenha de Pau-ferro",
			ru = "Древесина железного дерева",
			ko = "강철나무 목재",
			cn = "铁木木料",
			tw = "鐵木木材",
		},
	},
	[573057] = {
		readable = "Ironwood Lumber",
		model = 6922313,
		text = {
			en = "Ironwood Lumber",
			es = "Maderaférrea",
			mx = "Madera xiloférrea",
			de = "Eisenholz",
			fr = "Bois de bois-de-fer",
			it = "Legname di Legnoduro",
			pt = "Lenha de Pau-ferro",
			ru = "Древесина железного дерева",
			ko = "강철나무 목재",
			cn = "铁木木料",
			tw = "鐵木木材",
		},
	},
	[573368] = {
		readable = "Ironwood Lumber",
		model = 6922313,
		text = {
			en = "Ironwood Lumber",
			es = "Maderaférrea",
			mx = "Madera xiloférrea",
			de = "Eisenholz",
			fr = "Bois de bois-de-fer",
			it = "Legname di Legnoduro",
			pt = "Lenha de Pau-ferro",
			ru = "Древесина железного дерева",
			ko = "강철나무 목재",
			cn = "铁木木料",
			tw = "鐵木木材",
		},
	},
	[573459] = {
		readable = "Ironwood Lumber",
		model = 6922313,
		text = {
			en = "Ironwood Lumber",
			es = "Maderaférrea",
			mx = "Madera xiloférrea",
			de = "Eisenholz",
			fr = "Bois de bois-de-fer",
			it = "Legname di Legnoduro",
			pt = "Lenha de Pau-ferro",
			ru = "Древесина железного дерева",
			ko = "강철나무 목재",
			cn = "铁木木料",
			tw = "鐵木木材",
		},
	},
	[573695] = {
		readable = "Ironwood Lumber",
		model = 6922313,
		text = {
			en = "Ironwood Lumber",
			es = "Maderaférrea",
			mx = "Madera xiloférrea",
			de = "Eisenholz",
			fr = "Bois de bois-de-fer",
			it = "Legname di Legnoduro",
			pt = "Lenha de Pau-ferro",
			ru = "Древесина железного дерева",
			ko = "강철나무 목재",
			cn = "铁木木料",
			tw = "鐵木木材",
		},
	},
	[574416] = {
		readable = "Ironwood Lumber",
		model = 6922313,
		text = {
			en = "Ironwood Lumber",
			es = "Maderaférrea",
			mx = "Madera xiloférrea",
			de = "Eisenholz",
			fr = "Bois de bois-de-fer",
			it = "Legname di Legnoduro",
			pt = "Lenha de Pau-ferro",
			ru = "Древесина железного дерева",
			ko = "강철나무 목재",
			cn = "铁木木料",
			tw = "鐵木木材",
		},
	},
	[574596] = {
		readable = "Ironwood Lumber",
		model = 6922313,
		text = {
			en = "Ironwood Lumber",
			es = "Maderaférrea",
			mx = "Madera xiloférrea",
			de = "Eisenholz",
			fr = "Bois de bois-de-fer",
			it = "Legname di Legnoduro",
			pt = "Lenha de Pau-ferro",
			ru = "Древесина железного дерева",
			ko = "강철나무 목재",
			cn = "铁木木料",
			tw = "鐵木木材",
		},
	},
	[574599] = {
		readable = "Ironwood Lumber",
		model = 6922313,
		text = {
			en = "Ironwood Lumber",
			es = "Maderaférrea",
			mx = "Madera xiloférrea",
			de = "Eisenholz",
			fr = "Bois de bois-de-fer",
			it = "Legname di Legnoduro",
			pt = "Lenha de Pau-ferro",
			ru = "Древесина железного дерева",
			ko = "강철나무 목재",
			cn = "铁木木料",
			tw = "鐵木木材",
		},
	},
	[574611] = {
		readable = "Ashwood Lumber",
		model = 6922313,
		text = {
			en = "Ashwood Lumber",
			es = "Madera de fresno",
			mx = "Madera de xiloceniza",
			de = "Aschenholz",
			fr = "Bois de frêne",
			it = "Legname di Legno Secco",
			pt = "Lenha de Freixo",
			ru = "Ясеневая древесина",
			ko = "잿빛나무 목재",
			cn = "灰木木料",
			tw = "灰木木材",
		},
	},
	[574731] = {
		readable = "Ironwood Lumber",
		model = 6922313,
		text = {
			en = "Ironwood Lumber",
			es = "Maderaférrea",
			mx = "Madera xiloférrea",
			de = "Eisenholz",
			fr = "Bois de bois-de-fer",
			it = "Legname di Legnoduro",
			pt = "Lenha de Pau-ferro",
			ru = "Древесина железного дерева",
			ko = "강철나무 목재",
			cn = "铁木木料",
			tw = "鐵木木材",
		},
	},
	[574913] = {
		readable = "Ironwood Lumber",
		model = 6922313,
		text = {
			en = "Ironwood Lumber",
			es = "Maderaférrea",
			mx = "Madera xiloférrea",
			de = "Eisenholz",
			fr = "Bois de bois-de-fer",
			it = "Legname di Legnoduro",
			pt = "Lenha de Pau-ferro",
			ru = "Древесина железного дерева",
			ko = "강철나무 목재",
			cn = "铁木木料",
			tw = "鐵木木材",
		},
	},
	[574938] = {
		readable = "Ironwood Lumber",
		model = 6922313,
		text = {
			en = "Ironwood Lumber",
			es = "Maderaférrea",
			mx = "Madera xiloférrea",
			de = "Eisenholz",
			fr = "Bois de bois-de-fer",
			it = "Legname di Legnoduro",
			pt = "Lenha de Pau-ferro",
			ru = "Древесина железного дерева",
			ko = "강철나무 목재",
			cn = "铁木木料",
			tw = "鐵木木材",
		},
	},
	[574966] = {
		readable = "Ironwood Lumber",
		model = 6922313,
		text = {
			en = "Ironwood Lumber",
			es = "Maderaférrea",
			mx = "Madera xiloférrea",
			de = "Eisenholz",
			fr = "Bois de bois-de-fer",
			it = "Legname di Legnoduro",
			pt = "Lenha de Pau-ferro",
			ru = "Древесина железного дерева",
			ko = "강철나무 목재",
			cn = "铁木木料",
			tw = "鐵木木材",
		},
	},
	[575031] = {
		readable = "Ironwood Lumber",
		model = 6922313,
		text = {
			en = "Ironwood Lumber",
			es = "Maderaférrea",
			mx = "Madera xiloférrea",
			de = "Eisenholz",
			fr = "Bois de bois-de-fer",
			it = "Legname di Legnoduro",
			pt = "Lenha de Pau-ferro",
			ru = "Древесина железного дерева",
			ko = "강철나무 목재",
			cn = "铁木木料",
			tw = "鐵木木材",
		},
	},
	[576113] = {
		readable = "Ironwood Lumber",
		model = 6922313,
		text = {
			en = "Ironwood Lumber",
			es = "Maderaférrea",
			mx = "Madera xiloférrea",
			de = "Eisenholz",
			fr = "Bois de bois-de-fer",
			it = "Legname di Legnoduro",
			pt = "Lenha de Pau-ferro",
			ru = "Древесина железного дерева",
			ko = "강철나무 목재",
			cn = "铁木木料",
			tw = "鐵木木材",
		},
	},
	[576199] = {
		readable = "Ironwood Lumber",
		model = 6922313,
		text = {
			en = "Ironwood Lumber",
			es = "Maderaférrea",
			mx = "Madera xiloférrea",
			de = "Eisenholz",
			fr = "Bois de bois-de-fer",
			it = "Legname di Legnoduro",
			pt = "Lenha de Pau-ferro",
			ru = "Древесина железного дерева",
			ko = "강철나무 목재",
			cn = "铁木木料",
			tw = "鐵木木材",
		},
	},
	[576282] = {
		readable = "Ironwood Lumber",
		model = 6922313,
		text = {
			en = "Ironwood Lumber",
			es = "Maderaférrea",
			mx = "Madera xiloférrea",
			de = "Eisenholz",
			fr = "Bois de bois-de-fer",
			it = "Legname di Legnoduro",
			pt = "Lenha de Pau-ferro",
			ru = "Древесина железного дерева",
			ko = "강철나무 목재",
			cn = "铁木木料",
			tw = "鐵木木材",
		},
	},
	[576400] = {
		readable = "Ironwood Lumber",
		model = 6922313,
		text = {
			en = "Ironwood Lumber",
			es = "Maderaférrea",
			mx = "Madera xiloférrea",
			de = "Eisenholz",
			fr = "Bois de bois-de-fer",
			it = "Legname di Legnoduro",
			pt = "Lenha de Pau-ferro",
			ru = "Древесина железного дерева",
			ko = "강철나무 목재",
			cn = "铁木木料",
			tw = "鐵木木材",
		},
	},
	[576402] = {
		readable = "Ironwood Lumber",
		model = 6922313,
		text = {
			en = "Ironwood Lumber",
			es = "Maderaférrea",
			mx = "Madera xiloférrea",
			de = "Eisenholz",
			fr = "Bois de bois-de-fer",
			it = "Legname di Legnoduro",
			pt = "Lenha de Pau-ferro",
			ru = "Древесина железного дерева",
			ko = "강철나무 목재",
			cn = "铁木木料",
			tw = "鐵木木材",
		},
	},
	[576448] = {
		readable = "Ironwood Lumber",
		model = 6922313,
		text = {
			en = "Ironwood Lumber",
			es = "Maderaférrea",
			mx = "Madera xiloférrea",
			de = "Eisenholz",
			fr = "Bois de bois-de-fer",
			it = "Legname di Legnoduro",
			pt = "Lenha de Pau-ferro",
			ru = "Древесина железного дерева",
			ko = "강철나무 목재",
			cn = "铁木木料",
			tw = "鐵木木材",
		},
	},
	[576622] = {
		readable = "Ironwood Lumber",
		model = 6922313,
		text = {
			en = "Ironwood Lumber",
			es = "Maderaférrea",
			mx = "Madera xiloférrea",
			de = "Eisenholz",
			fr = "Bois de bois-de-fer",
			it = "Legname di Legnoduro",
			pt = "Lenha de Pau-ferro",
			ru = "Древесина железного дерева",
			ko = "강철나무 목재",
			cn = "铁木木料",
			tw = "鐵木木材",
		},
	},
	[576692] = {
		readable = "Ironwood Lumber",
		model = 6922313,
		text = {
			en = "Ironwood Lumber",
			es = "Maderaférrea",
			mx = "Madera xiloférrea",
			de = "Eisenholz",
			fr = "Bois de bois-de-fer",
			it = "Legname di Legnoduro",
			pt = "Lenha de Pau-ferro",
			ru = "Древесина железного дерева",
			ko = "강철나무 목재",
			cn = "铁木木料",
			tw = "鐵木木材",
		},
	},
	[576717] = {
		readable = "Ironwood Lumber",
		model = 6922313,
		text = {
			en = "Ironwood Lumber",
			es = "Maderaférrea",
			mx = "Madera xiloférrea",
			de = "Eisenholz",
			fr = "Bois de bois-de-fer",
			it = "Legname di Legnoduro",
			pt = "Lenha de Pau-ferro",
			ru = "Древесина железного дерева",
			ko = "강철나무 목재",
			cn = "铁木木料",
			tw = "鐵木木材",
		},
	},
	[577703] = {
		readable = "Ironwood Lumber",
		model = 6922313,
		text = {
			en = "Ironwood Lumber",
			es = "Maderaférrea",
			mx = "Madera xiloférrea",
			de = "Eisenholz",
			fr = "Bois de bois-de-fer",
			it = "Legname di Legnoduro",
			pt = "Lenha de Pau-ferro",
			ru = "Древесина железного дерева",
			ko = "강철나무 목재",
			cn = "铁木木料",
			tw = "鐵木木材",
		},
	},
	[577787] = {
		readable = "Ironwood Lumber",
		model = 6922313,
		text = {
			en = "Ironwood Lumber",
			es = "Maderaférrea",
			mx = "Madera xiloférrea",
			de = "Eisenholz",
			fr = "Bois de bois-de-fer",
			it = "Legname di Legnoduro",
			pt = "Lenha de Pau-ferro",
			ru = "Древесина железного дерева",
			ko = "강철나무 목재",
			cn = "铁木木料",
			tw = "鐵木木材",
		},
	},
	[577792] = {
		readable = "Ironwood Lumber",
		model = 6922313,
		text = {
			en = "Ironwood Lumber",
			es = "Maderaférrea",
			mx = "Madera xiloférrea",
			de = "Eisenholz",
			fr = "Bois de bois-de-fer",
			it = "Legname di Legnoduro",
			pt = "Lenha de Pau-ferro",
			ru = "Древесина железного дерева",
			ko = "강철나무 목재",
			cn = "铁木木料",
			tw = "鐵木木材",
		},
	},
	[577999] = {
		readable = "Ironwood Lumber",
		model = 6922313,
		text = {
			en = "Ironwood Lumber",
			es = "Maderaférrea",
			mx = "Madera xiloférrea",
			de = "Eisenholz",
			fr = "Bois de bois-de-fer",
			it = "Legname di Legnoduro",
			pt = "Lenha de Pau-ferro",
			ru = "Древесина железного дерева",
			ko = "강철나무 목재",
			cn = "铁木木料",
			tw = "鐵木木材",
		},
	},
	[578023] = {
		readable = "Ironwood Lumber",
		model = 6922313,
		text = {
			en = "Ironwood Lumber",
			es = "Maderaférrea",
			mx = "Madera xiloférrea",
			de = "Eisenholz",
			fr = "Bois de bois-de-fer",
			it = "Legname di Legnoduro",
			pt = "Lenha de Pau-ferro",
			ru = "Древесина железного дерева",
			ko = "강철나무 목재",
			cn = "铁木木料",
			tw = "鐵木木材",
		},
	},
	[578925] = {
		readable = "Ironwood Lumber",
		model = 6922313,
		text = {
			en = "Ironwood Lumber",
			es = "Maderaférrea",
			mx = "Madera xiloférrea",
			de = "Eisenholz",
			fr = "Bois de bois-de-fer",
			it = "Legname di Legnoduro",
			pt = "Lenha de Pau-ferro",
			ru = "Древесина железного дерева",
			ko = "강철나무 목재",
			cn = "铁木木料",
			tw = "鐵木木材",
		},
	},
	[581830] = {
		readable = "Ironwood Lumber",
		model = 6922313,
		text = {
			en = "Ironwood Lumber",
			es = "Maderaférrea",
			mx = "Madera xiloférrea",
			de = "Eisenholz",
			fr = "Bois de bois-de-fer",
			it = "Legname di Legnoduro",
			pt = "Lenha de Pau-ferro",
			ru = "Древесина железного дерева",
			ko = "강철나무 목재",
			cn = "铁木木料",
			tw = "鐵木木材",
		},
	},
	[581876] = {
		readable = "Ironwood Lumber",
		model = 6922313,
		text = {
			en = "Ironwood Lumber",
			es = "Maderaférrea",
			mx = "Madera xiloférrea",
			de = "Eisenholz",
			fr = "Bois de bois-de-fer",
			it = "Legname di Legnoduro",
			pt = "Lenha de Pau-ferro",
			ru = "Древесина железного дерева",
			ko = "강철나무 목재",
			cn = "铁木木料",
			tw = "鐵木木材",
		},
	},
	[582143] = {
		readable = "Ironwood Lumber",
		model = 6922313,
		text = {
			en = "Ironwood Lumber",
			es = "Maderaférrea",
			mx = "Madera xiloférrea",
			de = "Eisenholz",
			fr = "Bois de bois-de-fer",
			it = "Legname di Legnoduro",
			pt = "Lenha de Pau-ferro",
			ru = "Древесина железного дерева",
			ko = "강철나무 목재",
			cn = "铁木木料",
			tw = "鐵木木材",
		},
	},
	[582149] = {
		readable = "Ironwood Lumber",
		model = 6922313,
		text = {
			en = "Ironwood Lumber",
			es = "Maderaférrea",
			mx = "Madera xiloférrea",
			de = "Eisenholz",
			fr = "Bois de bois-de-fer",
			it = "Legname di Legnoduro",
			pt = "Lenha de Pau-ferro",
			ru = "Древесина железного дерева",
			ko = "강철나무 목재",
			cn = "铁木木料",
			tw = "鐵木木材",
		},
	},
	[584445] = {
		readable = "Ironwood Lumber",
		model = 6922313,
		text = {
			en = "Ironwood Lumber",
			es = "Maderaférrea",
			mx = "Madera xiloférrea",
			de = "Eisenholz",
			fr = "Bois de bois-de-fer",
			it = "Legname di Legnoduro",
			pt = "Lenha de Pau-ferro",
			ru = "Древесина железного дерева",
			ko = "강철나무 목재",
			cn = "铁木木料",
			tw = "鐵木木材",
		},
	},
	[584475] = {
		readable = "Ironwood Lumber",
		model = 6922313,
		text = {
			en = "Ironwood Lumber",
			es = "Maderaférrea",
			mx = "Madera xiloférrea",
			de = "Eisenholz",
			fr = "Bois de bois-de-fer",
			it = "Legname di Legnoduro",
			pt = "Lenha de Pau-ferro",
			ru = "Древесина железного дерева",
			ko = "강철나무 목재",
			cn = "铁木木料",
			tw = "鐵木木材",
		},
	},
	[584615] = {
		readable = "Ironwood Lumber",
		model = 6922313,
		text = {
			en = "Ironwood Lumber",
			es = "Maderaférrea",
			mx = "Madera xiloférrea",
			de = "Eisenholz",
			fr = "Bois de bois-de-fer",
			it = "Legname di Legnoduro",
			pt = "Lenha de Pau-ferro",
			ru = "Древесина железного дерева",
			ko = "강철나무 목재",
			cn = "铁木木料",
			tw = "鐵木木材",
		},
	},
	[584694] = {
		readable = "Ironwood Lumber",
		model = 6922313,
		text = {
			en = "Ironwood Lumber",
			es = "Maderaférrea",
			mx = "Madera xiloférrea",
			de = "Eisenholz",
			fr = "Bois de bois-de-fer",
			it = "Legname di Legnoduro",
			pt = "Lenha de Pau-ferro",
			ru = "Древесина железного дерева",
			ko = "강철나무 목재",
			cn = "铁木木料",
			tw = "鐵木木材",
		},
	},
})
do ObjectDB[objectID] = objectData; end
