local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[550011] = {
		readable = "Paint-Speckled Gourd",
		model = 6326910,
		text = {
			en = "Paint-Speckled Gourd",
			es = "[Paint-Speckled Gourd]",
			mx = "[Paint-Speckled Gourd]",
			de = "[Paint-Speckled Gourd]",
			fr = "[Paint-Speckled Gourd]",
			it = "[Paint-Speckled Gourd]",
			pt = "[Paint-Speckled Gourd]",
			ru = "[Paint-Speckled Gourd]",
			ko = "[Paint-Speckled Gourd]",
			cn = "[Paint-Speckled Gourd]",
			tw = "[Paint-Speckled Gourd]",
		},
	},
	[555250] = {
		readable = "Forgotten Researcher's Cache",
		model = 6210898,
		text = {
			en = "Forgotten Researcher's Cache",
			es = "[Forgotten Researcher's Cache]",
			mx = "[Forgotten Researcher's Cache]",
			de = "[Forgotten Researcher's Cache]",
			fr = "[Forgotten Researcher's Cache]",
			it = "[Forgotten Researcher's Cache]",
			pt = "[Forgotten Researcher's Cache]",
			ru = "[Forgotten Researcher's Cache]",
			ko = "[Forgotten Researcher's Cache]",
			cn = "[Forgotten Researcher's Cache]",
			tw = "[Forgotten Researcher's Cache]",
		},
	},
	[557986] = {
		readable = "Petalwing Plume",
		model = 199704,
		text = {
			en = "Petalwing Plume",
			es = "[Petalwing Plume]",
			mx = "[Petalwing Plume]",
			de = "[Petalwing Plume]",
			fr = "[Petalwing Plume]",
			it = "[Petalwing Plume]",
			pt = "[Petalwing Plume]",
			ru = "[Petalwing Plume]",
			ko = "[Petalwing Plume]",
			cn = "[Petalwing Plume]",
			tw = "[Petalwing Plume]",
		},
	},
	[565238] = {
		readable = "Light Shard",
		model = 1607561,
		text = {
			en = "Light Shard",
			es = "[Light Shard]",
			mx = "[Light Shard]",
			de = "[Light Shard]",
			fr = "[Light Shard]",
			it = "[Light Shard]",
			pt = "[Light Shard]",
			ru = "[Light Shard]",
			ko = "[Light Shard]",
			cn = "[Light Shard]",
			tw = "[Light Shard]",
		},
	},
	[571132] = {
		readable = "Glowing Moth",
		model = 124932,
		text = {
			en = "Glowing Moth",
			es = "Polilla resplandeciente",
			mx = "Polilla brillante",
			de = "Leuchtende Motte",
			fr = "Phalène luminescent",
			it = "Falena Luminosa",
			pt = "Mariposa Brilhante",
			ru = "Светящийся мотылек",
			ko = "빛나는 나방",
			cn = "发光的飞蛾",
			tw = "發光蛾",
		},
	},
	[571149] = {
		readable = "Glowing Moth",
		model = 124932,
		text = {
			en = "Glowing Moth",
			es = "Polilla resplandeciente",
			mx = "Polilla brillante",
			de = "Leuchtende Motte",
			fr = "Phalène luminescent",
			it = "Falena Luminosa",
			pt = "Mariposa Brilhante",
			ru = "Светящийся мотылек",
			ko = "빛나는 나방",
			cn = "发光的飞蛾",
			tw = "發光蛾",
		},
	},
	[571718] = {
		readable = "Selune's Stormarion Cores",
		model = 6210898,
		text = {
			en = "Selune's Stormarion Cores",
			es = "[Selune's Stormarion Cores]",
			mx = "[Selune's Stormarion Cores]",
			de = "[Selune's Stormarion Cores]",
			fr = "[Selune's Stormarion Cores]",
			it = "[Selune's Stormarion Cores]",
			pt = "[Selune's Stormarion Cores]",
			ru = "[Selune's Stormarion Cores]",
			ko = "[Selune's Stormarion Cores]",
			cn = "[Selune's Stormarion Cores]",
			tw = "[Selune's Stormarion Cores]",
		},
	},
	[572819] = {
		readable = "Void-Shielded Tomb",
		model = 5916219,
		text = {
			en = "Void-Shielded Tomb",
			es = "[Void-Shielded Tomb]",
			mx = "[Void-Shielded Tomb]",
			de = "[Void-Shielded Tomb]",
			fr = "[Void-Shielded Tomb]",
			it = "[Void-Shielded Tomb]",
			pt = "[Void-Shielded Tomb]",
			ru = "[Void-Shielded Tomb]",
			ko = "[Void-Shielded Tomb]",
			cn = "[Void-Shielded Tomb]",
			tw = "[Void-Shielded Tomb]",
		},
	},
	[572906] = {
		readable = "Key of Fused Darkness",
		model = 970204,
		text = {
			en = "Key of Fused Darkness",
			es = "[Key of Fused Darkness]",
			mx = "[Key of Fused Darkness]",
			de = "[Key of Fused Darkness]",
			fr = "[Key of Fused Darkness]",
			it = "[Key of Fused Darkness]",
			pt = "[Key of Fused Darkness]",
			ru = "[Key of Fused Darkness]",
			ko = "[Key of Fused Darkness]",
			cn = "[Key of Fused Darkness]",
			tw = "[Key of Fused Darkness]",
		},
	},
	[574576] = {
		readable = "Idago's Warspear",
		model = 6212428,
		text = {
			en = "Idago's Warspear",
			es = "[Idago's Warspear]",
			mx = "[Idago's Warspear]",
			de = "[Idago's Warspear]",
			fr = "[Idago's Warspear]",
			it = "[Idago's Warspear]",
			pt = "[Idago's Warspear]",
			ru = "[Idago's Warspear]",
			ko = "[Idago's Warspear]",
			cn = "[Idago's Warspear]",
			tw = "[Idago's Warspear]",
		},
	},
})
do ObjectDB[objectID] = objectData; end
