local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[613758] = {
		readable = "Honored Warrior's Urn",
		model = 6870560,
		text = {
			en = "Honored Warrior's Urn",
			es = "[Honored Warrior's Urn]",
			mx = "[Honored Warrior's Urn]",
			de = "Urne des wohlwollenden Kriegers",
			fr = "Urne de combat glorieux",
			it = "[Honored Warrior's Urn]",
			pt = "[Honored Warrior's Urn]",
			ru = "[Honored Warrior's Urn]",
			ko = "[Honored Warrior's Urn]",
			cn = "[Honored Warrior's Urn]",
			tw = "[Honored Warrior's Urn]",
		},
	},
	[613760] = {
		readable = "Honored Warrior's Urn",
		model = 6870560,
		text = {
			en = "Honored Warrior's Urn",
			es = "[Honored Warrior's Urn]",
			mx = "[Honored Warrior's Urn]",
			de = "[Honored Warrior's Urn]",
			fr = "Urne de combat glorieux",
			it = "[Honored Warrior's Urn]",
			pt = "[Honored Warrior's Urn]",
			ru = "[Honored Warrior's Urn]",
			ko = "[Honored Warrior's Urn]",
			cn = "[Honored Warrior's Urn]",
			tw = "[Honored Warrior's Urn]",
		},
	},
	[613823] = {
		readable = "Ancient Runestone",
		model = 6796710,
		text = {
			en = "Ancient Runestone",
			es = "[Ancient Runestone]",
			mx = "[Ancient Runestone]",
			de = "Uralter Runenstein",
			fr = "Pierre runique ancienne",
			it = "[Ancient Runestone]",
			pt = "[Ancient Runestone]",
			ru = "[Ancient Runestone]",
			ko = "[Ancient Runestone]",
			cn = "[Ancient Runestone]",
			tw = "[Ancient Runestone]",
		},
	},
	[613827] = {
		readable = "Derelict Mural",
		model = 6715096,
		text = {
			en = "Derelict Mural",
			es = "[Derelict Mural]",
			mx = "[Derelict Mural]",
			de = "Heruntergekommenes Wandbild",
			fr = "[Derelict Mural]",
			it = "[Derelict Mural]",
			pt = "[Derelict Mural]",
			ru = "[Derelict Mural]",
			ko = "[Derelict Mural]",
			cn = "[Derelict Mural]",
			tw = "[Derelict Mural]",
		},
	},
	[613828] = {
		readable = "Forgotten Mural",
		model = 6712537,
		text = {
			en = "Forgotten Mural",
			es = "[Forgotten Mural]",
			mx = "[Forgotten Mural]",
			de = "[Forgotten Mural]",
			fr = "[Forgotten Mural]",
			it = "[Forgotten Mural]",
			pt = "[Forgotten Mural]",
			ru = "[Forgotten Mural]",
			ko = "[Forgotten Mural]",
			cn = "[Forgotten Mural]",
			tw = "[Forgotten Mural]",
		},
	},
	[615963] = {
		readable = "Sporespawned Cache",
		model = 5838194,
		text = {
			en = "Sporespawned Cache",
			es = "[Sporespawned Cache]",
			mx = "[Sporespawned Cache]",
			de = "[Sporespawned Cache]",
			fr = "[Sporespawned Cache]",
			it = "[Sporespawned Cache]",
			pt = "[Sporespawned Cache]",
			ru = "[Sporespawned Cache]",
			ko = "[Sporespawned Cache]",
			cn = "[Sporespawned Cache]",
			tw = "[Sporespawned Cache]",
		},
	},
	[617163] = {
		readable = "Malignant Chest",
		model = 6210898,
		text = {
			en = "Malignant Chest",
			es = "[Malignant Chest]",
			mx = "[Malignant Chest]",
			de = "[Malignant Chest]",
			fr = "[Malignant Chest]",
			it = "[Malignant Chest]",
			pt = "[Malignant Chest]",
			ru = "[Malignant Chest]",
			ko = "[Malignant Chest]",
			cn = "[Malignant Chest]",
			tw = "[Malignant Chest]",
		},
	},
	[617237] = {
		readable = "Sealed Twilight's Blade Cache",
		model = 5975175,
		text = {
			en = "Sealed Twilight's Blade Cache",
			es = "[Sealed Twilight's Blade Cache]",
			mx = "[Sealed Twilight's Blade Cache]",
			de = "Versiegeltes Lager der Zwielichtklinge",
			fr = "[Sealed Twilight's Blade Cache]",
			it = "[Sealed Twilight's Blade Cache]",
			pt = "[Sealed Twilight's Blade Cache]",
			ru = "[Sealed Twilight's Blade Cache]",
			ko = "[Sealed Twilight's Blade Cache]",
			cn = "[Sealed Twilight's Blade Cache]",
			tw = "[Sealed Twilight's Blade Cache]",
		},
	},
	[617245] = {
		readable = "Broken Armor",
		model = 1015965,
		text = {
			en = "Broken Armor",
			es = "Broken Armor",
			mx = "Broken Armor",
			de = "Broken Armor",
			fr = "Broken Armor",
			it = "Broken Armor",
			pt = "Broken Armor",
			ru = "Broken Armor",
			ko = "Broken Armor",
			cn = "Broken Armor",
			tw = "Broken Armor",
		},
	},
	[617375] = {
		readable = "Murloc-Skewered Lynxfish",
		model = 1091579,
		text = {
			en = "Murloc-Skewered Lynxfish",
			es = "[Murloc-Skewered Lynxfish]",
			mx = "Pezlince ensartado múrloc",
			de = "Luchsfischspieß nach Murlocart",
			fr = "Brochette murloc de poisson-lynx",
			it = "Pescelince Infilzato dai Murloc",
			pt = "Peixe-lince Espetado por Murlocs",
			ru = "Мурлочий шашлык из рысевки",
			ko = "[Murloc-Skewered Lynxfish]",
			cn = "[Murloc-Skewered Lynxfish]",
			tw = "[Murloc-Skewered Lynxfish]",
		},
	},
	[617432] = {
		readable = "Forgotten Ink and Quill",
		model = 6935639,
		text = {
			en = "Forgotten Ink and Quill",
		},
	},
})
do ObjectDB[objectID] = objectData; end
