local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[656049] = {
		readable = "Odd Smelling Crate",
		model = 6159540,
		text = {
			en = "Odd Smelling Crate",
			es = "[Odd Smelling Crate]",
			mx = "[Odd Smelling Crate]",
			de = "[Odd Smelling Crate]",
			fr = "[Odd Smelling Crate]",
			it = "[Odd Smelling Crate]",
			pt = "[Odd Smelling Crate]",
			ru = "[Odd Smelling Crate]",
			ko = "[Odd Smelling Crate]",
			cn = "[Odd Smelling Crate]",
			tw = "[Odd Smelling Crate]",
		},
	},
	[658801] = {
		readable = "Specimen Container",
		model = 5916193,
		text = {
			en = "Specimen Container",
			es = "[Specimen Container]",
			mx = "[Specimen Container]",
			de = "[Specimen Container]",
			fr = "[Specimen Container]",
			it = "[Specimen Container]",
			pt = "[Specimen Container]",
			ru = "[Specimen Container]",
			ko = "[Specimen Container]",
			cn = "[Specimen Container]",
			tw = "[Specimen Container]",
		},
	},
	[658803] = {
		readable = "Spiked Shell",
		model = 6361139,
		text = {
			en = "Spiked Shell",
			es = "[Spiked Shell]",
			mx = "[Spiked Shell]",
			de = "[Spiked Shell]",
			fr = "[Spiked Shell]",
			it = "[Spiked Shell]",
			pt = "[Spiked Shell]",
			ru = "[Spiked Shell]",
			ko = "[Spiked Shell]",
			cn = "[Spiked Shell]",
			tw = "[Spiked Shell]",
		},
	},
})
do ObjectDB[objectID] = objectData; end
