local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[516465] = {
		readable = "Weighty Variable Rod",
		model = 3997999,
		text = {
			en = "Weighty Variable Rod",
			es = "Vara variable pesada",
			mx = "Vara variable pesada",
			de = "Schwerer Stab der Variablen",
			fr = "Bâtonnet variable alourdi",
			it = "Verga Variabile Pesante",
			pt = "Bastão de Variáveis Pesadas",
			ru = "Увесистый переменный жезл",
			ko = "묵직한 변수 막대",
			cn = "沉重的变量之杖",
			tw = "沉重的變數節杖",
		},
	},
	[516649] = {
		readable = "Research Log",
		model = 4335904,
		text = {
			en = "Research Log",
			es = "Registro de investigación",
			mx = "Registro de investigación",
			de = "Forschungstagebuch",
			fr = "Carnet de recherche",
			it = "Registro di Ricerca",
			pt = "Registro de Pesquisa",
			ru = "Журнал исследователя",
			ko = "연구 기록",
			cn = "研究日志",
			tw = "研究紀錄",
		},
	},
	[519447] = {
		readable = "Sun-Blessed Ballista",
		model = 6005290,
		text = {
			en = "Sun-Blessed Ballista",
			es = "Balista bendita por el sol",
			mx = "Balista de bendición solar",
			de = "Sonnengesegnete Balliste",
			fr = "Baliste bénie par le soleil",
			it = "Balista Benedetta dal Sole",
			pt = "Balista Soalheira",
			ru = "Солнцезарная баллиста",
			ko = "태양축복 쇠뇌",
			cn = "日佑弩炮",
			tw = "日祝弩砲",
		},
	},
	[519448] = {
		readable = "Sun-Blessed Ballista",
		model = 6005290,
		text = {
			en = "Sun-Blessed Ballista",
			es = "Balista bendita por el sol",
			mx = "Balista de bendición solar",
			de = "Sonnengesegnete Balliste",
			fr = "Baliste bénie par le soleil",
			it = "Balista Benedetta dal Sole",
			pt = "Balista Soalheira",
			ru = "Солнцезарная баллиста",
			ko = "태양축복 쇠뇌",
			cn = "日佑弩炮",
			tw = "日祝弩砲",
		},
	},
	[523499] = {
		readable = "Marsh Moss",
		model = 1794519,
		text = {
			en = "Marsh Moss",
			es = "Musgo de marisma",
			mx = "Musgo de pantano",
			de = "Morastmoos",
			fr = "Mousse des marais",
			it = "Muschio di Palude",
			pt = "Musgo do Pântano",
			ru = "Болотный мох",
			ko = "늪지대 이끼",
			cn = "沼泽苔",
			tw = "沼澤苔蘚",
		},
	},
	[523615] = {
		readable = "Fragrant Dreaming Glory",
		model = 219446,
		text = {
			en = "Fragrant Dreaming Glory",
			es = "Gloria de ensueño fragante",
			mx = "Gloria de ensueño fragante",
			de = "Duftende Traumwinde",
			fr = "Glaurier parfumé",
			it = "Gloria d'Oro Odorosa",
			pt = "Glória-sonhadora Fragrante",
			ru = "Ароматное сияние грез",
			ko = "향긋한 꿈초롱이",
			cn = "芳香的梦露花",
			tw = "芬芳的譽夢草",
		},
	},
	[523829] = {
		readable = "Cozy Heat Lamp",
		model = 3258516,
		text = {
			en = "Cozy Heat Lamp",
			es = "Lámpara de calor acogedora",
			mx = "Lámpara de calor acogedora",
			de = "Gemütliche Heizlampe",
			fr = "Lampe chauffante confortable",
			it = "Lampada Termica Confortante",
			pt = "Lâmpada de Calor Confortável",
			ru = "Уютная обогревательная лампа",
			ko = "아늑한 보온 등불",
			cn = "舒适的加热灯",
			tw = "溫暖的保溫燈",
		},
	},
	[524348] = {
		readable = "Snake Egg",
		model = 1658900,
		text = {
			en = "Snake Egg",
			es = "Huevo de serpiente",
			mx = "Huevo de serpiente",
			de = "Schlangenei",
			fr = "Œuf de serpent",
			it = "Uovo di Serpente",
			pt = "Ovo de Cobra",
			ru = "Змеиное яйцо",
			ko = "뱀 알",
			cn = "蛇蛋",
			tw = "蛇蛋",
		},
	},
	[527827] = {
		readable = "Trampled Bush",
		model = 5898776,
		text = {
			en = "Trampled Bush",
			es = "Arbusto pisoteado",
			mx = "Arbusto pisoteado",
			de = "Niedergetrampelter Busch",
			fr = "Buisson piétiné",
			it = "Cespuglio Calpestato",
			pt = "Arbusto Pisoteado",
			ru = "Растоптанный куст",
			ko = "짓밟힌 덤불",
			cn = "被踏过的树丛",
			tw = "被踐踏的灌木叢",
		},
	},
	[527829] = {
		readable = "Hasty Nest",
		model = 939261,
		text = {
			en = "Hasty Nest",
			es = "Nido improvisado",
			mx = "Nido armado a las apuradas",
			de = "Behelfsmäßiges Nest",
			fr = "Nid bâclé",
			it = "Nido Improvvisato",
			pt = "Ninho Improvisado",
			ru = "Недостроенное гнездо",
			ko = "황급하게 만든 둥지",
			cn = "仓促搭建的巢穴",
			tw = "草率的巢穴",
		},
	},
	[527831] = {
		readable = "Territorial Dispute",
		model = 6005271,
		text = {
			en = "Territorial Dispute",
		},
	},
})
do ObjectDB[objectID] = objectData; end
