local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[554848] = {
		readable = "Legacy Stone of the Goddess Guidance",
		model = 6712539,
		text = {
			en = "Legacy Stone of the Goddess Guidance",
			es = "[Legacy Stone of the Goddess Guidance]",
			mx = "[Legacy Stone of the Goddess Guidance]",
			de = "Vermächtnisstein der göttlichen Führung",
			fr = "Pierre d’héritage du conseil de la déesse",
			it = "[Legacy Stone of the Goddess Guidance]",
			pt = "[Legacy Stone of the Goddess Guidance]",
			ru = "Вековой камень наставления богини",
			ko = "[Legacy Stone of the Goddess Guidance]",
			cn = "[Legacy Stone of the Goddess Guidance]",
			tw = "[Legacy Stone of the Goddess Guidance]",
		},
	},
	[554966] = {
		readable = "Legacy Stone",
		model = 6712539,
		text = {
			en = "Legacy Stone",
			es = "[Legacy Stone]",
			mx = "[Legacy Stone]",
			de = "Vermächtnisstein",
			fr = "Pierre d’héritage",
			it = "[Legacy Stone]",
			pt = "[Legacy Stone]",
			ru = "Вековой камень",
			ko = "[Legacy Stone]",
			cn = "[Legacy Stone]",
			tw = "[Legacy Stone]",
		},
	},
	[555181] = {
		readable = "Etched Scroll",
		model = 6103388,
		text = {
			en = "Etched Scroll",
			es = "Pergamino con grabados",
			mx = "Pergamino con grabados",
			de = "Geätzte Schriftrolle",
			fr = "Parchemin gravé",
			it = "Pergamena Segnata",
			pt = "Pergaminho Gravado",
			ru = "Резной свиток",
			ko = "새겨진 두루마리",
			cn = "被侵蚀的卷轴",
			tw = "蝕刻卷軸",
		},
	},
	[555431] = {
		readable = "Scroll of Replenishment",
		model = 5975119,
		text = {
			en = "Scroll of Replenishment",
			es = "Pergamino de reabastecimiento",
			mx = "Pergamino de reposición",
			de = "Schriftrolle der Erfrischung",
			fr = "Parchemin de requinquage",
			it = "Pergamena del Ripristino",
			pt = "Pergaminho de Reabastecimento",
			ru = "Свиток восполнения",
			ko = "원기회복의 두루마리",
			cn = "补给卷轴",
			tw = "回復卷軸",
		},
	},
	[555631] = {
		readable = "Remnant of Anguish",
		model = 353152,
		text = {
			en = "Remnant of Anguish",
			es = "Remanente de angustia",
			mx = "Resto de angustia",
			de = "Überrest der Qual",
			fr = "Vestige d’angoisse",
			it = "Residuo dell'Angoscia",
			pt = "Resquício de Angústia",
			ru = "Отголосок страдания",
			ko = "고뇌의 잔여물",
			cn = "痛苦残渣",
			tw = "餘留苦痛",
		},
	},
	[562086] = {
		readable = "Resonance Stone",
		model = 6796710,
		text = {
			en = "Resonance Stone",
			es = "Piedra de resonancia",
			mx = "[Resonance Stone]",
			de = "Resonanzstein",
			fr = "Pierre de résonance",
			it = "[Resonance Stone]",
			pt = "[Resonance Stone]",
			ru = "[Resonance Stone]",
			ko = "[Resonance Stone]",
			cn = "[Resonance Stone]",
			tw = "[Resonance Stone]",
		},
	},
	[564925] = {
		readable = "Surplus Elementium",
		model = 372763,
		text = {
			en = "Surplus Elementium",
			es = "Excedentes de elementium",
			mx = "Elementium excedente",
			de = "Überschüssiges Elementium",
			fr = "Surplus d’élémentium",
			it = "Elementio in Eccesso",
			pt = "Elemêntio Excedente",
			ru = "Избыточный элементий",
			ko = "잉여 엘레멘티움",
			cn = "多余的源质",
			tw = "過剩源質",
		},
	},
	[566093] = {
		readable = "Locked Strongbox",
		model = 5975175,
		text = {
			en = "Locked Strongbox",
			es = "Caja fuerte cerrada",
			mx = "Caja fuerte cerrada",
			de = "Verschlossene Schließkassette",
			fr = "Coffre renforcé verrouillé",
			it = "Forziere Bloccato",
			pt = "Caixa-forte Trancada",
			ru = "Запертый сейф",
			ko = "[Locked Strongbox]",
			cn = "锁住的保险箱",
			tw = "上鎖的保險箱",
		},
	},
	[566768] = {
		readable = "Cache of the Deathless",
		model = 1314905,
		text = {
			en = "Cache of the Deathless",
			es = "[Cache of the Deathless]",
			mx = "[Cache of the Deathless]",
			de = "Truhe des Unsterblichen",
			fr = "Cache de l’Impérissable",
			it = "[Cache of the Deathless]",
			pt = "[Cache of the Deathless]",
			ru = "Тайник бессмертного",
			ko = "죽지 않는 자의 보관함",
			cn = "不灭者的宝箱",
			tw = "無死者寶箱",
		},
	},
	[571604] = {
		readable = "Weapon Rack",
		model = 6390448,
		text = {
			en = "Weapon Rack",
			es = "Expositor de armas",
			mx = "Expositor de armas",
			de = "Waffenregal",
			fr = "Râtelier d’armes",
			it = "Rastrelliera delle Armi",
			pt = "Cavalete de Armas",
			ru = "Оружейная стойка",
			ko = "무기 선반",
			cn = "武器架",
			tw = "武器架",
		},
	},
})
do ObjectDB[objectID] = objectData; end
