local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[571289] = {
		readable = "Glowing Moth",
		model = 124932,
		text = {
			en = "Glowing Moth",
			es = "Polilla resplandeciente",
			mx = "Polilla brillante",
			de = "Leuchtende Motte",
			fr = "Phalène luminescent",
			it = "Falena Luminosa",
			pt = "Mariposa Brilhante",
			ru = "Светящийся мотылек",
			ko = "빛나는 나방",
			cn = "发光的飞蛾",
			tw = "發光蛾",
		},
	},
	[571295] = {
		readable = "Glowing Moth",
		model = 124932,
		text = {
			en = "Glowing Moth",
			es = "Polilla resplandeciente",
			mx = "Polilla brillante",
			de = "Leuchtende Motte",
			fr = "Phalène luminescent",
			it = "Falena Luminosa",
			pt = "Mariposa Brilhante",
			ru = "Светящийся мотылек",
			ko = "빛나는 나방",
			cn = "发光的飞蛾",
			tw = "發光蛾",
		},
	},
	[571296] = {
		readable = "Glowing Moth",
		model = 124932,
		text = {
			en = "Glowing Moth",
			es = "Polilla resplandeciente",
			mx = "Polilla brillante",
			de = "Leuchtende Motte",
			fr = "Phalène luminescent",
			it = "Falena Luminosa",
			pt = "Mariposa Brilhante",
			ru = "Светящийся мотылек",
			ko = "빛나는 나방",
			cn = "发光的飞蛾",
			tw = "發光蛾",
		},
	},
	[571297] = {
		readable = "Glowing Moth",
		model = 124932,
		text = {
			en = "Glowing Moth",
			es = "Polilla resplandeciente",
			mx = "Polilla brillante",
			de = "Leuchtende Motte",
			fr = "Phalène luminescent",
			it = "Falena Luminosa",
			pt = "Mariposa Brilhante",
			ru = "Светящийся мотылек",
			ko = "빛나는 나방",
			cn = "发光的飞蛾",
			tw = "發光蛾",
		},
	},
	[571298] = {
		readable = "Glowing Moth",
		model = 124932,
		text = {
			en = "Glowing Moth",
			es = "Polilla resplandeciente",
			mx = "Polilla brillante",
			de = "Leuchtende Motte",
			fr = "Phalène luminescent",
			it = "Falena Luminosa",
			pt = "Mariposa Brilhante",
			ru = "Светящийся мотылек",
			ko = "빛나는 나방",
			cn = "发光的飞蛾",
			tw = "發光蛾",
		},
	},
	[571301] = {
		readable = "Glowing Moth",
		model = 124932,
		text = {
			en = "Glowing Moth",
			es = "Polilla resplandeciente",
			mx = "Polilla brillante",
			de = "Leuchtende Motte",
			fr = "Phalène luminescent",
			it = "Falena Luminosa",
			pt = "Mariposa Brilhante",
			ru = "Светящийся мотылек",
			ko = "빛나는 나방",
			cn = "发光的飞蛾",
			tw = "發光蛾",
		},
	},
	[571302] = {
		readable = "Glowing Moth",
		model = 124932,
		text = {
			en = "Glowing Moth",
			es = "Polilla resplandeciente",
			mx = "Polilla brillante",
			de = "Leuchtende Motte",
			fr = "Phalène luminescent",
			it = "Falena Luminosa",
			pt = "Mariposa Brilhante",
			ru = "Светящийся мотылек",
			ko = "빛나는 나방",
			cn = "发光的飞蛾",
			tw = "發光蛾",
		},
	},
	[571304] = {
		readable = "Glowing Moth",
		model = 124932,
		text = {
			en = "Glowing Moth",
			es = "Polilla resplandeciente",
			mx = "Polilla brillante",
			de = "Leuchtende Motte",
			fr = "Phalène luminescent",
			it = "Falena Luminosa",
			pt = "Mariposa Brilhante",
			ru = "Светящийся мотылек",
			ko = "빛나는 나방",
			cn = "发光的飞蛾",
			tw = "發光蛾",
		},
	},
	[571310] = {
		readable = "Glowing Moth",
		model = 124932,
		text = {
			en = "Glowing Moth",
			es = "Polilla resplandeciente",
			mx = "Polilla brillante",
			de = "Leuchtende Motte",
			fr = "Phalène luminescent",
			it = "Falena Luminosa",
			pt = "Mariposa Brilhante",
			ru = "Светящийся мотылек",
			ko = "빛나는 나방",
			cn = "发光的飞蛾",
			tw = "發光蛾",
		},
	},
	[571311] = {
		readable = "Glowing Moth",
		model = 124932,
		text = {
			en = "Glowing Moth",
			es = "Polilla resplandeciente",
			mx = "Polilla brillante",
			de = "Leuchtende Motte",
			fr = "Phalène luminescent",
			it = "Falena Luminosa",
			pt = "Mariposa Brilhante",
			ru = "Светящийся мотылек",
			ko = "빛나는 나방",
			cn = "发光的飞蛾",
			tw = "發光蛾",
		},
	},
	[571313] = {
		readable = "Glowing Moth",
		model = 124932,
		text = {
			en = "Glowing Moth",
			es = "Polilla resplandeciente",
			mx = "Polilla brillante",
			de = "Leuchtende Motte",
			fr = "Phalène luminescent",
			it = "Falena Luminosa",
			pt = "Mariposa Brilhante",
			ru = "Светящийся мотылек",
			ko = "빛나는 나방",
			cn = "发光的飞蛾",
			tw = "發光蛾",
		},
	},
	[571320] = {
		readable = "Glowing Moth",
		model = 124932,
		text = {
			en = "Glowing Moth",
			es = "Polilla resplandeciente",
			mx = "Polilla brillante",
			de = "Leuchtende Motte",
			fr = "Phalène luminescent",
			it = "Falena Luminosa",
			pt = "Mariposa Brilhante",
			ru = "Светящийся мотылек",
			ko = "빛나는 나방",
			cn = "发光的飞蛾",
			tw = "發光蛾",
		},
	},
})
do ObjectDB[objectID] = objectData; end
