local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[616918] = {
		readable = "Void Rift",
		model = 1624366,
		text = {
			en = "Void Rift",
			es = "Falla de Vacío",
			mx = "Falla del Vacío",
			de = "Leerenriss",
			fr = "Faille du Vide",
			it = "Fenditura del Vuoto",
			pt = "Fissura do Caos",
			ru = "Разлом Бездны",
			ko = "공허의 균열",
			cn = "虚空裂隙",
			tw = "虛無裂隙",
		},
	},
	[618844] = {
		readable = "Delve Campfire",
		model = 1525053,
		text = {
			en = "Delve Campfire",
			es = "Hoguera de la profundidad",
			mx = "Fogata de abismo",
			de = "Tiefenlagerfeuer",
			fr = "Feu de camp de Gouffre",
			it = "Fuoco da Campo della Scorribanda",
			pt = "Fogueira de Imersão",
			ru = "Костер вылазки",
			ko = "구렁 모닥불",
			cn = "地下堡营火",
			tw = "探究營火",
		},
	},
	[620105] = {
		readable = "Tasty Meat",
		model = 6051299,
		text = {
			en = "Tasty Meat",
			es = "Carne sabrosa",
			mx = "Carne sabrosa",
			de = "Schmackhaftes Fleisch",
			fr = "Viande appétissante",
			it = "Carne Gustosa",
			pt = "Carne Saborosa",
			ru = "Вкусное мясо",
			ko = "맛있는 고기",
			cn = "[Tasty Meat]",
			tw = "[Tasty Meat]",
		},
	},
	[627049] = {
		readable = "Hearthlight Armillary",
		model = 6033622,
		text = {
			en = "Hearthlight Armillary",
			es = "Armilla luzhogar",
			mx = "Hoguera armilar",
			de = "Heimlicht-Armillarsphäre",
			fr = "Sphère armillaire de foyer",
			it = "Armilla della Luce del Focolare",
			pt = "Armila Lumelar",
			ru = "Армиллярная сфера очага",
			ko = "난로불빛 팔찌",
			cn = "[Hearthlight Armillary]",
			tw = "爐光鍍金圓球",
		},
	},
	[628381] = {
		readable = "Sturdy Torch",
		model = 2503603,
		text = {
			en = "Sturdy Torch",
			es = "Antorcha recia",
			mx = "Antorcha robusta",
			de = "Stabile Fackel",
			fr = "Torche robuste",
			it = "Torcia Rinforzata",
			pt = "Tocha Resistente",
			ru = "Прочный факел",
			ko = "튼튼한 횃불",
			cn = "坚固的火把",
			tw = "結實火炬",
		},
	},
	[630870] = {
		readable = "Portal to Astalor's Sanctum",
		model = 351493,
		text = {
			en = "Portal to Astalor's Sanctum",
			es = "Portal al Sagrario de Astalor",
			mx = "[Portal to Astalor's Sanctum]",
			de = "Portal zu Astalors Sanktum",
			fr = "Portail vers le sanctum d’Astalor",
			it = "Portale per il Santuario di Astalor",
			pt = "Portal para o Sacrário de Astalor",
			ru = "Портал в покои Асталора",
			ko = "아스탈로르의 성소로 통하는 차원문",
			cn = "[Portal to Astalor's Sanctum]",
			tw = "[Portal to Astalor's Sanctum]",
		},
	},
	[638873] = {
		readable = "Orb of Translocation",
		model = 6024535,
		text = {
			en = "Orb of Translocation",
			es = "Orbe de traslado",
			mx = "Orbe de traslado",
			de = "Translokationskugel",
			fr = "Orbe de transposition",
			it = "Sfera di Traslocazione",
			pt = "Orbe de Deslocamento",
			ru = "Сфера транслокации",
			ko = "순간이동의 보주",
			cn = "传送宝珠",
			tw = "傳送之門",
		},
	},
})
do ObjectDB[objectID] = objectData; end
