local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[525962] = {
		readable = "Failed Experiment",
		model = 240975,
		text = {
			en = "Failed Experiment",
			es = "[Failed Experiment]",
			mx = "[Failed Experiment]",
			de = "[Failed Experiment]",
			fr = "[Failed Experiment]",
			it = "[Failed Experiment]",
			pt = "[Failed Experiment]",
			ru = "[Failed Experiment]",
			ko = "[Failed Experiment]",
			cn = "[Failed Experiment]",
			tw = "[Failed Experiment]",
		},
	},
	[525963] = {
		readable = "Pristine Potion",
		model = 4240485,
		text = {
			en = "Pristine Potion",
			es = "Poción prístina",
			mx = "[Pristine Potion]",
			de = "Makelloser Trank",
			fr = "Potion immaculée",
			it = "Pozione Immacolata",
			pt = "Poção Impecável",
			ru = "Безупречное зелье",
			ko = "[Pristine Potion]",
			cn = "原初药水",
			tw = "原始藥水",
		},
	},
	[525964] = {
		readable = "Measured Ladle",
		model = 6326885,
		text = {
			en = "Measured Ladle",
			es = "[Measured Ladle]",
			mx = "[Measured Ladle]",
			de = "Abgemessene Kelle",
			fr = "Louche graduée",
			it = "[Measured Ladle]",
			pt = "[Measured Ladle]",
			ru = "[Measured Ladle]",
			ko = "[Measured Ladle]",
			cn = "[Measured Ladle]",
			tw = "[Measured Ladle]",
		},
	},
	[525965] = {
		readable = "Freshly Plucked Peacebloom",
		model = 219481,
		text = {
			en = "Freshly Plucked Peacebloom",
			es = "Flor de paz recién cortada",
			mx = "[Freshly Plucked Peacebloom]",
			de = "Frisch gepflückte Friedensblume",
			fr = "Pacifique fraîchement cueillie",
			it = "Sbocciapace Appena Raccolto",
			pt = "Botão-da-paz Recém-arrancado",
			ru = "Свежайший мироцвет",
			ko = "[Freshly Plucked Peacebloom]",
			cn = "新采摘的宁神花",
			tw = "剛摘下的寧神花",
		},
	},
	[525966] = {
		readable = "Vial of Zul'Aman Oddities",
		model = 5364266,
		text = {
			en = "Vial of Zul'Aman Oddities",
			es = "[Vial of Zul'Aman Oddities]",
			mx = "[Vial of Zul'Aman Oddities]",
			de = "[Vial of Zul'Aman Oddities]",
			fr = "[Vial of Zul'Aman Oddities]",
			it = "Fiala di Stranezze di Zul'aman",
			pt = "[Vial of Zul'Aman Oddities]",
			ru = "[Vial of Zul'Aman Oddities]",
			ko = "[Vial of Zul'Aman Oddities]",
			cn = "[Vial of Zul'Aman Oddities]",
			tw = "[Vial of Zul'Aman Oddities]",
		},
	},
	[525967] = {
		readable = "Vial of Rootlands Oddities",
		model = 5364267,
		text = {
			en = "Vial of Rootlands Oddities",
			es = "[Vial of Rootlands Oddities]",
			mx = "[Vial of Rootlands Oddities]",
			de = "Phiole der Kuriositäten der Wurzellande",
			fr = "Fiole de curiosités des terres des Racines",
			it = "[Vial of Rootlands Oddities]",
			pt = "[Vial of Rootlands Oddities]",
			ru = "[Vial of Rootlands Oddities]",
			ko = "[Vial of Rootlands Oddities]",
			cn = "[Vial of Rootlands Oddities]",
			tw = "[Vial of Rootlands Oddities]",
		},
	},
	[525968] = {
		readable = "Vial of Voidstorm Oddities",
		model = 5364269,
		text = {
			en = "Vial of Voidstorm Oddities",
			es = "[Vial of Voidstorm Oddities]",
			mx = "[Vial of Voidstorm Oddities]",
			de = "[Vial of Voidstorm Oddities]",
			fr = "[Vial of Voidstorm Oddities]",
			it = "[Vial of Voidstorm Oddities]",
			pt = "[Vial of Voidstorm Oddities]",
			ru = "[Vial of Voidstorm Oddities]",
			ko = "[Vial of Voidstorm Oddities]",
			cn = "[Vial of Voidstorm Oddities]",
			tw = "[Vial of Voidstorm Oddities]",
		},
	},
	[525970] = {
		readable = "Bloomed Bud",
		model = 6437978,
		text = {
			en = "Bloomed Bud",
			es = "[Bloomed Bud]",
			mx = "[Bloomed Bud]",
			de = "Blühende Knospe",
			fr = "[Bloomed Bud]",
			it = "[Bloomed Bud]",
			pt = "[Bloomed Bud]",
			ru = "[Bloomed Bud]",
			ko = "[Bloomed Bud]",
			cn = "[Bloomed Bud]",
			tw = "[Bloomed Bud]",
		},
	},
	[525972] = {
		readable = "Simple Leaf Pruners",
		model = 955741,
		text = {
			en = "Simple Leaf Pruners",
			es = "Podadora sencilla",
			mx = "[Simple Leaf Pruners]",
			de = "Einfacher Blattschneider",
			fr = "Sécateur simple",
			it = "Cesoie Semplici per Fogliame",
			pt = "Tesoura de Folhas Simples",
			ru = "Простые садовые ножницы",
			ko = "[Simple Leaf Pruners]",
			cn = "[Simple Leaf Pruners]",
			tw = "[Simple Leaf Pruners]",
		},
	},
	[525973] = {
		readable = "Lightbloom Root",
		model = 6048324,
		text = {
			en = "Lightbloom Root",
			es = "[Lightbloom Root]",
			mx = "[Lightbloom Root]",
			de = "Lichtblütenwurzel",
			fr = "[Lightbloom Root]",
			it = "[Lightbloom Root]",
			pt = "[Lightbloom Root]",
			ru = "[Lightbloom Root]",
			ko = "[Lightbloom Root]",
			cn = "[Lightbloom Root]",
			tw = "[Lightbloom Root]",
		},
	},
	[525975] = {
		readable = "Harvester's Sickle",
		model = 1031834,
		text = {
			en = "Harvester's Sickle",
			es = "[Harvester's Sickle]",
			mx = "[Harvester's Sickle]",
			de = "Sichel des Ernters",
			fr = "Faucille de moisson",
			it = "[Harvester's Sickle]",
			pt = "Foice do Ceifador",
			ru = "Серп жнеца",
			ko = "[Harvester's Sickle]",
			cn = "[Harvester's Sickle]",
			tw = "[Harvester's Sickle]",
		},
	},
})
do ObjectDB[objectID] = objectData; end
