local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[504349] = {
		readable = "Cracked Holokey",
		model = 5479266,
		text = {
			en = "Cracked Holokey",
			es = "Holollave agrietada",
			mx = "Holollave agrietada",
			de = "Gesprungener Holoschlüssel",
			fr = "Holoclé fissurée",
			it = "Olochiave Incrinata",
			pt = "Holochave Rachada",
			ru = "Треснутый голографический ключ",
			ko = "금이 간 투영 열쇠",
			cn = "开裂的全息钥匙",
			tw = "裂開的全息鑰匙",
		},
	},
	[523589] = {
		readable = "Slain Beast",
		model = 124640,
		text = {
			en = "Slain Beast",
			es = "Bestia muerta",
			mx = "[Slain Beast]",
			de = "Getötete Bestie",
			fr = "Bête morte",
			it = "Bestia Uccisa",
			pt = "Fera Abatida",
			ru = "Убитый зверь",
			ko = "죽은 야수",
			cn = "死亡的野兽",
			tw = "被殺的野獸",
		},
	},
	[556511] = {
		readable = "Sunfruit",
		model = 5242777,
		text = {
			en = "Sunfruit",
			es = "Fruta solar",
			mx = "Fruta del sol",
			de = "Sonnenfrucht",
			fr = "Fruit solaire",
			it = "Solarancia",
			pt = "Frutassol",
			ru = "Солнцеплод",
			ko = "태양과",
			cn = "太阳果",
			tw = "太陽果",
		},
	},
})
do ObjectDB[objectID] = objectData; end
