local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[574585] = {
		readable = "Idago's Banner",
		model = 6212406,
		text = {
			en = "Idago's Banner",
			es = "[Idago's Banner]",
			mx = "[Idago's Banner]",
			de = "[Idago's Banner]",
			fr = "[Idago's Banner]",
			it = "[Idago's Banner]",
			pt = "[Idago's Banner]",
			ru = "[Idago's Banner]",
			ko = "[Idago's Banner]",
			cn = "[Idago's Banner]",
			tw = "[Idago's Banner]",
		},
	},
	[574750] = {
		readable = "Stolen Supplies",
		model = 6075563,
		text = {
			en = "Stolen Supplies",
			es = "[Stolen Supplies]",
			mx = "[Stolen Supplies]",
			de = "[Stolen Supplies]",
			fr = "[Stolen Supplies]",
			it = "[Stolen Supplies]",
			pt = "[Stolen Supplies]",
			ru = "[Stolen Supplies]",
			ko = "[Stolen Supplies]",
			cn = "[Stolen Supplies]",
			tw = "[Stolen Supplies]",
		},
	},
	[577799] = {
		readable = "Artisan's Cache",
		model = 6017293,
		text = {
			en = "Artisan's Cache",
			es = "Alijo de artesano",
			mx = "Alijo de artesano",
			de = "Truhe des Fachmanns",
			fr = "Cache d’artisan",
			it = "Cassa dell'Artigiano",
			pt = "Baú de Artífice",
			ru = "Тайник умельца",
			ko = "[Artisan's Cache]",
			cn = "[Artisan's Cache]",
			tw = "[Artisan's Cache]",
		},
	},
	[578030] = {
		readable = "Ancient Bone",
		model = 4417263,
		text = {
			en = "Ancient Bone",
			es = "[Ancient Bone]",
			mx = "[Ancient Bone]",
			de = "[Ancient Bone]",
			fr = "[Ancient Bone]",
			it = "[Ancient Bone]",
			pt = "[Ancient Bone]",
			ru = "[Ancient Bone]",
			ko = "[Ancient Bone]",
			cn = "[Ancient Bone]",
			tw = "[Ancient Bone]",
		},
	},
	[584517] = {
		readable = "Heavy Trunk",
		model = 5128194,
		text = {
			en = "Heavy Trunk",
			es = "Baúl pesado",
			mx = "Baúl pesado",
			de = "Schwere Truhe",
			fr = "Malle lourde",
			it = "Baule Pesante",
			pt = "Baú Pesado",
			ru = "Тяжелый ларь",
			ko = "[Heavy Trunk]",
			cn = "[Heavy Trunk]",
			tw = "沉重的箱子",
		},
	},
	[584519] = {
		readable = "Heavy Trunk",
		model = 5128194,
		text = {
			en = "Heavy Trunk",
			es = "Baúl pesado",
			mx = "Baúl pesado",
			de = "Schwere Truhe",
			fr = "Malle lourde",
			it = "Baule Pesante",
			pt = "Baú Pesado",
			ru = "Тяжелый ларь",
			ko = "[Heavy Trunk]",
			cn = "[Heavy Trunk]",
			tw = "沉重的箱子",
		},
	},
	[587307] = {
		readable = "Stone Vat",
		model = 6026040,
		text = {
			en = "Stone Vat",
			es = "Contenedor de piedra",
			mx = "Tanque de piedra",
			de = "Steinbottich",
			fr = "Cuve en pierre",
			it = "Tinozza di Pietra",
			pt = "Tanque de Pedra",
			ru = "Каменный чан",
			ko = "[Stone Vat]",
			cn = "石缸",
			tw = "石缸",
		},
	},
	[587443] = {
		readable = "Ripe Grapes",
		model = 996188,
		text = {
			en = "Ripe Grapes",
			es = "Uvas maduras",
			mx = "Uvas maduras",
			de = "Reife Trauben",
			fr = "Raisins mûrs",
			it = "Grappoli Maturi",
			pt = "Uvas Maduras",
			ru = "Спелый виноград",
			ko = "[Ripe Grapes]",
			cn = "成熟的葡萄",
			tw = "成熟的葡萄",
		},
	},
	[626983] = {
		readable = "Ripe Grapes",
		model = 996188,
		text = {
			en = "Ripe Grapes",
			es = "Uvas maduras",
			mx = "Uvas maduras",
			de = "Reife Trauben",
			fr = "Raisins mûrs",
			it = "Grappoli Maturi",
			pt = "Uvas Maduras",
			ru = "Спелый виноград",
			ko = "[Ripe Grapes]",
			cn = "成熟的葡萄",
			tw = "成熟的葡萄",
		},
	},
	[626987] = {
		readable = "Ripe Grapes",
		model = 996188,
		text = {
			en = "Ripe Grapes",
			es = "Uvas maduras",
			mx = "Uvas maduras",
			de = "Reife Trauben",
			fr = "Raisins mûrs",
			it = "Grappoli Maturi",
			pt = "Uvas Maduras",
			ru = "Спелый виноград",
			ko = "[Ripe Grapes]",
			cn = "成熟的葡萄",
			tw = "成熟的葡萄",
		},
	},
	[587912] = {
		readable = "Giant Grab Bag",
		model = 4213278,
		text = {
			en = "Giant Grab Bag",
			es = "[Giant Grab Bag]",
			mx = "[Giant Grab Bag]",
			de = "Riesenwundertüte",
			fr = "Sac à malice géant",
			it = "[Giant Grab Bag]",
			pt = "[Giant Grab Bag]",
			ru = "[Giant Grab Bag]",
			ko = "[Giant Grab Bag]",
			cn = "[Giant Grab Bag]",
			tw = "[Giant Grab Bag]",
		},
	},
	[589095] = {
		readable = "Scavenger's Hoard",
		model = 4566885,
		text = {
			en = "Scavenger's Hoard",
			es = "[Scavenger's Hoard]",
			mx = "[Scavenger's Hoard]",
			de = "[Scavenger's Hoard]",
			fr = "[Scavenger's Hoard]",
			it = "[Scavenger's Hoard]",
			pt = "[Scavenger's Hoard]",
			ru = "[Scavenger's Hoard]",
			ko = "[Scavenger's Hoard]",
		},
	},
})
do ObjectDB[objectID] = objectData; end
