local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[613269] = {
		readable = "Battered Safebox Key",
		model = 970204,
		text = {
			en = "Battered Safebox Key",
			es = "Llave de caja fuerte maltrecha",
			mx = "[Battered Safebox Key]",
			de = "Lädierter Truhenschlüssel",
			fr = "Clé de coffre endommagée",
			it = "Chiave della Cassetta di Sicurezza Rovinata",
			pt = "[Battered Safebox Key]",
			ru = "[Battered Safebox Key]",
			ko = "[Battered Safebox Key]",
			cn = "破烂的保险箱钥匙",
			tw = "殘破的保險箱鑰匙",
		},
	},
	[613271] = {
		readable = "Worn Safebox Key",
		model = 970204,
		text = {
			en = "Worn Safebox Key",
			es = "Llave de caja fuerte desgastada",
			mx = "[Worn Safebox Key]",
			de = "Abgenutzter Truhenschlüssel",
			fr = "Clé de coffre usée",
			it = "Chiave della Cassetta di Sicurezza Consumata",
			pt = "[Worn Safebox Key]",
			ru = "[Worn Safebox Key]",
			ko = "[Worn Safebox Key]",
			cn = "磨损的保险箱钥匙",
			tw = "磨損的保險箱鑰匙",
		},
	},
	[613272] = {
		readable = "Tarnished Safebox Key",
		model = 970204,
		text = {
			en = "Tarnished Safebox Key",
			es = "Llave de caja fuerte deslustrada",
			mx = "[Tarnished Safebox Key]",
			de = "Befleckter Truhenschlüssel",
			fr = "Clé de coffre ternie",
			it = "Chiave della Cassetta di Sicurezza Ossidata",
			pt = "[Tarnished Safebox Key]",
			ru = "[Tarnished Safebox Key]",
			ko = "[Tarnished Safebox Key]",
			cn = "褪色的保险箱钥匙",
			tw = "黯淡的保險箱鑰匙",
		},
	},
	[613317] = {
		readable = "Half-Digested Viscera",
		model = 337611,
		text = {
			en = "Half-Digested Viscera",
			es = "[Half-Digested Viscera]",
			mx = "[Half-Digested Viscera]",
			de = "[Half-Digested Viscera]",
			fr = "[Half-Digested Viscera]",
			it = "[Half-Digested Viscera]",
			pt = "[Half-Digested Viscera]",
			ru = "[Half-Digested Viscera]",
			ko = "[Half-Digested Viscera]",
			cn = "[Half-Digested Viscera]",
			tw = "[Half-Digested Viscera]",
		},
	},
	[613327] = {
		readable = "Faindel's Quiver",
		model = 6700995,
		text = {
			en = "Faindel's Quiver",
			es = "[Faindel's Quiver]",
			mx = "[Faindel's Quiver]",
			de = "[Faindel's Quiver]",
			fr = "[Faindel's Quiver]",
			it = "[Faindel's Quiver]",
			pt = "[Faindel's Quiver]",
			ru = "[Faindel's Quiver]",
			ko = "[Faindel's Quiver]",
			cn = "[Faindel's Quiver]",
			tw = "[Faindel's Quiver]",
		},
	},
	[613358] = {
		readable = "Exaliburn",
		model = 6980930,
		text = {
			en = "Exaliburn",
			es = "[Exaliburn]",
			mx = "[Exaliburn]",
			de = "[Exaliburn]",
			fr = "[Exaliburn]",
			it = "[Exaliburn]",
			pt = "[Exaliburn]",
			ru = "[Exaliburn]",
			ko = "[Exaliburn]",
			cn = "[Exaliburn]",
			tw = "[Exaliburn]",
		},
	},
	[613392] = {
		readable = "Impenetrably Sealed Gourd",
		model = 6326901,
		text = {
			en = "Impenetrably Sealed Gourd",
			es = "[Impenetrably Sealed Gourd]",
			mx = "[Impenetrably Sealed Gourd]",
			de = "Undurchdringlich versiegelter Kürbis",
			fr = "[Impenetrably Sealed Gourd]",
			it = "[Impenetrably Sealed Gourd]",
			pt = "[Impenetrably Sealed Gourd]",
			ru = "[Impenetrably Sealed Gourd]",
			ko = "[Impenetrably Sealed Gourd]",
			cn = "[Impenetrably Sealed Gourd]",
			tw = "[Impenetrably Sealed Gourd]",
		},
	},
	[613701] = {
		readable = "Honored Warrior's Urn",
		model = 6870560,
		text = {
			en = "Honored Warrior's Urn",
			es = "[Honored Warrior's Urn]",
			mx = "Urna de guerrero honrado",
			de = "[Honored Warrior's Urn]",
			fr = "Urne de combat glorieux",
			it = "[Honored Warrior's Urn]",
			pt = "[Honored Warrior's Urn]",
			ru = "[Honored Warrior's Urn]",
			ko = "[Honored Warrior's Urn]",
			cn = "[Honored Warrior's Urn]",
			tw = "[Honored Warrior's Urn]",
		},
	},
	[613727] = {
		readable = "Honored Warrior's Cache",
		model = 6195750,
		text = {
			en = "Honored Warrior's Cache",
			es = "[Honored Warrior's Cache]",
			mx = "Alijo de guerrero honrado",
			de = "Schatz des wohlwollenden Kriegers",
			fr = "Cache de combat glorieux",
			it = "Cassa del Guerriero Onorato",
			pt = "Baú do Guerreiro Honrado",
			ru = "Сундук почетного воина",
			ko = "[Honored Warrior's Cache]",
			cn = "[Honored Warrior's Cache]",
			tw = "[Honored Warrior's Cache]",
		},
	},
	[613729] = {
		readable = "Sunstrider Vessel",
		model = 4324806,
		text = {
			en = "Sunstrider Vessel",
			es = "Recipiente de Caminante del Sol",
			mx = "Receptáculo de Caminante del Sol",
			de = "Gefäß der Sonnenwanderer",
			fr = "Réceptacle de Haut-Soleil",
			it = "Ricettacolo dei Solealto",
			pt = "Receptáculo Andassol",
			ru = "Сосуд Солнечного Скитальца",
			ko = "[Sunstrider Vessel]",
			cn = "逐日者容器",
			tw = "[Sunstrider Vessel]",
		},
	},
	[613757] = {
		readable = "Honored Warrior's Urn",
		model = 6870560,
		text = {
			en = "Honored Warrior's Urn",
		},
	},
})
do ObjectDB[objectID] = objectData; end
