local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[525976] = {
		readable = "Peculiar Lotus",
		model = 577018,
		text = {
			en = "Peculiar Lotus",
			es = "[Peculiar Lotus]",
			mx = "[Peculiar Lotus]",
			de = "[Peculiar Lotus]",
			fr = "[Peculiar Lotus]",
			it = "[Peculiar Lotus]",
			pt = "[Peculiar Lotus]",
			ru = "[Peculiar Lotus]",
			ko = "[Peculiar Lotus]",
			cn = "[Peculiar Lotus]",
			tw = "[Peculiar Lotus]",
		},
	},
	[525977] = {
		readable = "Planting Shovel",
		model = 929413,
		text = {
			en = "Planting Shovel",
			es = "[Planting Shovel]",
			mx = "[Planting Shovel]",
			de = "Pflanzschaufel",
			fr = "[Planting Shovel]",
			it = "[Planting Shovel]",
			pt = "[Planting Shovel]",
			ru = "[Planting Shovel]",
			ko = "[Planting Shovel]",
			cn = "[Planting Shovel]",
			tw = "[Planting Shovel]",
		},
	},
	[527670] = {
		readable = "Lightwood Pile",
		model = 6690013,
		text = {
			en = "Lightwood Pile",
			es = "[Lightwood Pile]",
			mx = "[Lightwood Pile]",
			de = "[Lightwood Pile]",
			fr = "[Lightwood Pile]",
			it = "[Lightwood Pile]",
			pt = "[Lightwood Pile]",
			ru = "[Lightwood Pile]",
			ko = "[Lightwood Pile]",
			cn = "[Lightwood Pile]",
			tw = "[Lightwood Pile]",
		},
	},
	[531204] = {
		readable = "Completed Javelin",
		model = 4631422,
		text = {
			en = "Completed Javelin",
			es = "[Completed Javelin]",
			mx = "[Completed Javelin]",
			de = "[Completed Javelin]",
			fr = "[Completed Javelin]",
			it = "[Completed Javelin]",
			pt = "[Completed Javelin]",
			ru = "[Completed Javelin]",
			ko = "[Completed Javelin]",
			cn = "[Completed Javelin]",
			tw = "[Completed Javelin]",
		},
	},
	[531575] = {
		readable = "Glowshroom",
		model = 973608,
		text = {
			en = "Glowshroom",
			es = "[Glowshroom]",
			mx = "[Glowshroom]",
			de = "[Glowshroom]",
			fr = "[Glowshroom]",
			it = "[Glowshroom]",
			pt = "[Glowshroom]",
			ru = "[Glowshroom]",
			ko = "[Glowshroom]",
			cn = "[Glowshroom]",
			tw = "[Glowshroom]",
		},
	},
	[539042] = {
		readable = "Ruz'avalt's Prized Tackle",
		model = 6075567,
		text = {
			en = "Ruz'avalt's Prized Tackle",
			es = "[Ruz'avalt's Prized Tackle]",
			mx = "Derribo preciado de Ruz'avalt",
			de = "Ruz'avalts wertvoller Besitz",
			fr = "Précieux appâts de Ruz’avalt",
			it = "Equipaggiamento da Pesca Pregevole di Ruz'avalt",
			pt = "Equipamento de Pesca Precioso de Ruz'avalt",
			ru = "[Ruz'avalt's Prized Tackle]",
			ko = "[Ruz'avalt's Prized Tackle]",
			cn = "[Ruz'avalt's Prized Tackle]",
			tw = "[Ruz'avalt's Prized Tackle]",
		},
	},
	[539046] = {
		readable = "Honored Warrior's Cache",
		model = 6195750,
		text = {
			en = "Honored Warrior's Cache",
			es = "[Honored Warrior's Cache]",
			mx = "[Honored Warrior's Cache]",
			de = "[Honored Warrior's Cache]",
			fr = "[Honored Warrior's Cache]",
			it = "[Honored Warrior's Cache]",
			pt = "[Honored Warrior's Cache]",
			ru = "[Honored Warrior's Cache]",
			ko = "[Honored Warrior's Cache]",
			cn = "[Honored Warrior's Cache]",
			tw = "[Honored Warrior's Cache]",
		},
	},
	[539049] = {
		readable = "Bait and Tackle",
		model = 3857150,
		text = {
			en = "Bait and Tackle",
			es = "Cebo y aparejos",
			mx = "Artículos de pesca",
			de = "Köder und Angelzubehör",
			fr = "Appât appâteur",
			it = "Esca e Attrezzatura",
			pt = "[Bait and Tackle]",
			ru = "Наживка и снасти",
			ko = "[Bait and Tackle]",
			cn = "[Bait and Tackle]",
			tw = "[Bait and Tackle]",
		},
	},
	[539050] = {
		readable = "Burrow Bounty",
		model = 1859057,
		text = {
			en = "Burrow Bounty",
			es = "[Burrow Bounty]",
			mx = "Recompensa de madriguera",
			de = "Vergrabene Beute",
			fr = "Trésor enfoui",
			it = "[Burrow Bounty]",
			pt = "Recompensa de Escavação",
			ru = "Зарытые запасы",
			ko = "[Burrow Bounty]",
			cn = "[Burrow Bounty]",
			tw = "[Burrow Bounty]",
		},
	},
	[539052] = {
		readable = "Secret Formula",
		model = 1310400,
		text = {
			en = "Secret Formula",
			es = "[Secret Formula]",
			mx = "Fórmula secreta",
			de = "Geheime Formel",
			fr = "Formule secrète",
			it = "Formula Segreta",
			pt = "Fórmula Secreta",
			ru = "Секретный рецепт",
			ko = "[Secret Formula]",
			cn = "[Secret Formula]",
			tw = "[Secret Formula]",
		},
	},
	[539053] = {
		readable = "Abandoned Nest",
		model = 4532354,
		text = {
			en = "Abandoned Nest",
			es = "[Abandoned Nest]",
			mx = "Nido abandonado",
			de = "Verlassenes Nest",
			fr = "Nid abandonné",
			it = "Nido Abbandonato",
			pt = "Ninho Abandonado",
			ru = "Заброшенное гнездо",
			ko = "[Abandoned Nest]",
			cn = "[Abandoned Nest]",
			tw = "[Abandoned Nest]",
		},
	},
	[542839] = {
		readable = "K'areshi Keepsake",
		model = 6320659,
		text = {
			en = "K'areshi Keepsake",
			es = "[K'areshi Keepsake]",
			mx = "[K'areshi Keepsake]",
			de = "[K'areshi Keepsake]",
			fr = "[K'areshi Keepsake]",
			it = "[K'areshi Keepsake]",
			pt = "[K'areshi Keepsake]",
			ru = "[K'areshi Keepsake]",
		},
	},
})
do ObjectDB[objectID] = objectData; end
