local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[525892] = {
		readable = "Sin'dorei Tanning Oil",
		model = 4198215,
		text = {
			en = "Sin'dorei Tanning Oil",
			es = "Aceite para curtir sin'dorei",
			mx = "Aceite para curtido sin'dorei",
			de = "Gerböl der Sin'dorei",
			fr = "Huile de tannage sin’dorei",
			it = "Olio per Tannatura dei Sin'dorei",
			pt = "[Sin'dorei Tanning Oil]",
			ru = "Син'дорайское дубильное масло",
			ko = "[Sin'dorei Tanning Oil]",
			cn = "[Sin'dorei Tanning Oil]",
			tw = "[Sin'dorei Tanning Oil]",
		},
	},
	[570235] = {
		readable = "Worm Bait",
		model = 4320283,
		text = {
			en = "Worm Bait",
			es = "[Worm Bait]",
			mx = "[Worm Bait]",
			de = "[Worm Bait]",
			fr = "[Worm Bait]",
			it = "[Worm Bait]",
			pt = "[Worm Bait]",
			ru = "[Worm Bait]",
			ko = "[Worm Bait]",
			cn = "[Worm Bait]",
			tw = "[Worm Bait]",
		},
	},
	[571169] = {
		readable = "Glowing Moth",
		model = 124932,
		text = {
			en = "Glowing Moth",
			es = "Polilla resplandeciente",
			mx = "Polilla brillante",
			de = "Leuchtende Motte",
			fr = "Phalène luminescent",
			it = "Falena Luminosa",
			pt = "Mariposa Brilhante",
			ru = "Светящийся мотылек",
			ko = "빛나는 나방",
			cn = "发光的飞蛾",
			tw = "發光蛾",
		},
	},
	[571264] = {
		readable = "Glowing Moth",
		model = 124932,
		text = {
			en = "Glowing Moth",
			es = "Polilla resplandeciente",
			mx = "Polilla brillante",
			de = "Leuchtende Motte",
			fr = "Phalène luminescent",
			it = "Falena Luminosa",
			pt = "Mariposa Brilhante",
			ru = "Светящийся мотылек",
			ko = "빛나는 나방",
			cn = "发光的飞蛾",
			tw = "發光蛾",
		},
	},
	[571280] = {
		readable = "Glowing Moth",
		model = 124932,
		text = {
			en = "Glowing Moth",
			es = "Polilla resplandeciente",
			mx = "Polilla brillante",
			de = "Leuchtende Motte",
			fr = "Phalène luminescent",
			it = "Falena Luminosa",
			pt = "Mariposa Brilhante",
			ru = "Светящийся мотылек",
			ko = "빛나는 나방",
			cn = "发光的飞蛾",
			tw = "發光蛾",
		},
	},
	[571281] = {
		readable = "Glowing Moth",
		model = 124932,
		text = {
			en = "Glowing Moth",
			es = "Polilla resplandeciente",
			mx = "Polilla brillante",
			de = "Leuchtende Motte",
			fr = "Phalène luminescent",
			it = "Falena Luminosa",
			pt = "Mariposa Brilhante",
			ru = "Светящийся мотылек",
			ko = "빛나는 나방",
			cn = "发光的飞蛾",
			tw = "發光蛾",
		},
	},
	[573714] = {
		readable = "Ani's Trinket Bag",
		model = 6212425,
		text = {
			en = "Ani's Trinket Bag",
			es = "[Ani's Trinket Bag]",
			mx = "Bolsa de abalorios de Ani",
			de = "Anis Schmuckstücktasche",
			fr = "Sac de babioles d’Ani",
			it = "Borsa dei Monili di Ani",
			pt = "Bolsa de Berloques da Ani",
			ru = "Сумка Ани с безделушками",
			ko = "[Ani's Trinket Bag]",
			cn = "[Ani's Trinket Bag]",
			tw = "[Ani's Trinket Bag]",
		},
	},
})
do ObjectDB[objectID] = objectData; end
