local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[621762] = {
		readable = "Anar'alah Belore",
		model = 7241266,
		text = {
			en = "Anar'alah Belore",
			es = "Anar'alah belore",
			mx = "Anar'alah Belore",
			de = "Anar'alah belore",
			fr = "Anar’alah belore",
			it = "Anar'alah Belore",
			pt = "Anar'alah Belore",
			ru = "Анар'ала белоре",
			ko = "[Anar'alah Belore]",
			cn = "[Anar'alah Belore]",
			tw = "以太陽之名",
		},
	},
	[627841] = {
		readable = "Imperial Mug",
		model = 5373467,
		text = {
			en = "Imperial Mug",
			es = "Jarra imperial",
			mx = "Jarra imperial",
			de = "Kaiserlicher Krug",
			fr = "Chope impériale",
			it = "Tazza Imperiale",
			pt = "Caneca Imperial",
			ru = "Имперская кружка",
			ko = "제국 잔",
			cn = "皇家酒杯",
			tw = "帝國杯子",
		},
	},
	[628949] = {
		readable = "Shadowmoon Lumber",
		model = 6922313,
		text = {
			en = "Shadowmoon Lumber",
			es = "Madera de Sombraluna",
			mx = "[Shadowmoon Lumber]",
			de = "Schattenmondholz",
			fr = "Bois d’Ombrelune",
			it = "Legname di Torvaluna",
			pt = "Lenha da Lua Negra",
			ru = "Древесина Призрачной Луны",
			ko = "[Shadowmoon Lumber]",
			cn = "[Shadowmoon Lumber]",
			tw = "影月木材",
		},
	},
	[628950] = {
		readable = "Shadowmoon Lumber",
		model = 6922313,
		text = {
			en = "Shadowmoon Lumber",
			es = "Madera de Sombraluna",
			mx = "[Shadowmoon Lumber]",
			de = "Schattenmondholz",
			fr = "Bois d’Ombrelune",
			it = "Legname di Torvaluna",
			pt = "Lenha da Lua Negra",
			ru = "Древесина Призрачной Луны",
			ko = "어둠달 목재",
			cn = "[Shadowmoon Lumber]",
			tw = "影月木材",
		},
	},
	[628951] = {
		readable = "Shadowmoon Lumber",
		model = 6922313,
		text = {
			en = "Shadowmoon Lumber",
			es = "Madera de Sombraluna",
			mx = "[Shadowmoon Lumber]",
			de = "[Shadowmoon Lumber]",
			fr = "[Shadowmoon Lumber]",
			it = "[Shadowmoon Lumber]",
			pt = "Lenha da Lua Negra",
			ru = "Древесина Призрачной Луны",
			ko = "[Shadowmoon Lumber]",
			cn = "影月木料",
			tw = "影月木材",
		},
	},
	[628952] = {
		readable = "Shadowmoon Lumber",
		model = 6922313,
		text = {
			en = "Shadowmoon Lumber",
			es = "Madera de Sombraluna",
			mx = "[Shadowmoon Lumber]",
			de = "Schattenmondholz",
			fr = "Bois d’Ombrelune",
			it = "Legname di Torvaluna",
			pt = "Lenha da Lua Negra",
			ru = "Древесина Призрачной Луны",
			ko = "어둠달 목재",
			cn = "[Shadowmoon Lumber]",
			tw = "影月木材",
		},
	},
	[628953] = {
		readable = "Shadowmoon Lumber",
		model = 6922313,
		text = {
			en = "Shadowmoon Lumber",
			es = "Madera de Sombraluna",
			mx = "Madera sombraluna",
			de = "Schattenmondholz",
			fr = "Bois d’Ombrelune",
			it = "Legname di Torvaluna",
			pt = "Lenha da Lua Negra",
			ru = "Древесина Призрачной Луны",
			ko = "[Shadowmoon Lumber]",
			cn = "影月木料",
			tw = "[Shadowmoon Lumber]",
		},
	},
	[628954] = {
		readable = "Shadowmoon Lumber",
		model = 6922313,
		text = {
			en = "Shadowmoon Lumber",
			es = "Madera de Sombraluna",
			mx = "Madera sombraluna",
			de = "Schattenmondholz",
			fr = "Bois d’Ombrelune",
			it = "Legname di Torvaluna",
			pt = "Lenha da Lua Negra",
			ru = "Древесина Призрачной Луны",
			ko = "어둠달 목재",
			cn = "[Shadowmoon Lumber]",
			tw = "影月木材",
		},
	},
	[628955] = {
		readable = "Shadowmoon Lumber",
		model = 6922313,
		text = {
			en = "Shadowmoon Lumber",
			es = "Madera de Sombraluna",
			mx = "Madera sombraluna",
			de = "Schattenmondholz",
			fr = "Bois d’Ombrelune",
			it = "Legname di Torvaluna",
			pt = "Lenha da Lua Negra",
			ru = "Древесина Призрачной Луны",
			ko = "어둠달 목재",
			cn = "[Shadowmoon Lumber]",
			tw = "[Shadowmoon Lumber]",
		},
	},
	[628956] = {
		readable = "Shadowmoon Lumber",
		model = 6922313,
		text = {
			en = "Shadowmoon Lumber",
		},
	},
})
do ObjectDB[objectID] = objectData; end
