local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[526979] = {
		readable = "Challenger's Cache",
		model = 1314905,
		text = {
			en = "Challenger's Cache",
			es = "Alijo de contendiente",
			mx = "Alijo del Contendiente",
			de = "Schatz des Herausforderers",
			fr = "Cache de prétendant ou de prétendante",
			it = "Cassa dello Sfidante",
			pt = "Baú do Desafiante",
			ru = "Тайник претендента",
			ko = "도전자의 보관함",
			cn = "挑战者的箱子",
			tw = "挑戰者的儲物箱",
		},
	},
	[526980] = {
		readable = "Challenger's Cache",
		model = 1314905,
		text = {
			en = "Challenger's Cache",
			es = "Alijo de contendiente",
			mx = "Alijo del Contendiente",
			de = "Schatz des Herausforderers",
			fr = "Cache de prétendant ou de prétendante",
			it = "Cassa dello Sfidante",
			pt = "Baú do Desafiante",
			ru = "Тайник претендента",
			ko = "도전자의 보관함",
			cn = "挑战者的箱子",
			tw = "挑戰者的儲物箱",
		},
	},
	[528074] = {
		readable = "Missing Voidband",
		model = 3718234,
		text = {
			en = "Missing Voidband",
			es = "Aro del Vacío desaparecido",
			mx = "Banda del Vacío perdida",
			de = "Vermisstes Leerenband",
			fr = "Bandeau du Vide manquant",
			it = "Vera del Vuoto Perduta",
			pt = "Aro Caótico Perdido",
			ru = "Потерянное кольцо Бездны",
			ko = "[Missing Voidband]",
			cn = "遗失的虚空之戒",
			tw = "消失的虛無指環",
		},
	},
	[528080] = {
		readable = "Missing Token Box",
		model = 3855954,
		text = {
			en = "Missing Token Box",
			es = "Caja de fichas desaparecida",
			mx = "Caja de fichas perdida",
			de = "Vermisste Abzeichenkiste",
			fr = "Boîte à jetons manquante",
			it = "Scatola di Gettoni Perduta",
			pt = "Caixa de Fichas Perdida",
			ru = "Потерянная коробочка жетонов",
			ko = "[Missing Token Box]",
			cn = "遗失的代币盒",
			tw = "消失的代幣箱",
		},
	},
	[528082] = {
		readable = "Missing Luggage",
		model = 3846063,
		text = {
			en = "Missing Luggage",
			es = "Equipaje desaparecido",
			mx = "Equipaje perdido",
			de = "Vermisstes Gepäck",
			fr = "Bagage manquant",
			it = "Bagaglio Perduto",
			pt = "Bagagem Perdida",
			ru = "Потерянный багаж",
			ko = "[Missing Luggage]",
			cn = "遗失的行李",
			tw = "消失的行李",
		},
	},
	[528084] = {
		readable = "Missing Scrolls",
		model = 3836266,
		text = {
			en = "Missing Scrolls",
			es = "Pergaminos desaparecidos",
			mx = "Pergaminos perdidos",
			de = "Vermisste Schriftrollen",
			fr = "Parchemins manquants",
			it = "Pergamene Perdute",
			pt = "Pergaminhos Perdidos",
			ru = "Потерянные свитки",
			ko = "[Missing Scrolls]",
			cn = "遗失的卷轴",
			tw = "消失的卷軸",
		},
	},
	[528283] = {
		readable = "Vesto's Stolen Goods",
		model = 3855963,
		text = {
			en = "Vesto's Stolen Goods",
			es = "Bienes robados de Vesto",
			mx = "Bienes robados de Vesto",
			de = "Om’Stos gestohlene Waren",
			fr = "Marchandises volées de Vesto",
			it = "Merci Rubate di Vesto",
			pt = "Mercadorias Roubadas de Vesto",
			ru = "Украденные вещи Весто",
			ko = "[Vesto's Stolen Goods]",
			cn = "维斯托的失窃货物",
			tw = "維斯多被偷的貨物's Stolen Goods",
		},
	},
	[528303] = {
		readable = "Arcane Recorder",
		model = 4496829,
		text = {
			en = "Arcane Recorder",
			es = "Registrador Arcano",
			mx = "Grabador arcano",
			de = "Arkaner Aufzeichner",
			fr = "Enregistreur arcanique",
			it = "Registratore Arcano",
			pt = "Registrador Arcano",
			ru = "Чародейский регистратор",
			ko = "비전 기록기",
			cn = "奥术记录器",
			tw = "秘法錄音器",
		},
	},
	[528308] = {
		readable = "Arcane Recorder",
		model = 4496829,
		text = {
			en = "Arcane Recorder",
			es = "Registrador Arcano",
			mx = "Grabador arcano",
			de = "Arkaner Aufzeichner",
			fr = "Enregistreur arcanique",
			it = "Registratore Arcano",
			pt = "Registrador Arcano",
			ru = "Чародейский регистратор",
			ko = "비전 기록기",
			cn = "奥术记录器",
			tw = "秘法錄音器",
		},
	},
	[528309] = {
		readable = "Arcane Recorder",
		model = 4496829,
		text = {
			en = "Arcane Recorder",
			es = "Registrador Arcano",
			mx = "Grabador arcano",
			de = "Arkaner Aufzeichner",
			fr = "Enregistreur arcanique",
			it = "Registratore Arcano",
			pt = "Registrador Arcano",
			ru = "Чародейский регистратор",
			ko = "비전 기록기",
			cn = "奥术记录器",
			tw = "秘法錄音器",
		},
	},
	[531388] = {
		readable = "Weapon Rack",
		model = 6252864,
		text = {
			en = "Weapon Rack",
			es = "Expositor de armas",
			mx = "Expositor de armas",
			de = "Waffenständer",
			fr = "Râtelier d’armes",
			it = "Rastrelliera delle Armi",
			pt = "Cavalete de Armas",
			ru = "Оружейная стойка",
			ko = "무기 선반",
		},
	},
})
do ObjectDB[objectID] = objectData; end
