local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[506640] = {
		readable = "Faded Journal Page",
		model = 3978479,
		text = {
			en = "Faded Journal Page",
			es = "Página de diario borrosa",
			mx = "Página de diario desgastada",
			de = "Verblasste Tagebuchseite",
			fr = "Page de journal estompée",
			it = "Pagina di Diario Sbiadita",
			pt = "Página de Diário Esmaecida",
			ru = "Выцветшая страница с записями",
			ko = "색 바랜 일지 책장",
			cn = "褪色的日志书页",
			tw = "褪色的日記書頁",
		},
	},
	[507026] = {
		readable = "Portal to K'aresh",
		model = 3540722,
		text = {
			en = "Portal to K'aresh",
			es = "Portal a K'aresh",
			mx = "Portal a K'aresh",
			de = "Portal nach K'aresh",
			fr = "Portail vers K’aresh",
			it = "Portale per K'aresh",
			pt = "Portal para K'aresh",
			ru = "Портал в К'ареш",
			ko = "크아레쉬로 통하는 차원문",
			cn = "[Portal to K'aresh]",
			tw = "凱瑞西傳送門",
		},
	},
	[507867] = {
		readable = "Soggy Journal Page",
		model = 3978479,
		text = {
			en = "Soggy Journal Page",
			es = "Página de diario empapada",
			mx = "Página de diario empapada",
			de = "Durchweichte Tagebuchseite",
			fr = "Page de journal détrempée",
			it = "Pagina di Diario Inzuppata",
			pt = "Página de Diário Encharcada",
			ru = "Отсыревшая страница из дневника",
			ko = "젖은 일지 한 쪽",
			cn = "湿透的日志书页",
			tw = "濕透的日記書頁",
		},
	},
	[507868] = {
		readable = "Stained Journal Page",
		model = 3978479,
		text = {
			en = "Stained Journal Page",
			es = "Página de diario manchada",
			mx = "Página de diario manchada",
			de = "Befleckte Tagebuchseite",
			fr = "Page de journal tachée",
			it = "Pagina di Diario Macchiata",
			pt = "Página de Diário Manchada",
			ru = "Грязная страница из дневника",
			ko = "얼룩진 일지 한 쪽",
			cn = "有污渍的日志书页",
			tw = "汙損的日誌書頁",
		},
	},
	[507869] = {
		readable = "Torn Journal Page",
		model = 3978479,
		text = {
			en = "Torn Journal Page",
			es = "Página de diario rota",
			mx = "Página de diario rota",
			de = "Zerfledderte Tagebuchseite",
			fr = "Page de journal déchirée",
			it = "Pagina di Diario Strappata",
			pt = "Página de Diário Rasgada",
			ru = "Вырванная страница из дневника",
			ko = "찢어진 일지 한 쪽",
			cn = "撕破的日志书页",
			tw = "殘破的日誌書頁",
		},
	},
	[507870] = {
		readable = "Weathered Journal Page",
		model = 3978479,
		text = {
			en = "Weathered Journal Page",
			es = "Página de diario deteriorada",
			mx = "Página de diario desgastada",
			de = "Verwitterte Tagebuchseite",
			fr = "Page de journal abîmée",
			it = "Pagina di Diario Logora",
			pt = "Página de Diário Desgastada",
			ru = "Ветхая страница из дневника",
			ko = "낡은 일지 한 쪽",
			cn = "风蚀的日志书页",
			tw = "老舊的日誌書頁",
		},
	},
	[507947] = {
		readable = "Sun-Blessed Ballista",
		model = 6005290,
		text = {
			en = "Sun-Blessed Ballista",
			es = "Balista bendita por el sol",
			mx = "Balista de bendición solar",
			de = "Sonnengesegnete Balliste",
			fr = "Baliste bénie par le soleil",
			it = "Balista Benedetta dal Sole",
			pt = "Balista Soalheira",
			ru = "Солнцезарная баллиста",
			ko = "태양축복 쇠뇌",
			cn = "日佑弩炮",
			tw = "日祝弩砲",
		},
	},
	[508366] = {
		readable = "Emergency Supplies",
		model = 5689832,
		text = {
			en = "Emergency Supplies",
			es = "Suministros de emergencia",
			mx = "Suministros de emergencia",
			de = "Notvorräte",
			fr = "Fournitures d’urgence",
			it = "Kit d'Emergenza",
			pt = "Equipamentos de Emergência",
			ru = "Неприкосновенный запас",
			ko = "긴급 보급품",
			cn = "应急物资",
			tw = "緊急補給",
		},
	},
	[509463] = {
		readable = "Stolen Coffer",
		model = 3450703,
		text = {
			en = "Stolen Coffer",
			es = "Arca robada",
			mx = "Cofre robado",
			de = "Gestohlener Kasten",
			fr = "Coffret dérobé",
			it = "Scrigno Rubato",
			pt = "Cofre Roubado",
			ru = "Украденная шкатулка",
			ko = "훔쳐낸 궤짝",
			cn = "失窃的宝匣",
			tw = "被偷的寶庫",
		},
	},
	[509464] = {
		readable = "Secure Crate",
		model = 3450717,
		text = {
			en = "Secure Crate",
			es = "Cajón seguro",
			mx = "Cajón seguro",
			de = "Gesicherte Kiste",
			fr = "Caisse sûre",
			it = "Cassa Sicura",
			pt = "Caixote Fechado",
			ru = "Надежный ящик",
			ko = "단단히 잠긴 상자",
			cn = "保险箱",
			tw = "保險木箱",
		},
	},
	[510772] = {
		readable = "Weighty Variable Rod",
		model = 3997999,
		text = {
			en = "Weighty Variable Rod",
			es = "Vara variable pesada",
			mx = "Vara variable pesada",
			de = "Schwerer Stab der Variablen",
			fr = "Bâtonnet variable alourdi",
			it = "Verga Variabile Pesante",
			pt = "Bastão de Variáveis Pesadas",
			ru = "Увесистый переменный жезл",
			ko = "묵직한 변수 막대",
			cn = "沉重的变量之杖",
			tw = "沉重的變數節杖",
		},
	},
	[516462] = {
		readable = "Odd Flower",
		model = 6080358,
		text = {
			en = "Odd Flower",
			es = "Flor extraña",
			mx = "Flor extraña",
			de = "Seltsame Blume",
		},
	},
})
do ObjectDB[objectID] = objectData; end
