local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[619665] = {
		readable = "Vista Point",
		model = 4496829,
		text = {
			en = "Vista Point",
			es = "[Vista Point]",
			mx = "[Vista Point]",
			de = "[Vista Point]",
			fr = "[Vista Point]",
			it = "[Vista Point]",
			pt = "[Vista Point]",
			ru = "[Vista Point]",
			ko = "[Vista Point]",
			cn = "[Vista Point]",
			tw = "[Vista Point]",
		},
	},
	[620206] = {
		readable = "Rookery Cache Key",
		model = 970208,
		text = {
			en = "Rookery Cache Key",
			es = "Llave de alijo del Grajero",
			mx = "[Rookery Cache Key]",
			de = "Truhenschlüssel des Horsts",
			fr = "Clé de cache de la colonie",
			it = "Chiave dello Scrigno della Corveria",
			pt = "[Rookery Cache Key]",
			ru = "Ключ от тайника Гнездовья",
			ko = "[Rookery Cache Key]",
			cn = "[Rookery Cache Key]",
			tw = "[Rookery Cache Key]",
		},
	},
	[620314] = {
		readable = "Tablet of Akil'zon",
		model = 6212409,
		text = {
			en = "Tablet of Akil'zon",
			es = "[Tablet of Akil'zon]",
			mx = "Tablilla de Akil'zon",
			de = "Schrifttafel von Akil'zon",
			fr = "Tablette d’Akil’zon",
			it = "Tavoletta di Akil'zon",
			pt = "[Tablet of Akil'zon]",
			ru = "Скрижаль Акил'зон",
			ko = "[Tablet of Akil'zon]",
			cn = "[Tablet of Akil'zon]",
			tw = "[Tablet of Akil'zon]",
		},
	},
	[620318] = {
		readable = "Ruia's Storage",
		model = 6730919,
		text = {
			en = "Ruia's Storage",
			es = "[Ruia's Storage]",
			mx = "[Ruia's Storage]",
			de = "Ruias Lager",
			fr = "Réserve de Ruia",
			it = "[Ruia's Storage]",
			pt = "[Ruia's Storage]",
			ru = "[Ruia's Storage]",
			ko = "[Ruia's Storage]",
			cn = "[Ruia's Storage]",
			tw = "[Ruia's Storage]",
		},
	},
	[620321] = {
		readable = "Tablet of Halazzi",
		model = 6212409,
		text = {
			en = "Tablet of Halazzi",
			es = "[Tablet of Halazzi]",
			mx = "Tablilla de Halazzi",
			de = "Schrifttafel von Halazzi",
			fr = "Tablette d’Halazzi",
			it = "Tavoletta di Halazzi",
			pt = "Tabuleta de Halazzi",
			ru = "Скрижаль Халаззи",
			ko = "[Tablet of Halazzi]",
			cn = "[Tablet of Halazzi]",
			tw = "[Tablet of Halazzi]",
		},
	},
	[620323] = {
		readable = "Tablet of Jan'alai",
		model = 6212409,
		text = {
			en = "Tablet of Jan'alai",
			es = "[Tablet of Jan'alai]",
			mx = "Tablilla de Jan'alai",
			de = "Schrifttafel von Jan'alai",
			fr = "Tablette de Jan’alai",
			it = "Tavoletta di Jan'alai",
			pt = "Tabuleta de Jan'alai",
			ru = "Скрижаль Джан'алай",
			ko = "[Tablet of Jan'alai]",
			cn = "[Tablet of Jan'alai]",
			tw = "[Tablet of Jan'alai]",
		},
	},
	[620324] = {
		readable = "Tablet of Nalorakk",
		model = 6212409,
		text = {
			en = "Tablet of Nalorakk",
			es = "Tablilla de Nalorakk",
			mx = "Tablilla de Nalorakk",
			de = "Schrifttafel von Nalorakk",
			fr = "Tablette de Nalorakk",
			it = "Tavoletta di Nalorakk",
			pt = "[Tablet of Nalorakk]",
			ru = "Скрижаль Налоракка",
			ko = "[Tablet of Nalorakk]",
			cn = "[Tablet of Nalorakk]",
			tw = "[Tablet of Nalorakk]",
		},
	},
	[620325] = {
		readable = "Tablet of the Witherbark",
		model = 6212409,
		text = {
			en = "Tablet of the Witherbark",
			es = "Tablet of the Witherbark",
			mx = "Tablet of the Witherbark",
			de = "Tablet of the Witherbark",
			fr = "Tablet of the Witherbark",
			it = "Tablet of the Witherbark",
			pt = "Tablet of the Witherbark",
			ru = "Tablet of the Witherbark",
			ko = "Tablet of the Witherbark",
			cn = "Tablet of the Witherbark",
			tw = "Tablet of the Witherbark",
		},
	},
	[620326] = {
		readable = "Tablet of Kulzi",
		model = 6212409,
		text = {
			en = "Tablet of Kulzi",
			es = "[Tablet of Kulzi]",
			mx = "Tablilla de Kulzi",
			de = "Schrifttafel von Kulzi",
			fr = "Tablette de Kulzi",
			it = "Tavoletta di Kulzi",
			pt = "Tabuleta de Kurzi",
			ru = "[Tablet of Kulzi]",
			ko = "[Tablet of Kulzi]",
			cn = "[Tablet of Kulzi]",
			tw = "[Tablet of Kulzi]",
		},
	},
})
do ObjectDB[objectID] = objectData; end
