local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[527398] = {
		readable = "Suspicious Document",
		model = 5502807,
		text = {
			en = "Suspicious Document",
			de = "Verdächtiges Dokument",
			es = "Documento sospechoso",
			mx = "Documento sospechoso",
			fr = "Document suspect",
			it = "Documento Sospetto",
			pt = "Documento Suspeito",
			ru = "Подозрительный документ",
			ko = "수상한 화물",
			cn = "可疑的文件",
			tw = "可疑的文件",
		},
	},
	[527409] = {
		readable = "Suspicious Document",
		model = 5007027,
		text = {
			en = "Suspicious Document",
			de = "Verdächtiges Dokument",
			es = "Documento sospechoso",
			mx = "Documento sospechoso",
			fr = "Document suspect",
			it = "Documento Sospetto",
			pt = "Documento Suspeito",
			ru = "Подозрительный документ",
			ko = "수상한 화물",
			cn = "可疑的文件",
			tw = "可疑的文件",
		},
	},
	[527413] = {
		readable = "Suspicious Document",
		model = 5502807,
		text = {
			en = "Suspicious Document",
			de = "Verdächtiges Dokument",
			es = "Documento sospechoso",
			mx = "Documento sospechoso",
			fr = "Document suspect",
			it = "Documento Sospetto",
			pt = "Documento Suspeito",
			ru = "Подозрительный документ",
			ko = "수상한 화물",
			cn = "可疑的文件",
			tw = "可疑的文件",
		},
	},
	[527415] = {
		readable = "Suspicious Document",
		model = 5502807,
		text = {
			en = "Suspicious Document",
			de = "Verdächtiges Dokument",
			es = "Documento sospechoso",
			mx = "Documento sospechoso",
			fr = "Document suspect",
			it = "Documento Sospetto",
			pt = "Documento Suspeito",
			ru = "Подозрительный документ",
			ko = "수상한 화물",
			cn = "可疑的文件",
			tw = "可疑的文件",
		},
	},
	[527416] = {
		readable = "Suspicious Document",
		model = 5007027,
		text = {
			en = "Suspicious Document",
			de = "Verdächtiges Dokument",
			es = "Documento sospechoso",
			mx = "Documento sospechoso",
			fr = "Document suspect",
			it = "Documento Sospetto",
			pt = "Documento Suspeito",
			ru = "Подозрительный документ",
			ko = "수상한 화물",
			cn = "可疑的文件",
			tw = "可疑的文件",
		},
	},
})
do ObjectDB[objectID] = objectData; end
