local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[618273] = {
		readable = "Sturdy Chest",
		model = 5128194,
		text = {
			en = "Sturdy Chest",
			es = "[Sturdy Chest]",
			mx = "[Sturdy Chest]",
			de = "[Sturdy Chest]",
			fr = "[Sturdy Chest]",
			it = "[Sturdy Chest]",
			pt = "[Sturdy Chest]",
			ru = "[Sturdy Chest]",
			ko = "[Sturdy Chest]",
			cn = "[Sturdy Chest]",
			tw = "[Sturdy Chest]",
		},
	},
	[618274] = {
		readable = "Sturdy Chest",
		model = 5128194,
		text = {
			en = "Sturdy Chest",
			es = "[Sturdy Chest]",
			mx = "Cofre robusto",
			de = "Robuste Truhe",
			fr = "[Sturdy Chest]",
			it = "[Sturdy Chest]",
			pt = "[Sturdy Chest]",
			ru = "Прочный сундук",
			ko = "[Sturdy Chest]",
			cn = "[Sturdy Chest]",
			tw = "[Sturdy Chest]",
		},
	},
	[618275] = {
		readable = "Sturdy Chest",
		model = 5128194,
		text = {
			en = "Sturdy Chest",
			es = "Sturdy Chest",
			mx = "Sturdy Chest",
			de = "Sturdy Chest",
			fr = "Sturdy Chest",
			it = "Sturdy Chest",
			pt = "Sturdy Chest",
			ru = "Sturdy Chest",
			ko = "Sturdy Chest",
			cn = "Sturdy Chest",
			tw = "Sturdy Chest",
		},
	},
	[618276] = {
		readable = "Sturdy Chest",
		model = 5128194,
		text = {
			en = "Sturdy Chest",
			es = "[Sturdy Chest]",
			mx = "[Sturdy Chest]",
			de = "Robuste Truhe",
			fr = "Coffre solide",
			it = "[Sturdy Chest]",
			pt = "[Sturdy Chest]",
			ru = "[Sturdy Chest]",
			ko = "[Sturdy Chest]",
			cn = "[Sturdy Chest]",
			tw = "[Sturdy Chest]",
		},
	},
	[618277] = {
		readable = "Sturdy Chest",
		model = 5128194,
		text = {
			en = "Sturdy Chest",
			es = "[Sturdy Chest]",
			mx = "[Sturdy Chest]",
			de = "[Sturdy Chest]",
			fr = "[Sturdy Chest]",
			it = "[Sturdy Chest]",
			pt = "[Sturdy Chest]",
			ru = "[Sturdy Chest]",
			ko = "[Sturdy Chest]",
			cn = "[Sturdy Chest]",
			tw = "[Sturdy Chest]",
		},
	},
	[618278] = {
		readable = "Sturdy Chest",
		model = 5128194,
		text = {
			en = "Sturdy Chest",
			es = "Cofre robusto",
			mx = "[Sturdy Chest]",
			de = "Robuste Truhe",
			fr = "Coffre solide",
			it = "[Sturdy Chest]",
			pt = "[Sturdy Chest]",
			ru = "[Sturdy Chest]",
			ko = "[Sturdy Chest]",
			cn = "[Sturdy Chest]",
			tw = "[Sturdy Chest]",
		},
	},
	[618279] = {
		readable = "Sturdy Chest",
		model = 5128194,
		text = {
			en = "Sturdy Chest",
			es = "[Sturdy Chest]",
			mx = "[Sturdy Chest]",
			de = "[Sturdy Chest]",
			fr = "[Sturdy Chest]",
			it = "[Sturdy Chest]",
			pt = "[Sturdy Chest]",
			ru = "[Sturdy Chest]",
			ko = "[Sturdy Chest]",
			cn = "[Sturdy Chest]",
			tw = "[Sturdy Chest]",
		},
	},
	[618280] = {
		readable = "Sturdy Chest",
		model = 5128194,
		text = {
			en = "Sturdy Chest",
			es = "[Sturdy Chest]",
			mx = "[Sturdy Chest]",
			de = "[Sturdy Chest]",
			fr = "[Sturdy Chest]",
			it = "[Sturdy Chest]",
			pt = "[Sturdy Chest]",
			ru = "[Sturdy Chest]",
			ko = "[Sturdy Chest]",
			cn = "[Sturdy Chest]",
			tw = "[Sturdy Chest]",
		},
	},
	[618281] = {
		readable = "Sturdy Chest",
		model = 5128194,
		text = {
			en = "Sturdy Chest",
			es = "[Sturdy Chest]",
			mx = "[Sturdy Chest]",
			de = "[Sturdy Chest]",
			fr = "[Sturdy Chest]",
			it = "[Sturdy Chest]",
			pt = "[Sturdy Chest]",
			ru = "[Sturdy Chest]",
			ko = "[Sturdy Chest]",
			cn = "[Sturdy Chest]",
			tw = "[Sturdy Chest]",
		},
	},
	[618283] = {
		readable = "Sturdy Chest",
		model = 5128194,
		text = {
			en = "Sturdy Chest",
			es = "Sturdy Chest",
			mx = "Sturdy Chest",
		},
	},
})
do ObjectDB[objectID] = objectData; end
