local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[618273] = {
		readable = "Sturdy Chest",
		model = 5128194,
		text = {
			en = "Sturdy Chest",
			es = "[Sturdy Chest]",
			mx = "[Sturdy Chest]",
			de = "[Sturdy Chest]",
			fr = "[Sturdy Chest]",
			it = "[Sturdy Chest]",
			pt = "[Sturdy Chest]",
			ru = "[Sturdy Chest]",
			ko = "[Sturdy Chest]",
			cn = "[Sturdy Chest]",
			tw = "[Sturdy Chest]",
		},
	},
	[618274] = {
		readable = "<span style=\"color: #A335EE\">Sturdy Chest</span>",
		model = 5128194,
		text = {
			en = "<span style=\"color: #A335EE\">Sturdy Chest</span>",
			es = "[Sturdy Chest]",
			mx = "<span style=\"color: #A335EE\">Cofre robusto</span>",
			de = "<span style=\"color: #A335EE\">Robuste Truhe</span>",
			fr = "[Sturdy Chest]",
			it = "[Sturdy Chest]",
			pt = "[Sturdy Chest]",
			ru = "<span style=\"color: #A335EE\">Прочный сундук</span>",
			ko = "[Sturdy Chest]",
			cn = "[Sturdy Chest]",
			tw = "[Sturdy Chest]",
		},
	},
	[618275] = {
		readable = "<span style=\"color: #A335EE\">Sturdy Chest</span>",
		model = 5128194,
		text = {
			en = "<span style=\"color: #A335EE\">Sturdy Chest</span>",
			es = "<span style=\"color: #A335EE\">Sturdy Chest</span>",
			mx = "<span style=\"color: #A335EE\">Sturdy Chest</span>",
			de = "<span style=\"color: #A335EE\">Sturdy Chest</span>",
			fr = "<span style=\"color: #A335EE\">Sturdy Chest</span>",
			it = "<span style=\"color: #A335EE\">Sturdy Chest</span>",
			pt = "<span style=\"color: #A335EE\">Sturdy Chest</span>",
			ru = "<span style=\"color: #A335EE\">Sturdy Chest</span>",
			ko = "<span style=\"color: #A335EE\">Sturdy Chest</span>",
			cn = "<span style=\"color: #A335EE\">Sturdy Chest</span>",
			tw = "<span style=\"color: #A335EE\">Sturdy Chest</span>",
		},
	},
	[618276] = {
		readable = "<span style=\"color: #A335EE\">Sturdy Chest</span>",
		model = 5128194,
		text = {
			en = "<span style=\"color: #A335EE\">Sturdy Chest</span>",
			es = "[Sturdy Chest]",
			mx = "[Sturdy Chest]",
			de = "<span style=\"color: #A335EE\">Robuste Truhe</span>",
			fr = "<span style=\"color: #A335EE\">Coffre solide</span>",
			it = "[Sturdy Chest]",
			pt = "[Sturdy Chest]",
			ru = "[Sturdy Chest]",
			ko = "[Sturdy Chest]",
			cn = "[Sturdy Chest]",
			tw = "[Sturdy Chest]",
		},
	},
	[618277] = {
		readable = "<span style=\"color: #A335EE\">Sturdy Chest</span>",
		model = 5128194,
		text = {
			en = "<span style=\"color: #A335EE\">Sturdy Chest</span>",
			es = "[Sturdy Chest]",
			mx = "[Sturdy Chest]",
			de = "[Sturdy Chest]",
			fr = "[Sturdy Chest]",
			it = "[Sturdy Chest]",
			pt = "[Sturdy Chest]",
			ru = "[Sturdy Chest]",
			ko = "[Sturdy Chest]",
			cn = "[Sturdy Chest]",
			tw = "[Sturdy Chest]",
		},
	},
	[618278] = {
		readable = "<span style=\"color: #A335EE\">Sturdy Chest</span>",
		model = 5128194,
		text = {
			en = "<span style=\"color: #A335EE\">Sturdy Chest</span>",
			es = "<span style=\"color: #A335EE\">Cofre robusto</span>",
			mx = "[Sturdy Chest]",
			de = "<span style=\"color: #A335EE\">Robuste Truhe</span>",
			fr = "<span style=\"color: #A335EE\">Coffre solide</span>",
			it = "[Sturdy Chest]",
			pt = "[Sturdy Chest]",
			ru = "[Sturdy Chest]",
			ko = "[Sturdy Chest]",
			cn = "[Sturdy Chest]",
			tw = "[Sturdy Chest]",
		},
	},
	[618279] = {
		readable = "<span style=\"color: #A335EE\">Sturdy Chest</span>",
		model = 5128194,
		text = {
			en = "<span style=\"color: #A335EE\">Sturdy Chest</span>",
			es = "[Sturdy Chest]",
			mx = "[Sturdy Chest]",
			de = "[Sturdy Chest]",
			fr = "[Sturdy Chest]",
			it = "[Sturdy Chest]",
			pt = "[Sturdy Chest]",
			ru = "[Sturdy Chest]",
			ko = "[Sturdy Chest]",
			cn = "[Sturdy Chest]",
			tw = "[Sturdy Chest]",
		},
	},
	[618280] = {
		readable = "Sturdy Chest",
		model = 5128194,
		text = {
			en = "Sturdy Chest",
			es = "[Sturdy Chest]",
			mx = "[Sturdy Chest]",
			de = "[Sturdy Chest]",
			fr = "[Sturdy Chest]",
			it = "[Sturdy Chest]",
			pt = "[Sturdy Chest]",
			ru = "[Sturdy Chest]",
			ko = "[Sturdy Chest]",
			cn = "[Sturdy Chest]",
			tw = "[Sturdy Chest]",
		},
	},
	[618281] = {
		readable = "Sturdy Chest",
		model = 5128194,
		text = {
			en = "Sturdy Chest",
			es = "[Sturdy Chest]",
			mx = "[Sturdy Chest]",
			de = "[Sturdy Chest]",
			fr = "[Sturdy Chest]",
			it = "[Sturdy Chest]",
			pt = "[Sturdy Chest]",
			ru = "[Sturdy Chest]",
			ko = "[Sturdy Chest]",
			cn = "[Sturdy Chest]",
			tw = "[Sturdy Chest]",
		},
	},
	[618283] = {
		readable = "<span style=\"color: #A335EE\">Sturdy Chest</span>",
		model = 5128194,
		text = {
			en = "<span style=\"color: #A335EE\">Sturdy Chest</span>",
			es = "<span style=\"color: #A335EE\">Sturdy Chest</span>",
			mx = "<span style=\"color: #A335EE\">Sturdy Chest</span>",
		},
	},
})
do ObjectDB[objectID] = objectData; end
