local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[649115] = {
		readable = "Chewed Meat",
		model = 198343,
		text = {
			en = "Chewed Meat",
			es = "Carne mordisqueada",
			mx = "[Chewed Meat]",
			de = "Angekautes Fleisch",
			fr = "Viande mâchonnée",
			it = "[Chewed Meat]",
			pt = "[Chewed Meat]",
			ru = "Пожеванное мясо",
			ko = "물어뜯긴 고기",
			cn = "碎烂的肉",
			tw = "被咬過的肉",
		},
	},
	[649189] = {
		readable = "Ritual Circle",
		model = 5975159,
		text = {
			en = "Ritual Circle",
			es = "Círculo ritual",
			mx = "Círculo ritual",
			de = "Ritualkreis",
			fr = "Cercle rituel",
			it = "Circolo del Rituale",
			pt = "Círculo Ritual",
			ru = "Ритуальный круг",
			ko = "의식 진",
			cn = "仪式法阵",
			tw = "儀式法陣",
		},
	},
	[649412] = {
		readable = "Void-Tainted Nest",
		model = 1279713,
		text = {
			en = "Void-Tainted Nest",
			es = "Nido contaminado del Vacío",
			mx = "[Void-Tainted Nest]",
			de = "Leerenbesudeltes Nest",
			fr = "Nid corrompu par le Vide",
			it = "[Void-Tainted Nest]",
			pt = "Ninho Maculado de Caos",
			ru = "Оскверненное Бездной гнездо",
			ko = "공허에 오염된 둥지",
			cn = "虚空侵染的巢穴",
			tw = "虛無污化鷹巢",
		},
	},
})
do ObjectDB[objectID] = objectData; end
