local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[464146] = {
		readable = "Blue Floristar",
		model = 987197,
		text = {
			en = "Blue Floristar",
			es = "Blue Floristar",
			mx = "Blue Floristar",
			de = "Blue Floristar",
			fr = "Blue Floristar",
			it = "Blue Floristar",
			pt = "Blue Floristar",
			ru = "Blue Floristar",
			ko = "Blue Floristar",
			cn = "Blue Floristar",
			tw = "Blue Floristar",
		},
	},
	[466704] = {
		readable = "Crate of Produce",
		model = 1709047,
		text = {
			en = "Crate of Produce",
			es = "Crate of Produce",
			mx = "Crate of Produce",
			de = "Crate of Produce",
			fr = "Crate of Produce",
			it = "Crate of Produce",
			pt = "Crate of Produce",
			ru = "Crate of Produce",
			ko = "Crate of Produce",
			cn = "Crate of Produce",
			tw = "Crate of Produce",
		},
	},
	[474043] = {
		readable = "Gorgoa Reed",
		model = 3684823,
		text = {
			en = "Gorgoa Reed",
			es = "Gorgoa Reed",
			mx = "Gorgoa Reed",
			de = "Gorgoa Reed",
			fr = "Gorgoa Reed",
			it = "Gorgoa Reed",
			pt = "Gorgoa Reed",
			ru = "Gorgoa Reed",
			ko = "Gorgoa Reed",
			cn = "Gorgoa Reed",
			tw = "Gorgoa Reed",
		},
	},
	[504683] = {
		readable = "Wooden Barrel",
		model = 531027,
		text = {
			en = "Wooden Barrel",
			es = "Wooden Barrel",
			mx = "Wooden Barrel",
			de = "Wooden Barrel",
			fr = "Wooden Barrel",
			it = "Wooden Barrel",
			pt = "Wooden Barrel",
			ru = "Wooden Barrel",
			ko = "Wooden Barrel",
			cn = "Wooden Barrel",
			tw = "Wooden Barrel",
		},
	},
	[504788] = {
		readable = "Wooden Barrel",
		model = 531027,
		text = {
			en = "Wooden Barrel",
			es = "Wooden Barrel",
			mx = "Wooden Barrel",
			de = "Wooden Barrel",
			fr = "Wooden Barrel",
			it = "Wooden Barrel",
			pt = "Wooden Barrel",
			ru = "Wooden Barrel",
			ko = "Wooden Barrel",
			cn = "Wooden Barrel",
			tw = "Wooden Barrel",
		},
	},
	[504789] = {
		readable = "Wooden Barrel",
		model = 531027,
		text = {
			en = "Wooden Barrel",
			es = "Wooden Barrel",
			mx = "Wooden Barrel",
			de = "Wooden Barrel",
			fr = "Wooden Barrel",
			it = "Wooden Barrel",
			pt = "Wooden Barrel",
			ru = "Wooden Barrel",
			ko = "Wooden Barrel",
			cn = "Wooden Barrel",
			tw = "Wooden Barrel",
		},
	},
	[504790] = {
		readable = "Wooden Barrel",
		model = 531027,
		text = {
			en = "Wooden Barrel",
			es = "Wooden Barrel",
			mx = "Wooden Barrel",
			de = "Wooden Barrel",
			fr = "Wooden Barrel",
			it = "Wooden Barrel",
			pt = "Wooden Barrel",
			ru = "Wooden Barrel",
			ko = "Wooden Barrel",
			cn = "Wooden Barrel",
			tw = "Wooden Barrel",
		},
	},
	[509560] = {
		readable = "Barrel of Fireworks",
		model = 198273,
		text = {
			en = "Barrel of Fireworks",
			es = "Barrel of Fireworks",
			mx = "Barrel of Fireworks",
			de = "Barrel of Fireworks",
			fr = "Barrel of Fireworks",
			it = "Barrel of Fireworks",
			pt = "Barrel of Fireworks",
			ru = "Barrel of Fireworks",
			ko = "Barrel of Fireworks",
			cn = "Barrel of Fireworks",
			tw = "Barrel of Fireworks",
		},
	},
})
do ObjectDB[objectID] = objectData; end
