local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[572254] = {
		readable = "Ironwood Lumber",
		model = 6922313,
		text = {
			en = "Ironwood Lumber",
			es = "[Ironwood Lumber]",
			mx = "[Ironwood Lumber]",
			de = "[Ironwood Lumber]",
			fr = "[Ironwood Lumber]",
			it = "[Ironwood Lumber]",
			pt = "[Ironwood Lumber]",
			ru = "[Ironwood Lumber]",
			ko = "[Ironwood Lumber]",
			cn = "[Ironwood Lumber]",
			tw = "[Ironwood Lumber]",
		},
	},
	[573057] = {
		readable = "Ironwood Lumber",
		model = 6922313,
		text = {
			en = "Ironwood Lumber",
			es = "Maderaférrea",
			mx = "[Ironwood Lumber]",
			de = "Eisenholz",
			fr = "Bois de bois-de-fer",
			it = "[Ironwood Lumber]",
			pt = "Lenha de Pau-ferro",
			ru = "Древесина железного дерева",
			ko = "[Ironwood Lumber]",
			cn = "[Ironwood Lumber]",
			tw = "[Ironwood Lumber]",
		},
	},
	[573368] = {
		readable = "Ironwood Lumber",
		model = 6922313,
		text = {
			en = "Ironwood Lumber",
			es = "Maderaférrea",
			mx = "[Ironwood Lumber]",
			de = "Eisenholz",
			fr = "Bois de bois-de-fer",
			it = "[Ironwood Lumber]",
			pt = "Lenha de Pau-ferro",
			ru = "Древесина железного дерева",
			ko = "[Ironwood Lumber]",
			cn = "[Ironwood Lumber]",
			tw = "[Ironwood Lumber]",
		},
	},
	[573459] = {
		readable = "Ironwood Lumber",
		model = 6922313,
		text = {
			en = "Ironwood Lumber",
			es = "Maderaférrea",
			mx = "[Ironwood Lumber]",
			de = "Eisenholz",
			fr = "Bois de bois-de-fer",
			it = "[Ironwood Lumber]",
			pt = "Lenha de Pau-ferro",
			ru = "Древесина железного дерева",
			ko = "[Ironwood Lumber]",
			cn = "[Ironwood Lumber]",
			tw = "[Ironwood Lumber]",
		},
	},
	[573695] = {
		readable = "Ironwood Lumber",
		model = 6922313,
		text = {
			en = "Ironwood Lumber",
			es = "Maderaférrea",
			mx = "[Ironwood Lumber]",
			de = "Eisenholz",
			fr = "Bois de bois-de-fer",
			it = "[Ironwood Lumber]",
			pt = "Lenha de Pau-ferro",
			ru = "Древесина железного дерева",
			ko = "[Ironwood Lumber]",
			cn = "[Ironwood Lumber]",
			tw = "[Ironwood Lumber]",
		},
	},
	[574416] = {
		readable = "Ironwood Lumber",
		model = 6922313,
		text = {
			en = "Ironwood Lumber",
			es = "[Ironwood Lumber]",
			mx = "[Ironwood Lumber]",
			de = "Eisenholz",
			fr = "Bois de bois-de-fer",
			it = "[Ironwood Lumber]",
			pt = "Lenha de Pau-ferro",
			ru = "Древесина железного дерева",
			ko = "[Ironwood Lumber]",
			cn = "[Ironwood Lumber]",
			tw = "[Ironwood Lumber]",
		},
	},
	[574596] = {
		readable = "Ironwood Lumber",
		model = 6922313,
		text = {
			en = "Ironwood Lumber",
			es = "Maderaférrea",
			mx = "[Ironwood Lumber]",
			de = "Eisenholz",
			fr = "Bois de bois-de-fer",
			it = "Legname di Legnoduro",
			pt = "Lenha de Pau-ferro",
			ru = "Древесина железного дерева",
			ko = "[Ironwood Lumber]",
			cn = "[Ironwood Lumber]",
			tw = "[Ironwood Lumber]",
		},
	},
	[574599] = {
		readable = "Ironwood Lumber",
		model = 6922313,
		text = {
			en = "Ironwood Lumber",
			es = "Maderaférrea",
			mx = "[Ironwood Lumber]",
			de = "Eisenholz",
			fr = "Bois de bois-de-fer",
			it = "[Ironwood Lumber]",
			pt = "Lenha de Pau-ferro",
			ru = "Древесина железного дерева",
			ko = "강철나무 목재",
			cn = "[Ironwood Lumber]",
			tw = "[Ironwood Lumber]",
		},
	},
	[574611] = {
		readable = "Ashwood Lumber",
		model = 6922313,
		text = {
			en = "Ashwood Lumber",
			es = "[Ashwood Lumber]",
			mx = "[Ashwood Lumber]",
			de = "[Ashwood Lumber]",
			fr = "[Ashwood Lumber]",
			it = "[Ashwood Lumber]",
			pt = "[Ashwood Lumber]",
			ru = "[Ashwood Lumber]",
			ko = "[Ashwood Lumber]",
			cn = "[Ashwood Lumber]",
			tw = "[Ashwood Lumber]",
		},
	},
	[574731] = {
		readable = "Ironwood Lumber",
		model = 6922313,
		text = {
			en = "Ironwood Lumber",
			es = "Maderaférrea",
			mx = "[Ironwood Lumber]",
			de = "Eisenholz",
			fr = "Bois de bois-de-fer",
			it = "[Ironwood Lumber]",
			pt = "Lenha de Pau-ferro",
			ru = "Древесина железного дерева",
			ko = "강철나무 목재",
			cn = "[Ironwood Lumber]",
			tw = "[Ironwood Lumber]",
		},
	},
	[574913] = {
		readable = "Ironwood Lumber",
		model = 6922313,
		text = {
			en = "Ironwood Lumber",
			es = "[Ironwood Lumber]",
			mx = "[Ironwood Lumber]",
			de = "[Ironwood Lumber]",
			fr = "[Ironwood Lumber]",
			it = "[Ironwood Lumber]",
			pt = "[Ironwood Lumber]",
			ru = "[Ironwood Lumber]",
			ko = "[Ironwood Lumber]",
			cn = "[Ironwood Lumber]",
			tw = "[Ironwood Lumber]",
		},
	},
	[574938] = {
		readable = "Ironwood Lumber",
		model = 6922313,
		text = {
			en = "Ironwood Lumber",
			es = "Maderaférrea",
			mx = "[Ironwood Lumber]",
			de = "Eisenholz",
			fr = "Bois de bois-de-fer",
			it = "[Ironwood Lumber]",
			pt = "[Ironwood Lumber]",
			ru = "Древесина железного дерева",
			ko = "강철나무 목재",
			cn = "[Ironwood Lumber]",
			tw = "[Ironwood Lumber]",
		},
	},
	[574966] = {
		readable = "Ironwood Lumber",
		model = 6922313,
		text = {
			en = "Ironwood Lumber",
			es = "Maderaférrea",
			mx = "[Ironwood Lumber]",
			de = "Eisenholz",
			fr = "Bois de bois-de-fer",
			it = "[Ironwood Lumber]",
			pt = "Lenha de Pau-ferro",
			ru = "Древесина железного дерева",
			ko = "강철나무 목재",
			cn = "[Ironwood Lumber]",
			tw = "[Ironwood Lumber]",
		},
	},
	[575031] = {
		readable = "Ironwood Lumber",
		model = 6922313,
		text = {
			en = "Ironwood Lumber",
			es = "Maderaférrea",
			mx = "[Ironwood Lumber]",
			de = "Eisenholz",
			fr = "Bois de bois-de-fer",
			it = "[Ironwood Lumber]",
			pt = "Lenha de Pau-ferro",
			ru = "Древесина железного дерева",
			ko = "강철나무 목재",
			cn = "[Ironwood Lumber]",
			tw = "[Ironwood Lumber]",
		},
	},
	[576113] = {
		readable = "Ironwood Lumber",
		model = 6922313,
		text = {
			en = "Ironwood Lumber",
			es = "Maderaférrea",
			mx = "[Ironwood Lumber]",
			de = "Eisenholz",
			fr = "Bois de bois-de-fer",
			it = "[Ironwood Lumber]",
			pt = "Lenha de Pau-ferro",
			ru = "Древесина железного дерева",
			ko = "[Ironwood Lumber]",
			cn = "[Ironwood Lumber]",
			tw = "[Ironwood Lumber]",
		},
	},
	[576199] = {
		readable = "Ironwood Lumber",
		model = 6922313,
		text = {
			en = "Ironwood Lumber",
			es = "Maderaférrea",
			mx = "[Ironwood Lumber]",
			de = "Eisenholz",
			fr = "Bois de bois-de-fer",
			it = "Legname di Legnoduro",
			pt = "Lenha de Pau-ferro",
			ru = "Древесина железного дерева",
			ko = "[Ironwood Lumber]",
			cn = "[Ironwood Lumber]",
			tw = "[Ironwood Lumber]",
		},
	},
	[576282] = {
		readable = "Ironwood Lumber",
		model = 6922313,
		text = {
			en = "Ironwood Lumber",
			es = "Maderaférrea",
			mx = "[Ironwood Lumber]",
			de = "Eisenholz",
			fr = "Bois de bois-de-fer",
			it = "Legname di Legnoduro",
			pt = "Lenha de Pau-ferro",
			ru = "Древесина железного дерева",
			ko = "[Ironwood Lumber]",
			cn = "[Ironwood Lumber]",
			tw = "[Ironwood Lumber]",
		},
	},
	[576400] = {
		readable = "Ironwood Lumber",
		model = 6922313,
		text = {
			en = "Ironwood Lumber",
			es = "Maderaférrea",
			mx = "[Ironwood Lumber]",
			de = "Eisenholz",
			fr = "Bois de bois-de-fer",
			it = "[Ironwood Lumber]",
			pt = "[Ironwood Lumber]",
			ru = "Древесина железного дерева",
			ko = "[Ironwood Lumber]",
			cn = "[Ironwood Lumber]",
			tw = "[Ironwood Lumber]",
		},
	},
	[576402] = {
		readable = "Ironwood Lumber",
		model = 6922313,
		text = {
			en = "Ironwood Lumber",
			es = "Maderaférrea",
			mx = "[Ironwood Lumber]",
			de = "Eisenholz",
			fr = "Bois de bois-de-fer",
			it = "Legname di Legnoduro",
			pt = "[Ironwood Lumber]",
			ru = "[Ironwood Lumber]",
			ko = "[Ironwood Lumber]",
			cn = "[Ironwood Lumber]",
			tw = "[Ironwood Lumber]",
		},
	},
	[576448] = {
		readable = "Ironwood Lumber",
		model = 6922313,
		text = {
			en = "Ironwood Lumber",
			es = "Maderaférrea",
			mx = "[Ironwood Lumber]",
			de = "Eisenholz",
			fr = "Bois de bois-de-fer",
			it = "[Ironwood Lumber]",
			pt = "Lenha de Pau-ferro",
			ru = "Древесина железного дерева",
			ko = "[Ironwood Lumber]",
			cn = "[Ironwood Lumber]",
			tw = "[Ironwood Lumber]",
		},
	},
	[576622] = {
		readable = "Ironwood Lumber",
		model = 6922313,
		text = {
			en = "Ironwood Lumber",
			es = "Maderaférrea",
			mx = "[Ironwood Lumber]",
			de = "Eisenholz",
			fr = "Bois de bois-de-fer",
			it = "Legname di Legnoduro",
			pt = "Lenha de Pau-ferro",
			ru = "[Ironwood Lumber]",
			ko = "[Ironwood Lumber]",
			cn = "[Ironwood Lumber]",
			tw = "[Ironwood Lumber]",
		},
	},
	[576692] = {
		readable = "Ironwood Lumber",
		model = 6922313,
		text = {
			en = "Ironwood Lumber",
			es = "Maderaférrea",
			mx = "[Ironwood Lumber]",
			de = "Eisenholz",
			fr = "Bois de bois-de-fer",
			it = "Legname di Legnoduro",
			pt = "Lenha de Pau-ferro",
			ru = "Древесина железного дерева",
			ko = "[Ironwood Lumber]",
			cn = "[Ironwood Lumber]",
			tw = "[Ironwood Lumber]",
		},
	},
	[576717] = {
		readable = "Ironwood Lumber",
		model = 6922313,
		text = {
			en = "Ironwood Lumber",
			es = "[Ironwood Lumber]",
			mx = "[Ironwood Lumber]",
			de = "Eisenholz",
			fr = "Bois de bois-de-fer",
			it = "[Ironwood Lumber]",
			pt = "Lenha de Pau-ferro",
			ru = "Древесина железного дерева",
			ko = "[Ironwood Lumber]",
			cn = "[Ironwood Lumber]",
			tw = "[Ironwood Lumber]",
		},
	},
	[577703] = {
		readable = "Ironwood Lumber",
		model = 6922313,
		text = {
			en = "Ironwood Lumber",
			es = "[Ironwood Lumber]",
			mx = "[Ironwood Lumber]",
			de = "Eisenholz",
			fr = "Bois de bois-de-fer",
			it = "[Ironwood Lumber]",
			pt = "Lenha de Pau-ferro",
			ru = "Древесина железного дерева",
			ko = "[Ironwood Lumber]",
			cn = "[Ironwood Lumber]",
			tw = "[Ironwood Lumber]",
		},
	},
	[577787] = {
		readable = "Ironwood Lumber",
		model = 6922313,
		text = {
			en = "Ironwood Lumber",
			es = "[Ironwood Lumber]",
			mx = "[Ironwood Lumber]",
			de = "Eisenholz",
			fr = "Bois de bois-de-fer",
			it = "[Ironwood Lumber]",
			pt = "[Ironwood Lumber]",
			ru = "Древесина железного дерева",
			ko = "[Ironwood Lumber]",
			cn = "[Ironwood Lumber]",
			tw = "[Ironwood Lumber]",
		},
	},
	[577792] = {
		readable = "Ironwood Lumber",
		model = 6922313,
		text = {
			en = "Ironwood Lumber",
			es = "Maderaférrea",
			mx = "[Ironwood Lumber]",
			de = "Eisenholz",
			fr = "Bois de bois-de-fer",
			it = "[Ironwood Lumber]",
			pt = "Lenha de Pau-ferro",
			ru = "[Ironwood Lumber]",
			ko = "[Ironwood Lumber]",
			cn = "[Ironwood Lumber]",
			tw = "[Ironwood Lumber]",
		},
	},
	[577999] = {
		readable = "Ironwood Lumber",
		model = 6922313,
		text = {
			en = "Ironwood Lumber",
			es = "[Ironwood Lumber]",
			mx = "[Ironwood Lumber]",
			de = "Eisenholz",
			fr = "Bois de bois-de-fer",
			it = "[Ironwood Lumber]",
			pt = "[Ironwood Lumber]",
			ru = "[Ironwood Lumber]",
			ko = "[Ironwood Lumber]",
			cn = "[Ironwood Lumber]",
			tw = "[Ironwood Lumber]",
		},
	},
	[578023] = {
		readable = "Ironwood Lumber",
		model = 6922313,
		text = {
			en = "Ironwood Lumber",
			es = "Maderaférrea",
			mx = "[Ironwood Lumber]",
			de = "Eisenholz",
			fr = "Bois de bois-de-fer",
			it = "[Ironwood Lumber]",
			pt = "[Ironwood Lumber]",
			ru = "[Ironwood Lumber]",
			ko = "[Ironwood Lumber]",
			cn = "[Ironwood Lumber]",
			tw = "[Ironwood Lumber]",
		},
	},
	[578925] = {
		readable = "Ironwood Lumber",
		model = 6922313,
		text = {
			en = "Ironwood Lumber",
			es = "Maderaférrea",
			mx = "[Ironwood Lumber]",
			de = "Eisenholz",
			fr = "Bois de bois-de-fer",
			it = "[Ironwood Lumber]",
			pt = "Lenha de Pau-ferro",
			ru = "Древесина железного дерева",
			ko = "강철나무 목재",
			cn = "[Ironwood Lumber]",
			tw = "[Ironwood Lumber]",
		},
	},
	[581830] = {
		readable = "Ironwood Lumber",
		model = 6922313,
		text = {
			en = "Ironwood Lumber",
			es = "Maderaférrea",
			mx = "[Ironwood Lumber]",
			de = "Eisenholz",
			fr = "Bois de bois-de-fer",
			it = "[Ironwood Lumber]",
			pt = "Lenha de Pau-ferro",
			ru = "Древесина железного дерева",
			ko = "강철나무 목재",
			cn = "[Ironwood Lumber]",
			tw = "[Ironwood Lumber]",
		},
	},
	[581876] = {
		readable = "Ironwood Lumber",
		model = 6922313,
		text = {
			en = "Ironwood Lumber",
			es = "Maderaférrea",
			mx = "[Ironwood Lumber]",
			de = "Eisenholz",
			fr = "Bois de bois-de-fer",
			it = "[Ironwood Lumber]",
			pt = "Lenha de Pau-ferro",
			ru = "Древесина железного дерева",
			ko = "[Ironwood Lumber]",
			cn = "[Ironwood Lumber]",
			tw = "[Ironwood Lumber]",
		},
	},
	[582143] = {
		readable = "Ironwood Lumber",
		model = 6922313,
		text = {
			en = "Ironwood Lumber",
			es = "[Ironwood Lumber]",
			mx = "[Ironwood Lumber]",
			de = "Eisenholz",
			fr = "[Ironwood Lumber]",
			it = "[Ironwood Lumber]",
			pt = "[Ironwood Lumber]",
			ru = "[Ironwood Lumber]",
			ko = "[Ironwood Lumber]",
			cn = "[Ironwood Lumber]",
			tw = "[Ironwood Lumber]",
		},
	},
	[582149] = {
		readable = "Ironwood Lumber",
		model = 6922313,
		text = {
			en = "Ironwood Lumber",
			es = "Maderaférrea",
			mx = "[Ironwood Lumber]",
			de = "Eisenholz",
			fr = "Bois de bois-de-fer",
			it = "[Ironwood Lumber]",
			pt = "Lenha de Pau-ferro",
			ru = "Древесина железного дерева",
			ko = "[Ironwood Lumber]",
			cn = "[Ironwood Lumber]",
			tw = "[Ironwood Lumber]",
		},
	},
	[584445] = {
		readable = "Ironwood Lumber",
		model = 6922313,
		text = {
			en = "Ironwood Lumber",
			es = "Maderaférrea",
			mx = "[Ironwood Lumber]",
			de = "Eisenholz",
			fr = "Bois de bois-de-fer",
			it = "[Ironwood Lumber]",
			pt = "Lenha de Pau-ferro",
			ru = "Древесина железного дерева",
			ko = "[Ironwood Lumber]",
			cn = "[Ironwood Lumber]",
			tw = "[Ironwood Lumber]",
		},
	},
	[584475] = {
		readable = "Ironwood Lumber",
		model = 6922313,
		text = {
			en = "Ironwood Lumber",
			es = "[Ironwood Lumber]",
			mx = "[Ironwood Lumber]",
			de = "Eisenholz",
			fr = "Bois de bois-de-fer",
			it = "[Ironwood Lumber]",
			pt = "[Ironwood Lumber]",
			ru = "Древесина железного дерева",
			ko = "강철나무 목재",
			cn = "[Ironwood Lumber]",
			tw = "[Ironwood Lumber]",
		},
	},
	[584615] = {
		readable = "Ironwood Lumber",
		model = 6922313,
		text = {
			en = "Ironwood Lumber",
			es = "Maderaférrea",
			mx = "[Ironwood Lumber]",
			de = "Eisenholz",
			fr = "Bois de bois-de-fer",
			it = "[Ironwood Lumber]",
			pt = "Lenha de Pau-ferro",
			ru = "Древесина железного дерева",
			ko = "강철나무 목재",
			cn = "[Ironwood Lumber]",
			tw = "[Ironwood Lumber]",
		},
	},
	[584694] = {
		readable = "Ironwood Lumber",
		model = 6922313,
		text = {
			en = "Ironwood Lumber",
			es = "Maderaférrea",
			mx = "[Ironwood Lumber]",
			de = "Eisenholz",
			fr = "Bois de bois-de-fer",
			it = "[Ironwood Lumber]",
			pt = "[Ironwood Lumber]",
			ru = "Древесина железного дерева",
			ko = "[Ironwood Lumber]",
			cn = "[Ironwood Lumber]",
			tw = "[Ironwood Lumber]",
		},
	},
})
do ObjectDB[objectID] = objectData; end
