local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[508705] = {
		readable = "Lena's Stein",
		model = 2918348,
		text = {
			en = "Lena's Stein",
			es = "Lena's Stein",
			mx = "Lena's Stein",
			de = "Lena's Stein",
			fr = "Lena's Stein",
			it = "Lena's Stein",
			pt = "Lena's Stein",
			ru = "Lena's Stein",
			ko = "Lena's Stein",
			cn = "Lena's Stein",
			tw = "Lena's Stein",
		},
	},
	[508709] = {
		readable = "Aln Mushroom",
		text = {
			en = "Aln Mushroom",
			es = "Aln Mushroom",
			mx = "Aln Mushroom",
			de = "Aln Mushroom",
			fr = "Aln Mushroom",
			it = "Aln Mushroom",
			pt = "Aln Mushroom",
			ru = "Aln Mushroom",
			ko = "Aln Mushroom",
			cn = "Aln Mushroom",
			tw = "Aln Mushroom",
		},
	},
	[516293] = {
		readable = "Bloodclot Shrub",
		model = 4684648,
		text = {
			en = "Bloodclot Shrub",
			es = "Bloodclot Shrub",
			mx = "Bloodclot Shrub",
			de = "Bloodclot Shrub",
			fr = "Bloodclot Shrub",
			it = "Bloodclot Shrub",
			pt = "Bloodclot Shrub",
			ru = "Bloodclot Shrub",
			ko = "Bloodclot Shrub",
			cn = "Bloodclot Shrub",
			tw = "Bloodclot Shrub",
		},
	},
	[516363] = {
		readable = "Sedated Spellbook",
		model = 4298562,
		text = {
			en = "Sedated Spellbook",
			es = "Sedated Spellbook",
			mx = "Sedated Spellbook",
			de = "Sedated Spellbook",
			fr = "Sedated Spellbook",
			it = "Sedated Spellbook",
			pt = "Sedated Spellbook",
			ru = "Sedated Spellbook",
			ko = "Sedated Spellbook",
			cn = "Sedated Spellbook",
			tw = "Sedated Spellbook",
		},
	},
	[517146] = {
		readable = "Dropped Note",
		model = 929395,
		text = {
			en = "Dropped Note",
			es = "Dropped Note",
			mx = "Dropped Note",
			de = "Dropped Note",
			fr = "Dropped Note",
			it = "Dropped Note",
			pt = "Dropped Note",
			ru = "Dropped Note",
			ko = "Dropped Note",
			cn = "Dropped Note",
			tw = "Dropped Note",
		},
	},
	[518640] = {
		readable = "Lightspire Spear",
		model = 3038741,
		text = {
			en = "Lightspire Spear",
			es = "Lightspire Spear",
			mx = "Lightspire Spear",
			de = "Lightspire Spear",
			fr = "Lightspire Spear",
			it = "Lightspire Spear",
			pt = "Lightspire Spear",
			ru = "Lightspire Spear",
			ko = "Lightspire Spear",
			cn = "Lightspire Spear",
			tw = "Lightspire Spear",
		},
	},
	[519235] = {
		readable = "Art and Architecture of Silvermoon: Vol. 3",
		text = {
			en = "Art and Architecture of Silvermoon: Vol. 3",
			es = "Art and Architecture of Silvermoon: Vol. 3",
			mx = "Art and Architecture of Silvermoon: Vol. 3",
			de = "Art and Architecture of Silvermoon: Vol. 3",
			fr = "Art and Architecture of Silvermoon: Vol. 3",
			it = "Art and Architecture of Silvermoon: Vol. 3",
			pt = "Art and Architecture of Silvermoon: Vol. 3",
			ru = "Art and Architecture of Silvermoon: Vol. 3",
			ko = "Art and Architecture of Silvermoon: Vol. 3",
			cn = "Art and Architecture of Silvermoon: Vol. 3",
			tw = "Art and Architecture of Silvermoon: Vol. 3",
		},
	},
	[519237] = {
		readable = "Satchel of Herbs",
		text = {
			en = "Satchel of Herbs",
			es = "Satchel of Herbs",
			mx = "Satchel of Herbs",
			de = "Satchel of Herbs",
			fr = "Satchel of Herbs",
			it = "Satchel of Herbs",
			pt = "Satchel of Herbs",
			ru = "Satchel of Herbs",
			ko = "Satchel of Herbs",
			cn = "Satchel of Herbs",
			tw = "Satchel of Herbs",
		},
	},
	[519240] = {
		readable = "Nondescript Bottle of Water",
		text = {
			en = "Nondescript Bottle of Water",
			es = "Nondescript Bottle of Water",
			mx = "Nondescript Bottle of Water",
			de = "Nondescript Bottle of Water",
			fr = "Nondescript Bottle of Water",
			it = "Nondescript Bottle of Water",
			pt = "Nondescript Bottle of Water",
			ru = "Nondescript Bottle of Water",
			ko = "Nondescript Bottle of Water",
			cn = "Nondescript Bottle of Water",
			tw = "Nondescript Bottle of Water",
		},
	},
	[520354] = {
		readable = "Submerged Cargo",
		model = 1349031,
		text = {
			en = "Submerged Cargo",
			es = "Submerged Cargo",
			mx = "Submerged Cargo",
			de = "Submerged Cargo",
			fr = "Submerged Cargo",
			it = "Submerged Cargo",
			pt = "Submerged Cargo",
			ru = "Submerged Cargo",
			ko = "Submerged Cargo",
			cn = "Submerged Cargo",
			tw = "Submerged Cargo",
		},
	},
	[523389] = {
		readable = "Krohm's Smithing Hammer",
		model = 4095170,
		text = {
			en = "Krohm's Smithing Hammer",
			es = "Krohm's Smithing Hammer",
			mx = "Krohm's Smithing Hammer",
			de = "Krohm's Smithing Hammer",
			fr = "Krohm's Smithing Hammer",
			it = "Krohm's Smithing Hammer",
			pt = "Krohm's Smithing Hammer",
			ru = "Krohm's Smithing Hammer",
			ko = "Krohm's Smithing Hammer",
			cn = "Krohm's Smithing Hammer",
			tw = "Krohm's Smithing Hammer",
		},
	},
	[523390] = {
		readable = "Mara's Prayer Book",
		text = {
			en = "Mara's Prayer Book",
			es = "Mara's Prayer Book",
			mx = "Mara's Prayer Book",
			de = "Mara's Prayer Book",
			fr = "Mara's Prayer Book",
			it = "Mara's Prayer Book",
			pt = "Mara's Prayer Book",
			ru = "Mara's Prayer Book",
			ko = "Mara's Prayer Book",
			cn = "Mara's Prayer Book",
			tw = "Mara's Prayer Book",
		},
	},
	[523391] = {
		readable = "Uther's Healing Kit",
		model = 4417703,
		text = {
			en = "Uther's Healing Kit",
			es = "Uther's Healing Kit",
			mx = "Uther's Healing Kit",
			de = "Uther's Healing Kit",
			fr = "Uther's Healing Kit",
			it = "Uther's Healing Kit",
			pt = "Uther's Healing Kit",
			ru = "Uther's Healing Kit",
			ko = "Uther's Healing Kit",
			cn = "Uther's Healing Kit",
			tw = "Uther's Healing Kit",
		},
	},
	[525307] = {
		readable = "Shipment Crate",
		text = {
			en = "Shipment Crate",
			es = "Shipment Crate",
			mx = "Shipment Crate",
			de = "Shipment Crate",
			fr = "Shipment Crate",
			it = "Shipment Crate",
			pt = "Shipment Crate",
			ru = "Shipment Crate",
			ko = "Shipment Crate",
			cn = "Shipment Crate",
			tw = "Shipment Crate",
		},
	},
	[525492] = {
		readable = "Forgotten Skullcleaver",
		model = 1015733,
		text = {
			en = "Forgotten Skullcleaver",
			es = "Forgotten Skullcleaver",
			mx = "Forgotten Skullcleaver",
			de = "Forgotten Skullcleaver",
			fr = "Forgotten Skullcleaver",
			it = "Forgotten Skullcleaver",
			pt = "Forgotten Skullcleaver",
			ru = "Forgotten Skullcleaver",
			ko = "Forgotten Skullcleaver",
			cn = "Forgotten Skullcleaver",
			tw = "Forgotten Skullcleaver",
		},
	},
	[525493] = {
		readable = "Fallen Longsword",
		model = 970087,
		text = {
			en = "Fallen Longsword",
			es = "Fallen Longsword",
			mx = "Fallen Longsword",
			de = "Fallen Longsword",
			fr = "Fallen Longsword",
			it = "Fallen Longsword",
			pt = "Fallen Longsword",
			ru = "Fallen Longsword",
			ko = "Fallen Longsword",
			cn = "Fallen Longsword",
			tw = "Fallen Longsword",
		},
	},
	[526810] = {
		readable = "Missing Journal",
		model = 4298562,
		text = {
			en = "Missing Journal",
			es = "Missing Journal",
			mx = "Missing Journal",
			de = "Missing Journal",
			fr = "Missing Journal",
			it = "Missing Journal",
			pt = "Missing Journal",
			ru = "Missing Journal",
			ko = "Missing Journal",
			cn = "Missing Journal",
			tw = "Missing Journal",
		},
	},
	[527117] = {
		readable = "Iceberry Bush",
		text = {
			en = "Iceberry Bush",
			es = "Iceberry Bush",
			mx = "Iceberry Bush",
			de = "Iceberry Bush",
			fr = "Iceberry Bush",
			it = "Iceberry Bush",
			pt = "Iceberry Bush",
			ru = "Iceberry Bush",
			ko = "Iceberry Bush",
			cn = "Iceberry Bush",
			tw = "Iceberry Bush",
		},
	},
	[527218] = {
		readable = "Depleted Wardbreaker",
		text = {
			en = "Depleted Wardbreaker",
			es = "Depleted Wardbreaker",
			mx = "Depleted Wardbreaker",
			de = "Depleted Wardbreaker",
			fr = "Depleted Wardbreaker",
			it = "Depleted Wardbreaker",
			pt = "Depleted Wardbreaker",
			ru = "Depleted Wardbreaker",
			ko = "Depleted Wardbreaker",
			cn = "Depleted Wardbreaker",
			tw = "Depleted Wardbreaker",
		},
	},
	[527240] = {
		readable = "Magister's Chest",
		text = {
			en = "Magister's Chest",
			es = "Magister's Chest",
			mx = "Magister's Chest",
			de = "Magister's Chest",
			fr = "Magister's Chest",
			it = "Magister's Chest",
			pt = "Magister's Chest",
			ru = "Magister's Chest",
			ko = "Magister's Chest",
			cn = "Magister's Chest",
			tw = "Magister's Chest",
		},
	},
	[527363] = {
		readable = "Basket of Spell Reagents",
		model = 875120,
		text = {
			en = "Basket of Spell Reagents",
			es = "Basket of Spell Reagents",
			mx = "Basket of Spell Reagents",
			de = "Basket of Spell Reagents",
			fr = "Basket of Spell Reagents",
			it = "Basket of Spell Reagents",
			pt = "Basket of Spell Reagents",
			ru = "Basket of Spell Reagents",
			ko = "Basket of Spell Reagents",
			cn = "Basket of Spell Reagents",
			tw = "Basket of Spell Reagents",
		},
	},
	[527364] = {
		readable = "Thrumming Amulet",
		model = 3718230,
		text = {
			en = "Thrumming Amulet",
			es = "Thrumming Amulet",
			mx = "Thrumming Amulet",
			de = "Thrumming Amulet",
			fr = "Thrumming Amulet",
			it = "Thrumming Amulet",
			pt = "Thrumming Amulet",
			ru = "Thrumming Amulet",
			ko = "Thrumming Amulet",
			cn = "Thrumming Amulet",
			tw = "Thrumming Amulet",
		},
	},
	[527365] = {
		readable = "Arcane Sword",
		text = {
			en = "Arcane Sword",
			es = "Arcane Sword",
			mx = "Arcane Sword",
			de = "Arcane Sword",
			fr = "Arcane Sword",
			it = "Arcane Sword",
			pt = "Arcane Sword",
			ru = "Arcane Sword",
			ko = "Arcane Sword",
			cn = "Arcane Sword",
			tw = "Arcane Sword",
		},
	},
	[528004] = {
		readable = "Weeping Caps",
		text = {
			en = "Weeping Caps",
			es = "Weeping Caps",
			mx = "Weeping Caps",
			de = "Weeping Caps",
			fr = "Weeping Caps",
			it = "Weeping Caps",
			pt = "Weeping Caps",
			ru = "Weeping Caps",
			ko = "Weeping Caps",
			cn = "Weeping Caps",
			tw = "Weeping Caps",
		},
	},
	[528310] = {
		readable = "Mysterious Corpse",
		text = {
			en = "Mysterious Corpse",
			es = "Mysterious Corpse",
			mx = "Mysterious Corpse",
			de = "Mysterious Corpse",
			fr = "Mysterious Corpse",
			it = "Mysterious Corpse",
			pt = "Mysterious Corpse",
			ru = "Mysterious Corpse",
			ko = "Mysterious Corpse",
			cn = "Mysterious Corpse",
			tw = "Mysterious Corpse",
		},
	},
	[529683] = {
		readable = "Blisterskin Kelp",
		text = {
			en = "Blisterskin Kelp",
			es = "Blisterskin Kelp",
			mx = "Blisterskin Kelp",
			de = "Blisterskin Kelp",
			fr = "Blisterskin Kelp",
			it = "Blisterskin Kelp",
			pt = "Blisterskin Kelp",
			ru = "Blisterskin Kelp",
			ko = "Blisterskin Kelp",
			cn = "Blisterskin Kelp",
			tw = "Blisterskin Kelp",
		},
	},
	[531227] = {
		readable = "Lost Amani Oar",
		text = {
			en = "Lost Amani Oar",
			es = "Lost Amani Oar",
			mx = "Lost Amani Oar",
			de = "Lost Amani Oar",
			fr = "Lost Amani Oar",
			it = "Lost Amani Oar",
			pt = "Lost Amani Oar",
			ru = "Lost Amani Oar",
			ko = "Lost Amani Oar",
			cn = "Lost Amani Oar",
			tw = "Lost Amani Oar",
		},
	},
	[531508] = {
		readable = "Recharged Wardbreaker",
		text = {
			en = "Recharged Wardbreaker",
			es = "Recharged Wardbreaker",
			mx = "Recharged Wardbreaker",
			de = "Recharged Wardbreaker",
			fr = "Recharged Wardbreaker",
			it = "Recharged Wardbreaker",
			pt = "Recharged Wardbreaker",
			ru = "Recharged Wardbreaker",
			ko = "Recharged Wardbreaker",
			cn = "Recharged Wardbreaker",
			tw = "Recharged Wardbreaker",
		},
	},
	[532495] = {
		readable = "Healing Salve",
		model = 5100462,
		text = {
			en = "Healing Salve",
			es = "Healing Salve",
			mx = "Healing Salve",
			de = "Healing Salve",
			fr = "Healing Salve",
			it = "Healing Salve",
			pt = "Healing Salve",
			ru = "Healing Salve",
			ko = "Healing Salve",
			cn = "Healing Salve",
			tw = "Healing Salve",
		},
	},
	[539051] = {
		readable = "Mrruk's Mangy Trove",
		model = 955699,
		text = {
			en = "Mrruk's Mangy Trove",
			es = "Mrruk's Mangy Trove",
			mx = "Mrruk's Mangy Trove",
			de = "Mrruk's Mangy Trove",
			fr = "Mrruk's Mangy Trove",
			it = "Mrruk's Mangy Trove",
			pt = "Mrruk's Mangy Trove",
			ru = "Mrruk's Mangy Trove",
			ko = "Mrruk's Mangy Trove",
			cn = "Mrruk's Mangy Trove",
			tw = "Mrruk's Mangy Trove",
		},
	},
	[539207] = {
		readable = "Hastily Packed Belongings",
		text = {
			en = "Hastily Packed Belongings",
			es = "Hastily Packed Belongings",
			mx = "Hastily Packed Belongings",
			de = "Hastily Packed Belongings",
			fr = "Hastily Packed Belongings",
			it = "Hastily Packed Belongings",
			pt = "Hastily Packed Belongings",
			ru = "Hastily Packed Belongings",
			ko = "Hastily Packed Belongings",
			cn = "Hastily Packed Belongings",
			tw = "Hastily Packed Belongings",
		},
	},
	[539728] = {
		readable = "Crate of Fel Artifacts",
		text = {
			en = "Crate of Fel Artifacts",
			es = "Crate of Fel Artifacts",
			mx = "Crate of Fel Artifacts",
			de = "Crate of Fel Artifacts",
			fr = "Crate of Fel Artifacts",
			it = "Crate of Fel Artifacts",
			pt = "Crate of Fel Artifacts",
			ru = "Crate of Fel Artifacts",
			ko = "Crate of Fel Artifacts",
			cn = "Crate of Fel Artifacts",
			tw = "Crate of Fel Artifacts",
		},
	},
	[539770] = {
		readable = "Strewn Rags",
		model = 5530943,
		text = {
			en = "Strewn Rags",
			es = "Strewn Rags",
			mx = "Strewn Rags",
			de = "Strewn Rags",
			fr = "Strewn Rags",
			it = "Strewn Rags",
			pt = "Strewn Rags",
			ru = "Strewn Rags",
			ko = "Strewn Rags",
			cn = "Strewn Rags",
			tw = "Strewn Rags",
		},
	},
	[539772] = {
		readable = "\"Empty\" Wine Bottle",
		text = {
			en = "\"Empty\" Wine Bottle",
			es = "\"Empty\" Wine Bottle",
			mx = "\"Empty\" Wine Bottle",
			de = "\"Empty\" Wine Bottle",
			fr = "\"Empty\" Wine Bottle",
			it = "\"Empty\" Wine Bottle",
			pt = "\"Empty\" Wine Bottle",
			ru = "\"Empty\" Wine Bottle",
			ko = "\"Empty\" Wine Bottle",
			cn = "\"Empty\" Wine Bottle",
			tw = "\"Empty\" Wine Bottle",
		},
	},
	[539773] = {
		readable = "Concealed Crate",
		text = {
			en = "Concealed Crate",
			es = "Concealed Crate",
			mx = "Concealed Crate",
			de = "Concealed Crate",
			fr = "Concealed Crate",
			it = "Concealed Crate",
			pt = "Concealed Crate",
			ru = "Concealed Crate",
			ko = "Concealed Crate",
			cn = "Concealed Crate",
			tw = "Concealed Crate",
		},
	},
	[539774] = {
		readable = "Inconspicuous Ledger",
		text = {
			en = "Inconspicuous Ledger",
			es = "Inconspicuous Ledger",
			mx = "Inconspicuous Ledger",
			de = "Inconspicuous Ledger",
			fr = "Inconspicuous Ledger",
			it = "Inconspicuous Ledger",
			pt = "Inconspicuous Ledger",
			ru = "Inconspicuous Ledger",
			ko = "Inconspicuous Ledger",
			cn = "Inconspicuous Ledger",
			tw = "Inconspicuous Ledger",
		},
	},
	[539775] = {
		readable = "Mislaid Bag",
		text = {
			en = "Mislaid Bag",
			es = "Mislaid Bag",
			mx = "Mislaid Bag",
			de = "Mislaid Bag",
			fr = "Mislaid Bag",
			it = "Mislaid Bag",
			pt = "Mislaid Bag",
			ru = "Mislaid Bag",
			ko = "Mislaid Bag",
			cn = "Mislaid Bag",
			tw = "Mislaid Bag",
		},
	},
	[542854] = {
		readable = "Ominous Lockbox",
		text = {
			en = "Ominous Lockbox",
			es = "Ominous Lockbox",
			mx = "Ominous Lockbox",
			de = "Ominous Lockbox",
			fr = "Ominous Lockbox",
			it = "Ominous Lockbox",
			pt = "Ominous Lockbox",
			ru = "Ominous Lockbox",
			ko = "Ominous Lockbox",
			cn = "Ominous Lockbox",
			tw = "Ominous Lockbox",
		},
	},
	[547829] = {
		readable = "Golden Sunleaf",
		text = {
			en = "Golden Sunleaf",
			es = "Golden Sunleaf",
			mx = "Golden Sunleaf",
			de = "Golden Sunleaf",
			fr = "Golden Sunleaf",
			it = "Golden Sunleaf",
			pt = "Golden Sunleaf",
			ru = "Golden Sunleaf",
			ko = "Golden Sunleaf",
			cn = "Golden Sunleaf",
			tw = "Golden Sunleaf",
		},
	},
	[548731] = {
		readable = "Stolen Provisions",
		text = {
			en = "Stolen Provisions",
			es = "Stolen Provisions",
			mx = "Stolen Provisions",
			de = "Stolen Provisions",
			fr = "Stolen Provisions",
			it = "Stolen Provisions",
			pt = "Stolen Provisions",
			ru = "Stolen Provisions",
			ko = "Stolen Provisions",
			cn = "Stolen Provisions",
			tw = "Stolen Provisions",
		},
	},
	[554628] = {
		readable = "Forgotten Staff",
		text = {
			en = "Forgotten Staff",
			es = "Forgotten Staff",
			mx = "Forgotten Staff",
			de = "Forgotten Staff",
			fr = "Forgotten Staff",
			it = "Forgotten Staff",
			pt = "Forgotten Staff",
			ru = "Forgotten Staff",
			ko = "Forgotten Staff",
			cn = "Forgotten Staff",
			tw = "Forgotten Staff",
		},
	},
	[555178] = {
		readable = "Artisan's Cache",
		text = {
			en = "Artisan's Cache",
			es = "Artisan's Cache",
			mx = "Artisan's Cache",
			de = "Artisan's Cache",
			fr = "Artisan's Cache",
			it = "Artisan's Cache",
			pt = "Artisan's Cache",
			ru = "Artisan's Cache",
			ko = "Artisan's Cache",
			cn = "Artisan's Cache",
			tw = "Artisan's Cache",
		},
	},
	[555351] = {
		readable = "Burbling Paint Pot",
		text = {
			en = "Burbling Paint Pot",
			es = "Burbling Paint Pot",
			mx = "Burbling Paint Pot",
			de = "Burbling Paint Pot",
			fr = "Burbling Paint Pot",
			it = "Burbling Paint Pot",
			pt = "Burbling Paint Pot",
			ru = "Burbling Paint Pot",
			ko = "Burbling Paint Pot",
			cn = "Burbling Paint Pot",
			tw = "Burbling Paint Pot",
		},
	},
	[555381] = {
		readable = "Sinara Vine",
		model = 3855392,
		text = {
			en = "Sinara Vine",
			es = "Sinara Vine",
			mx = "Sinara Vine",
			de = "Sinara Vine",
			fr = "Sinara Vine",
			it = "Sinara Vine",
			pt = "Sinara Vine",
			ru = "Sinara Vine",
			ko = "Sinara Vine",
			cn = "Sinara Vine",
			tw = "Sinara Vine",
		},
	},
	[555383] = {
		readable = "Belanise Cluster",
		text = {
			en = "Belanise Cluster",
			es = "Belanise Cluster",
			mx = "Belanise Cluster",
			de = "Belanise Cluster",
			fr = "Belanise Cluster",
			it = "Belanise Cluster",
			pt = "Belanise Cluster",
			ru = "Belanise Cluster",
			ko = "Belanise Cluster",
			cn = "Belanise Cluster",
			tw = "Belanise Cluster",
		},
	},
	[555462] = {
		readable = "Forgotten Amani Cache",
		text = {
			en = "Forgotten Amani Cache",
			es = "Forgotten Amani Cache",
			mx = "Forgotten Amani Cache",
			de = "Forgotten Amani Cache",
			fr = "Forgotten Amani Cache",
			it = "Forgotten Amani Cache",
			pt = "Forgotten Amani Cache",
			ru = "Forgotten Amani Cache",
			ko = "Forgotten Amani Cache",
			cn = "Forgotten Amani Cache",
			tw = "Forgotten Amani Cache",
		},
	},
	[555830] = {
		readable = "Index of Ranger Corps Recipes vol. VII",
		text = {
			en = "Index of Ranger Corps Recipes vol. VII",
			es = "Index of Ranger Corps Recipes vol. VII",
			mx = "Index of Ranger Corps Recipes vol. VII",
			de = "Index of Ranger Corps Recipes vol. VII",
			fr = "Index of Ranger Corps Recipes vol. VII",
			it = "Index of Ranger Corps Recipes vol. VII",
			pt = "Index of Ranger Corps Recipes vol. VII",
			ru = "Index of Ranger Corps Recipes vol. VII",
			ko = "Index of Ranger Corps Recipes vol. VII",
			cn = "Index of Ranger Corps Recipes vol. VII",
			tw = "Index of Ranger Corps Recipes vol. VII",
		},
	},
	[555832] = {
		readable = "Songs for the Silver Streams",
		text = {
			en = "Songs for the Silver Streams",
			es = "Songs for the Silver Streams",
			mx = "Songs for the Silver Streams",
			de = "Songs for the Silver Streams",
			fr = "Songs for the Silver Streams",
			it = "Songs for the Silver Streams",
			pt = "Songs for the Silver Streams",
			ru = "Songs for the Silver Streams",
			ko = "Songs for the Silver Streams",
			cn = "Songs for the Silver Streams",
			tw = "Songs for the Silver Streams",
		},
	},
	[556758] = {
		readable = "Intercepted Shipment",
		text = {
			en = "Intercepted Shipment",
			es = "Intercepted Shipment",
			mx = "Intercepted Shipment",
			de = "Intercepted Shipment",
			fr = "Intercepted Shipment",
			it = "Intercepted Shipment",
			pt = "Intercepted Shipment",
			ru = "Intercepted Shipment",
			ko = "Intercepted Shipment",
			cn = "Intercepted Shipment",
			tw = "Intercepted Shipment",
		},
	},
	[556759] = {
		readable = "Intercepted Shipment",
		text = {
			en = "Intercepted Shipment",
			es = "Intercepted Shipment",
			mx = "Intercepted Shipment",
			de = "Intercepted Shipment",
			fr = "Intercepted Shipment",
			it = "Intercepted Shipment",
			pt = "Intercepted Shipment",
			ru = "Intercepted Shipment",
			ko = "Intercepted Shipment",
			cn = "Intercepted Shipment",
			tw = "Intercepted Shipment",
		},
	},
	[556760] = {
		readable = "Intercepted Shipment",
		text = {
			en = "Intercepted Shipment",
			es = "Intercepted Shipment",
			mx = "Intercepted Shipment",
			de = "Intercepted Shipment",
			fr = "Intercepted Shipment",
			it = "Intercepted Shipment",
			pt = "Intercepted Shipment",
			ru = "Intercepted Shipment",
			ko = "Intercepted Shipment",
			cn = "Intercepted Shipment",
			tw = "Intercepted Shipment",
		},
	},
	[556761] = {
		readable = "Intercepted Shipment",
		text = {
			en = "Intercepted Shipment",
			es = "Intercepted Shipment",
			mx = "Intercepted Shipment",
			de = "Intercepted Shipment",
			fr = "Intercepted Shipment",
			it = "Intercepted Shipment",
			pt = "Intercepted Shipment",
			ru = "Intercepted Shipment",
			ko = "Intercepted Shipment",
			cn = "Intercepted Shipment",
			tw = "Intercepted Shipment",
		},
	},
	[556762] = {
		readable = "Intercepted Shipment",
		text = {
			en = "Intercepted Shipment",
			es = "Intercepted Shipment",
			mx = "Intercepted Shipment",
			de = "Intercepted Shipment",
			fr = "Intercepted Shipment",
			it = "Intercepted Shipment",
			pt = "Intercepted Shipment",
			ru = "Intercepted Shipment",
			ko = "Intercepted Shipment",
			cn = "Intercepted Shipment",
			tw = "Intercepted Shipment",
		},
	},
	[566101] = {
		readable = "Unlocked Strongbox",
		text = {
			en = "Unlocked Strongbox",
			es = "Unlocked Strongbox",
			mx = "Unlocked Strongbox",
			de = "Unlocked Strongbox",
			fr = "Unlocked Strongbox",
			it = "Unlocked Strongbox",
			pt = "Unlocked Strongbox",
			ru = "Unlocked Strongbox",
			ko = "Unlocked Strongbox",
			cn = "Unlocked Strongbox",
			tw = "Unlocked Strongbox",
		},
	},
	[568254] = {
		readable = "Scattered Supplies",
		text = {
			en = "Scattered Supplies",
			es = "Scattered Supplies",
			mx = "Scattered Supplies",
			de = "Scattered Supplies",
			fr = "Scattered Supplies",
			it = "Scattered Supplies",
			pt = "Scattered Supplies",
			ru = "Scattered Supplies",
			ko = "Scattered Supplies",
			cn = "Scattered Supplies",
			tw = "Scattered Supplies",
		},
	},
	[568332] = {
		readable = "Blooming Graveblossom",
		text = {
			en = "Blooming Graveblossom",
			es = "Blooming Graveblossom",
			mx = "Blooming Graveblossom",
			de = "Blooming Graveblossom",
			fr = "Blooming Graveblossom",
			it = "Blooming Graveblossom",
			pt = "Blooming Graveblossom",
			ru = "Blooming Graveblossom",
			ko = "Blooming Graveblossom",
			cn = "Blooming Graveblossom",
			tw = "Blooming Graveblossom",
		},
	},
	[568439] = {
		readable = "Mysterious Bloom",
		model = 1728502,
		text = {
			en = "Mysterious Bloom",
			es = "Mysterious Bloom",
			mx = "Mysterious Bloom",
			de = "Mysterious Bloom",
			fr = "Mysterious Bloom",
			it = "Mysterious Bloom",
			pt = "Mysterious Bloom",
			ru = "Mysterious Bloom",
			ko = "Mysterious Bloom",
			cn = "Mysterious Bloom",
			tw = "Mysterious Bloom",
		},
	},
	[568505] = {
		readable = "Mysterious Bloom",
		model = 1728502,
		text = {
			en = "Mysterious Bloom",
			es = "Mysterious Bloom",
			mx = "Mysterious Bloom",
			de = "Mysterious Bloom",
			fr = "Mysterious Bloom",
			it = "Mysterious Bloom",
			pt = "Mysterious Bloom",
			ru = "Mysterious Bloom",
			ko = "Mysterious Bloom",
			cn = "Mysterious Bloom",
			tw = "Mysterious Bloom",
		},
	},
	[568515] = {
		readable = "Mysterious Bloom",
		model = 1728502,
		text = {
			en = "Mysterious Bloom",
			es = "Mysterious Bloom",
			mx = "Mysterious Bloom",
			de = "Mysterious Bloom",
			fr = "Mysterious Bloom",
			it = "Mysterious Bloom",
			pt = "Mysterious Bloom",
			ru = "Mysterious Bloom",
			ko = "Mysterious Bloom",
			cn = "Mysterious Bloom",
			tw = "Mysterious Bloom",
		},
	},
	[571099] = {
		readable = "Glowing Moth",
		text = {
			en = "Glowing Moth",
			es = "Glowing Moth",
			mx = "Glowing Moth",
			de = "Glowing Moth",
			fr = "Glowing Moth",
			it = "Glowing Moth",
			pt = "Glowing Moth",
			ru = "Glowing Moth",
			ko = "Glowing Moth",
			cn = "Glowing Moth",
			tw = "Glowing Moth",
		},
	},
	[571121] = {
		readable = "Glowing Moth",
		text = {
			en = "Glowing Moth",
			es = "Glowing Moth",
			mx = "Glowing Moth",
			de = "Glowing Moth",
			fr = "Glowing Moth",
			it = "Glowing Moth",
			pt = "Glowing Moth",
			ru = "Glowing Moth",
			ko = "Glowing Moth",
			cn = "Glowing Moth",
			tw = "Glowing Moth",
		},
	},
	[571130] = {
		readable = "Glowing Moth",
		text = {
			en = "Glowing Moth",
			es = "Glowing Moth",
			mx = "Glowing Moth",
			de = "Glowing Moth",
			fr = "Glowing Moth",
			it = "Glowing Moth",
			pt = "Glowing Moth",
			ru = "Glowing Moth",
			ko = "Glowing Moth",
			cn = "Glowing Moth",
			tw = "Glowing Moth",
		},
	},
	[571138] = {
		readable = "Glowing Moth",
		text = {
			en = "Glowing Moth",
			es = "Glowing Moth",
			mx = "Glowing Moth",
			de = "Glowing Moth",
			fr = "Glowing Moth",
			it = "Glowing Moth",
			pt = "Glowing Moth",
			ru = "Glowing Moth",
			ko = "Glowing Moth",
			cn = "Glowing Moth",
			tw = "Glowing Moth",
		},
	},
	[571139] = {
		readable = "Glowing Moth",
		text = {
			en = "Glowing Moth",
			es = "Glowing Moth",
			mx = "Glowing Moth",
			de = "Glowing Moth",
			fr = "Glowing Moth",
			it = "Glowing Moth",
			pt = "Glowing Moth",
			ru = "Glowing Moth",
			ko = "Glowing Moth",
			cn = "Glowing Moth",
			tw = "Glowing Moth",
		},
	},
	[571141] = {
		readable = "Glowing Moth",
		text = {
			en = "Glowing Moth",
			es = "Glowing Moth",
			mx = "Glowing Moth",
			de = "Glowing Moth",
			fr = "Glowing Moth",
			it = "Glowing Moth",
			pt = "Glowing Moth",
			ru = "Glowing Moth",
			ko = "Glowing Moth",
			cn = "Glowing Moth",
			tw = "Glowing Moth",
		},
	},
	[571146] = {
		readable = "Glowing Moth",
		text = {
			en = "Glowing Moth",
			es = "Glowing Moth",
			mx = "Glowing Moth",
			de = "Glowing Moth",
			fr = "Glowing Moth",
			it = "Glowing Moth",
			pt = "Glowing Moth",
			ru = "Glowing Moth",
			ko = "Glowing Moth",
			cn = "Glowing Moth",
			tw = "Glowing Moth",
		},
	},
	[571147] = {
		readable = "Glowing Moth",
		text = {
			en = "Glowing Moth",
			es = "Glowing Moth",
			mx = "Glowing Moth",
			de = "Glowing Moth",
			fr = "Glowing Moth",
			it = "Glowing Moth",
			pt = "Glowing Moth",
			ru = "Glowing Moth",
			ko = "Glowing Moth",
			cn = "Glowing Moth",
			tw = "Glowing Moth",
		},
	},
	[571148] = {
		readable = "Glowing Moth",
		text = {
			en = "Glowing Moth",
			es = "Glowing Moth",
			mx = "Glowing Moth",
			de = "Glowing Moth",
			fr = "Glowing Moth",
			it = "Glowing Moth",
			pt = "Glowing Moth",
			ru = "Glowing Moth",
			ko = "Glowing Moth",
			cn = "Glowing Moth",
			tw = "Glowing Moth",
		},
	},
	[571157] = {
		readable = "Glowing Moth",
		text = {
			en = "Glowing Moth",
			es = "Glowing Moth",
			mx = "Glowing Moth",
			de = "Glowing Moth",
			fr = "Glowing Moth",
			it = "Glowing Moth",
			pt = "Glowing Moth",
			ru = "Glowing Moth",
			ko = "Glowing Moth",
			cn = "Glowing Moth",
			tw = "Glowing Moth",
		},
	},
	[571493] = {
		readable = "Inky Black Potion",
		model = 243479,
		text = {
			en = "Inky Black Potion",
			es = "Inky Black Potion",
			mx = "Inky Black Potion",
			de = "Inky Black Potion",
			fr = "Inky Black Potion",
			it = "Inky Black Potion",
			pt = "Inky Black Potion",
			ru = "Inky Black Potion",
			ko = "Inky Black Potion",
			cn = "Inky Black Potion",
			tw = "Inky Black Potion",
		},
	},
	[571494] = {
		readable = "Giant Growth Potion",
		model = 3036713,
		text = {
			en = "Giant Growth Potion",
			es = "Giant Growth Potion",
			mx = "Giant Growth Potion",
			de = "Giant Growth Potion",
			fr = "Giant Growth Potion",
			it = "Giant Growth Potion",
			pt = "Giant Growth Potion",
			ru = "Giant Growth Potion",
			ko = "Giant Growth Potion",
			cn = "Giant Growth Potion",
			tw = "Giant Growth Potion",
		},
	},
	[571495] = {
		readable = "Savory Deviate Delight",
		model = 1091574,
		text = {
			en = "Savory Deviate Delight",
			es = "Savory Deviate Delight",
			mx = "Savory Deviate Delight",
			de = "Savory Deviate Delight",
			fr = "Savory Deviate Delight",
			it = "Savory Deviate Delight",
			pt = "Savory Deviate Delight",
			ru = "Savory Deviate Delight",
			ko = "Savory Deviate Delight",
			cn = "Savory Deviate Delight",
			tw = "Savory Deviate Delight",
		},
	},
	[571496] = {
		readable = "Pygmy Oil",
		model = 775408,
		text = {
			en = "Pygmy Oil",
			es = "Pygmy Oil",
			mx = "Pygmy Oil",
			de = "Pygmy Oil",
			fr = "Pygmy Oil",
			it = "Pygmy Oil",
			pt = "Pygmy Oil",
			ru = "Pygmy Oil",
			ko = "Pygmy Oil",
			cn = "Pygmy Oil",
			tw = "Pygmy Oil",
		},
	},
	[571497] = {
		readable = "Reflecting Prism",
		model = 1572190,
		text = {
			en = "Reflecting Prism",
			es = "Reflecting Prism",
			mx = "Reflecting Prism",
			de = "Reflecting Prism",
			fr = "Reflecting Prism",
			it = "Reflecting Prism",
			pt = "Reflecting Prism",
			ru = "Reflecting Prism",
			ko = "Reflecting Prism",
			cn = "Reflecting Prism",
			tw = "Reflecting Prism",
		},
	},
	[571554] = {
		readable = "Giant Growth Potion",
		model = 3036713,
		text = {
			en = "Giant Growth Potion",
			es = "Giant Growth Potion",
			mx = "Giant Growth Potion",
			de = "Giant Growth Potion",
			fr = "Giant Growth Potion",
			it = "Giant Growth Potion",
			pt = "Giant Growth Potion",
			ru = "Giant Growth Potion",
			ko = "Giant Growth Potion",
			cn = "Giant Growth Potion",
			tw = "Giant Growth Potion",
		},
	},
	[571555] = {
		readable = "Giant Growth Potion",
		model = 3036713,
		text = {
			en = "Giant Growth Potion",
			es = "Giant Growth Potion",
			mx = "Giant Growth Potion",
			de = "Giant Growth Potion",
			fr = "Giant Growth Potion",
			it = "Giant Growth Potion",
			pt = "Giant Growth Potion",
			ru = "Giant Growth Potion",
			ko = "Giant Growth Potion",
			cn = "Giant Growth Potion",
			tw = "Giant Growth Potion",
		},
	},
	[571556] = {
		readable = "Inky Black Potion",
		model = 243479,
		text = {
			en = "Inky Black Potion",
			es = "Inky Black Potion",
			mx = "Inky Black Potion",
			de = "Inky Black Potion",
			fr = "Inky Black Potion",
			it = "Inky Black Potion",
			pt = "Inky Black Potion",
			ru = "Inky Black Potion",
			ko = "Inky Black Potion",
			cn = "Inky Black Potion",
			tw = "Inky Black Potion",
		},
	},
	[571557] = {
		readable = "Inky Black Potion",
		model = 243479,
		text = {
			en = "Inky Black Potion",
			es = "Inky Black Potion",
			mx = "Inky Black Potion",
			de = "Inky Black Potion",
			fr = "Inky Black Potion",
			it = "Inky Black Potion",
			pt = "Inky Black Potion",
			ru = "Inky Black Potion",
			ko = "Inky Black Potion",
			cn = "Inky Black Potion",
			tw = "Inky Black Potion",
		},
	},
	[571558] = {
		readable = "Pygmy Oil",
		model = 775408,
		text = {
			en = "Pygmy Oil",
			es = "Pygmy Oil",
			mx = "Pygmy Oil",
			de = "Pygmy Oil",
			fr = "Pygmy Oil",
			it = "Pygmy Oil",
			pt = "Pygmy Oil",
			ru = "Pygmy Oil",
			ko = "Pygmy Oil",
			cn = "Pygmy Oil",
			tw = "Pygmy Oil",
		},
	},
	[571559] = {
		readable = "Pygmy Oil",
		model = 775408,
		text = {
			en = "Pygmy Oil",
			es = "Pygmy Oil",
			mx = "Pygmy Oil",
			de = "Pygmy Oil",
			fr = "Pygmy Oil",
			it = "Pygmy Oil",
			pt = "Pygmy Oil",
			ru = "Pygmy Oil",
			ko = "Pygmy Oil",
			cn = "Pygmy Oil",
			tw = "Pygmy Oil",
		},
	},
	[571560] = {
		readable = "Reflecting Prism",
		model = 1572190,
		text = {
			en = "Reflecting Prism",
			es = "Reflecting Prism",
			mx = "Reflecting Prism",
			de = "Reflecting Prism",
			fr = "Reflecting Prism",
			it = "Reflecting Prism",
			pt = "Reflecting Prism",
			ru = "Reflecting Prism",
			ko = "Reflecting Prism",
			cn = "Reflecting Prism",
			tw = "Reflecting Prism",
		},
	},
	[571561] = {
		readable = "Reflecting Prism",
		model = 1572190,
		text = {
			en = "Reflecting Prism",
			es = "Reflecting Prism",
			mx = "Reflecting Prism",
			de = "Reflecting Prism",
			fr = "Reflecting Prism",
			it = "Reflecting Prism",
			pt = "Reflecting Prism",
			ru = "Reflecting Prism",
			ko = "Reflecting Prism",
			cn = "Reflecting Prism",
			tw = "Reflecting Prism",
		},
	},
	[571562] = {
		readable = "Savory Deviate Delight",
		model = 1091574,
		text = {
			en = "Savory Deviate Delight",
			es = "Savory Deviate Delight",
			mx = "Savory Deviate Delight",
			de = "Savory Deviate Delight",
			fr = "Savory Deviate Delight",
			it = "Savory Deviate Delight",
			pt = "Savory Deviate Delight",
			ru = "Savory Deviate Delight",
			ko = "Savory Deviate Delight",
			cn = "Savory Deviate Delight",
			tw = "Savory Deviate Delight",
		},
	},
	[571563] = {
		readable = "Savory Deviate Delight",
		model = 1091574,
		text = {
			en = "Savory Deviate Delight",
			es = "Savory Deviate Delight",
			mx = "Savory Deviate Delight",
			de = "Savory Deviate Delight",
			fr = "Savory Deviate Delight",
			it = "Savory Deviate Delight",
			pt = "Savory Deviate Delight",
			ru = "Savory Deviate Delight",
			ko = "Savory Deviate Delight",
			cn = "Savory Deviate Delight",
			tw = "Savory Deviate Delight",
		},
	},
	[572498] = {
		readable = "Lost Amani Trinket",
		text = {
			en = "Lost Amani Trinket",
			es = "Lost Amani Trinket",
			mx = "Lost Amani Trinket",
			de = "Lost Amani Trinket",
			fr = "Lost Amani Trinket",
			it = "Lost Amani Trinket",
			pt = "Lost Amani Trinket",
			ru = "Lost Amani Trinket",
			ko = "Lost Amani Trinket",
			cn = "Lost Amani Trinket",
			tw = "Lost Amani Trinket",
		},
	},
	[572806] = {
		readable = "Fragment of Revelation",
		text = {
			en = "Fragment of Revelation",
			es = "Fragment of Revelation",
			mx = "Fragment of Revelation",
			de = "Fragment of Revelation",
			fr = "Fragment of Revelation",
			it = "Fragment of Revelation",
			pt = "Fragment of Revelation",
			ru = "Fragment of Revelation",
			ko = "Fragment of Revelation",
			cn = "Fragment of Revelation",
			tw = "Fragment of Revelation",
		},
	},
	[573307] = {
		readable = "Kemet's Simmering Cauldron",
		text = {
			en = "Kemet's Simmering Cauldron",
			es = "Kemet's Simmering Cauldron",
			mx = "Kemet's Simmering Cauldron",
			de = "Kemet's Simmering Cauldron",
			fr = "Kemet's Simmering Cauldron",
			it = "Kemet's Simmering Cauldron",
			pt = "Kemet's Simmering Cauldron",
			ru = "Kemet's Simmering Cauldron",
			ko = "Kemet's Simmering Cauldron",
			cn = "Kemet's Simmering Cauldron",
			tw = "Kemet's Simmering Cauldron",
		},
	},
	[577796] = {
		readable = "Artisan's Cache",
		text = {
			en = "Artisan's Cache",
			es = "Artisan's Cache",
			mx = "Artisan's Cache",
			de = "Artisan's Cache",
			fr = "Artisan's Cache",
			it = "Artisan's Cache",
			pt = "Artisan's Cache",
			ru = "Artisan's Cache",
			ko = "Artisan's Cache",
			cn = "Artisan's Cache",
			tw = "Artisan's Cache",
		},
	},
	[577797] = {
		readable = "Artisan's Cache",
		text = {
			en = "Artisan's Cache",
			es = "Artisan's Cache",
			mx = "Artisan's Cache",
			de = "Artisan's Cache",
			fr = "Artisan's Cache",
			it = "Artisan's Cache",
			pt = "Artisan's Cache",
			ru = "Artisan's Cache",
			ko = "Artisan's Cache",
			cn = "Artisan's Cache",
			tw = "Artisan's Cache",
		},
	},
	[577798] = {
		readable = "Artisan's Cache",
		text = {
			en = "Artisan's Cache",
			es = "Artisan's Cache",
			mx = "Artisan's Cache",
			de = "Artisan's Cache",
			fr = "Artisan's Cache",
			it = "Artisan's Cache",
			pt = "Artisan's Cache",
			ru = "Artisan's Cache",
			ko = "Artisan's Cache",
			cn = "Artisan's Cache",
			tw = "Artisan's Cache",
		},
	},
	[577800] = {
		readable = "Artisan's Cache",
		text = {
			en = "Artisan's Cache",
			es = "Artisan's Cache",
			mx = "Artisan's Cache",
			de = "Artisan's Cache",
			fr = "Artisan's Cache",
			it = "Artisan's Cache",
			pt = "Artisan's Cache",
			ru = "Artisan's Cache",
			ko = "Artisan's Cache",
			cn = "Artisan's Cache",
			tw = "Artisan's Cache",
		},
	},
	[577805] = {
		readable = "Strange Seed",
		text = {
			en = "Strange Seed",
			es = "Strange Seed",
			mx = "Strange Seed",
			de = "Strange Seed",
			fr = "Strange Seed",
			it = "Strange Seed",
			pt = "Strange Seed",
			ru = "Strange Seed",
			ko = "Strange Seed",
			cn = "Strange Seed",
			tw = "Strange Seed",
		},
	},
	[582179] = {
		readable = "Twilight Ordinance",
		text = {
			en = "Twilight Ordinance",
			es = "Twilight Ordinance",
			mx = "Twilight Ordinance",
			de = "Twilight Ordinance",
			fr = "Twilight Ordinance",
			it = "Twilight Ordinance",
			pt = "Twilight Ordinance",
			ru = "Twilight Ordinance",
			ko = "Twilight Ordinance",
			cn = "Twilight Ordinance",
			tw = "Twilight Ordinance",
		},
	},
	[584793] = {
		readable = "Ritual Supplies",
		text = {
			en = "Ritual Supplies",
			es = "Ritual Supplies",
			mx = "Ritual Supplies",
			de = "Ritual Supplies",
			fr = "Ritual Supplies",
			it = "Ritual Supplies",
			pt = "Ritual Supplies",
			ru = "Ritual Supplies",
			ko = "Ritual Supplies",
			cn = "Ritual Supplies",
			tw = "Ritual Supplies",
		},
	},
	[587574] = {
		readable = "Ani's Feathered Totem",
		text = {
			en = "Ani's Feathered Totem",
			es = "Ani's Feathered Totem",
			mx = "Ani's Feathered Totem",
			de = "Ani's Feathered Totem",
			fr = "Ani's Feathered Totem",
			it = "Ani's Feathered Totem",
			pt = "Ani's Feathered Totem",
			ru = "Ani's Feathered Totem",
			ko = "Ani's Feathered Totem",
			cn = "Ani's Feathered Totem",
			tw = "Ani's Feathered Totem",
		},
	},
	[587576] = {
		readable = "Ani's Scented Strobilus",
		text = {
			en = "Ani's Scented Strobilus",
			es = "Ani's Scented Strobilus",
			mx = "Ani's Scented Strobilus",
			de = "Ani's Scented Strobilus",
			fr = "Ani's Scented Strobilus",
			it = "Ani's Scented Strobilus",
			pt = "Ani's Scented Strobilus",
			ru = "Ani's Scented Strobilus",
			ko = "Ani's Scented Strobilus",
			cn = "Ani's Scented Strobilus",
			tw = "Ani's Scented Strobilus",
		},
	},
	[587577] = {
		readable = "Ani's Carved Effigy",
		text = {
			en = "Ani's Carved Effigy",
			es = "Ani's Carved Effigy",
			mx = "Ani's Carved Effigy",
			de = "Ani's Carved Effigy",
			fr = "Ani's Carved Effigy",
			it = "Ani's Carved Effigy",
			pt = "Ani's Carved Effigy",
			ru = "Ani's Carved Effigy",
			ko = "Ani's Carved Effigy",
			cn = "Ani's Carved Effigy",
			tw = "Ani's Carved Effigy",
		},
	},
	[613267] = {
		readable = "Farstrider's Lost Quiver",
		text = {
			en = "Farstrider's Lost Quiver",
			es = "Farstrider's Lost Quiver",
			mx = "Farstrider's Lost Quiver",
			de = "Farstrider's Lost Quiver",
			fr = "Farstrider's Lost Quiver",
			it = "Farstrider's Lost Quiver",
			pt = "Farstrider's Lost Quiver",
			ru = "Farstrider's Lost Quiver",
			ko = "Farstrider's Lost Quiver",
			cn = "Farstrider's Lost Quiver",
			tw = "Farstrider's Lost Quiver",
		},
	},
	[613887] = {
		readable = "Unfinished Sheet Music",
		model = 4324473,
		text = {
			en = "Unfinished Sheet Music",
			es = "Unfinished Sheet Music",
			mx = "Unfinished Sheet Music",
			de = "Unfinished Sheet Music",
			fr = "Unfinished Sheet Music",
			it = "Unfinished Sheet Music",
			pt = "Unfinished Sheet Music",
			ru = "Unfinished Sheet Music",
			ko = "Unfinished Sheet Music",
			cn = "Unfinished Sheet Music",
			tw = "Unfinished Sheet Music",
		},
	},
})
do ObjectDB[objectID] = objectData; end
