local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[239907] = {
		readable = "Exposed Ley Crystal",
		model = 1108690,
		text = {
			en = "Exposed Ley Crystal",
			es = "[Exposed Ley Crystal]",
			mx = "[Exposed Ley Crystal]",
			de = "[Exposed Ley Crystal]",
			fr = "[Exposed Ley Crystal]",
			it = "[Exposed Ley Crystal]",
			pt = "[Exposed Ley Crystal]",
			ru = "[Exposed Ley Crystal]",
			ko = "[Exposed Ley Crystal]",
			cn = "[Exposed Ley Crystal]",
			tw = "[Exposed Ley Crystal]",
		},
	},
	[241912] = {
		readable = "Exposed Ley Crystal",
		model = 1108688,
		text = {
			en = "Exposed Ley Crystal",
			es = "[Exposed Ley Crystal]",
			mx = "[Exposed Ley Crystal]",
			de = "[Exposed Ley Crystal]",
			fr = "[Exposed Ley Crystal]",
			it = "[Exposed Ley Crystal]",
			pt = "[Exposed Ley Crystal]",
			ru = "[Exposed Ley Crystal]",
			ko = "[Exposed Ley Crystal]",
			cn = "[Exposed Ley Crystal]",
			tw = "[Exposed Ley Crystal]",
		},
	},
	[241913] = {
		readable = "Exposed Ley Crystal",
		model = 1108689,
		text = {
			en = "Exposed Ley Crystal",
			es = "[Exposed Ley Crystal]",
			mx = "[Exposed Ley Crystal]",
			de = "[Exposed Ley Crystal]",
			fr = "[Exposed Ley Crystal]",
			it = "[Exposed Ley Crystal]",
			pt = "[Exposed Ley Crystal]",
			ru = "[Exposed Ley Crystal]",
			ko = "[Exposed Ley Crystal]",
			cn = "[Exposed Ley Crystal]",
			tw = "[Exposed Ley Crystal]",
		},
	},
})
do ObjectDB[objectID] = objectData; end
