local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[503050] = {
		readable = "Complainer Container 9000",
		model = 5900875,
		text = {
			en = "Complainer Container 9000",
			es = "Guardaquejas 9000",
			mx = "Contenedor de quejas 9000",
			de = "Beschwerdebehältnis 9000",
			fr = "Conteneur à râleries 9000",
			it = "Contenitore di Lamentele 9000",
			pt = "Recipiente de Reclamantes 9000",
			ru = "Контейнер для жалобщиков 9000",
			ko = "불평불만 보관함 9000",
			cn = "投诉收容装置9000型",
			tw = "投訴容器9000型",
		},
	},
	[503056] = {
		readable = "Customer Retrival Harpoons",
		model = 6216761,
		text = {
			en = "Customer Retrival Harpoons",
			es = "Arpones de devoluciones a clientes",
			mx = "Arpones de recuperación de clientes",
			de = "Kundenbergungsharpunen",
			fr = "Harpons de récupération de clientèle",
			it = "Arpioni per Recupero Clienti",
			pt = "Arpões de Recuperação de Clientes",
			ru = "Гарпуны для клиентов",
			ko = "고객 회수 작살",
			cn = "客户寻回鱼叉",
			tw = "顧客尋回魚叉",
		},
	},
	[503329] = {
		readable = "Corroded Plaque",
		model = 199987,
		text = {
			en = "Corroded Plaque",
			es = "Placa corroída",
			mx = "Placa corroída",
			de = "Verrostete Plakette",
			fr = "Plaque corrodée",
			it = "Placca Corrosa",
			pt = "Placa Corroída",
			ru = "Проржавевшая таблица",
			ko = "부식된 명판",
			cn = "腐蚀的铭牌",
			tw = "腐蝕名牌",
		},
	},
	[504311] = {
		readable = "Lifeblood Crystal",
		model = 166432,
		text = {
			en = "Lifeblood Crystal",
			es = "Cristal de sangre de vida",
			mx = "Cristal de sangrevida",
			de = "Lebensblutkristall",
			fr = "Cristal sang-de-vie",
			it = "Cristallo di Sangue Vitale",
			pt = "Cristal de Sangue Vital",
			ru = "Кристалл жизненной силы",
			ko = "생명의 피 수정",
			cn = "命源水晶",
			tw = "生命之血水晶",
		},
	},
	[509426] = {
		readable = "Bloodeye Cage",
		model = 318185,
		text = {
			en = "Bloodeye Cage",
			es = "Cajón Ojosangre",
			mx = "Jaula Ojosangre",
			de = "Käfig des Blutaugenklans",
			fr = "Cage œil-sanglant",
			it = "Gabbia degli Occhiotruce",
			pt = "Jaula dos Olhos de Sangue",
			ru = "Клетка клана Кровавого Глаза",
			ko = "붉은눈 우리",
			cn = "血眼牢笼",
			tw = "血眼牢籠",
		},
	},
	[516296] = {
		readable = "Sureki Cage",
		model = 4996096,
		text = {
			en = "Sureki Cage",
			es = "Jaula sureki",
			mx = "Jaula sureki",
			de = "Surekischer Käfig",
			fr = "Cage sureki",
			it = "Gabbia dei Sureki",
			pt = "Jaula Sureki",
			ru = "Клетка суреки",
			ko = "수레키 우리",
			cn = "苏雷吉笼子",
			tw = "蘇芮基籠子",
		},
	},
	[516357] = {
		readable = "Arcane Translocator",
		model = 6024535,
		text = {
			en = "Arcane Translocator",
			es = "Trasladador Arcano",
			mx = "Traslocador arcano",
			de = "Arkantranslokator",
			fr = "Transposeur arcanique",
			it = "Traslocatore Arcano",
			pt = "Translocador Arcano",
			ru = "Чародейский транслокатор",
			ko = "비전 위치변환기",
			cn = "奥术传送器",
			tw = "秘法移位裝置",
		},
	},
	[516358] = {
		readable = "Arcane Translocator",
		model = 6024535,
		text = {
			en = "Arcane Translocator",
			es = "Trasladador Arcano",
			mx = "Traslocador arcano",
			de = "Arkantranslokator",
			fr = "Transposeur arcanique",
			it = "Traslocatore Arcano",
			pt = "Translocador Arcano",
			ru = "Чародейский транслокатор",
			ko = "비전 위치변환기",
			cn = "奥术传送器",
			tw = "秘法移位裝置",
		},
	},
	[516757] = {
		readable = "Voidbane Stash",
		model = 1062118,
		text = {
			en = "Voidbane Stash",
			es = "Alijo terrovacío",
			mx = "Alijo aterravacío",
			de = "Leerenfluchvorrat",
			fr = "Fortune vacuicide",
			it = "Riserva di Malvuoto",
			pt = "Faixa da Perdição do Caos",
			ru = "Тайник проклятия Бездны",
			ko = "공허파멸 은닉함",
			cn = "虚厄贮藏",
			tw = "虛無之禍儲物箱",
		},
	},
	[516836] = {
		readable = "Voidbane Gem",
		model = 1282669,
		text = {
			en = "Voidbane Gem",
			es = "Gema terrovacío",
			mx = "Gema aterravacío",
			de = "Leerenfluchedelstein",
			fr = "Gemme vacuicide",
			it = "Gemma di Malvuoto",
			pt = "Gema da Perdição do Caos",
			ru = "Самоцвет проклятия Бездны",
			ko = "공허파멸 보석",
			cn = "虚厄宝石",
			tw = "虛無之禍寶石",
		},
	},
	[516932] = {
		readable = "Tranquility Bloom",
		model = 7136522,
		text = {
			en = "Tranquility Bloom",
			es = "Flor de tranquilidad",
			mx = "Flor de tranquilidad",
			de = "Harmonieblume",
			fr = "Tranquillette",
			it = "Bocciolo Tranquillo",
			pt = "Floração da Tranquilidade",
			ru = "Тихоцвет",
			ko = "평온의 꽃송이",
			cn = "宁心花",
		},
	},
})
do ObjectDB[objectID] = objectData; end
