local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[495091] = {
		readable = "Improvised Explosive",
		model = 985356,
		text = {
			en = "Improvised Explosive",
			es = "Explosivo improvisado",
			mx = "Explosivo improvisado",
			de = "Behelfsmäßiger Sprengstoff",
			fr = "Explosif improvisé",
			it = "Esplosivo Improvvisato",
			pt = "Explosivo Improvisado",
			ru = "Самодельные бомбы",
			ko = "즉석 폭탄",
			cn = "粗制炸药",
			tw = "臨時組裝的炸彈",
		},
	},
	[495148] = {
		readable = "Glyph of Jab",
		model = 521207,
		text = {
			en = "Glyph of Jab",
			es = "Glifo de Atizar",
			mx = "Glifo de golpe rápido",
			de = "Glyphe 'Hieb'",
			fr = "Glyphe de crochet",
			it = "Glifo - Diretto",
			pt = "Glifo de Jabe",
			ru = "Символ оружия тигра",
			ko = "문양: 타",
			cn = "贯日突雕文",
			tw = "刺擊雕紋",
		},
	},
	[500095] = {
		readable = "Powdered De-Pollutant",
		model = 5689834,
		text = {
			en = "Powdered De-Pollutant",
			es = "Descontaminante en polvo",
			mx = "Descontaminante en polvo",
			de = "Pulverisierter Verschmutzungsentferner",
			fr = "Dépolluant en poudre",
			it = "De-Inquinante in Polvere",
			pt = "Despoluidor em Pó",
			ru = "Порошок-антизагрязнитель",
			ko = "가루로 빻은 오염 물질 제거제",
			cn = "粉末去污剂",
			tw = "粉狀去汙物",
		},
	},
	[500714] = {
		readable = "S.C.R.A.P. Heap",
		model = 5689812,
		text = {
			en = "S.C.R.A.P. Heap",
			es = "Montón de C.H.A.T.A.R.R.A.",
			mx = "Montón de C.H.A.T.A.R.R.A.",
			de = "S.C.H.R.O.T.T.-Haufen",
			fr = "Tas de D.E.B.R.I.S.",
			it = "Cumulo di S.C.A.R.T.O.",
			pt = "Pilha de S.U.C.A.T.A.",
			ru = "Гора ХЛАМа",
			ko = "폐.품.단 더미",
			cn = "S.C.R.A.P.废料堆",
			tw = "S.C.R.A.P.垃圾場",
		},
	},
	[500715] = {
		readable = "S.C.R.A.P. Heap",
		model = 5689812,
		text = {
			en = "S.C.R.A.P. Heap",
			es = "Montón de C.H.A.T.A.R.R.A.",
			mx = "Montón de C.H.A.T.A.R.R.A.",
			de = "S.C.H.R.O.T.T.-Haufen",
			fr = "Tas de D.E.B.R.I.S.",
			it = "Cumulo di S.C.A.R.T.O.",
			pt = "Pilha de S.U.C.A.T.A.",
			ru = "Гора ХЛАМа",
			ko = "폐.품.단 더미",
			cn = "S.C.R.A.P.废料堆",
			tw = "S.C.R.A.P.垃圾場",
		},
	},
	[500716] = {
		readable = "S.C.R.A.P. Heap",
		model = 5689812,
		text = {
			en = "S.C.R.A.P. Heap",
			es = "Montón de C.H.A.T.A.R.R.A.",
			mx = "Montón de C.H.A.T.A.R.R.A.",
			de = "S.C.H.R.O.T.T.-Haufen",
			fr = "Tas de D.E.B.R.I.S.",
			it = "Cumulo di S.C.A.R.T.O.",
			pt = "Pilha de S.U.C.A.T.A.",
			ru = "Гора ХЛАМа",
			ko = "폐.품.단 더미",
			cn = "S.C.R.A.P.废料堆",
			tw = "S.C.R.A.P.垃圾場",
		},
	},
	[500717] = {
		readable = "S.C.R.A.P. Heap",
		model = 5689812,
		text = {
			en = "S.C.R.A.P. Heap",
			es = "Montón de C.H.A.T.A.R.R.A.",
			mx = "Montón de C.H.A.T.A.R.R.A.",
			de = "S.C.H.R.O.T.T.-Haufen",
			fr = "Tas de D.E.B.R.I.S.",
			it = "Cumulo di S.C.A.R.T.O.",
			pt = "Pilha de S.U.C.A.T.A.",
			ru = "Гора ХЛАМа",
			ko = "폐.품.단 더미",
			cn = "S.C.R.A.P.废料堆",
			tw = "S.C.R.A.P.垃圾場",
		},
	},
	[500718] = {
		readable = "S.C.R.A.P. Heap",
		model = 5689812,
		text = {
			en = "S.C.R.A.P. Heap",
			es = "Montón de C.H.A.T.A.R.R.A.",
			mx = "Montón de C.H.A.T.A.R.R.A.",
			de = "S.C.H.R.O.T.T.-Haufen",
			fr = "Tas de D.E.B.R.I.S.",
			it = "Cumulo di S.C.A.R.T.O.",
			pt = "Pilha de S.U.C.A.T.A.",
			ru = "Гора ХЛАМа",
			ko = "폐.품.단 더미",
			cn = "S.C.R.A.P.废料堆",
			tw = "S.C.R.A.P.垃圾場",
		},
	},
	[500719] = {
		readable = "S.C.R.A.P. Heap",
		model = 5689812,
		text = {
			en = "S.C.R.A.P. Heap",
			es = "Montón de C.H.A.T.A.R.R.A.",
			mx = "Montón de C.H.A.T.A.R.R.A.",
			de = "S.C.H.R.O.T.T.-Haufen",
			fr = "Tas de D.E.B.R.I.S.",
			it = "Cumulo di S.C.A.R.T.O.",
			pt = "Pilha de S.U.C.A.T.A.",
			ru = "Гора ХЛАМа",
			ko = "폐.품.단 더미",
			cn = "S.C.R.A.P.废料堆",
			tw = "S.C.R.A.P.垃圾場",
		},
	},
	[500720] = {
		readable = "S.C.R.A.P. Heap",
		model = 5689812,
		text = {
			en = "S.C.R.A.P. Heap",
			es = "Montón de C.H.A.T.A.R.R.A.",
			mx = "Montón de C.H.A.T.A.R.R.A.",
			de = "S.C.H.R.O.T.T.-Haufen",
			fr = "Tas de D.E.B.R.I.S.",
			it = "Cumulo di S.C.A.R.T.O.",
			pt = "Pilha de S.U.C.A.T.A.",
			ru = "Гора ХЛАМа",
			ko = "폐.품.단 더미",
			cn = "S.C.R.A.P.废料堆",
			tw = "S.C.R.A.P.垃圾場",
		},
	},
	[502532] = {
		readable = "Charged Battery",
		model = 2736566,
		text = {
			en = "Charged Battery",
			es = "Batería cargada",
			mx = "Batería cargada",
			de = "Geladene Batterie",
			fr = "Batterie chargée",
			it = "Batteria Carica",
			pt = "Bateria Carregada",
			ru = "Заряженная батарея",
			ko = "충전된 전지",
			cn = "充能的电池",
			tw = "充好電的電池",
		},
	},
	[503044] = {
		readable = "Ultra-Pasteurized Flesh Substitute",
		model = 6048469,
		text = {
			en = "Ultra-Pasteurized Flesh Substitute",
			es = "Sucedáneo de carne ultrapasteurizada",
			mx = "Sustituto de carne ultrapasteurizada",
		},
	},
})
do ObjectDB[objectID] = objectData; end
