local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[525890] = {
		readable = "Thalassian Skinning Knife",
		model = 977082,
		text = {
			en = "Thalassian Skinning Knife",
			es = "Cuchillo de desuello thalassiano",
			mx = "Cuchillo para desollar thalassiano",
			de = "Thalassisches Kürschnermesser",
			fr = "Couteau à dépecer thalassien",
			it = "Coltello da Scuoiatore Thalassiano",
			pt = "Faca de Esfolamento Talassiana",
			ru = "Талассийский нож для снятия шкур",
			ko = "[Thalassian Skinning Knife]",
			cn = "[Thalassian Skinning Knife]",
			tw = "[Thalassian Skinning Knife]",
		},
	},
	[525895] = {
		readable = "Primal Hide",
		model = 3619351,
		text = {
			en = "Primal Hide",
			es = "Pellejo primigenio",
			mx = "Cuero primigenio",
			de = "Urtümlicher Balg",
			fr = "Peau primordiale",
			it = "Pelle Primordiale",
			pt = "Pelego Primevo",
			ru = "Изначальная шкура",
			ko = "[Primal Hide]",
			cn = "原始皮毛",
			tw = "原始獸皮",
		},
	},
	[525896] = {
		readable = "Cadre Skinning Knife",
		model = 977082,
		text = {
			en = "Cadre Skinning Knife",
			es = "Cuchillo de desuello de cuadro",
			mx = "[Cadre Skinning Knife]",
			de = "Kürschnermesser des Kaders",
			fr = "Couteau à dépecer de la cellule",
			it = "Coltello da Scuoiatore Scelto",
			pt = "[Cadre Skinning Knife]",
			ru = "Нож команды шкуродеров",
			ko = "[Cadre Skinning Knife]",
			cn = "[Cadre Skinning Knife]",
			tw = "精銳剝皮小刀",
		},
	},
	[525974] = {
		readable = "A Spade",
		model = 4618738,
		text = {
			en = "A Spade",
			es = "Una pala",
			mx = "[A Spade]",
			de = "Ein Spaten",
			fr = "Bêche",
			it = "[A Spade]",
			pt = "Uma Pá",
			ru = "Лопата",
			ko = "모종삽",
			cn = "铲子",
			tw = "鏟子",
		},
	},
	[531174] = {
		readable = "Fragrant Mushroom",
		model = 5925838,
		text = {
			en = "Fragrant Mushroom",
			es = "Champiñón fragante",
			mx = "[Fragrant Mushroom]",
			de = "Duftpilz",
			fr = "Champignon parfumé",
			it = "Fungo Fragrante",
			pt = "Cogumelo Fragrante",
			ru = "Душистый гриб",
			ko = "[Fragrant Mushroom]",
			cn = "芬芳蘑菇",
			tw = "芳香蘑菇",
		},
	},
	[531479] = {
		readable = "Ranger's Cache",
		model = 6005278,
		text = {
			en = "Ranger's Cache",
			es = "Alijo de forestal",
			mx = "[Ranger's Cache]",
			de = "Vorrat des Waldläufers",
			fr = "Cache de forestier",
			it = "Cassa del Guardaboschi",
			pt = "Tesouro do Patrulheiro",
			ru = "Тайник следопыта",
			ko = "[Ranger's Cache]",
			cn = "[Ranger's Cache]",
			tw = "[Ranger's Cache]",
		},
	},
	[531480] = {
		readable = "Dead Drop",
		model = 6009494,
		text = {
			en = "Dead Drop",
			es = "Ariete destructor",
			mx = "[Dead Drop]",
			de = "Toter Briefkasten",
			fr = "Piquet boîte morte",
			it = "Messaggio Segreto",
			pt = "[Dead Drop]",
			ru = "Проблемный груз",
			ko = "[Dead Drop]",
			cn = "[Dead Drop]",
			tw = "間諜交易",
		},
	},
	[558184] = {
		readable = "Decaying Fighter",
		model = 1869518,
		text = {
			en = "Decaying Fighter",
			es = "Luchador en descomposición",
			mx = "[Decaying Fighter]",
			de = "Verfallender Kämpfer",
			fr = "Combattant putréfié",
			it = "Combattente Decadente",
			pt = "Combatente em Decomposição",
			ru = "Гниющий боец",
			ko = "썩어가는 전투원",
			cn = "[Decaying Fighter]",
			tw = "[Decaying Fighter]",
		},
	},
	[563491] = {
		readable = "Moldy Chunks",
		model = 4238921,
		text = {
			en = "Moldy Chunks",
			es = "Trozos con moho",
			mx = "[Moldy Chunks]",
			de = "Schimmlige Brocken",
			fr = "Moisissure",
			it = "Pezzi Ammuffiti",
			pt = "Torrões de Mofo",
			ru = "Плесневелые куски",
			ko = "곰팡이 핀 덩어리",
			cn = "[Moldy Chunks]",
			tw = "[Moldy Chunks]",
		},
	},
	[571163] = {
		readable = "Glowing Moth",
		model = 124932,
		text = {
			en = "Glowing Moth",
			es = "Polilla resplandeciente",
			mx = "Polilla brillante",
			de = "Leuchtende Motte",
			fr = "Phalène luminescent",
			it = "Falena Luminosa",
			pt = "Mariposa Brilhante",
			ru = "Светящийся мотылек",
			ko = "빛나는 나방",
			cn = "发光的飞蛾",
			tw = "發光蛾",
		},
	},
	[571164] = {
		readable = "Glowing Moth",
		model = 124932,
		text = {
			en = "Glowing Moth",
			es = "Polilla resplandeciente",
			mx = "Polilla brillante",
			de = "Leuchtende Motte",
			fr = "Phalène luminescent",
			it = "Falena Luminosa",
			pt = "Mariposa Brilhante",
			ru = "Светящийся мотылек",
			ko = "빛나는 나방",
			cn = "发光的飞蛾",
			tw = "發光蛾",
		},
	},
})
do ObjectDB[objectID] = objectData; end
