local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[571307] = {
		readable = "Glowing Moth",
		model = 124932,
		text = {
			en = "Glowing Moth",
			es = "Polilla resplandeciente",
			mx = "Polilla brillante",
			de = "Leuchtende Motte",
			fr = "Phalène luminescent",
			it = "Falena Luminosa",
			pt = "Mariposa Brilhante",
			ru = "Светящийся мотылек",
			ko = "빛나는 나방",
			cn = "发光的飞蛾",
			tw = "發光蛾",
		},
	},
	[571315] = {
		readable = "Glowing Moth",
		model = 124932,
		text = {
			en = "Glowing Moth",
			es = "Polilla resplandeciente",
			mx = "Polilla brillante",
			de = "Leuchtende Motte",
			fr = "Phalène luminescent",
			it = "Falena Luminosa",
			pt = "Mariposa Brilhante",
			ru = "Светящийся мотылек",
			ko = "빛나는 나방",
			cn = "发光的飞蛾",
			tw = "發光蛾",
		},
	},
	[571316] = {
		readable = "Glowing Moth",
		model = 124932,
		text = {
			en = "Glowing Moth",
			es = "Polilla resplandeciente",
			mx = "Polilla brillante",
			de = "Leuchtende Motte",
			fr = "Phalène luminescent",
			it = "Falena Luminosa",
			pt = "Mariposa Brilhante",
			ru = "Светящийся мотылек",
			ko = "빛나는 나방",
			cn = "发光的飞蛾",
			tw = "發光蛾",
		},
	},
	[571317] = {
		readable = "Glowing Moth",
		model = 124932,
		text = {
			en = "Glowing Moth",
			es = "Polilla resplandeciente",
			mx = "Polilla brillante",
			de = "Leuchtende Motte",
			fr = "Phalène luminescent",
			it = "Falena Luminosa",
			pt = "Mariposa Brilhante",
			ru = "Светящийся мотылек",
			ko = "빛나는 나방",
			cn = "发光的飞蛾",
			tw = "發光蛾",
		},
	},
	[571318] = {
		readable = "Glowing Moth",
		model = 124932,
		text = {
			en = "Glowing Moth",
			es = "Polilla resplandeciente",
			mx = "Polilla brillante",
			de = "Leuchtende Motte",
			fr = "Phalène luminescent",
			it = "Falena Luminosa",
			pt = "Mariposa Brilhante",
			ru = "Светящийся мотылек",
			ko = "빛나는 나방",
			cn = "发光的飞蛾",
			tw = "發光蛾",
		},
	},
	[571322] = {
		readable = "Glowing Moth",
		model = 124932,
		text = {
			en = "Glowing Moth",
			es = "Polilla resplandeciente",
			mx = "Polilla brillante",
			de = "Leuchtende Motte",
			fr = "Phalène luminescent",
			it = "Falena Luminosa",
			pt = "Mariposa Brilhante",
			ru = "Светящийся мотылек",
			ko = "빛나는 나방",
			cn = "发光的飞蛾",
			tw = "發光蛾",
		},
	},
	[571329] = {
		readable = "Glowing Moth",
		model = 124932,
		text = {
			en = "Glowing Moth",
			es = "Polilla resplandeciente",
			mx = "Polilla brillante",
			de = "Leuchtende Motte",
			fr = "Phalène luminescent",
			it = "Falena Luminosa",
			pt = "Mariposa Brilhante",
			ru = "Светящийся мотылек",
			ko = "빛나는 나방",
			cn = "发光的飞蛾",
			tw = "發光蛾",
		},
	},
	[572029] = {
		readable = "Scarred Spear",
		model = 943686,
		text = {
			en = "Scarred Spear",
			es = "Lanza cicatrícea",
			mx = "[Scarred Spear]",
			de = "Verschrammter Speer",
			fr = "Lance griffée",
			it = "[Scarred Spear]",
			pt = "[Scarred Spear]",
			ru = "Иссеченное копье",
			ko = "[Scarred Spear]",
			cn = "[Scarred Spear]",
			tw = "[Scarred Spear]",
		},
	},
	[572030] = {
		readable = "Ebon Banner",
		model = 194802,
		text = {
			en = "Ebon Banner",
			es = "Estandarte ébano",
			mx = "[Ebon Banner]",
			de = "Schwarzbanner",
			fr = "Bannière d’ébène",
			it = "Stendardo d'Ebano",
			pt = "Estandarte de Ébano",
			ru = "Черное знамя",
			ko = "[Ebon Banner]",
			cn = "[Ebon Banner]",
			tw = "[Ebon Banner]",
		},
	},
	[572032] = {
		readable = "Ancient Zandalari Scroll",
		model = 774267,
		text = {
			en = "Ancient Zandalari Scroll",
			es = "[Ancient Zandalari Scroll]",
			mx = "[Ancient Zandalari Scroll]",
			de = "[Ancient Zandalari Scroll]",
			fr = "[Ancient Zandalari Scroll]",
			it = "[Ancient Zandalari Scroll]",
			pt = "[Ancient Zandalari Scroll]",
			ru = "[Ancient Zandalari Scroll]",
			ko = "[Ancient Zandalari Scroll]",
			cn = "[Ancient Zandalari Scroll]",
			tw = "[Ancient Zandalari Scroll]",
		},
	},
})
do ObjectDB[objectID] = objectData; end
