local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[527833] = {
		readable = "Archeology Chest",
		model = 942843,
		text = {
			en = "Archeology Chest",
			es = "Archeology Chest",
			mx = "Archeology Chest",
			de = "Archeology Chest",
			fr = "Archeology Chest",
			it = "Archeology Chest",
			pt = "Archeology Chest",
			ru = "Archeology Chest",
			ko = "Archeology Chest",
			cn = "Archeology Chest",
			tw = "Archeology Chest",
		},
	},
	[529396] = {
		readable = "Weapon Crate",
		model = 1271629,
		text = {
			en = "Weapon Crate",
			es = "Weapon Crate",
			mx = "Weapon Crate",
			de = "Weapon Crate",
			fr = "Weapon Crate",
			it = "Weapon Crate",
			pt = "Weapon Crate",
			ru = "Weapon Crate",
			ko = "Weapon Crate",
			cn = "Weapon Crate",
			tw = "Weapon Crate",
		},
	},
	[529397] = {
		readable = "Curio Lockbox",
		model = 1341657,
		text = {
			en = "Curio Lockbox",
			es = "Curio Lockbox",
			mx = "Curio Lockbox",
			de = "Curio Lockbox",
			fr = "Curio Lockbox",
			it = "Curio Lockbox",
			pt = "Curio Lockbox",
			ru = "Curio Lockbox",
			ko = "Curio Lockbox",
			cn = "Curio Lockbox",
			tw = "Curio Lockbox",
		},
	},
})
do ObjectDB[objectID] = objectData; end
