local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[571495] = {
		readable = "Savory Deviate Delight",
		model = 1091574,
		text = {
			en = "Savory Deviate Delight",
			es = "Delicia de pez descarriado sabrosa",
			mx = "Delicia de pez descarriado sabrosa",
			de = "Pikantes Deviat Supreme",
			fr = "Délice de déviant",
			it = "Pesce Mutante all'Acquapazza",
			pt = "Delícia de Peixe Anormal",
			ru = "Загадочное острое лакомство",
			ko = "돌연변이 물고기 별미",
			cn = "美味风蛇",
			tw = "美味變異點心",
		},
	},
	[571562] = {
		readable = "Savory Deviate Delight",
		model = 1091574,
		text = {
			en = "Savory Deviate Delight",
			es = "Delicia de pez descarriado sabrosa",
			mx = "Delicia de pez descarriado sabrosa",
			de = "Pikantes Deviat Supreme",
			fr = "Délice de déviant",
			it = "Pesce Mutante all'Acquapazza",
			pt = "Delícia de Peixe Anormal",
			ru = "Загадочное острое лакомство",
			ko = "돌연변이 물고기 별미",
			cn = "美味风蛇",
			tw = "美味變異點心",
		},
	},
	[571563] = {
		readable = "Savory Deviate Delight",
		model = 1091574,
		text = {
			en = "Savory Deviate Delight",
			es = "Delicia de pez descarriado sabrosa",
			mx = "Delicia de pez descarriado sabrosa",
			de = "Pikantes Deviat Supreme",
			fr = "Délice de déviant",
			it = "Pesce Mutante all'Acquapazza",
			pt = "Delícia de Peixe Anormal",
			ru = "Загадочное острое лакомство",
			ko = "돌연변이 물고기 별미",
			cn = "美味风蛇",
			tw = "美味變異點心",
		},
	},
})
do ObjectDB[objectID] = objectData; end
