local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[516935] = {
		readable = "Azeroot",
		model = 6942075,
		text = {
			en = "Azeroot",
			es = "Azerraíz",
			mx = "Azerraíz",
			de = "Azerwurz",
			fr = "Azeracine",
			it = "Azeradice",
			pt = "Raizeroth",
			ru = "Азефит",
			ko = "아제뿌리",
			cn = "艾泽之根",
			tw = "杜根草",
		},
	},
	[517225] = {
		readable = "Timewarped Starlight Rose",
		model = 1357601,
		text = {
			en = "Timewarped Starlight Rose",
			es = "Rosa luz estelar distorsionada por el tiempo",
			mx = "Rosa luz estelar cronodistorsionada",
			de = "Zeitverzerrte Sternlichtrose",
			fr = "Rose lumétoile distordue dans le temps",
			it = "Rosa Lucestellare Fuoritempo",
			pt = "Rosa-da-luz-estelar Transtemporal",
			ru = "Искаженная временем звездная роза",
			ko = "시간왜곡 별빛 장미",
			cn = "时空扭曲星光玫瑰",
			tw = "時光扭曲的星輝玫瑰",
		},
	},
	[517227] = {
		readable = "Timewarped Leystone Deposit",
		model = 1244489,
		text = {
			en = "Timewarped Leystone Deposit",
			es = "Depósito de piedra Ley distorsionada por el tiempo",
			mx = "Depósito de piedra ley cronodistorsionado",
			de = "Zeitverzerrtes Leysteinvorkommen",
			fr = "Gisement de tellurium distordu dans le temps",
			it = "Deposito di Fagliaroccia Fuoritempo",
			pt = "Depósito de Pedra de Meridiano Transtemporal",
			ru = "Искаженные временем залежи силового камня",
			ko = "시간왜곡 지맥석 광맥",
			cn = "时空扭曲魔石矿脉",
			tw = "時光扭曲的脈石礦床",
		},
	},
	[517672] = {
		readable = "Emergency Exit",
		model = 6156070,
		text = {
			en = "Emergency Exit",
			es = "Salida de emergencia",
			mx = "Salida de emergencia",
			de = "Notausstieg",
			fr = "Issue de secours",
			it = "Uscita d'Emergenza",
			pt = "Saída de Emergência",
			ru = "Аварийный выход",
			ko = "긴급 하차",
			cn = "紧急出口",
			tw = "緊急逃生門",
		},
	},
	[522157] = {
		readable = "Bomb Pile",
		model = 254423,
		text = {
			en = "Bomb Pile",
			es = "Pila de bombas",
			mx = "Pila de bombas",
			de = "Bombenhaufen",
			fr = "Pile de bombes",
			it = "Mucchio di Bombe",
			pt = "Pilha de Bombas",
			ru = "Груда бомб",
			ko = "폭탄 더미",
			cn = "一堆炸弹",
			tw = "炸彈堆",
		},
	},
	[523281] = {
		readable = "Refulgent Copper",
		model = 6891162,
		text = {
			en = "Refulgent Copper",
			es = "Cobre refulgente",
			mx = "Cobre refulgente",
			de = "Glänzendes Kupfer",
			fr = "Cuivre éclatant",
			it = "Rame Rifulgente",
			pt = "Cobre Refulgente",
			ru = "Сверкающая медь",
			ko = "광명구리",
			cn = "耀辉铜矿",
			tw = "輝煌銅礦",
		},
	},
	[523283] = {
		readable = "Refulgent Copper Seam",
		model = 6891164,
		text = {
			en = "Refulgent Copper Seam",
			es = "Veta de cobre refulgente",
			mx = "Veta de cobre refulgente",
			de = "Glänzendes Kupferflöz",
			fr = "Veine de cuivre éclatant",
			it = "Vena di Rame Rifulgente",
			pt = "Jazida de Cobre Refulgente",
			ru = "Пласт сверкающей меди",
			ko = "광명구리 융기",
			cn = "耀辉铜矿层",
			tw = "輝煌銅礦層",
		},
	},
	[523286] = {
		readable = "Wild Refulgent Copper",
		model = 6891174,
		text = {
			en = "Wild Refulgent Copper",
			es = "Cobre refulgente salvaje",
			mx = "Cobre refulgente salvaje",
			de = "Wildes glänzendes Kupfer",
			fr = "Cuivre éclatant sauvage",
			it = "Rame Rifulgente Selvaggio",
			pt = "Cobre Refulgente Selvagem",
			ru = "Дикая сверкающая медь",
			ko = "야생 광명구리",
			cn = "狂野耀辉铜矿",
			tw = "狂野輝煌銅礦",
		},
	},
	[523378] = {
		readable = "Portal to Nagrand",
		model = 3540722,
		text = {
			en = "Portal to Nagrand",
			es = "Portal a Nagrand",
			mx = "Portal a Nagrand",
			de = "Portal nach Nagrand",
			fr = "Portail vers Nagrand",
			it = "Portale per Nagrand",
			pt = "Portal para Nagrand",
			ru = "Портал в Награнд",
			ko = "나그란드로 통하는 차원문",
			cn = "通往纳格兰的传送门",
			tw = "納葛蘭傳送門",
		},
	},
	[523409] = {
		readable = "Shiny Trash Can",
		model = 5771149,
		text = {
			en = "Shiny Trash Can",
			es = "Cubo de basura brillante",
			mx = "Bote de basura brillante",
			de = "Glänzende Mülltonne",
			fr = "Poubelle étincelante",
			it = "Pattumiera Luccicante",
			pt = "Lata de Lixo Brilhosa",
			ru = "Блестящая корзина для мусора",
			ko = "빛나는 쓰레기 깡통",
			cn = "闪亮的垃圾桶",
			tw = "亮晶晶的垃圾桶",
		},
	},
	[523516] = {
		readable = "Portal to the Atrium",
		model = 3540722,
		text = {
			en = "Portal to the Atrium",
			es = "Portal al Claustro",
			mx = "Portal al Atrio",
			de = "Portal in das Atrium",
			fr = "Portail vers l’Atrium",
			it = "Portale per l'Atrio",
			pt = "Portal para o Átrio",
		},
	},
})
do ObjectDB[objectID] = objectData; end
