local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[531891] = {
		readable = "Vanguard Scout",
		model = 1593999,
		text = {
			en = "Vanguard Scout",
			es = "[Vanguard Scout]",
			mx = "[Vanguard Scout]",
			de = "[Vanguard Scout]",
			fr = "[Vanguard Scout]",
			it = "[Vanguard Scout]",
			pt = "[Vanguard Scout]",
			ru = "[Vanguard Scout]",
			ko = "[Vanguard Scout]",
			cn = "[Vanguard Scout]",
			tw = "[Vanguard Scout]",
		},
	},
	[587126] = {
		readable = "Training Rod of Polymorph",
		model = 244255,
		text = {
			en = "Training Rod of Polymorph",
			es = "[Training Rod of Polymorph]",
			mx = "[Training Rod of Polymorph]",
			de = "[Training Rod of Polymorph]",
			fr = "[Training Rod of Polymorph]",
			it = "[Training Rod of Polymorph]",
			pt = "[Training Rod of Polymorph]",
			ru = "[Training Rod of Polymorph]",
			ko = "[Training Rod of Polymorph]",
			cn = "[Training Rod of Polymorph]",
			tw = "[Training Rod of Polymorph]",
		},
	},
	[614560] = {
		readable = "Durable Vase",
		model = 6796709,
		text = {
			en = "Durable Vase",
			es = "Jarrón duradero",
			mx = "Jarrón resistente",
			de = "Robuste Vase",
			fr = "Vase durable",
			it = "Vaso Durevole",
			pt = "Vaso Durável",
			ru = "Прочная ваза",
			ko = "튼튼한 꽃병",
			cn = "牢固的花瓶",
			tw = "耐用瓶子",
		},
	},
	[615930] = {
		readable = "Hanging Flask",
		model = 6326908,
		text = {
			en = "Hanging Flask",
			es = "Frasco colgante",
			mx = "Frasco colgante",
			de = "Hängendes Fläschchen",
			fr = "Flacon suspendu",
			it = "Fiasca Appesa",
			pt = "Frasco Pendurado",
			ru = "Подвесная фляга",
			ko = "매달린 영약",
			cn = "悬挂的药剂",
			tw = "掛著的精煉藥劑",
		},
	},
	[615936] = {
		readable = "Dangling Jug",
		model = 6252857,
		text = {
			en = "Dangling Jug",
			es = "Jarra bamboleante",
			mx = "Jarro colgante",
			de = "Baumelnder Krug",
			fr = "Pichet pendant",
			it = "Brocca Penzolante",
			pt = "Jarra Pendente",
			ru = "Висящий кувшин",
			ko = "달랑거리는 단지",
			cn = "垂吊的壶",
			tw = "懸吊的罐子",
		},
	},
	[615939] = {
		readable = "Discarded Bottle",
		model = 6326911,
		text = {
			en = "Discarded Bottle",
			es = "Botella desechada",
			mx = "Botella abandonada",
			de = "Weggeworfene Flasche",
			fr = "Bouteille jetée",
			it = "Bottiglia Abbandonata",
			pt = "Garrafa Descartada",
			ru = "Брошенная бутылка",
			ko = "버려진 병",
			cn = "被丢弃的瓶子",
			tw = "丟棄的瓶子",
		},
	},
})
do ObjectDB[objectID] = objectData; end
