local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[437628] = {
		readable = "Nearly-empty Cask",
		model = 5525412,
		text = {
			en = "Nearly-empty Cask",
			es = "Tonel casi vacío",
			mx = "Tonel casi vacío",
			de = "Fast leere Tonne",
			fr = "Fût presque vide",
			it = "Barile Quasi Vuoto",
			pt = "Barril Quase Vazio",
			ru = "Почти опустевший бочонок",
			ko = "거의 빈 궤짝",
			cn = "几乎全空的木桶",
			tw = "幾乎見底的桶子",
		},
	},
	[449135] = {
		readable = "Mislaid Tool",
		model = 5280301,
		text = {
			en = "Mislaid Tool",
			es = "Herramienta extraviada",
			mx = "Herramienta extraviada",
			de = "Verlegtes Werkzeug",
			fr = "Outil égaré",
			it = "Attrezzo Smarrito",
			pt = "Ferramenta Extraviada",
			ru = "Потерянный инструмент",
			ko = "잘못 놓인 도구",
			cn = "错放的工具",
			tw = "放錯地方的工具",
		},
	},
	[449140] = {
		readable = "Mislaid Tool",
		model = 5280302,
		text = {
			en = "Mislaid Tool",
			es = "Herramienta extraviada",
			mx = "Herramienta extraviada",
			de = "Verlegtes Werkzeug",
			fr = "Outil égaré",
			it = "Attrezzo Smarrito",
			pt = "Ferramenta Extraviada",
			ru = "Потерянный инструмент",
			ko = "잘못 놓인 도구",
			cn = "错放的工具",
			tw = "放錯地方的工具",
		},
	},
	[455915] = {
		readable = "Frying Pan",
		model = 145612,
		text = {
			en = "Frying Pan",
			es = "Sartén",
			mx = "Sartén",
			de = "Bratpfanne",
			fr = "Poêle à frire",
			it = "Padella",
			pt = "Frigideira",
			ru = "Сковорода",
			ko = "프라이팬",
			cn = "煎锅",
			tw = "煎鍋",
		},
	},
})
do ObjectDB[objectID] = objectData; end
