local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[546728] = {
		readable = "Legacy Stone of True Calling",
		model = 6712539,
		text = {
			en = "Legacy Stone of True Calling",
			es = "[Legacy Stone of True Calling]",
			mx = "[Legacy Stone of True Calling]",
			de = "Vermächtnisstein der wahren Bestimmung",
			fr = "Pierre d’héritage de vocation véritable",
			it = "[Legacy Stone of True Calling]",
			pt = "Pedra Ancestral do Verdadeiro Chamado",
			ru = "Вековой камень истинного призвания",
			ko = "[Legacy Stone of True Calling]",
			cn = "[Legacy Stone of True Calling]",
			tw = "[Legacy Stone of True Calling]",
		},
	},
	[547286] = {
		readable = "Snow Patch",
		model = 196993,
		text = {
			en = "Snow Patch",
			es = "Zona nevada",
			mx = "Parche de nieve",
			de = "Schneefeld",
			fr = "Plaque de neige",
			it = "Chiazza di Neve",
			pt = "Área Nevada",
			ru = "Снежник",
			ko = "눈 뭉치",
			cn = "积雪",
			tw = "雪堆",
		},
	},
	[547288] = {
		readable = "Snow Mound",
		model = 124640,
		text = {
			en = "Snow Mound",
			es = "Montículo de nieve",
			mx = "Montículo de nieve",
			de = "Schneehügel",
			fr = "Monticule de neige",
			it = "Mucchio di Neve",
			pt = "Monte de Neve",
			ru = "Сугроб",
			ko = "눈더미",
			cn = "雪堆",
			tw = "雪堆",
		},
	},
	[547473] = {
		readable = "Orb of Translocation",
		model = 6024535,
		text = {
			en = "Orb of Translocation",
			es = "Orbe de traslado",
			mx = "Orbe de traslado",
			de = "Translokationskugel",
			fr = "Orbe de transposition",
			it = "Sfera di Traslocazione",
			pt = "Orbe de Deslocamento",
			ru = "Сфера транслокации",
			ko = "순간이동의 보주",
			cn = "传送宝珠",
			tw = "傳送之門",
		},
	},
	[547474] = {
		readable = "Orb of Translocation",
		model = 6024535,
		text = {
			en = "Orb of Translocation",
			es = "Orbe de traslado",
			mx = "Orbe de traslado",
			de = "Translokationskugel",
			fr = "Orbe de transposition",
			it = "Sfera di Traslocazione",
			pt = "Orbe de Deslocamento",
			ru = "Сфера транслокации",
			ko = "순간이동의 보주",
			cn = "传送宝珠",
			tw = "傳送之門",
		},
	},
	[548615] = {
		readable = "Amethryl Flower",
		model = 6747139,
		text = {
			en = "Amethryl Flower",
			es = "[Amethryl Flower]",
			mx = "[Amethryl Flower]",
			de = "Amethrilblume",
			fr = "Fleur d’améthryle",
			it = "[Amethryl Flower]",
			pt = "[Amethryl Flower]",
			ru = "Амефриловый цветок",
			ko = "[Amethryl Flower]",
			cn = "[Amethryl Flower]",
			tw = "[Amethryl Flower]",
		},
	},
	[549348] = {
		readable = "Stove",
		model = 1852119,
		text = {
			en = "Stove",
			es = "Estufa",
			mx = "Estufa",
			de = "Herd",
			fr = "Fourneau",
			it = "Stufa",
			pt = "Fogão",
			ru = "Печка",
			ko = "난로",
			cn = "火炉",
			tw = "爐子",
		},
	},
	[554501] = {
		readable = "Dropped Shield",
		model = 192182,
		text = {
			en = "Dropped Shield",
			es = "Escudo caído",
			mx = "Escudo abandonado",
			de = "Fallen gelassener Schild",
			fr = "Bouclier égaré",
			it = "Scudo Caduto",
			pt = "Escudo Largado",
			ru = "Оброненный щит",
			ko = "떨어뜨린 방패",
			cn = "遗弃的盾牌",
			tw = "掉落的盾牌",
		},
	},
	[554508] = {
		readable = "Dropped Weapon",
		model = 970087,
		text = {
			en = "Dropped Weapon",
			es = "Arma caída",
			mx = "Arma abandonada",
			de = "Fallen gelassene Waffe",
			fr = "Arme égarée",
			it = "Arma Caduta",
			pt = "Arma Largada",
			ru = "Оброненное оружие",
			ko = "떨어뜨린 무기",
			cn = "遗弃的武器",
			tw = "掉落的武器",
		},
	},
	[554509] = {
		readable = "Dropped Weapon",
		model = 244238,
		text = {
			en = "Dropped Weapon",
			es = "Arma caída",
			mx = "Arma abandonada",
			de = "Fallen gelassene Waffe",
			fr = "Arme égarée",
			it = "Arma Caduta",
			pt = "Arma Largada",
			ru = "Оброненное оружие",
			ko = "떨어뜨린 무기",
			cn = "遗弃的武器",
			tw = "掉落的武器",
		},
	},
	[554679] = {
		readable = "Legacy Stone of True Self",
		model = 6712539,
		text = {
			en = "Legacy Stone of True Self",
			es = "[Legacy Stone of True Self]",
			mx = "[Legacy Stone of True Self]",
			de = "Vermächtnisstein des wahren Selbst",
			fr = "Pierre d’héritage du vrai soi",
			it = "[Legacy Stone of True Self]",
			pt = "Pedra Ancestral do Verdadeiro Ser",
			ru = "Вековой камень истинной натуры",
			ko = "[Legacy Stone of True Self]",
			cn = "[Legacy Stone of True Self]",
		},
	},
})
do ObjectDB[objectID] = objectData; end
