local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[544785] = {
		readable = "Empty Seed Sack",
		model = 6055097,
		text = {
			en = "Empty Seed Sack",
			es = "[Empty Seed Sack]",
			mx = "[Empty Seed Sack]",
			de = "[Empty Seed Sack]",
			fr = "[Empty Seed Sack]",
			it = "[Empty Seed Sack]",
			pt = "[Empty Seed Sack]",
			ru = "[Empty Seed Sack]",
			ko = "[Empty Seed Sack]",
			cn = "[Empty Seed Sack]",
			tw = "[Empty Seed Sack]",
		},
	},
	[548700] = {
		readable = "Well-Worn Ladle",
		model = 6326885,
		text = {
			en = "Well-Worn Ladle",
			es = "[Well-Worn Ladle]",
			mx = "[Well-Worn Ladle]",
			de = "[Well-Worn Ladle]",
			fr = "[Well-Worn Ladle]",
			it = "[Well-Worn Ladle]",
			pt = "[Well-Worn Ladle]",
			ru = "[Well-Worn Ladle]",
			ko = "[Well-Worn Ladle]",
			cn = "[Well-Worn Ladle]",
			tw = "[Well-Worn Ladle]",
		},
	},
	[548703] = {
		readable = "Pilfered Crafting Drill",
		model = 6252856,
		text = {
			en = "Pilfered Crafting Drill",
			es = "[Pilfered Crafting Drill]",
			mx = "[Pilfered Crafting Drill]",
			de = "[Pilfered Crafting Drill]",
			fr = "[Pilfered Crafting Drill]",
			it = "[Pilfered Crafting Drill]",
			pt = "[Pilfered Crafting Drill]",
			ru = "[Pilfered Crafting Drill]",
			ko = "[Pilfered Crafting Drill]",
			cn = "[Pilfered Crafting Drill]",
			tw = "[Pilfered Crafting Drill]",
		},
	},
	[549189] = {
		readable = "The Great Vault",
		model = 6036354,
		text = {
			en = "The Great Vault",
			es = "La gran cámara",
			mx = "La Gran bóveda",
			de = "Die Große Schatzkammer",
			fr = "La grande chambre forte",
			it = "La Gran Banca",
			pt = "O Grande Cofre",
			ru = "Великое хранилище",
			ko = "위대한 금고",
			cn = "宏伟宝库",
			tw = "寶庫",
		},
	},
	[550008] = {
		readable = "Splattered Scroll",
		model = 6326920,
		text = {
			en = "Splattered Scroll",
			es = "[Splattered Scroll]",
		},
	},
})
do ObjectDB[objectID] = objectData; end
