local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[523535] = {
		readable = "Torch",
		model = 5347378,
		text = {
			en = "Torch",
			es = "Antorcha",
			mx = "Antorcha",
			de = "Fackel",
			fr = "Torche",
			it = "Torcia",
			pt = "Tocha",
			ru = "Факел",
			ko = "횃불",
			cn = "火炬",
			tw = "火炬",
		},
	},
	[523601] = {
		readable = "Terminas' Vault",
		model = 6210898,
		text = {
			en = "Terminas' Vault",
			es = "Caja fuerte de Términas",
			mx = "[Terminas' Vault]",
			de = "Terminas' Tresor",
			fr = "Caveau de Terminas",
			it = "Forziere di Terminas",
			pt = "Cofre de Terminas",
			ru = "Хранилище Рокоса",
			ko = "테르미나스의 금고",
			cn = "特泯纳斯的宝库",
			tw = "特蒙諾斯的寶庫",
		},
	},
	[525100] = {
		readable = "Fragrant Dreaming Glory",
		model = 219446,
		text = {
			en = "Fragrant Dreaming Glory",
			es = "Gloria de ensueño fragante",
			mx = "Gloria de ensueño fragante",
			de = "Duftende Traumwinde",
			fr = "Glaurier parfumé",
			it = "Gloria d'Oro Odorosa",
			pt = "Glória-sonhadora Fragrante",
			ru = "Ароматное сияние грез",
			ko = "향긋한 꿈초롱이",
			cn = "芳香的梦露花",
			tw = "芬芳的譽夢草",
		},
	},
	[525110] = {
		readable = "Stove",
		model = 1852119,
		text = {
			en = "Stove",
			es = "Estufa",
			mx = "Estufa",
			de = "Herd",
			fr = "Fourneau",
			it = "Stufa",
			pt = "Fogão",
			ru = "Печка",
			ko = "난로",
			cn = "火炉",
			tw = "爐子",
		},
	},
	[525189] = {
		readable = "Portal to the Oasis",
		model = 3540722,
		text = {
			en = "Portal to the Oasis",
			es = "[Portal to the Oasis]",
			mx = "Portal al Oasis",
			de = "Portal zur Oase",
			fr = "Portail vers l’Oasis",
			it = "[Portal to the Oasis]",
			pt = "Portal para o Oásis",
			ru = "Портал в \"Оазис\"",
			ko = "[Portal to the Oasis]",
			cn = "通往绿洲的传送门",
			tw = "[Portal to the Oasis]",
		},
	},
	[525823] = {
		readable = "Sureki Shadecaster",
		model = 5516443,
		text = {
			en = "Sureki Shadecaster",
			es = "Proyector de sombras sureki",
			mx = "Emanasombras sureki",
			de = "Schattenwerfer der Sureki",
			fr = "Lance-ombre sureki",
			it = "Gettaombre dei Sureki",
			pt = "Umbrovisor Sureki",
			ru = "Теневещатель суреки",
			ko = "수레키 그늘투영기",
			cn = "苏雷吉映影仪",
			tw = "蘇芮基投影儀",
		},
	},
	[526951] = {
		readable = "Challenger's Cache",
		model = 1314905,
		text = {
			en = "Challenger's Cache",
			es = "Alijo de contendiente",
			mx = "Alijo del Contendiente",
			de = "Schatz des Herausforderers",
			fr = "Cache de prétendant ou de prétendante",
			it = "Cassa dello Sfidante",
			pt = "Baú do Desafiante",
			ru = "Тайник претендента",
			ko = "도전자의 보관함",
			cn = "挑战者的箱子",
			tw = "挑戰者的儲物箱",
		},
	},
	[526959] = {
		readable = "Challenger's Cache",
		model = 1314905,
		text = {
			en = "Challenger's Cache",
			es = "Alijo de contendiente",
			mx = "Alijo del Contendiente",
			de = "Schatz des Herausforderers",
			fr = "Cache de prétendant ou de prétendante",
			it = "Cassa dello Sfidante",
			pt = "Baú do Desafiante",
			ru = "Тайник претендента",
			ko = "도전자의 보관함",
			cn = "挑战者的箱子",
			tw = "挑戰者的儲物箱",
		},
	},
	[526962] = {
		readable = "Challenger's Cache",
		model = 1314905,
		text = {
			en = "Challenger's Cache",
			es = "Alijo de contendiente",
			mx = "Alijo del Contendiente",
			de = "Schatz des Herausforderers",
			fr = "Cache de prétendant ou de prétendante",
			it = "Cassa dello Sfidante",
			pt = "Baú do Desafiante",
			ru = "Тайник претендента",
			ko = "도전자의 보관함",
			cn = "挑战者的箱子",
			tw = "挑戰者的儲物箱",
		},
	},
	[526963] = {
		readable = "Challenger's Cache",
		model = 1314905,
		text = {
			en = "Challenger's Cache",
			es = "Alijo de contendiente",
			mx = "Alijo del Contendiente",
			de = "Schatz des Herausforderers",
			fr = "Cache de prétendant ou de prétendante",
			it = "Cassa dello Sfidante",
			pt = "Baú do Desafiante",
			ru = "Тайник претендента",
			ko = "도전자의 보관함",
			cn = "挑战者的箱子",
			tw = "挑戰者的儲物箱",
		},
	},
	[526972] = {
		readable = "Challenger's Cache",
		model = 1314905,
		text = {
			en = "Challenger's Cache",
			es = "Alijo de contendiente",
			mx = "Alijo del Contendiente",
			de = "Schatz des Herausforderers",
			fr = "Cache de prétendant ou de prétendante",
			it = "Cassa dello Sfidante",
			pt = "Baú do Desafiante",
			ru = "Тайник претендента",
			ko = "도전자의 보관함",
			cn = "挑战者的箱子",
			tw = "挑戰者的儲物箱",
		},
	},
	[526977] = {
		readable = "Challenger's Cache",
		model = 1314905,
		text = {
			en = "Challenger's Cache",
			es = "Alijo de contendiente",
			mx = "Alijo del Contendiente",
			de = "Schatz des Herausforderers",
			fr = "Cache de prétendant ou de prétendante",
			it = "Cassa dello Sfidante",
			pt = "Baú do Desafiante",
			ru = "Тайник претендента",
			ko = "도전자의 보관함",
			cn = "挑战者的箱子",
		},
	},
})
do ObjectDB[objectID] = objectData; end
