local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[525934] = {
		readable = "Intrepid Explorer's Marker",
		model = 6050858,
		text = {
			en = "Intrepid Explorer's Marker",
			es = "[Intrepid Explorer's Marker]",
			mx = "[Intrepid Explorer's Marker]",
			de = "[Intrepid Explorer's Marker]",
			fr = "[Intrepid Explorer's Marker]",
			it = "[Intrepid Explorer's Marker]",
			pt = "[Intrepid Explorer's Marker]",
			ru = "[Intrepid Explorer's Marker]",
			ko = "[Intrepid Explorer's Marker]",
			cn = "[Intrepid Explorer's Marker]",
			tw = "[Intrepid Explorer's Marker]",
		},
	},
	[525935] = {
		readable = "Spare Ink",
		model = 4494591,
		text = {
			en = "Spare Ink",
			es = "[Spare Ink]",
			mx = "[Spare Ink]",
			de = "Ersatztinte",
			fr = "[Spare Ink]",
			it = "[Spare Ink]",
			pt = "[Spare Ink]",
			ru = "[Spare Ink]",
			ko = "[Spare Ink]",
			cn = "[Spare Ink]",
			tw = "[Spare Ink]",
		},
	},
	[525936] = {
		readable = "Leather-Bound Techniques",
		model = 4337371,
		text = {
			en = "Leather-Bound Techniques",
			es = "[Leather-Bound Techniques]",
			mx = "[Leather-Bound Techniques]",
			de = "[Leather-Bound Techniques]",
			fr = "[Leather-Bound Techniques]",
			it = "[Leather-Bound Techniques]",
			pt = "[Leather-Bound Techniques]",
			ru = "[Leather-Bound Techniques]",
			ko = "[Leather-Bound Techniques]",
			cn = "[Leather-Bound Techniques]",
			tw = "[Leather-Bound Techniques]",
		},
	},
	[525938] = {
		readable = "Handy Wrench",
		model = 1033014,
		text = {
			en = "Handy Wrench",
			es = "Llave práctica",
			mx = "[Handy Wrench]",
			de = "[Handy Wrench]",
			fr = "[Handy Wrench]",
			it = "Chiave Meccanica Maneggevole",
			pt = "[Handy Wrench]",
			ru = "Удобный гаечный ключ",
			ko = "[Handy Wrench]",
			cn = "[Handy Wrench]",
			tw = "[Handy Wrench]",
		},
	},
	[525939] = {
		readable = "What To Do When Nothing Works",
		model = 949617,
		text = {
			en = "What To Do When Nothing Works",
			es = "Qué hacer cuando nada funciona",
			mx = "Qué hacer cuando nada funciona",
			de = "Was tun, wenn nichts funktioniert",
			fr = "À l’aide ! Quand rien ne fonctionne",
			it = "Cosa Fare Quando Niente Funziona",
			pt = "O Que Fazer Quando Nada Dá Certo",
			ru = "Что делать, когда ничего не помогло",
			ko = "[What To Do When Nothing Works]",
			cn = "无计可施时的妙计",
			tw = "[What To Do When Nothing Works]",
		},
	},
	[525940] = {
		readable = "Offline Helper Bot",
		model = 244201,
		text = {
			en = "Offline Helper Bot",
			es = "[Offline Helper Bot]",
			mx = "[Offline Helper Bot]",
			de = "[Offline Helper Bot]",
			fr = "[Offline Helper Bot]",
			it = "[Offline Helper Bot]",
			pt = "[Offline Helper Bot]",
			ru = "[Offline Helper Bot]",
			ko = "[Offline Helper Bot]",
			cn = "[Offline Helper Bot]",
			tw = "[Offline Helper Bot]",
		},
	},
	[525941] = {
		readable = "Ethereal Stormwrench",
		model = 5916208,
		text = {
			en = "Ethereal Stormwrench",
			es = "[Ethereal Stormwrench]",
			mx = "[Ethereal Stormwrench]",
			de = "[Ethereal Stormwrench]",
			fr = "[Ethereal Stormwrench]",
			it = "[Ethereal Stormwrench]",
			pt = "[Ethereal Stormwrench]",
			ru = "[Ethereal Stormwrench]",
			ko = "[Ethereal Stormwrench]",
			cn = "[Ethereal Stormwrench]",
			tw = "[Ethereal Stormwrench]",
		},
	},
	[525942] = {
		readable = "Expeditious Pylon",
		model = 6699745,
		text = {
			en = "Expeditious Pylon",
			es = "[Expeditious Pylon]",
			mx = "[Expeditious Pylon]",
			de = "Flinker Pylon",
			fr = "[Expeditious Pylon]",
			it = "[Expeditious Pylon]",
			pt = "[Expeditious Pylon]",
			ru = "[Expeditious Pylon]",
			ko = "[Expeditious Pylon]",
			cn = "[Expeditious Pylon]",
			tw = "[Expeditious Pylon]",
		},
	},
	[525943] = {
		readable = "Manual of Mistakes and Mishaps",
		model = 6025929,
		text = {
			en = "Manual of Mistakes and Mishaps",
			es = "Manual de errores y contratiempos",
			mx = "[Manual of Mistakes and Mishaps]",
			de = "Handbuch der Fehler und Missgeschicke",
			fr = "Petit livre des grosses erreurs",
			it = "Manuale degli Errori e delle Disavventure",
			pt = "Manual de Erros e Contratempos",
			ru = "Пособие по промахам и просчетам",
			ko = "[Manual of Mistakes and Mishaps]",
			cn = "错误与失误手册",
			tw = "故障排除手冊",
		},
	},
	[525944] = {
		readable = "MIniturized Transport Skiff",
		model = 7110528,
		text = {
			en = "MIniturized Transport Skiff",
			es = "[MIniturized Transport Skiff]",
			mx = "[MIniturized Transport Skiff]",
			de = "[MIniturized Transport Skiff]",
			fr = "[MIniturized Transport Skiff]",
			it = "[MIniturized Transport Skiff]",
			pt = "[MIniturized Transport Skiff]",
			ru = "[MIniturized Transport Skiff]",
			ko = "[MIniturized Transport Skiff]",
			cn = "[MIniturized Transport Skiff]",
			tw = "[MIniturized Transport Skiff]",
		},
	},
	[525945] = {
		readable = "One Engineer's Junk",
		model = 1305336,
		text = {
			en = "One Engineer's Junk",
			es = "Chatarra de ingeniero",
			mx = "Basura de un ingeniero",
			de = "Des einen Ingenieurs Schrott",
			fr = "Comment recycler sa camelote",
			it = "Cianfrusaglie di un Ingegnere",
			pt = "Tralha de Engenheiro",
			ru = "Многообещающий хлам",
			ko = "[One Engineer's Junk]",
			cn = "某个工程师的垃圾",
			tw = "[One Engineer's Junk]",
		},
	},
	[525946] = {
		readable = "Sin'dorei Enchanting Rod",
		model = 2438950,
		text = {
			en = "Sin'dorei Enchanting Rod",
			es = "[Sin'dorei Enchanting Rod]",
			mx = "[Sin'dorei Enchanting Rod]",
			de = "Verzauberkunstrute der Sin'dorei",
			fr = "[Sin'dorei Enchanting Rod]",
			it = "Verga d'Incantamento dei Sin'dorei",
			pt = "[Sin'dorei Enchanting Rod]",
			ru = "Син'дорайский рунический жезл",
			ko = "[Sin'dorei Enchanting Rod]",
			cn = "[Sin'dorei Enchanting Rod]",
			tw = "[Sin'dorei Enchanting Rod]",
		},
	},
	[525947] = {
		readable = "Loa-Blessed Dust",
		model = 942448,
		text = {
			en = "Loa-Blessed Dust",
		},
	},
})
do ObjectDB[objectID] = objectData; end
