local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[571290] = {
		readable = "Glowing Moth",
		model = 124932,
		text = {
			en = "Glowing Moth",
			es = "Polilla resplandeciente",
			mx = "[Glowing Moth]",
			de = "Leuchtende Motte",
			fr = "Phalène luminescent",
			it = "[Glowing Moth]",
			pt = "[Glowing Moth]",
			ru = "Светящийся мотылек",
			ko = "[Glowing Moth]",
			cn = "[Glowing Moth]",
			tw = "[Glowing Moth]",
		},
	},
	[571291] = {
		readable = "Glowing Moth",
		model = 124932,
		text = {
			en = "Glowing Moth",
			es = "Polilla resplandeciente",
			mx = "[Glowing Moth]",
			de = "Leuchtende Motte",
			fr = "Phalène luminescent",
			it = "Falena Luminosa",
			pt = "[Glowing Moth]",
			ru = "Светящийся мотылек",
			ko = "[Glowing Moth]",
			cn = "发光的飞蛾",
			tw = "[Glowing Moth]",
		},
	},
	[571292] = {
		readable = "Glowing Moth",
		model = 124932,
		text = {
			en = "Glowing Moth",
			es = "Polilla resplandeciente",
			mx = "[Glowing Moth]",
			de = "Leuchtende Motte",
			fr = "Phalène luminescent",
			it = "[Glowing Moth]",
			pt = "[Glowing Moth]",
			ru = "Светящийся мотылек",
			ko = "[Glowing Moth]",
			cn = "[Glowing Moth]",
			tw = "[Glowing Moth]",
		},
	},
	[571293] = {
		readable = "Glowing Moth",
		model = 124932,
		text = {
			en = "Glowing Moth",
			es = "Polilla resplandeciente",
			mx = "[Glowing Moth]",
			de = "Leuchtende Motte",
			fr = "Phalène luminescent",
			it = "[Glowing Moth]",
			pt = "[Glowing Moth]",
			ru = "Светящийся мотылек",
			ko = "[Glowing Moth]",
			cn = "[Glowing Moth]",
			tw = "[Glowing Moth]",
		},
	},
	[571294] = {
		readable = "Glowing Moth",
		model = 124932,
		text = {
			en = "Glowing Moth",
			es = "Polilla resplandeciente",
			mx = "[Glowing Moth]",
			de = "Leuchtende Motte",
			fr = "Phalène luminescent",
			it = "[Glowing Moth]",
			pt = "[Glowing Moth]",
			ru = "Светящийся мотылек",
			ko = "[Glowing Moth]",
			cn = "[Glowing Moth]",
			tw = "[Glowing Moth]",
		},
	},
	[571308] = {
		readable = "Glowing Moth",
		model = 124932,
		text = {
			en = "Glowing Moth",
			es = "Polilla resplandeciente",
			mx = "[Glowing Moth]",
			de = "Leuchtende Motte",
			fr = "Phalène luminescent",
			it = "Falena Luminosa",
			pt = "[Glowing Moth]",
			ru = "Светящийся мотылек",
			ko = "[Glowing Moth]",
			cn = "发光的飞蛾",
			tw = "[Glowing Moth]",
		},
	},
	[571312] = {
		readable = "Glowing Moth",
		model = 124932,
		text = {
			en = "Glowing Moth",
			es = "Polilla resplandeciente",
			mx = "[Glowing Moth]",
			de = "Leuchtende Motte",
			fr = "Phalène luminescent",
			it = "Falena Luminosa",
			pt = "[Glowing Moth]",
			ru = "Светящийся мотылек",
			ko = "[Glowing Moth]",
			cn = "发光的飞蛾",
			tw = "[Glowing Moth]",
		},
	},
	[571314] = {
		readable = "Glowing Moth",
		model = 124932,
		text = {
			en = "Glowing Moth",
			es = "Polilla resplandeciente",
			mx = "[Glowing Moth]",
			de = "Leuchtende Motte",
			fr = "Phalène luminescent",
			it = "Falena Luminosa",
			pt = "[Glowing Moth]",
			ru = "Светящийся мотылек",
			ko = "[Glowing Moth]",
			cn = "发光的飞蛾",
			tw = "[Glowing Moth]",
		},
	},
	[571319] = {
		readable = "Glowing Moth",
		model = 124932,
		text = {
			en = "Glowing Moth",
			es = "Polilla resplandeciente",
			mx = "[Glowing Moth]",
			de = "Leuchtende Motte",
			fr = "Phalène luminescent",
			it = "[Glowing Moth]",
			pt = "[Glowing Moth]",
			ru = "Светящийся мотылек",
			ko = "[Glowing Moth]",
			cn = "[Glowing Moth]",
			tw = "[Glowing Moth]",
		},
	},
	[571323] = {
		readable = "Glowing Moth",
		model = 124932,
		text = {
			en = "Glowing Moth",
			es = "Polilla resplandeciente",
			mx = "[Glowing Moth]",
			de = "Leuchtende Motte",
			fr = "Phalène luminescent",
			it = "[Glowing Moth]",
			pt = "[Glowing Moth]",
			ru = "Светящийся мотылек",
			ko = "[Glowing Moth]",
			cn = "[Glowing Moth]",
			tw = "[Glowing Moth]",
		},
	},
	[571324] = {
		readable = "Glowing Moth",
		model = 124932,
		text = {
			en = "Glowing Moth",
			es = "Polilla resplandeciente",
			mx = "[Glowing Moth]",
			de = "Leuchtende Motte",
			fr = "Phalène luminescent",
			it = "[Glowing Moth]",
		},
	},
})
do ObjectDB[objectID] = objectData; end
