local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[616804] = {
		readable = "Ancient Amani Tablet",
		model = 6212409,
		text = {
			en = "Ancient Amani Tablet",
			es = "[Ancient Amani Tablet]",
			mx = "[Ancient Amani Tablet]",
			de = "[Ancient Amani Tablet]",
			fr = "[Ancient Amani Tablet]",
			it = "[Ancient Amani Tablet]",
			pt = "[Ancient Amani Tablet]",
			ru = "[Ancient Amani Tablet]",
			ko = "[Ancient Amani Tablet]",
			cn = "[Ancient Amani Tablet]",
			tw = "[Ancient Amani Tablet]",
		},
	},
	[617077] = {
		readable = "Vilebranch Scroll",
		model = 5975119,
		text = {
			en = "Vilebranch Scroll",
			es = "[Vilebranch Scroll]",
			mx = "[Vilebranch Scroll]",
			de = "[Vilebranch Scroll]",
			fr = "[Vilebranch Scroll]",
			it = "[Vilebranch Scroll]",
			pt = "[Vilebranch Scroll]",
			ru = "[Vilebranch Scroll]",
			ko = "[Vilebranch Scroll]",
			cn = "[Vilebranch Scroll]",
			tw = "[Vilebranch Scroll]",
		},
	},
	[639875] = {
		readable = "Feather of Jan'alai",
		model = 7550572,
		text = {
			en = "Feather of Jan'alai",
			es = "[Feather of Jan'alai]",
			mx = "[Feather of Jan'alai]",
			de = "[Feather of Jan'alai]",
			fr = "[Feather of Jan'alai]",
			it = "[Feather of Jan'alai]",
			pt = "[Feather of Jan'alai]",
			ru = "[Feather of Jan'alai]",
			ko = "[Feather of Jan'alai]",
			cn = "[Feather of Jan'alai]",
			tw = "[Feather of Jan'alai]",
		},
	},
	[654422] = {
		readable = "Energized Crystal Conductor",
		model = 5916222,
		text = {
			en = "Energized Crystal Conductor",
			es = "[Energized Crystal Conductor]",
			mx = "[Energized Crystal Conductor]",
			de = "[Energized Crystal Conductor]",
			fr = "[Energized Crystal Conductor]",
			it = "[Energized Crystal Conductor]",
			pt = "[Energized Crystal Conductor]",
			ru = "[Energized Crystal Conductor]",
			ko = "[Energized Crystal Conductor]",
			cn = "[Energized Crystal Conductor]",
			tw = "[Energized Crystal Conductor]",
		},
	},
	[654497] = {
		readable = "Energized Crystal Conductor",
		model = 5916222,
		text = {
			en = "Energized Crystal Conductor",
			es = "[Energized Crystal Conductor]",
			mx = "[Energized Crystal Conductor]",
			de = "[Energized Crystal Conductor]",
			fr = "[Energized Crystal Conductor]",
			it = "[Energized Crystal Conductor]",
			pt = "[Energized Crystal Conductor]",
			ru = "[Energized Crystal Conductor]",
			ko = "[Energized Crystal Conductor]",
			cn = "[Energized Crystal Conductor]",
			tw = "[Energized Crystal Conductor]",
		},
	},
	[655270] = {
		readable = "Domanaar Storage Vessel",
		model = 6391990,
		text = {
			en = "Domanaar Storage Vessel",
			es = "[Domanaar Storage Vessel]",
			mx = "[Domanaar Storage Vessel]",
			de = "[Domanaar Storage Vessel]",
			fr = "[Domanaar Storage Vessel]",
			it = "[Domanaar Storage Vessel]",
			pt = "[Domanaar Storage Vessel]",
			ru = "[Domanaar Storage Vessel]",
			ko = "[Domanaar Storage Vessel]",
			cn = "[Domanaar Storage Vessel]",
			tw = "[Domanaar Storage Vessel]",
		},
	},
	[655271] = {
		readable = "Hal'hadar Pocket-Storage",
		model = 6320659,
		text = {
			en = "Hal'hadar Pocket-Storage",
			es = "[Hal'hadar Pocket-Storage]",
			mx = "[Hal'hadar Pocket-Storage]",
			de = "[Hal'hadar Pocket-Storage]",
			fr = "[Hal'hadar Pocket-Storage]",
			it = "[Hal'hadar Pocket-Storage]",
			pt = "[Hal'hadar Pocket-Storage]",
			ru = "[Hal'hadar Pocket-Storage]",
			ko = "[Hal'hadar Pocket-Storage]",
			cn = "[Hal'hadar Pocket-Storage]",
			tw = "[Hal'hadar Pocket-Storage]",
		},
	},
	[655738] = {
		readable = "Nullframe Holoprint",
		model = 6321897,
		text = {
			en = "Nullframe Holoprint",
			es = "[Nullframe Holoprint]",
			mx = "[Nullframe Holoprint]",
			de = "[Nullframe Holoprint]",
			fr = "[Nullframe Holoprint]",
			it = "[Nullframe Holoprint]",
			pt = "[Nullframe Holoprint]",
			ru = "[Nullframe Holoprint]",
			ko = "[Nullframe Holoprint]",
			cn = "[Nullframe Holoprint]",
			tw = "[Nullframe Holoprint]",
		},
	},
	[656141] = {
		readable = "Soul Lattice Holoprint",
		model = 6321897,
		text = {
			en = "Soul Lattice Holoprint",
			es = "[Soul Lattice Holoprint]",
			mx = "[Soul Lattice Holoprint]",
			de = "[Soul Lattice Holoprint]",
			fr = "[Soul Lattice Holoprint]",
			it = "[Soul Lattice Holoprint]",
			pt = "[Soul Lattice Holoprint]",
			ru = "[Soul Lattice Holoprint]",
			ko = "[Soul Lattice Holoprint]",
			cn = "[Soul Lattice Holoprint]",
			tw = "[Soul Lattice Holoprint]",
		},
	},
	[656142] = {
		readable = "Glittering Crypt Holoprint",
		model = 6321897,
		text = {
			en = "Glittering Crypt Holoprint",
			es = "[Glittering Crypt Holoprint]",
			mx = "[Glittering Crypt Holoprint]",
			de = "[Glittering Crypt Holoprint]",
			fr = "[Glittering Crypt Holoprint]",
			it = "[Glittering Crypt Holoprint]",
			pt = "[Glittering Crypt Holoprint]",
			ru = "[Glittering Crypt Holoprint]",
			ko = "[Glittering Crypt Holoprint]",
		},
	},
})
do ObjectDB[objectID] = objectData; end
