DRAGONS_OF_NIGHTMARE = createHeader({
	readable = "Dragons of Nightmare",
	icon = 134157,
	text = {
		en = "Dragons of Nightmare",
		de = "Drachen des Alptraums",
		es = "Dragones de la pesadilla",
		mx = "Dragones de pesadilla",
		fr = "Dragons du Cauchemar",
		-- TODO: it = "",
		-- TODO: ko = "",
		-- TODO: pt = "",
		ru = "Драконы Кошмара",
		cn = "梦魇之龙",
		tw = "夢魘之龍",
	},
	lore = {
		en = "One of these dragons will spawn randomly at the associated coordinates across Azeroth.",
		-- TODO: de = "",
		es = "Uno de estos dragones aparecerá aleatoriamente en las coordenadas asociadas en todo Azeroth.",
		mx = "Uno de estos dragones aparecerá aleatoriamente en las coordenadas asociadas en todo Azeroth.",
		-- TODO: fr = "",
		-- TODO: it = "",
		-- TODO: ko = "",
		-- TODO: pt = "",
		-- TODO: ru = "",
		-- TODO: cn = "",
		tw = "這些龍中的一隻會在艾澤拉斯的相關座標隨機生成。",
	},
});
