VH_WAVE_6_BOSS = createHeader({
	readable = "Wave 6 Boss",
	icon = 135442,
	text = {
		en = "Wave 6 Boss",
		-- TODO: de = "",
		es = "Jefe de la oleada 6",
		mx = "Jefe de la oleada 6",
		-- TODO: fr = "",
		-- TODO: it = "",
		-- TODO: ko = "",
		-- TODO: pt = "",
		-- TODO: ru = "",
		-- TODO: cn = "",
		-- TODO: tw = "",
	},
});
VH_WAVE_12_BOSS = createHeader({
	readable = "Wave 12 Boss",
	icon = 236271,
	text = {
		en = "Wave 12 Boss",
		-- TODO: de = "",
		es = "Jefe de la oleada 12",
		mx = "Jefe de la oleada 12",
		-- TODO: fr = "",
		-- TODO: it = "",
		-- TODO: ko = "",
		-- TODO: pt = "",
		-- TODO: ru = "",
		-- TODO: cn = "",
		-- TODO: tw = "",
	},
});
VH_FINAL_WAVE_BOSS = createHeader({
	readable = "Final Wave Boss",
	icon = 135771,
	text = {
		en = "Final Wave Boss",
		-- TODO: de = "",
		es = "Jefe de la oleada final",
		mx = "Jefe de la oleada final",
		-- TODO: fr = "",
		-- TODO: it = "",
		-- TODO: ko = "",
		-- TODO: pt = "",
		-- TODO: ru = "",
		-- TODO: cn = "",
		-- TODO: tw = "",
	},
});
