GEAR_CONVERSION = createHeader({
	readable = "Gear Conversion",
	icon = 1391675,
	text = {
		en = "Gear Conversion",
		-- TODO: de = "",
		es = "Conversión de equipo",
		mx = "Conversión de equipo",
		-- TODO: fr = "",
		-- TODO: it = "",
		-- TODO: ko = "",
		-- TODO: pt = "",
		-- TODO: ru = "",
		cn = "装备转换",
		tw = "裝備轉換",
	},
	description = {
		en = "These items were obtained by characters created during the Remix Event and were automatically transferred to Retail when the event ended.",
		-- TODO: de = "",
		es = "Estos objetos fueron obtenidos por personajes creados durante el evento Remix y se transfirieron automáticamente a Retail cuando finalizó el evento.",
		mx = "Estos objetos fueron obtenidos por personajes creados durante el evento Remix y se transfirieron automáticamente a Retail cuando finalizó el evento.",
		-- TODO: fr = "",
		-- TODO: it = "",
		-- TODO: ko = "",
		-- TODO: pt = "",
		-- TODO: ru = "",
		cn = "这些物品是由在幻境新生活动期间创建的角色获得的，并在活动结束时自动转移到正式服。",
		-- TODO: tw = "",
	},
});
