# This is a workflow to harvest patches when items were added

name: Harvest item patches

on:
  workflow_dispatch:

jobs:
  harvest_items:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install requests beautifulsoup4

      - name: Harvest items
        working-directory: .contrib/Harvesters
        continue-on-error: true
        run: |
          python ItemPatchHarvester.py

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: Add item timelines
          title: Item patches
          branch: harvest-timelines-items
          delete-branch: true
